---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

data_params:
    sample_rate: 24000
    n_audio_samples: 720000

# training parameters
training_params:
    max_steps: 1000000
    batch_size: 16 # 10 for v100, 24 for A100
    base_lr: 4.0e-4
    warmup_steps: 3000
    hold_steps: 50000
    decay_steps: 3000000
    weight_decay: 0.01
    betas: (0.9, 0.98)
    shuffle_buffer: 128
    gradient_clip_val: 1.0
    semantic_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt"

ckpt_path: null

# running parameters
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: soundstorm
    version: sstk
    precision: bf16-mixed
    num_workers: 8
    accelerator: auto
    val_check_interval: 2000

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.instrumental.InstrumentalWebDataModule
    dataset_name: "SSTK_US"
    val_split: "SSTK_US"
    sample_rate: !ref <data_params[sample_rate]>
    duration: 30
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    min_length_ratio: 0.95
    normalize_audio: True
    aed_filtered: False
    avoid_vocal: True
    max_vocal_threshold: 0.5
    overlap_vocal_threshold: 0.1
    text_type: "sstk_random"
    max_num_crops: 3
    crop_step_size: 10
    mixed_ratio: 0.0
    use_pipe: False

# training module configuration
optimizer_class: !name:torch.optim.AdamW
    lr: !ref <training_params[base_lr]>
    weight_decay: !ref <training_params[weight_decay]>
    betas: !ref <training_params[betas]>
    fused: False

scheduler_class: !name:recipes.musiclm.optim.lr_scheduler.TriStageLR
    warmup_steps: !ref <training_params[warmup_steps]>
    hold_steps: !ref <training_params[hold_steps]>
    decay_steps: !ref <training_params[decay_steps]>

masking_scheme: !new:recipes.soundstorm.lightning.masking_scheme.DucMaskingScheme
    coarse_layers: 4
    mask_all_fine: False
    coarse_prob: null

pl_module: !new:recipes.soundstorm.lightning.soundstorm.SoundStorm
    sample_rate: !ref <data_params[sample_rate]>
    n_embd: 1536
    n_head: 12
    n_layer: 18
    conv_kernel_size: 5
    n_audio_samples: !ref <data_params[n_audio_samples]>
    audio_prompting: False
    masking_scheme: !ref <masking_scheme>
    fine_quantizer_embedding_dropout: True
    frontend: "sum"
    conditioning_dropout: 0.0
    attention_kwargs:
        enable_flash: True
        enable_mem_efficient: True  # only for V100
    optimizer_class: !ref <optimizer_class>
    scheduler_class: !ref <scheduler_class>
    semantic_ckpt: !ref <training_params[semantic_ckpt]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: step
    save_top_k: 20
    every_n_train_steps: !ref <run_opts[val_check_interval]>
    mode: max
    filename: "{step:06d}-{loss:.4f}"

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'

audio_demo: !new:recipes.soundstorm.callbacks.audio_demo.AudioDemo
    sample_rate: !ref <data_params[sample_rate]>
    max_demos_per_step: 1

# total_tokens: !new:recipes.musiclm.callbacks.loggers.LogTotalTokensCallback
# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_true"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 50
    max_steps: !ref <training_params[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null  # required now that we use an IterableDataset
    num_sanity_val_steps: 2
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !ref <audio_demo>
        # - !ref <total_tokens>
        # - !ref <log_gradient_scaler>
    plugins: !ref <plugins>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
