---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path:

# running parameters
run_opts:
  fast_dev_run: False
  tensorboard_dir: 'hdfs://harunava/home/byte_speech_sv/amy/log/'
  log_name: 'beat'
  version: 'mcc_perceiver'
  precision: 32
  accelerator: 'auto'
  num_workers: 5
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

train_params:
  learning_rate: 0.001
  max_epochs: -1
  batch_size: 32
  scheduler_patience: 20
  scheduler_decay_factor: 0.9
  do_tempo_loss: True
  devices: 'auto'
  shuffle_buffer: 1000
  num_iter: 20

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

teacher:
  teacher_name: "tcn"
  teacher_path: "hdfs://harunava/home/byte_speech_sv/amy/log/beat/0.3/checkpoints/epoch=56-step=28500.ckpt"

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 16000        # sampling rate for audio
  sample_len: 6.0             # duration in sec for input  #{24 or 6}
  sample_hop: 1               # hop len in sec for input
  hop_length: 160             # hop length to calculate spectrogram
  n_fft: 2048                 # number of fft to calculate spectrogram
  augmentation: False         # {true, false} use data augmentation
  input_feature: "hcqt"       # input feature type {mel, hcqt}
  do_time_augmentation: True  # use time stretching augmentation
  do_cqt_augmentation: True
  pitch_shift: False
  enable_short: False         # enable short audio, for structure and key
  semitone_scale: 1
  label_hop: 0.02             # hop len in sec for label/activation curve  #{0.01 or 0.02}


labels:
  beat_window_length: 2       # tolerance window when calculating beat labels
  n_beats: 3                  # number of output for beat prediction
  n_chord: 26                 # number of output for chord prediction
  n_segment: 7                # number of output for segment prediction
  n_keysig: 25
  n_tempo: 300

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.beat.preprocess.common.BeatPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <audio[label_hop]>
  chunk_per_sample: 5

# dataloader configuration
train_dataloader: !apply:recipes.beat.utils.dataset.get_train_dataset
  dataset_names: ["mcc"]
  preprocessor: !ref <preprocessor>
  shuffle_buffer: !ref <train_params[shuffle_buffer]> 
  batch_size: !ref <train_params[batch_size]>
  num_iter: !ref <train_params[num_iter]>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  to_tuple: "audio.npy"

val_dataloader: !apply:recipes.beat.utils.dataset.get_validation_dataset
  dataset_names: ["bytebeat"]
  preprocessor: !ref <preprocessor>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

test_dataloader: !apply:recipes.beat.utils.dataset.get_validation_dataset
  dataset_names: ["clip500"]
  preprocessor: !ref <preprocessor>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

# datamodule configuration
pl_datamodule: !new:recipes.beat.pl_modules.pl_datamodule.BeatDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

model_params:
  n_layers: 5
  spec_dim: 128
  temporal_dim: 128
  temporal_heads: 4
  spec_heads: 4
  resnet_pools: [[2, 2]]
  freq_pool_size: 2
  time_pool_size: 2
  num_fct: 4
  beat_pool: [1]
  n_channel: 512

perceiver_model_stage: !new:recipes.beat.models.perceiver.BeatPerceiverModelStage
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  hop_len: !ref <audio[hop_length]>
  n_layers: !ref <model_params[n_layers]>
  spec_dim: !ref <model_params[spec_dim]>
  temporal_dim: !ref <model_params[temporal_dim]>
  temporal_heads: !ref <model_params[temporal_heads]>
  resnet_pools: !ref <model_params[resnet_pools]>
  n_fft: !ref <audio[n_fft]>
  semitone_scale: !ref <audio[semitone_scale]>
  freq_pool_size: !ref <model_params[freq_pool_size]>
  time_pool_size: !ref <model_params[time_pool_size]>
  num_fct: !ref <model_params[num_fct]>

beat_classifier_stage: !new:recipes.beat.models.classifier.BeatClassifierStage
  n_channel: !ref <model_params[n_channel]>
  beat_pool: !ref <model_params[beat_pool]>
  n_beats: !ref <labels[n_beats]>
  n_tempo: !ref <labels[n_tempo]>

model: !new:samantha.core.BaseModel
  input_names: [audio, beats, tempo_label, aug_hop_size]
  output_names: [beat_pred, tempo_pred]
  stages:
    - !ref <perceiver_model_stage>
    - !ref <beat_classifier_stage>

################################################################################
##########                Post processing CONFIGURATION               ##########
################################################################################
post_processing_params:
  f_measure_threshold: 0.07
  use_tempo_prior: False

pl_module: !new:recipes.beat.pl_modules.pl_module_pseudo.LitPseudoBeat
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  hop_length: !ref <audio[hop_length]>
  beat_window_length: !ref <labels[beat_window_length]>
  n_beats: !ref <labels[n_beats]>
  n_tempo: !ref <labels[n_tempo]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  label_hop: !ref <audio[label_hop]>
  do_time_augmentation: !ref <audio[do_time_augmentation]>
  do_cqt_augmentation: !ref <audio[do_cqt_augmentation]>
  do_tempo_loss: !ref <train_params[do_tempo_loss]>
  f_measure_threshold: !ref <post_processing_params[f_measure_threshold]>
  use_tempo_prior: !ref <post_processing_params[use_tempo_prior]>
  teacher_name: !ref <teacher[teacher_name]>
  teacher_path: !ref <teacher[teacher_path]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

prediction_writer: !new:recipes.beat.pl_modules.callbacks.prediction_writer.BeatWriter
  output_dir: null

callbacks:
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    every_n_epochs: 1
    mode: "max"
    save_last: True
    monitor: Beat_Downbeat_f1
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'
  - !ref <prediction_writer>

trainer: !new:pytorch_lightning.Trainer
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  strategy: "ddp_find_unused_parameters_true"
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  callbacks: !ref <callbacks>
