---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
run_opts:
  fast_dev_run: False
  tensorboard_dir: 'hdfs://harunava/home/byte_speech_sv/amy/log/'
  log_name: 'beat_vocal'
  version: '0.1'
  precision: 32
  accelerator: 'auto'
  num_workers: 10
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

train_params:
  learning_rate: 0.001
  max_epochs: -1
  batch_size: 128
  scheduler_patience: 20
  scheduler_decay_factor: 0.5
  do_tempo_loss: False
  devices: 'auto'
  shuffle_buffer: 500
  num_iter: 50

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 16000        # sampling rate for audio
  sample_len: 6.0             # duration in sec for input  #{24 or 6}
  sample_hop: 1               # hop len in sec for input
  hop_length: 160             # hop length to calculate spectrogram
  n_fft: 2048                 # number of fft to calculate spectrogram
  augmentation: False         # {true, false} use data augmentation
  input_feature: "hcqt"       # input feature type {mel, hcqt}
  do_time_augmentation: True  # use time stretching augmentation
  do_cqt_augmentation: True
  pitch_shift: False
  enable_short: False         # enable short audio, for structure and key
  semitone_scale: 1
  label_hop: 0.02             # hop len in sec for label/activation curve  #{0.01 or 0.02}

labels:
  beat_window_length: 2       # tolerance window when calculating beat labels
  n_beats: 3                  # number of output for beat prediction
  n_tempo: 300

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.beat.preprocess.hdfs_common.BeatPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <audio[label_hop]>
  chunk_per_sample: 1

train_dataset: !new:webdataset.WebDataset
  urls: "pipe: hdfs dfs -cat \
         hdfs://harunava/home/byte_speech_sv/data/webdataset/vocal_beat/*_vocal_beat/train/shards-{0000..0043}.tar"
  resampled: True
train_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.beat.preprocess.common.BeatPreprocessor.train_batch_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.to_tuple ["audio.npy beats.pickle tempo_label"]
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

validation_dataset: !new:webdataset.WebDataset
  urls: "pipe: hdfs dfs -cat \
         hdfs://harunava/home/byte_speech_sv/data/webdataset/vocal_beat/*_vocal_beat/validation/*.tar"
val_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <validation_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.beat.preprocess.common.BeatPreprocessor.val_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio.npy beats.pickle tempo_label orig_beats dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

test_dataset: !new:webdataset.WebDataset
  urls: "pipe: hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/webdataset/vocal_beat/*_vocal_beat/test/*.tar"
test_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <test_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.beat.preprocess.common.BeatPreprocessor.val_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio.npy beats.pickle tempo_label orig_beats dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <train_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

val_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: True

test_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <test_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: True

# datamodule configuration
pl_datamodule: !new:recipes.beat.pl_modules.pl_datamodule.BeatDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

model_params:
  resnet_pools: [[2, 2]]
  n_channel: 128
  n_chan_conv: 1024
  front_conv: 1
  kernel_size: 5
  n_repeats: 1
  n_layers: 9
  beat_pool: [1]
  input_feature: "hcqt"

tcn_model_stage: !new:recipes.chord.models.tcn.TCNStage
  n_channel: !ref <model_params[n_channel]>
  n_chan_conv: !ref <model_params[n_chan_conv]>
  front_conv: !ref <model_params[front_conv]>
  kernel_size: !ref <model_params[kernel_size]>
  n_repeats: !ref <model_params[n_repeats]>
  n_layers: !ref <model_params[n_layers]>
  input_feature: !ref <model_params[input_feature]>
  sample_rate: !ref <audio[sampling_rate]>
  hop_length: !ref <audio[hop_length]>
  resnet_pools: !ref <model_params[resnet_pools]>
  n_fft: !ref <audio[n_fft]>
  semitone_scale: !ref <audio[semitone_scale]>

beat_classifier_stage: !new:recipes.beat.models.classifier.BeatClassifierStage
  n_channel: !ref <model_params[n_channel]>
  beat_pool: !ref <model_params[beat_pool]>
  n_beats: !ref <labels[n_beats]>
  n_tempo: !ref <labels[n_tempo]>

model: !new:samantha.core.BaseModel
  input_names: [audio, beats, tempo_label, aug_hop_size]
  output_names: [beat_pred, tempo_pred]
  stages:
    - !ref <tcn_model_stage>
    - !ref <beat_classifier_stage>

################################################################################
##########                Post processing CONFIGURATION               ##########
################################################################################
post_processing_params:
  f_measure_threshold: 0.2
  use_tempo_prior: False

pl_module: !new:recipes.beat.pl_modules.pl_module_vocal.LitVocalBeat
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  hop_length: !ref <audio[hop_length]>
  beat_window_length: !ref <labels[beat_window_length]>
  n_beats: !ref <labels[n_beats]>
  n_tempo: !ref <labels[n_tempo]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  label_hop: !ref <audio[label_hop]>
  do_time_augmentation: !ref <audio[do_time_augmentation]>
  do_cqt_augmentation: !ref <audio[do_cqt_augmentation]>
  do_tempo_loss: !ref <train_params[do_tempo_loss]>
  f_measure_threshold: !ref <post_processing_params[f_measure_threshold]>
  use_tempo_prior: !ref <post_processing_params[use_tempo_prior]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    every_n_epochs: 1
    mode: "max"
    monitor: "Beat_Downbeat_f1"

prediction_writer: !new:recipes.beat.pl_modules.callbacks.prediction_writer.BeatWriter
    output_path: null

trainer: !new:pytorch_lightning.Trainer
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  callbacks:
      - !ref <checkpoint>
      - !ref <prediction_writer>
