---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 16000
    n_mels: 80
    n_fft: 512
    win_length: 400
    hop_length: 160
    feature_cmvn: "LibriLightWebDataModule_SpeechTransform.stats.pt"

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    log_dir: "logs"
    log_name: umm
    version: !ref finetune_speech_melrecon_25hz_rq<model_cls[codebook_config[n_softmax]]>x<model_cls[codebook_config[codebook_size]]>_vq<model_cls[vq_config[codebook_size]]>x<model_cls[vq_config[codebook_dim]]>
    precision: "16-mixed"
    num_workers: 6
    accelerator: auto
    max_steps: 1000000
    val_check_interval: 5000
    batch_size: 20
    learning_rate: 1.0e-4 # TODO
    cycle_steps: 300000
    weight_decay: 0.1
    shuffle_buffer: 500
    gradient_clip_val: 1.0
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.librilight.LibriLightWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    split: "large"
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96] # TODO
    eps: 0.00000001

scheduler_cls: !name:recipes.umm_062.modules.lr_scheduler.DecayCosine
    init_lr: !ref <run_opts[learning_rate]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> / 2

model_cls: !name:recipes.umm_062.models.bestrq.BestRQMel
    frontend_config:
        kernel: 5
        conv_dim: [256, 256]
        feature_cmvn: !ref <extra_params[feature_cmvn]>
        sample_rate: !ref <extra_params[sample_rate]>
        n_mels: !ref <extra_params[n_mels]>
        n_fft: !ref <extra_params[n_fft]>
        win_length: !ref <extra_params[win_length]>
        hop_length: !ref <extra_params[hop_length]>
        mask_hop: 0.4
        mask_prob: 0.2 # TODO
        quantizer_layernorm: False # TODO
    encoder_config: !new:recipes.umm_062.models.flash_conformer.Wav2Vec2ConformerConfig
        hidden_size: 1024
        intermediate_size: 4096
        num_hidden_layers: 24
        num_attention_heads: 8
        max_source_positions: 750 # (sample_rate * max_seconds) / hop_length / 4
        position_embeddings_type: "rotary"
        layerdrop: 0
        is_causal: False
        vq_layer_idx: 12
    codebook_config:
        codebook_dim: 16
        codebook_size: 4096 # TODO
        n_softmax: 8 # TODO
    vq_config:
        dim: !ref <model_cls[encoder_config[hidden_size]]>
        codebook_size: 32768
        codebook_dim: 256
        threshold_ema_dead_code: 2
        kmeans_init: True
        kmeans_iters: 10
        sync_codebook: True

pl_module: !new:recipes.umm_062.modules.lit_module.BestRQMel
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.umm_062.modules.criterion.BestRQMelLoss
    extra_params: !ref <extra_params>
    required_modules:
        pretrained_bestrq:
            ckpt_path: "hdfs://haruna/home/byte_arnold_lf/lab/seed/umm/tasks/4456285/trials/16023847/output/logs/umm/pretrain_speech_25hz_8x4096/checkpoints/step=130000-tr_loss=3.3581-val_loss_0=0.0000.ckpt"
            init_fn: !name:recipes.umm_062.requires.model_initializer.init_pretrained_bestrq
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 300
      every_n_train_steps: !ref <run_opts[val_check_interval]> * 2
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_loss_0:.4f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.umm_062.callbacks.log_melspectrogram.LogMaskedMelSpectrogram
      n_examples: 4

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
