---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: 30
    # feature_mean: 3.287
    # feature_std: 20.043
    # duration: 10
    # feature_mean: 3.06
    # feature_std: 20.07
    n_fft: 2048
    hop_length: 240
    n_mels: 128
    mask_hop: 0.4
    mask_prob: 0.5
    state_dict_path: "/mnt/bn/zongyu-lq/logs/best_rq/pgc600k_25hz_4x8192_522m/checkpoints/step=075000-tr_loss=4.5369-val_loss_0=4.1857.pt"
    output_dir: "/mnt/bn/zongyu-lq/features/best_rq/pgc600k_melspec"
    bucket_size: 18000
    layer_idx: 12
    # latent_type: melspec

# running parameters
run_opts:
    fast_dev_run: False
    precision: "32"
    num_workers: 6
    accelerator: auto
    batch_size: 12
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    shuffle_buffer: 2000

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset: !new:recipes.musiclm.datasets.mcc.PGCDataset
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    max_num_crops: 1
    resampled: True
    shardshuffle: True

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.DataModule
    predict_dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

pl_module: !new:recipes.best_rq.modules.lit_module.Inference
    checkpointing: False
    extra_params: !ref <extra_params>

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    precision: !ref <run_opts[precision]>
    check_val_every_n_epoch: null
