data:
  batch_size: 3
  wav_list: './en_1400h.list'
  use_formant_shift: True
model:
  input_dim: 8
  feature_dim: 512
  num_blocks: 12
  dropout: 0
  segment_size: 64
  segment_stride: 32
  intra_seq2seq: 'sru'
  inter_seq2seq: 'roformer'
  diffusion_steps: 0
  num_chunks: 1
  chunk_length: 2500
  autoencoder: 'autoencoder'
  autoencoder_path: './logs_autoencoder_en_8dim/checkpoints/1000k_ckpt.pyt'
  autoencoder_config: './logs_autoencoder_en_8dim/config.yaml'
  model_ckpt_dir: './logs_20230604_sru-roformer_8in-12x512_64-32segs_aug-prompt-mel_cross-attn_mse-loss_bsz-256_rmsnorm_alleng4-10'
  save_interval: 2500
trainer:
  optimizer_kwargs:
    optimizer:
      type: "torch.optim.AdamW"
      params:
        lr: 3e-4
    scheduler:
      type: "cruise.optim.lr_scheduler.constant_lr"
  gradient_clip_val: 1
  max_epochs: 25
