---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']


extra_params:
    num_rounds: 1
    prompt_path: "/mnt/bn/audio-diffusion/data/mixture_prompts/karaoke-10s.csv"
    inference_conditions: style_audio
    max_items: null
    run_combinations: False

    output_dir: ./generated_output/conditional
    # Re-trained vocal checkpoint
    token2wav_type: diffusion
    semantic_type: bestrq

    # Model Settings
    sample_rate: 24000
    duration: 10
    sample_mode: "gumbel"

    ar_params:
        coarse_duration: 10
        fine_duration: 4
        coarse_stride: 5
        fine_stride: 3
        coarse_temperature: 0.9
        fine_temperature: 0.8
    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 3
        bf16_portion: 1.0

run_opts:
    fast_dev_run: False
    precision: 32
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 16
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.GTInferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/logs/umm/stage3_music_chroma_vq32768x32/checkpoints/step=0030000.ckpt
                initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/model_14_fix_rot/checkpoints/last.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
            vocoder:
                hpath: hdfs://harunava/home/byte_speech_sv/weitsung.lu/soundstream/dac_vae_125hz_24k_v2_part2/checkpoints/soundstream-step=374999-val_sdr=12.9557.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
        ar_modules:
            coarse:
                hpath: /mnt/bn/audio-diffusion/jt/model_archive/vocalmusic/coarse_flash_llama_wav2vec/bestrq_chroma_coarse_0.7b/checkpoints/step=295000-val_accu_0=17.92.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_coarse
                    cache_dir: !ref <run_opts[cache_dir]>
            fine:
                hpath: /mnt/bn/lyrics-to-song/ashaw/logs/bigmusic/fine/fine_mcc_mix/fixed_posemb_v1/checkpoints/step=206000-val_accu_0=10.44.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_fine
                    cache_dir: !ref <run_opts[cache_dir]>
            soundstream_dec:
                hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
                initializer: !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
                    cache_dir: !ref <run_opts[cache_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
