---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    num_rounds: 1
    prompt_path: "recipes/bigmusic/datasets/inference_prompts/pop.json"
    inference_conditions: style_audio
    max_items: null
    run_combinations: False

    output_dir: ./generated_output/conditional
    # Re-trained vocal checkpoint
    coarse_ckpt: "/mnt/bn/lyrics-to-song/ashaw/logs/l2s/coarse_unified/coarse_flash_llama_wav2vec/retrained_params/checkpoints/step=065000-val_accu_0=15.83.ckpt"
    # Fine - partial 60m balanced
    # fine_ckpt: "/mnt/bn/lyrics-to-song/ashaw/logs/l2s/fine/fine_flash_llama_mcc_vocals/vocal_finetune_60m/checkpoints/last.ckpt"
    fine_ckpt: "/mnt/bn/lyrics-to-song/ashaw/logs/bigmusic/fine/fine_mcc_mix/fixed_posemb_v0/checkpoints/step=051000-val_accu_0=9.54.ckpt"

    # for wer metrics
    umm_ckpt: "/mnt/bn/audio-diffusion/qq/logs/semantic_flash_llama/mcc/pretrain/step=0050000-loss=0.669.ckpt"

    semantic_duration: 10
    coarse_duration: 10
    fine_duration: 4
    coarse_stride: 5
    fine_stride: 3

    semantic_temperature: 1.0
    coarse_temperature: 0.9
    fine_temperature: 0.8
    sample_mode: "gumbel"

    # Model Settings
    sample_rate: 24000
    duration: 10
    lyrics_max_seq_len: 150
    semantic_frame_rate: 25
    soundstream_codebook_size: 1024
    soundstream_frame_rate: 50
    num_coarse: 4
    num_fine: 8

run_opts:
    fast_dev_run: False
    precision: 32
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm/mulan_phoneme
    batch_size: 16
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.GTInferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        soundstream_dec:
            hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            initializer: !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
                cache_dir: !ref <run_opts[cache_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
