---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

hp: !include:../hparams_x480.yaml

seed: 1996
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: /mnt/bn/zongyu-lq/logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: semantic_sparse
    version: mulan_cond_finetune
    precision: 16
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/musiclm_3ar_1024x12_x480
    profiler: simple
    flash_attn: null
    num_steps: 1_000_000
    batch_size: 60
    val_batch_size: 256
    sample_buffer_size: 600
    num_workers: 8
    learning_rate: 0.0002
    weight_decay: 0.1
    checkpointing: False
    hdfs_path: null
_checkpointing: !ref <run_opts[checkpointing]>

# gpt hyper-config
gpt_config: !new:transformers.GPT2Config
    vocab_size: 1025
    n_positions: 256
    n_ctx: 256
    n_embd: 1024
    n_layer: 24
    n_head: 16
    sparse_attn: True
    activation_function: gelu_new
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.1
    norm_fn: "rms_norm" # layer_norm, rms_norm
    layer_norm_epsilon: 0.00001
    initializer_range: 0.02
    c_attn_bias: False
    pos_type: "rope_attn" # learnable, rope, rope_attn
    qk_bias: False
    # train_len for block sparse attention
    train_len: 256
    layout_fn: "semantic_10s_layout"
    mask_file: "semantic_10s_mask.npy"
    use_cache: !apply:operator.not_ [!ref <_checkpointing>]

aed_gpt_dataset: !new:recipes.audio_lm.datasets.mcc.AEDGPTGenDataset
    resampled: True

mcc_n2m_dataset: !new:recipes.audio_lm.datasets.mcc.MCCN2MDataset
    resampled: True

mcc_gpt_dataset: !new:recipes.audio_lm.datasets.mcc.MCCGPTGenDataset
    resampled: True

playlist_dataset: !new:recipes.audio_lm.datasets.playlist.PlaylistDataset
    resampled: True

train_datasets:
    aed_gpt: !ref <aed_gpt_dataset>
    mcc_n2m: !ref <mcc_n2m_dataset>

selected_dataset_names: [aed_gpt, mcc_n2m]
weights: [3, 7]

train_dataset: !new:samantha.dataio.dataset.MultiIterableDatasetWithSampling
    datasets: !apply:recipes.audio_lm.datasets.utils.select_datasets
        - !ref <train_datasets>
        - !ref <selected_dataset_names>
    weights: !ref <weights>
    num_samples: 10_000_000
    seed: !ref <seed>

val_dataset: [!ref <mcc_gpt_dataset>, !ref <playlist_dataset>]

# datamodule configuration
pl_datamodule: !new:recipes.audio_lm.lit_modules.WDSDataModule
    train_dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    val_dataset: !ref <val_dataset>
    val_batch_size: !ref <run_opts[val_batch_size]>
    sample_buffer_size: !ref <run_opts[sample_buffer_size]>
    num_workers: !ref <run_opts[num_workers]>

# model configuration
model_cls: !name:recipes.audio_lm.modules.sparse_gpt2.GPT2LMHeadSparseModel
    config: !ref <gpt_config>
    flash_attn: !ref <run_opts[flash_attn]>
    logit_num: 1024
    use_cond: True
    cond_dim: 512
    cond_type: "linear"

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.95]
    eps: 0.00000001

scheduler_cls: !name:recipes.audio_lm.lr_schedulers.musiclm_lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: 2000
    cycle_steps: 500000
    min_lr: !ref <run_opts[learning_rate]> * 0.1

# coarse model setting
pl_module: !new:recipes.audio_lm.lit_modules.v6_3.lit_semantic.SemanticModule
    base_model_path: "/mnt/bn/zongyu-lq/logs/semantic_sparse/mulan_cond/checkpoints/step=050000-val_accu_0=34.92.pt"
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.audio_lm.modules.MaskedCrossEntropy
    extra_params: !ref <hp>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/g4/checkpoints/mulan-step=044800-median_rank_1=170-kaggle.ckpt
            - !name:recipes.audio_lm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        w2v:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1
            - !name:recipes.audio_lm.requires.model_initializer.init_w2v
              cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_last: True
      save_top_k: 10
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      monitor: val_accu_1
      mode: max
      filename: "{step:06d}-{val_accu_1:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 50
    limit_val_batches: 20
    val_check_interval: 1000
    # num_sanity_val_steps: 0
    strategy: !ref <run_opts[strategy]>
    max_steps: !ref <run_opts[num_steps]>
    precision: !ref <run_opts[precision]>
    profiler: !ref <run_opts[profiler]>
    callbacks: !ref <callbacks>
    gradient_clip_val: 1.0
    track_grad_norm: 2.0

ckpt_path: null
