---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 42
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: debug
    version: 0.2
    precision: 32
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/llm_debug/
    profiler: simple
    flash_attn: null
    num_epochs: 100
    batch_size: 1
    num_workers: 8
    learning_rate: 0.0003
    checkpointing: False

hp:
    max_token_lens: 2048
    audio_tokens_num: 100
    audio_token_dedup: true
    mask_input_for_train: false
    mask_input_for_val: true
    text_tokenizer: char

_checkpointing: !ref <run_opts[checkpointing]>

# gpt hyper-config
gpt_config: !new:transformers.GPT2Config
    vocab_size: 185
    n_positions: 2048
    n_ctx: 2048
    n_embd: 1024
    n_layer: 12
    n_head: 16
    activation_function: gelu_new
    resid_pdrop: 0.1
    embd_pdrop: 0.0
    attn_pdrop: 0.1
    layer_norm_epsilon: 0.00001
    initializer_range: 0.02
    use_cache: !apply:operator.not_ [!ref <_checkpointing>]
    summary_type: 'mean'
    summary_use_proj: True
    summary_activation: None
    summary_proj_to_labels: True
    summary_first_dropout: 0.1
    bos_token_id: 184
    eos_token_id: 184
    pad_token_id: 0

train_dataset: !new:recipes.llm_asr.datasets.GPT2ASRDataset
    path: /mnt/bn/ming-dev/data/librispeech/train_clean_100_bloom_dedup.txt
    hp: !ref <hp>
    task: joint

predict_dataset: !new:recipes.llm_asr.datasets.GPT2ASRDataset
    path: /mnt/bn/ming-dev/data/librispeech/dev_clean.json
    hp: !ref <hp>
    task: tts
    inference: True

collator: !new:recipes.llm_asr.datasets.Collator
    tokenizer_pad: 0

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    collate_fn: !ref <collator>
    shuffle: True
    drop_last: True
    pin_memory: True

predict_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    collate_fn: !ref <collator>
    shuffle: False
    drop_last: False
    pin_memory: True

# datamodule configuration
pl_datamodule: !new:recipes.llm_asr.lit_modules.DataModule
    train_dataloader: !ref <train_dataloader>
    predict_dataloader: !ref <predict_dataloader>

pl_module: !new:recipes.llm_asr.lit_modules.lit_llm.LLMModulePredict
    ckpt_path: "/mnt/bn/ming-dev/samantha_exp/train100_hubert-base-7l-km100_char/debug/version_0.2/checkpoints/epoch=24-step=5575-valid_token_acc=0.00.ckpt"
    test_dataset: !ref <predict_dataset>
    task: "tts"
    inference_out: "/root/asr_hyp.txt"
    extra_params: !ref <hp>
    required_modules:


logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>


callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      every_n_epochs: 1
      mode: max
      save_last: True
      save_top_k: 5
      save_on_train_epoch_end: True
      verbose: True
      monitor: "val_token_acc"
      filename: "{epoch:02d}-{step}-{valid_token_acc:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 50
    accumulate_grad_batches: 4
    strategy: !ref <run_opts[strategy]>
    max_epochs: !ref <run_opts[num_epochs]>
    precision: !ref <run_opts[precision]>
    profiler: !ref <run_opts[profiler]>
    callbacks: !ref <callbacks>
    gradient_clip_val: 1.0
    track_grad_norm: 2.0

ckpt_path: null
