# 2 codes
STATUS_CODE_OK = 20000000
STATUS_TEXT_OK = "OK"

# 4 codes
STATUS_CODE_EMPTY_DATA = 40000011
STATUS_TEXT_EMPTY_DATA = "EmptyData"
STATUS_CODE_INVALID_PAYLOAD = 40000020
STATUS_TEXT_INVALID_PAYLOAD = "InvalidPayload"
STATUS_TEXT_INVALID_PAYLOAD_AUDIO_FORMAT = (
    "InvalidPayload:NotSupportedInputAudioFormat"
)

STATUS_CODE_INVALID_ACCESS = 40200001
STATUS_TEXT_INVALID_ACCESS = "InvalidAccess"

STATUS_CODE_EMPTY_TEXT = 40402001
STATUS_TEXT_EMPTY_TEXT = "EmptyText"

STATUS_CODE_ILLEGAL_DATA = 40000012
STATUS_TEXT_ILLEGAL_DATA = "IllegalData:UnknownFormat"

STATUS_CODE_INVALID_DATA = 40000010
STATUS_TEXT_INVALID_DATA_TOO_SHORT_AUDIO = "InvalidData:TooShortAudio"
STATUS_TEXT_INVALID_DATA_MIR_NO_BEATS = "InvalidData:MIRNoBeats"
STATUS_TEXT_INVALID_DATA_MIR_NO_CHORDS = "InvalidData:MIRNoChords"
STATUS_TEXT_INVALID_DATA_MIR_NO_KEY = "InvalidData:MIRNoKey"
STATUS_TEXT_INVALID_DATA_MIR_NO_BEATS_CHORDS = "InvalidData:MIRNoBeatsChords"


# 5 codes
STATUS_CODE_SERVER_FAILED_INVOKE = 50000001
STATUS_TEXT_SERVER_FAILED_INVOKE = "ServerFailedInvoke"

STATUS_TEXT_DEFAULT_HANDLER_SETUP_FAILED = "DefaultHandlerSetupFailed"

STATUS_CODE_MIR_DOWNSTREAM_FAILED = 50004001

STATUS_CODE_PY_UNKNOWN = 50699999
STATUS_TEXT_PY_UNKNOWN = "PyWrapperServerUnknown"