---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 2023
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
# log_dir: hdfs://harunava/home/byte_speech_sv/weituo/mulan_exp #!apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
log_dir: /mnt/bn/audio-diffusion/t5_mulan_exp #!apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: T5_MuLan
    log_every_n_steps: 10
    version: n2m
    precision: 16
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    enable_activation_ckpt: True
    num_steps: 600000
    val_check_interval: 400
    batch_size: 72
    shuffle_buffer: 600
    val_batch_size: 128
    spec_aug: True
    text_encoder: avgpool
    music_encoder: mut
    emb_dim: 512
    seq_len: 400
    learning_rate: 4.e-5
    weight_decay: 5.e-4
    temperature: 0.1  # temperature in Multiview Coding loss

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

mcc_n2m_dataset: !new:recipes.t5_mulan.dataset.mcc.MCCN2MDatasetApril
    seq_len: !ref <run_opts[seq_len]>
    resampled: True

train_datasets:
    mcc_n2m: !ref <mcc_n2m_dataset>

selected_dataset_names: [mcc_n2m]
weights: [1.0]

train_dataset: !new:samantha.dataio.dataset.MultiIterableDataset
    datasets: !apply:recipes.mulan.dataset.utils.select_datasets
        - !ref <train_datasets>
        - !ref <selected_dataset_names>
    weights: !ref <weights>
    num_samples: 10_000_000
    seed: !ref <seed>

pl_datamodule: !new:recipes.t5_mulan.modules.pl_datamodule.MuLanDataModule
    train_dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    sample_buffer_size: !ref <run_opts[shuffle_buffer]>

pl_module: !new:recipes.t5_mulan.modules.pl_module.LitMuLanModule
    music_encoder: !ref <run_opts[music_encoder]>
    text_encoder: !ref <run_opts[text_encoder]>
    emb_dim: !ref <run_opts[emb_dim]>
    spec_aug: !ref <run_opts[spec_aug]>
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    temperature: !ref <run_opts[temperature]>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <log_dir>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: median_rank_0
      mode: min
      filename: mulan-{step:06d}-{median_rank_0:.0f}-kaggle
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: median_rank_1
      mode: min
      filename: mulan-{step:06d}-{median_rank_1:.0f}-kaggle
    - !new:recipes.mulan.modules.ema.EMA
      decay: 0.999

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: True
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    use_distributed_sampler: False
    logger: !ref <logger>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    precision: !ref <run_opts[precision]>
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
    num_sanity_val_steps: 0
