---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

# running parameters`
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]

run_opts:
  fast_dev_run: False
  hdfs_log_dir: "hdfs:///home/byte_speech_sv/ju-chiang.wang/umm_tag"
  log_name: 'karaoke'
  version: 'test_dataloader'
  precision: 16-mixed
  accelerator: 'auto'
  num_workers: 10
  pin_memory: True
  log_dir: logs
  val_check_interval: 5000  # validate every n steps of training
  pre_vq_latent: True
  cycle_steps: 200000
  weight_decay: 0.1
  warmup_steps: 2000

extra_params:
  final_pooling: True
  tag_types: ['genres', 'year', 'key', 'tempo', 'instruments']
  tag_loss_weights: [0.3, 0.1, 0.1, 0.1, 1.0]


################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
train_params:
  learning_rate: 0.0001
  max_epochs: -1
  batch_size: 16
  scheduler_patience: 20
  scheduler_decay_factor: 0.8
  devices: 'auto'
  shuffle_buffer: 100
  data_id: 6667

val_params:
  data_id: 5491
  num_sanity_val_steps: 2
  batch_size: 16
  per_node_max_num: 2000 # should be greater than num_iter * num_workers * batch_size
  check_val_every_n_epoch: 1

test_params:
  data_id: 5491 # to be determined
  batch_size: 1
  infer_batch_size: 32
  per_node_max_num: 6000


################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 24000        # sampling rate for audio
  sample_len: 30.0            # duration in sec for input  #{24 or 6}


################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

train_transformed: !new:recipes.mir2.parquet_dataset.karaoke.MusicFmParquetDataset
  sample_rate: !ref <audio[sampling_rate]>
  data_id: !ref <train_params[data_id]>
  batch_size: !ref <train_params[batch_size]>
  shuffle_buffer: !ref <train_params[shuffle_buffer]>
  sample_len: !ref <audio[sample_len]>
  tag_types: !ref <extra_params[tag_types]>

val_transformed: !new:recipes.mir2.parquet_dataset.karaoke.MusicFmParquetDataset
  sample_rate: !ref <audio[sampling_rate]>
  data_id: !ref <val_params[data_id]>
  batch_size: !ref <val_params[batch_size]>
  resampled: False
  sample_len: !ref <audio[sample_len]>
  tag_types: !ref <extra_params[tag_types]>
  validation: True

test_transformed: !new:recipes.mir2.parquet_dataset.karaoke.MusicFmParquetDataset
  sample_rate: !ref <audio[sampling_rate]>
  data_id: !ref <test_params[data_id]>
  batch_size: !ref <test_params[batch_size]>
  infer_batch_size: !ref <test_params[infer_batch_size]>
  resampled: False
  sample_len: !ref <audio[sample_len]>
  tag_types: !ref <extra_params[tag_types]>
  test: True


# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <train_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

val_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

test_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <test_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

# datamodule configuration
pl_datamodule: !new:recipes.beat.pl_modules.pl_datamodule.BeatDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>
