---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

hp: !include:../hparams_x480.yaml

seed: 1996
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: fine_sparse
    version: 0.4
    precision: 16
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/musiclm_3ar_128x15_x480
    profiler: simple
    flash_attn: null
    num_epochs: 100
    batch_size: 3
    num_workers: 8
    learning_rate: 0.0003
    weight_decay: 0.1
    checkpointing: False
    hdfs_path: null
_checkpointing: !ref <run_opts[checkpointing]>

# gpt hyper-config
gpt_config: !new:transformers.GPT2Config
    vocab_size: !ref <hp[num_res]> * <hp[quant_token_num]> + 1
    n_positions: 6016
    n_ctx: 6016
    n_embd: 1024
    n_layer: 24
    n_head: 16
    activation_function: gelu_new
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.1
    norm_fn: "rms_norm" # layer_norm, rms_norm
    layer_norm_epsilon: 0.00001
    initializer_range: 0.02
    c_attn_bias: False
    pos_type: "rope_attn" # learnable, rope, rope_attn
    qk_bias: False
    # train_len for block sparse attention
    train_len: 6016
    layout_fn: "fine_10s_layout_v3"
    mask_file: "fine_10s_mask_v6.npy"
    use_cache: !apply:operator.not_ [!ref <_checkpointing>]

train_dataset: !new:recipes.audio_lm.datasets.AudioLMDataset
    sample_rate: 24000
    sample_duration: 10
    meta_paths:
        - /mnt/bd/litang-lq-music-npy11/15m_filter_trim.txt
        - /mnt/bn/diff-music-data-b25af381/9M-aed-sieved-metalist.txt

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle: True
    drop_last: True
    pin_memory: True

# datamodule configuration
pl_datamodule: !new:recipes.audio_lm.lit_modules.DataModule
    train_dataloader: !ref <train_dataloader>

# model configuration
model_cls: !name:recipes.audio_lm.modules.sparse_gpt2.GPT2LMHeadSparseModel
    config: !ref <gpt_config>
    flash_attn: !ref <run_opts[flash_attn]>
    logit_num: !ref <hp[num_fine]> * <hp[quant_token_num]>
    use_cond: False
    cond_dim: 128
    cond_type: linear

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

_steps_per_epoch: !apply:operator.length_hint [!ref <train_dataloader>]
_world_size: !apply:recipes.audio_lm.utils.env.getenv_int ["WORLD_SIZE", 1]
scheduler_cls: !name:recipes.audio_lm.lr_schedulers.musiclm_lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: 2000
    cycle_steps: 500000
    min_lr: !ref <run_opts[learning_rate]> * 0.1

# coarse model setting
# for 3AR, it needs Mulan, W2V, SoundStream
# for 2AR, it needs Mulan, SoundStream
pl_module: !new:recipes.audio_lm.lit_modules.v6.lit_fine.FineModule
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.audio_lm.modules.MaskedCrossEntropy
    extra_params: !ref <hp>
    required_modules:
        sound_stream:
            - hdfs://haruna/home/byte_speech_sv/user/litang/vqgan_dev/2023-03-24_ss_dev_stft_x480_small_encoder/sound_stream_190k/
            - !name:recipes.audio_lm.requires.model_initializer.init_sound_stream
              cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      every_n_train_steps: 10
      mode: max
      save_last: True
      save_top_k: 200
      save_on_train_epoch_end: True
      verbose: True
      monitor: accu
      filename: "{epoch:02d}-{step}-{accu:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.audio_lm.callbacks.hdfs_callback.HdfsSavingCallback
      hdfs_path: !ref <run_opts[hdfs_path]>
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      n_log: 1000

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 1
    strategy: !ref <run_opts[strategy]>
    max_epochs: !ref <run_opts[num_epochs]>
    precision: !ref <run_opts[precision]>
    profiler: !ref <run_opts[profiler]>
    callbacks: !ref <callbacks>
    gradient_clip_val: 1.0

ckpt_path: null
