---

################################################################################
##########                      APP CONFIGURATION                    ##########
################################################################################

submodule_name: 'bigtts'

repo:
  func_path: 'recipes.serving.handler.api'
  preload_model_func_name: 'preload_models'

inputs:
  - source: 'data'
    type: 'bytes'
    name: 'prompt_wav'
  - source: 'payload'
    type: 'str'
    name: 'prompt_type'
  - source: 'payload'
    type: 'str'
    name: 'timbre_name'
  - source: 'payload'
    type: 'str'
    name: 'text'

outputs:
  -
    destination: 'data'
    name: 'result'
  - destination: 'payload'
    name: 'prompt_wav_url'
    type: 'str'
  - destination: 'payload'
    name: 'prompt_text'
    type: 'str'
  - destination: 'payload'
    name: 'generated_wav_url'
    type: 'str'
  - destination: 'payload'
    name: 'message'
    type: 'str'
