# pytorch_lightning==1.8.6
seed_everything: 4444
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

training_params:
    batch_size: 6
    num_workers: 10
    duration: [3, 5, 8, 10]
    shuffle_buffer_size: 0
    valid_batch_size: 5

    sample_rate: 44100
    n_fft: 1024
    hop_length: 49
    vae_dim: 128
    beta: 1e-3
    hidden_size: 1536
    n_mels: 160
    n_chroma: 12
    audio_channels: 2

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.sacodec.datasets.sacodec_dataset.ParquetDataModule
    # train_data_id: 2196 # wtl's vocoder dataset
    # valid_data_id: 2124
    # train_data_id: 6848 # zhongyi's sft dataset
    train_data_id: 8424 # wtl's original diffusion dataset
    valid_data_id: 8394
    # train_data_id: 1421 # US
    # valid_data_id: 444
    train_batch_size: !ref <training_params[batch_size]>
    valid_batch_size: !ref <training_params[valid_batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer_size]>
    num_workers: !ref <training_params[num_workers]>
    n_channels: !ref <training_params[audio_channels]>
    dataset_samplerate: !ref <training_params[sample_rate]>
    audio_duration: !ref <training_params[duration]>
    valid_audio_duration: [20]
    max_num_crops: 12
    resample_to_24k: True
    audio_augmentations: null
    # prefetch_factor: !ref <training_params[dataloader_prefetch_factor]>

pl_module: !new:recipes.sacodec.modules.sacodec_module_umm.SACodecModule
    sample_rate: !ref <training_params[sample_rate]>
    initial_learning_rate: 1e-4
    mel_loss_coeff: 15 # 15 for descript / 45 for single
    melspec_loss_type: descript
    mrd_loss_coeff: 0.1
    chroma_loss_coeff: 100
    mag_phase_coeff: 0.5
    sdr_loss_coeff: 0.5
    num_warmup_steps: 5000 # Optimizers warmup steps
    pretrain_mel_steps: 30000  # 0 means GAN objective from the first iteration
    kl_warmup_steps: 50000

    n_fft: !ref <training_params[n_fft]>
    hop_length: !ref <training_params[hop_length]>
    n_chroma: !ref <training_params[n_chroma]>
    n_mels: !ref <training_params[n_mels]>
    audio_channels: !ref <training_params[audio_channels]>

    encoder_cls: !name:recipes.sacodec.models.sacodec_umm.STFTEncoderVAEPostUMM
        n_fft: !ref <training_params[n_fft]>
        hop_length: !ref <training_params[hop_length]>
        vae_dim: !ref <training_params[vae_dim]>
        beta: !ref <training_params[beta]>
        hidden_size: !ref <training_params[hidden_size]>
        audio_channels: !ref <training_params[audio_channels]>
        even_pad: True
        umm_version: umm_cn_rope
        umm_block_layers: 1
        block_layers: [1, 4, 4]

    decoder_cls: !name:recipes.sacodec.models.sacodec.ISTFTDecoder
        n_fft: !ref <training_params[n_fft]>
        hop_length: !ref <training_params[hop_length]>
        vae_dim: !ref <training_params[vae_dim]>
        hidden_size: !ref <training_params[hidden_size]>
        audio_channels: !ref <training_params[audio_channels]>
        even_pad: True
        block_layers: [8, 4, 1]
        final_hidden_size: 3072


run_opts:
    log_dir: logs
    tensorboard_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: "sacodec_v5"
    hdfs_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/andrew.shaw
    version: 'test'
    val_check_interval: 20000


logger: !new:pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    project: !ref <run_opts[log_name]>
    name: !ref <run_opts[version]>
    # version: !ref <run_opts[version]>

trainer: !new:pytorch_lightning.Trainer
    logger: !ref <logger>
    callbacks:
        - !new:pytorch_lightning.callbacks.LearningRateMonitor
        - !new:pytorch_lightning.callbacks.ModelSummary
          max_depth: 2
        - !new:samantha.callbacks.HDFSModelCheckpoint
          monitor: val_loss
          filename: sacodec_checkpoint_{epoch}_{step}_{val_loss:.4f}
          dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
          hdfs_path: !ref <run_opts[hdfs_path]>/<run_opts[log_name]>/<run_opts[version]>
          every_n_train_steps: !ref <run_opts[val_check_interval]>
          mode: min
          save_top_k: 10
          save_last: true

    # Lightning calculates max_steps across all optimizer steps (rather than number of batches)
    # 2M equals to 1M steps per generator and 1M per discriminator
    max_steps: 1000000
    # You might want to limit val batches when evaluating all the metrics, as they are time-consuming
    limit_val_batches: 40
    accelerator: auto
    strategy: ddp_find_unused_parameters_true
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    log_every_n_steps: 100
    num_sanity_val_steps: 0
    val_check_interval: !ref <run_opts[val_check_interval]>
