# pytorch_lightning==1.8.6
seed_everything: 4444
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

training_params:
    batch_size: 14
    num_workers: 8
    duration: [5]
    shuffle_buffer_size: 0

    sample_rate: 44100
    n_fft: 1024
    hop_length: 49
    vae_dim: 128
    beta: 1e-3
    hidden_size: 1536
    n_mels: 160
    n_chroma: 12
    audio_channels: 2

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.sacodec.datasets.instrumental.InstrumentalWebDataModule
    dataset_name: "SSTK_US_1M_44k"
    val_split: "SSTK_US_44k"
    sample_rate: !ref <training_params[sample_rate]>
    duration: !ref <training_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer_size]>
    num_workers: !ref <training_params[num_workers]>
    pin_memory: True
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.1
    normalize_audio: False
    avoid_vocal: False
    max_vocal_threshold: 0.5
    text_type: sstk_dropout
    crop_type: random # for umm token2wav, random crop instead of section
    max_num_crops: 4
    mixed_ratio: 0.0
    use_pipe: False

pl_module: !new:recipes.sacodec.modules.sacodec_module.SACodecModule
    sample_rate: !ref <training_params[sample_rate]>
    initial_learning_rate: 1e-4
    mel_loss_coeff: 15 # 15 for descript / 45 for single
    melspec_loss_type: descript
    mrd_loss_coeff: 0.1
    chroma_loss_coeff: 100
    mag_phase_coeff: 0.5
    sdr_loss_coeff: 0.5
    num_warmup_steps: 5000 # Optimizers warmup steps
    pretrain_mel_steps: 10000  # 0 means GAN objective from the first iteration
    kl_warmup_steps: 40000

    n_fft: !ref <training_params[n_fft]>
    hop_length: !ref <training_params[hop_length]>
    n_chroma: !ref <training_params[n_chroma]>
    n_mels: !ref <training_params[n_mels]>
    audio_channels: !ref <training_params[audio_channels]>

    encoder_cls: !name:recipes.sacodec.models.sacodec.STFTEncoderVAE
        n_fft: !ref <training_params[n_fft]>
        hop_length: !ref <training_params[hop_length]>
        vae_dim: !ref <training_params[vae_dim]>
        beta: !ref <training_params[beta]>
        hidden_size: !ref <training_params[hidden_size]>
        audio_channels: !ref <training_params[audio_channels]>
        block_layers: [1, 4, 4]

    decoder_cls: !name:recipes.sacodec.models.sacodec.ISTFTDecoder
        n_fft: !ref <training_params[n_fft]>
        hop_length: !ref <training_params[hop_length]>
        vae_dim: !ref <training_params[vae_dim]>
        hidden_size: !ref <training_params[hidden_size]>
        audio_channels: !ref <training_params[audio_channels]>
        block_layers: [8, 4, 1]
        final_hidden_size: 3072


run_opts:
    log_dir: /mnt/bn/lyrics-to-song/ashaw/logs/sacodec
    tensorboard_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: "sacodec_v5"
    version: 'test'
    val_check_interval: 20000


logger: !new:pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    project: !ref <run_opts[log_name]>
    name: !ref <run_opts[version]>
    # version: !ref <run_opts[version]>

trainer: !new:pytorch_lightning.Trainer
    logger: !ref <logger>
    callbacks:
        - !new:pytorch_lightning.callbacks.LearningRateMonitor
        - !new:pytorch_lightning.callbacks.ModelSummary
          max_depth: 2
        - !new:pytorch_lightning.callbacks.ModelCheckpoint
          monitor: val_loss
          filename: sacodec_checkpoint_{epoch}_{step}_{val_loss:.4f}
          dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
          every_n_train_steps: !ref <run_opts[val_check_interval]>
          mode: min
          save_top_k: 10
          save_last: true

    # Lightning calculates max_steps across all optimizer steps (rather than number of batches)
    # 2M equals to 1M steps per generator and 1M per discriminator
    max_steps: 1000000
    # You might want to limit val batches when evaluating all the metrics, as they are time-consuming
    limit_val_batches: 40
    accelerator: auto
    strategy: ddp_find_unused_parameters_true
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    log_every_n_steps: 100
    val_check_interval: !ref <run_opts[val_check_interval]>
