---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path:

# running parameters
run_opts:
  fast_dev_run: False
  tensorboard_dir: 'hdfs://harunava/home/byte_speech_sv/amy/log/'
  log_name: 'structure'
  version: '0.1'
  precision: 32
  accelerator: 'auto'
  num_workers: 5
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

train_params:
  learning_rate: 0.0005
  max_epochs: -1
  batch_size: 32
  shuffle_buffer: 1000
  scheduler_patience: 40
  scheduler_decay_factor: 0.9
  devices: 'auto'
  num_iter: 100

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 16000       # sampling rate for audio
  sample_len: 36.0           # duration in sec for input  #{24 or 6}
  hop_length: 512            # hop length to calculate spectrogram
  n_fft: 1024                # number of fft to calculate spectrogram
  augmentation: True        # {true, false} use data augmentation
  input_feature: "hcqt"      # input feature type {mel, hcqt}
  semitone_scale: 1
  sample_hop: 9

labels:
  label_hop: 0.192
  enable_short: True
  n_boundary: 2
  n_function: 7
  alpha: 0.9

Postprosessing:
  n_top_bound: 14            # number of top probabilities for boundary
  n_top_chobound: 7          # number of top probabilities for chorus boundary
  n_top_choseg: 3            # number of top probabilities for chorus segment

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.structure.preprocess.common.StructurePreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <labels[label_hop]>
  augmentation: !ref <audio[augmentation]>

# dataloader configuration
train_dataloader: !apply:recipes.structure.utils.datasets.get_train_dataset
  dataset_names: ["labeled"]
  preprocessor: !ref <preprocessor>
  shuffle_buffer: !ref <train_params[shuffle_buffer]>
  batch_size: !ref <train_params[batch_size]>
  num_iter: !ref <train_params[num_iter]>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  to_tuple: "audio boundary_label function_label chorus_only"

val_dataloader: !apply:recipes.structure.utils.datasets.get_validation_dataset
  preprocessor: !ref <preprocessor>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

test_dataloader: !apply:recipes.structure.utils.datasets.get_testing_dataset
  preprocessor: !ref <preprocessor>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

# datamodule configuration
pl_datamodule: !new:recipes.structure.pl_modules.pl_datamodule.StructureDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

model_params:
  n_layers: 5                # number of layers for specTNT
  spec_dim: 96               # number of spectral dimension for specTNT
  spec_heads: 4              # number of spectral head for specTNT
  temporal_dim: 128          # number of temporal dimension for specTNT
  temporal_heads: 8
  resnet_pools: [[2, 3], [2, 1], [1, 2]]
  chord_pool: [2]

model: !apply:recipes.structure.models.get_models.get_specTNT
  sample_len: !ref <audio[sample_len]>
  sample_rate: !ref <audio[sampling_rate]>
  resnet_pool_sizes: !ref <model_params[resnet_pools]>
  n_fft: !ref <audio[n_fft]>
  depth: !ref <model_params[n_layers]>
  temporal_dim: !ref <model_params[temporal_dim]>
  temporal_heads: !ref <model_params[temporal_heads]>
  spec_dim: !ref <model_params[spec_dim]>
  spec_heads: !ref <model_params[spec_heads]>
  n_boundary: !ref <labels[n_boundary]>
  n_function: !ref <labels[n_function]>

pl_module: !new:recipes.structure.pl_modules.pl_module.LitStructure
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  alpha: !ref <labels[alpha]>
  n_fft: !ref <audio[n_fft]>
  sampling_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  label_hop: !ref <labels[label_hop]>
  sample_hop: !ref <audio[sample_hop]>
  n_top_bound: !ref <Postprosessing[n_top_bound]>
  enable_short: !ref <labels[enable_short]>
  n_boundary: !ref <labels[n_boundary]>
  n_function: !ref <labels[n_function]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

callbacks:
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    every_n_epochs: 1
    mode: "max"
    save_last: True
    monitor: summary
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'
  - !new:recipes.structure.pl_modules.callbacks.prediction_writer.StructureWriter
    output_path: null

trainer: !new:pytorch_lightning.Trainer
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  strategy: "ddp_find_unused_parameters_true"
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  callbacks: !ref <callbacks>
