---
# "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/huangzhiying.92/exp/samantha_bigtts_ref_enc/text2semantic/sft_WFVAE_v2_labv3_punc_data_id590_bt14000_16A100_accu5_byteT5_scr0.0_freezeTrue_langFalse/checkpoints/epoch=00-step=95000-kl_loss=0.12.ckpt"
run_opts:
    precision: 32
    strategy: ddp
    ar_model_name: VAET2SLangSpkModule
    ar_ckpt_path: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/huangzhiying.92/exp/samantha_bigtts_ref_enc/text2semantic/sft_WFVAE_v2_labv3_punc_data_id590_bt14000_16A100_accu5_byteT5_scr0.0_freezeTrue_langFalse/checkpoints/epoch=00-step=95000-kl_loss=0.12.ckpt"
    output_dir: 'taozi_outputs'
    meta_lst: ''
    num_workers: 4
    wvae_encoder: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wangxin.colin/ckpts/wvae_1.0/wavevae_encoder_%d.pt
    wvae_decoder: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wangxin.colin/ckpts/wvae_1.0/wavevae_decoder_%d.pt
    fast_dev_run: False
    seed: 1996
    prompt_tacolab_dir: ""
    infer_tacolab_dir: ""
    use_sy: False
    use_lang_id: False
    lang_tokens_num: 0
    lang2id: 'recipes/text2semantic/datasets/dict/lang2id.json'
    max_length: 8000
    use_spk_id: True
    spk_tokens_num: 16384
    spk2id: 'recipes/text2semantic/datasets/dict/spk2id.json'
    infer_spk_name: 'duibiao/sinong_conversation'
    get_lang_by_tacolab: False
    save_tacolab: False
    use_bpe: True
    tokenizer_type: 'byte-T5-base'
    tag_id: 3
    bpe_dir: 'resource/models/byte-T5-base'
    use_prompt: False
    input_type: '2dim'
    infer_mode: 'online'

predict_dataset: !new:recipes.text2semantic.datasets.meta_based_dataset.MetaBasedDataset
    meta_lst: !ref <run_opts[meta_lst]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:recipes.text2semantic.lit_modules.lit_data.DataModule
    predict_dataloader: !ref <dataloader>

pl_module: !new:recipes.text2semantic.lit_modules.lit_infer_lang_spk.BigTTSWVAEInferLangSpk
    ar_model_name: !ref <run_opts[ar_model_name]>
    ckpt_path: !ref <run_opts[ar_ckpt_path]>
    wvae_encoder: !ref <run_opts[wvae_encoder]>
    wvae_decoder: !ref <run_opts[wvae_decoder]>
    output_dir: !ref <run_opts[output_dir]>
    seed: !ref <run_opts[seed]>
    prompt_tacolab_dir: !ref <run_opts[prompt_tacolab_dir]>
    infer_tacolab_dir: !ref <run_opts[infer_tacolab_dir]>
    use_lang_id: !ref <run_opts[use_lang_id]>
    lang_tokens_num: !ref <run_opts[lang_tokens_num]>
    lang2id: !ref <run_opts[lang2id]>
    max_length: !ref <run_opts[max_length]>
    use_spk_id: !ref <run_opts[use_spk_id]>
    spk_tokens_num: !ref <run_opts[spk_tokens_num]>
    spk2id: !ref <run_opts[spk2id]>
    infer_spk_name: !ref <run_opts[infer_spk_name]>
    get_lang_by_tacolab: !ref <run_opts[get_lang_by_tacolab]>
    save_tacolab: !ref <run_opts[save_tacolab]>
    use_bpe: !ref <run_opts[use_bpe]>
    bpe_dir: !ref <run_opts[bpe_dir]>
    tokenizer_type: !ref <run_opts[tokenizer_type]>
    tag_id: !ref <run_opts[tag_id]>
    use_prompt: !ref <run_opts[use_prompt]>
    input_type: !ref <run_opts[input_type]>
    infer_mode: !ref <run_opts[infer_mode]>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
