---

run_opts:
    precision: 32
    strategy: ddp
    ar_model_name: VAET2SStopLangv2MultidimModule
    ar_ckpt_path: epoch=00-step=55000-kl_loss=0.82.ckpt
    output_dir: output_wavs
    meta_lst: testset/inner/inner_long_en_meta.lst
    num_workers: 4
    wvae_encoder: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/wangxin.colin/ckpts/wvae/wavevae_encoder_%d.pt # for va
    wvae_decoder: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/wangxin.colin/ckpts/wvae/wavevae_decoder_%d.pt # for va
    # wvae_encoder: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wangxin.colin/ckpts/wvae/wavevae_encoder_%d.pt # for cn
    # wvae_decoder: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wangxin.colin/ckpts/wvae/wavevae_decoder_%d.pt # for cn
    fast_dev_run: False
    seed: 1996
    prompt_tacolab_dir: ""
    infer_tacolab_dir: ""
    use_sy: False
    use_lang_id: False
    lang_tokens_num: 0
    lang2id: 'recipes/text2semantic/datasets/dict/lang2id.json'
    max_length: 8000
    use_spk_id: True
    spk_tokens_num: 16384
    spk2id: 'recipes/text2semantic/datasets/dict/spk2id.json'
    infer_spk_name: null
    get_lang_by_tacolab: False
    save_tacolab: False
    use_bpe: True
    tokenizer_type: 'flan-T5-large'
    tag_id: 3
    bpe_dir: 'resource/models/flan-T5-large'
    use_prompt: False
    input_type: '2dim'
    use_ref_enc: False
    use_sp: True
    module_cache: ".module_cache"
    max_paragraph_phoneme_size_zh: 240
    max_paragraph_phoneme_size_en: 240
    sil_interval: 0.3

predict_dataset: !new:recipes.text2semantic.datasets.meta_based_dataset.MetaBasedDataset
    meta_lst: !ref <run_opts[meta_lst]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:recipes.text2semantic.lit_modules.lit_data.DataModule
    predict_dataloader: !ref <dataloader>

pl_module: !new:recipes.text2semantic.lit_modules.lit_infer_lang_spk_online_streaming.BigTTSWVAEInferLangSpk
    ar_model_name: !ref <run_opts[ar_model_name]>
    ckpt_path: !ref <run_opts[ckpt_path]>
    wvae_encoder: !ref <run_opts[wvae_encoder]>
    wvae_decoder: !ref <run_opts[wvae_decoder]>
    output_dir: !ref <run_opts[output_dir]>
    seed: !ref <run_opts[seed]>
    prompt_tacolab_dir: !ref <run_opts[prompt_tacolab_dir]>
    infer_tacolab_dir: !ref <run_opts[infer_tacolab_dir]>
    use_lang_id: !ref <run_opts[use_lang_id]>
    lang_tokens_num: !ref <run_opts[lang_tokens_num]>
    lang2id: !ref <run_opts[lang2id]>
    max_length: !ref <run_opts[max_length]>
    use_spk_id: !ref <run_opts[use_spk_id]>
    spk_tokens_num: !ref <run_opts[spk_tokens_num]>
    spk2id: !ref <run_opts[spk2id]>
    infer_spk_name: !ref <run_opts[infer_spk_name]>
    get_lang_by_tacolab: !ref <run_opts[get_lang_by_tacolab]>
    save_tacolab: !ref <run_opts[save_tacolab]>
    use_bpe: !ref <run_opts[use_bpe]>
    bpe_dir: !ref <run_opts[bpe_dir]>
    tokenizer_type: !ref <run_opts[tokenizer_type]>
    tag_id: !ref <run_opts[tag_id]>
    use_prompt: !ref <run_opts[use_prompt]>
    input_type: !ref <run_opts[input_type]>
    use_ref_enc: !ref <run_opts[use_ref_enc]>
    use_sp: !ref <run_opts[use_sp]>
    module_cache: !ref <run_opts[module_cache]>
    max_paragraph_phoneme_size_zh: !ref <run_opts[max_paragraph_phoneme_size_zh]>
    max_paragraph_phoneme_size_en: !ref <run_opts[max_paragraph_phoneme_size_en]>
    sil_interval: !ref <run_opts[sil_interval]>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
