---

name: SAMANTHA
trigger:
  change:
  push:
    branches: [master]
    types: [branch]
jobs:
  lint:
    image: hub.byted.org/base/samantha_preview:1.0.0.43
    steps:
      - uses: actions/checkout
        inputs:
          depth: 1
          submodules: False
      - name: isort
        commands:
          - git ls-files samantha | grep -E "\.py$" | xargs isort --check-only
      - name: black
        commands:
          - git ls-files samantha | grep -E "\.py$" | xargs black --check --diff --color
      - name: flake8
        if: True
        commands:
          - git ls-files samantha | grep -E "\.py$" | xargs flake8 --count --statistics
      - name: yamllint
        if: True
        commands:
          - yamllint samantha recipes --no-warnings
  unittest:
    image: none
    runs-on:
      cluster: gpu
      linux: { }
    steps:
      - name: check env
        commands:
          - nvidia-smi
      - uses: actions/checkout
        inputs:
          depth: 1
          submodules: True
      - name: unittest
        commands:
          - sh tests/.run-coverage.sh
      - uses: actions/report
        if: True
        inputs:
          includes:
            - "report.xml"
      - uses: actions/codecov
        inputs:
          file: "coverage.xml"
