---
# @hanoihantrakul 18APR2024
# This training config exists because Ren Yi, Qingqing and myself were trying to
# ablate the effectiveness of the ConformerUMM, ConvUMM and DualUMM on the 
# downstream ZH Lyrics2Song task.
# 
# We wanted to train from scratch Stage1, Stage2 and Stage3 model using new data
# from Parquet ID 2255. 
#
# There are two configurations for this model:
# `umm_stage3_2255mixedZHEN.yaml` which trains on 2255mixedZHEN only <-- This config
# `umm_stage3_2255mixedZHEN+2375Speech.yaml` which takes trains on additional speech data. This makes the model more comparable to old MixUMM model.
#
# The associated stage2 config is `umm_stage2_2255mixedZHEN.yaml`
# This model has 723M params.
# With batch_size=6 and max_duration=60 I can get 66.20GB GPU utilization.
#


################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: !ref last.ckpt

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    frame_rate: 25
    n_mels: 128
    n_chroma: 12
    n_fft: 2048
    win_length: 2048
    hop_length: 240
    feature_cmvn: "recipes/datasets/mcc/data_ids=794.stats.pt" # we need this because original mkii ConformerUMM normalized using these statistics
    tokenizer:  # stage2 apply language tokenizer to both EN and CN

    num_segments: 3
    min_duration: 5
    max_duration: 60


# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    hdfs_log_dir: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/qinxin.025/logs"
    log_dir: logs
    log_name: umm2_conformer_2255mixedZHEN
    version: !ref stage3_reg1_2255mixedZHEN_2375Speech_optim_mem_<extra_params[tokenizer]>_<config[vq_type]><config[vq_codebook_size]>x<config[vq_codebook_dim]>
    precision: "bf16-mixed"
    num_workers: 4
    accelerator: auto
    warmup_steps: 1000
    max_steps: 5000000
    val_check_interval: 5000 # 14APR2024 @hanoihantrakul set limit_train_val_batches=1 so that validation loop is called
    ckpt_interval: 5000
    batch_size: 5 # There are VQ params so have to reduce memory
    
    # tokenizer setup #
    # cycle_steps: 500000
    # weight_decay: 0.1
    # learning_rate: 1.0e-4   
    
    # diffusion setup #
    weight_decay:  0.001
    cycle_steps: 500000
    learning_rate: 1.0e-4 #5.0e-5   # diffusion 5e-5


    shuffle_buffer: 800 # 8000 # See above comments on why I picked this number
    gradient_clip_val: 0.2 # change to diffsion setup -> 0.2 (1.0)
    checkpointing: False
    # num_spectrogram_val_samples_for_plotting: 8 # As of 13APR2024 This new flag controls the number of spectrograms from the validation dataset to plot to Merlin


################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

data:
  save_ckpt_interval: 5000
  train_dataset_ids: ["CN:9824","CN:9825","CN:13588"]
  train_dataset_weights: [5,5,1]
  val_dataset_ids: ["CN:9824"]
  val_dataset_weights: [1]
  predict_dataset_ids: ["CN:9824"]
  predict_dataset_weights: [1]

  train_batcher:
    type: "TokenBucketBatcher" # TokenBucketBatcher
    dynamic_batch: True
    maximum_bucket_size: 6000000 #6000000   
    bucket_schedule_key: "audio_shape"
    bucket_skip_warning_num: 100
    frame_rate: 25
    sample_rate: 24000
    # bucket_schedule_key: "audio_shape"
    # bucket_secondary_key: "text_length"
    # instrumental_target_ratio: 3.0   #偏小？设置大一点；
    buckets:
      [
        120000,
        240000,
        360000,
        480000,
        600000,
        720000,
        840000,
        960000,
        1080000,
        1200000,
        1320000,
        1440000,
        1560000,
        1680000,
        1800000,
        1920000,
        2040000,
        2160000,
        2280000,
        2400000,
        2520000,
        2640000,
        2760000,
        2880000,
        # 3000000,
        # 3120000,
        # 3240000,
        # 3360000,
        # 3480000,
        # 3600000,
        # 3720000,
        # 3840000,
        # 3960000,
        # 4080000,
        # 4200000,
        # 4320000,
        # 4440000,
        # 4560000,
        # 4680000,
        # 4800000,
        # 4920000,
        # 5040000,
        # 5160000,
        # 5280000,
        # 5400000,
        # 5520000,
        # 5640000,
        # 5760000,
        # 5880000,
        # 6000000,
      ]

  val_batcher:
    type: "TokenBucketBatcher"
    dynamic_batch: True
    maximum_bucket_size: 1440000
    bucket_schedule_key: "audio_shape"
    bucket_skip_warning_num: 100
    frame_rate: 25
    sample_rate: 24000
    buckets:
      [
        120000,
        240000,
        360000,
        480000,
        600000,
        720000,
        840000,
        960000,
        1080000,
        1200000,
        1320000,
        1440000,
      ]


  train_item_transform: # This is correctly indented
    - type: "ConvertMetaToDict"
    - type: "MusicParser44100"
      in_key: "audio"
      out_key: "audio"
      min_len: 10.0
      max_len: 800.0 #second
      stereo: True
    - type: "NormalizeAudioToFloat32"
      in_key: "audio"
      out_key: "audio"
    - type: "MusicWavMSRResample"
      out_key: ["audio_24000", "audio_44100"]
      in_key: "audio"
      sample_rate: [24000, 44100]
    - type: "CheckDataType"
      out_key: "data_type"
    - type: "UtteranceSegmentSampler"
      out_key: "audio_slice"
      num_segments: !ref <extra_params[num_segments]> # get number of data from one audio to
      full_song: True
      min_duration: !ref <extra_params[min_duration]> # min_duration 20 seconds
      max_duration: !ref <extra_params[max_duration]> # max_duration 2 min (2b conformer maxinput)
    - type: "SongSliceAudioCutWithMetaData"
      in_key: "audio_slice"
      out_key: "audio_slice"
      audio_key: ['audio_24000', 'audio_44100']
      duration_leeway_in_s: 2.0
      sample_rate: [24000, 44100]

    - type: "MusicMetaRWTransform"
      in_key: "audio_slice"
      out_key: null
      overwrite_item: true
      maybe_return_list_output: true

    - type: "TextNormalizer"
      in_key: "text"

    - type: "SanityCheck"
      keys: ["uttid", "audio_24000", "audio_44100", "meta", "data_type", "text", "audio_shape"]

  train_batch_transform: # <-- This should be here, at the same level as train_item_transform
    - type: AudioCollate
      in_key: "audio_24000"
      length_key: "audio_24000_length" #output audio_length
      stereo: False
      pad_value: 0.0

    - type: AudioCollate
      in_key: "audio_44100"
      length_key: "audio_44100_length"
      stereo: True
      pad_value: 0.0

    - type: NestListCollate
      key_list: ["uttid","data_type","text","audio_shape"]
      to_tensor: False
    
    - type: MixTokenCollate
      in_key: "text"
      out_key: "text_id"
      bpe_tokenizer_path: "/opt/tiger/tokenizer/bert-base-multilingual-uncased"
  
  val_item_transform: # This is correctly indented
    - type: "ConvertMetaToDict"
    - type: "MusicParser"
      in_key: "audio"
      out_key: "audio"
      min_len: 10.0
      max_len: 800.0 #second
      stereo: True
    - type: "NormalizeAudioToFloat32"
      in_key: "audio"
      out_key: "audio"
    - type: "MusicWavMSRResample"
      out_key: ["audio_24000", "audio_44100"]
      in_key: "audio"
      sample_rate: [24000, 44100]
    - type: "CheckDataType"
      out_key: "data_type"
    - type: "UtteranceSegmentSampler"
      out_key: "audio_slice"
      num_segments: !ref <extra_params[num_segments]> # get number of data from one audio
      full_song: True
      min_duration: !ref <extra_params[min_duration]> # min_duration 20 seconds
      max_duration: !ref <extra_params[max_duration]> # max_duration 2 min 
    - type: "SongSliceAudioCut"
      in_key: "audio_slice"
      out_key: "audio_slice"
      audio_key: ['audio_24000', 'audio_44100']
      duration_leeway_in_s: 2.0
      sample_rate: [24000, 44100]

    - type: "MusicMetaRWTransform"
      in_key: "audio_slice"
      out_key: null
      overwrite_item: true
      maybe_return_list_output: true

    - type: "TextNormalizer"
      in_key: "text"

    - type: "SanityCheck"
      keys: ["uttid", "audio_24000", "audio_44100", "meta", "data_type", "text", "audio_shape"]

  val_batch_transform: # <-- This should be here, at the same level as train_item_transform
    - type: AudioCollate
      in_key: "audio_24000"
      length_key: "audio_24000_length" #output audio_length
      stereo: False
      pad_value: 0.0

    - type: AudioCollate
      in_key: "audio_44100"
      length_key: "audio_44100_length"
      stereo: True
      pad_value: 0.0

    - type: NestListCollate
      key_list: ["uttid","data_type","text","audio_shape"]
      to_tensor: False
    
    - type: MixTokenCollate
      in_key: "text"
      out_key: "text_id"
      bpe_tokenizer_path: "/opt/tiger/tokenizer/bert-base-multilingual-uncased"
  
pl_datamodule: !new:samantha.dataio.bigmusic.lite.MusicLiteDataModule
  train_dataset_ids: !ref <data[train_dataset_ids]>
  train_dataset_weights: !ref <data[train_dataset_weights]>
  train_item_transform: !ref <data[train_item_transform]>
  train_batcher: !ref <data[train_batcher]>
  train_batch_transform: !ref <data[train_batch_transform]>
  val_dataset_ids: !ref <data[val_dataset_ids]>
  val_dataset_weights: !ref <data[val_dataset_weights]>
  val_item_transform: !ref <data[val_item_transform]>
  val_batcher: !ref <data[val_batcher]>
  val_batch_transform: !ref <data[val_batch_transform]>
  save_ckpt_interval: null # using trainer val_check_interval

#  ====== Tokenizer optimizer & scheduler_cls ======
# optimizer_cls: !name:torch.optim.AdamW
#     lr: !ref <run_opts[learning_rate]>
#     weight_decay: !ref <run_opts[weight_decay]>
#     betas: [0.9, 0.96]
#     eps: 0.00000001

# scheduler_cls: !name:recipes.umm2.modules.lr_scheduler.WarmupCosine
#     init_lr: !ref <run_opts[learning_rate]>
#     warmup_steps: !ref <run_opts[warmup_steps]>
#     cycle_steps: !ref <run_opts[cycle_steps]>
#     min_lr: !ref <run_opts[learning_rate]> * 0.1


#  ====== Token2latent optimizer & scheduler_cls ======
optimizer_cls: !name:deepspeed.ops.adam.FusedAdam
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.95]
    eps: 0.0000001

scheduler_cls: !name:recipes.bark.lr_schedulers.musiclm_lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1


config: !new:recipes.umm2.models.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    n_mels: !ref <extra_params[n_mels]>
    add_chroma: False
    add_ctc: False # There is a EN and CN speech. CTC turned on.
    add_pitch: False
    n_chroma: !ref <extra_params[n_chroma]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 12
    num_attention_heads: 8
    max_source_positions: 2500
    add_vq: False
    vq_type: "EMAEntropy"
    vq_proj_noise: 10000
    vq_codebook_size: 32768
    vq_codebook_dim: 32
    vq_layer_idx: 12
    vq_decay: 0.99
    w_loss_mel: 1.0
    w_loss_chroma: 1.0
    w_loss_vq: 1.0
    w_loss_ctc: 1.0
    w_loss_f0: 1.0
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    vocab_size: 105880
    ctc_blank_id: 105879
    ctc_zero_infinity: True
    use_bn: False
    ### 5JUL2024 @hanoihantrakul According to the Merlin Job Li Tang uses the following settings `first_conformer`, `act_fn`, `mask_mel`, `rope_enhance_pos`
    first_conformer: True 
    act_fn: "gelu" 
    mask_mel: False  
    rope_enhance_pos: 7500 # 300s*25Hz
    rotary_embedding_base: 10000
    hidden_dropout: 0.0
    activation_dropout: 0.0
    attention_dropout: 0.0
    conformer_conv_dropout: 0.0
    ### for ctc loss
    # ctc_loss_reduction: 'none'
    head_output_norm: False
    ctc_downsample: 4
    freeze_umm: False

    use_fused_kernel: True

bn_config: 
    bn_dim: 128
    hop_size: 900
    bn_norm_std: 1
    bn_norm_mean: 0
    bn_padding: -5
    bn_frame_rate: 50
    pad_trim: False
    silence_bn_path: recipes/voicebox/vocoder/silence_wvae/v3_40hz/silence_wvae.npy
    sample_rate: 44100

dit_config: !new:recipes.umm2.models.tasks.dit_module.ModelArgs
    cond_type: embed    # {embed, token}
    cond_mode: align    # {align, prefix}
    local_cond_dim: 256
    time_embed_dim: 256
    local_cond_project_type: linear
    
    # token
    token_embed_dim: !ref <config[vq_codebook_dim]> # 32
    token_hidden_dim: 768
    token_upscales: [2] # for 25Hz token & 50Hz bn
    token_downscales: [] 

    # llama  
    llama_provider: ctiga
    encoder_dim: 1536
    encoder_n_layers: 24
    encoder_n_heads: 24
    causal: False
    use_window_mask: True # False
    window_size: [400, 200] # bn_frame_rate * 8, bn_frame_rate * 4
    window_type: blockwise #elemwise
    flashattn_version: 2.3

    # bn features
    target: 'bn'
    prompt_feature: 'bn'
    ctx_feature: 'bn'
    in_channels: !ref <bn_config[bn_dim]>
    out_channels: !ref <bn_config[bn_dim]>
    bn_frame_rate: !ref <bn_config[bn_frame_rate]>

    # dit
    target_type: "velocity"
    min_t: 0.0
    max_t: 1.0
    use_unet_style_skip_connect: True

    # dropout
    cond_dropout: 0.1
    cond_padding: !ref <bn_config[bn_padding]>


model: !name:recipes.umm2.models.full.conformer_DiT_enc_v2.Stage2DiTEnc
    config: !ref <config>
    dit_config: !ref <dit_config>
    sigma: 0.2
    takes: ['audio','audio_length']


required_modules:
    pretrained: 
        # ckpt_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/qinxin.025/logs/stage1/25Hz_lr3e-4_cyc200k_bs10_otf_24k-44k-inst_10_10_2/checkpoints/step=0580000.ckpt
        # ckpt_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/qinxin.025/logs/stage2/25Hz_lr1e-4_cyc200k_bs8_otf_41251/checkpoints/step=0200000.ckpt
        # fused kernel + rmpad
        ckpt_path: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/si.luo/umm2/umm_stage2_rmpad_v4/2025062602_UMM-stage2_Dur5-60_fused_GB26X64H20/checkpoints/step=0060000.ckpt"
        loader: !name:recipes.umm2.loaders.stage1.EncoderOnlyModelLoader
        cache_dir: !ref <run_opts[cache_dir]>
    vocoder:
        hpath: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/andrew.shaw/sacodec_v5/sacodec_vB_44k_50h_128d_umm_rope_b2_vocal_h1536_ummdimfix_pretrain/checkpoints/sacodec_checkpoint_epoch=0_step=180000_val_loss=1.1525.ckpt
        initializer: !name:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.init_sacodec
            cache_dir: .module_cache/vocoder/sacodec
            version: umm


pl_module: !new:recipes.umm2.modules.stages.umm_DiT.Stage2DiT
    config: !ref <config>
    dit_config: !ref <dit_config>
    bn_config: !ref <bn_config>
    model_cls: !ref <model>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterions: ["l2"]
    required_modules: !ref <required_modules>
    checkpointing: !ref <run_opts[checkpointing]>
    extra_params: !ref <extra_params>


logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 5
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
      save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    # - !new:recipes.umm2.modules.callbacks.curriculum.CurriculumCallback
    #   datamodule: !ref <pl_datamodule>
      

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 10 #100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1 # TODO
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    limit_val_batches: 1 # Turn on 1 batch so that spectrograms from validation dataloader can be plotted
    limit_train_batches: 5000 # 10000 # Consult Colin Wang: forces an epoch to end every 10k steps and prevent OOM # See above comments on why I picked this number
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
