---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 8    # set to 1 if not using reranker
    samples_to_save: 1
    save_style_audio: True
    save_mode: wav  # wav|mp3|upload
    save_semantic_tokens: False
    prompt_path: "/mnt/bn/audio-diffusion/peng/sstk_random_30_prompts.csv"
    inference_conditions: "style_text,duration"
    max_items: null
    use_reranker: True

    output_dir: sstk_out

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_modules.SemanticModule
    semantic_ckpt: "/mnt/bn/audio-diffusion/peng/ar_rl_all/semantic_model_instrumental_07B/new_pretrain_sft_rl_cfg/checkpoints/step=000250.ckpt"
    mulan_ckpt: "/mnt/bn/audio-diffusion/peng/clap_sstk_mulan_files/MuLan_sstk/CLAP_genre_balanced/checkpoints/mulan-step=005000-median_rank_1=72-kaggle.ckpt"
    mulan_version: "sstkmae_v2"
    beat_ckpt: "/mnt/bn/audio-diffusion/multitask/beat_only_24sec_lr0.001/checkpoints/epoch=13-step=1400.pt"

    # For re-ranking
    rewards:
        style_text: 0.5
        style_audio: 0.0
        qualitative: 1.0
        loudness_sim: 0.0
        audio_metrics: 0.0
        semantic_diversity: 0.5
    positive_phrase: "high quality, catchy, memorable"
    negative_phrase: "noisy, boring, forgettable"

    # CFG
    use_controller_cfg: True
    controller_cfg_gamma: 2
    controller_cfg_label: negative_anchor

    # For intensity calculation
    intensity_calculation: "mean"
    intensity_hz: 1
    intensity_temperature: 1.0

    diffusion_version: 'sstk_v5' # sstk_v2 for 24k, sstk_v3 for 44.1k
    diffusion_params:
        window_length: 30 # in second
        vocoder_hz: 49 # 125 for 24k vocoder, 49 for '44.1k_sa' vocoder
        semantic_hz: 25
        latent_dim: 64 # 32 for 24k vocoder, 64 for '44.1k_sa' vocoder
        outpainting_overlap: 0.5 #[0, 1]
        sampler_version: 'v2' # use v2 to pair with sstk_v5 diffusion model, otherwise use v1
        diffusion_steps: 50
        schedule_slope: 4.0
        guidance_scale: 2.5
        bf16_portion: 0.0

    # this is only needed when sample_rate=44100 or 48000, for 24k its bypassed
    # '24k_to_48k_stereo' to use upsampling vocoder
    # '44.1k_sa' to use Stable Audio 44.1k stereo vocoder
    vocoder_version: '44.1k_sa'

    # Model Settings
    sample_rate: 44100  # 24000|44100
    duration: 30 # 30|45|60|75|90|105|120
    semantic_temperature: 1.0
    sample_mode: "top_p"
    sample_thresh: 0.8
    token2wav_type: "diffusion"
    exclude_eos: True

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 1  # set to 28 if not using reranker

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    transform_style_text: False
    extra_params: !ref <extra_params>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt
                initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                # hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/24k_v2/diffusion-step=600000-EMA.ckpt # 24k
                # hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/44.1k_stereo_v0/diffusion-step=450000-EMA.ckpt # 44.1k
                # hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/44.1k_stereo_v1/diffusion-step=250000-EMA.ckpt
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/44.1k_stereo_v2/diffusion-step=600000-EMA.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
                    sstk: True
                    version: !ref <extra_params[diffusion_version]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.models.diffusion_sampler.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    params: !ref <extra_params[diffusion_params]>
            vocoder:
                # hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/24k_v1/soundstream-step=1240000-val_sdr=12.5666-EMA.ckpt # 24k
                # hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/24k_v1_to_44.1k_stereo/soundstream-step=1490000-val_sdr=4.9540-EMA.ckpt  # '24k_to_48k_stereo'
                # hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/44.1k_stereo_sa_v0/last-EMA.ckpt # '44.1k_sa'
                hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/44.1k_stereo_sa_v1/last-EMA.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
                    sample_rate: !ref <extra_params[sample_rate]>
                    adapt_hopper: True
                    version: !ref <extra_params[vocoder_version]>
        reranker:
            hpath:
                rewards: !ref <extra_params[rewards]>
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_ckpt]>
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: !ref <extra_params[mulan_version]>
                    #asr:
                    #    hpath: en_punc
                    #    initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>
                sample_rate: !ref <extra_params[sample_rate]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
#   - !new:recipes.bigmusic.callbacks.mcs_metrics.MCSMetricsCallback
    - !new:recipes.bigmusic.callbacks.average_metrics.AverageMetricsCallback
#   - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
      beam_size: !ref <extra_params[beam_size]>
      samples_to_save: !ref <extra_params[samples_to_save]>
      save_style_audio: !ref <extra_params[save_style_audio]>
      save_mode: !ref <extra_params[save_mode]>
      save_semantic_tokens: !ref <extra_params[save_semantic_tokens]>
      normalize_volume: True

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    use_distributed_sampler: False # for multi-gpu inference
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
