---

# python3 -m samantha.main predict -c recipes/bigmusic/conf/Q4_2023/inference/inference_inst_gt_30s.yaml

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    num_rounds: 1
    prompt_path: "/mnt/bn/ashaw-us/repos/samantha/recipes/bigmusic/dev/ashaw/scripts/inference_scripts/janne_diffusion_reconstruct_audio/gt_prompts.csv"
    inference_conditions: style_audio
    max_items: null
    run_combinations: False

    output_dir: assets/generated_output_gt/instrumental_ummgan_44k
    # Re-trained vocal checkpoint
    token2wav_type: "ar-diffusion-vocoder"
    semantic_type: bestrq

    # Model Settings
    sample_rate: 44100
    duration: 120
    sample_mode: "gumbel"

    ar_params:
        coarse_duration: 10
        fine_duration: 4
        coarse_stride: 5
        fine_stride: 3
        coarse_temperature: 0.9
        fine_temperature: 0.8
        ar_sample_mode: gumbel

    diffusion_params: {}

token2wav_config: !include:../../../../../apps/bigmusic/umm/diffusion/conf/infer_generation_25hzConformer_49hzSS_streaming_us_v8.yaml

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 4
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.GTInferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/hanoi.hantrakul/logs/umm_conv_sstk/umm_stage3_conv1D_sstk_no_ctc_794_EMAVQ32768x32/checkpoints_for_inference_retry/step=0850000.ckpt
                initializer: !name:recipes.umm.requires.model_initializer.init_stage3_conv1d
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: !ref <token2wav_config[diffusion_config]>
                initializer: !name:apps.bigmusic.umm.diffusion.requires.model_initializer.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>

callbacks:
    # - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    use_distributed_sampler: False # for multi-gpu inference
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !ref <callbacks>
