---
# # python3 -m samantha.main predict -c recipes/bigmusic/conf/Q4_2023/inference/inference_inst_gt_30s.yaml
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    num_rounds: 1
    prompt_path: "/mnt/bn/ashaw-us/repos/samantha/recipes/bigmusic/dev/ashaw/scripts/inference_scripts/janne_diffusion_reconstruct_audio/gt_prompts.csv"
    inference_conditions: style_audio
    max_items: null
    run_combinations: False

    output_dir: assets/generated_output_gt/instrumental_44k
    # Re-trained vocal checkpoint
    token2wav_type: diffusion
    semantic_type: bestrq

    # Model Settings
    sample_rate: 44100
    duration: 120
    sample_mode: "gumbel"

    ar_params:
        coarse_duration: 10
        fine_duration: 4
        coarse_stride: 5
        fine_stride: 3
        coarse_temperature: 0.9
        fine_temperature: 0.8
        ar_sample_mode: gumbel

    diffusion_version: 'sstk_v5' # sstk_v2 for 24k, sstk_v3 for 44.1k
    diffusion_params:
        window_length: 30 # in second
        vocoder_hz: 49 # 125 for 24k vocoder, 49 for '44.1k_sa' vocoder
        semantic_hz: 25
        latent_dim: 64 # 32 for 24k vocoder, 64 for '44.1k_sa' vocoder
        outpainting_overlap: 0.5 #[0, 1]
        sampler_version: 'v2' # use v2 to pair with sstk_v5 diffusion model, otherwise use v1
        diffusion_steps: 50
        schedule_slope: 4.0
        guidance_scale: 2.5
        bf16_portion: 0.0
    vocoder_version: '44.1k_sa'


run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 4
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.GTInferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                # US conv UMM-chroma stage 3
                hpath: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/hanoi.hantrakul/logs/umm_conv_sstk/umm_stage3_conv1D_sstk_no_ctc_794_EMAVQ32768x32/checkpoints_for_inference_retry/step=0850000.ckpt
                initializer: !name:recipes.umm.requires.model_initializer.init_stage3_conv1d
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/44.1k_stereo_v2/diffusion-step=600000-EMA.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
                    sstk: True
                    version: !ref <extra_params[diffusion_version]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.models.diffusion_sampler.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    params: !ref <extra_params[diffusion_params]>
            vocoder:
                hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/44.1k_stereo_sa_v1/last-EMA.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
                    sample_rate: !ref <extra_params[sample_rate]>
                    adapt_hopper: True
                    version: !ref <extra_params[vocoder_version]>

callbacks:
    # - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    use_distributed_sampler: False # for multi-gpu inference
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !ref <callbacks>
