---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 4    # set to 1 if not using reranker
    samples_to_save: 1
    prompt_path: "/mnt/bn/audio-diffusion/data/bigmusic_text_prompts/instrumental_prompts_20231030_subset150.csv"
    inference_conditions: style_text,duration,structure
    max_items: null
    use_reranker: True

    output_dir: ./assets/generated_outputs_2m

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_modules.SemanticModule
    semantic_ckpt: "/mnt/bn/audio-diffusion/ducle/logs/semantic_model_instrumental_07B/sstk_vad_chorus-control_sstk-random_sstk-mulan+sstk-umm-nospeech-400k_2m-varlen/checkpoints/step=248000.ckpt"
    mulan_ckpt: "/mnt/bn/audio-diffusion/xuchen/mulan/models/mulan-step=014800-kaggle.ckpt"
    mulan_version: "sstk"

    rewards:
        style_text: 1.0
        qualitative: 1.0
        nonvocal: 1.0

    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 2.5
        bf16_portion: 0.0

    soundstorm_params:
        score_strategies: ["random", "random", "random", "random", "maskgit", "maskgit", "maskgit", "maskgit", "maskgit", "maskgit", "maskgit", "maskgit"]
        iterations: [64, 64, 32, 32, 16, 16, 8, 8, 4, 4, 2, 2]
        temperatures: [0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]

    # Model Settings
    sample_rate: 24000
    duration: 30 # 30|45|60|75|90|105|120
    semantic_temperature: 1.0
    sample_mode: "top_p"
    token2wav_type: "diffusion" # diffusion|soundstorm

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 4  # set to 28 if not using reranker

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    extra_params: !ref <extra_params>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt
                initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/model_14_30s_finetune/checkpoints/last-minimal.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    duration: !ref <extra_params[duration]>
            vocoder:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/soundstream-step=374999-val_sdr=12.9557-minimal.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
        soundstorm_modules:
            soundstorm:
                hpath: /mnt/bn/audio-diffusion/ducle/logs/soundstorm/sstk_sstk-umm-nospeech-400k/checkpoints/step=218000-loss=0.0000.ckpt
                initializer: !name:recipes.soundstorm.lightning.utils.init_soundstorm
                    cache_dir: !ref <run_opts[cache_dir]>
        reranker:
            hpath:
                rewards: !ref <extra_params[rewards]>
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_ckpt]>
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: !ref <extra_params[mulan_version]>
                    asr:
                        hpath: en_punc
                        initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    - !new:recipes.bigmusic.callbacks.mcs_metrics.MCSMetricsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
      beam_size: !ref <extra_params[beam_size]>
      samples_to_save: !ref <extra_params[samples_to_save]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
