---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 4    # set to 4 if using reranker
    samples_to_save: 1
    prompt_path: "/mnt/bn/audio-diffusion/data/bigmusic_text_prompts/vocal_prompts_20231031_mixed35_2min.csv"
    inference_conditions: style_text,lyrics_tokens # style_text|style_audio,lyrics_tokens,vocal_audio|vocal_text,chroma
    max_items: null
    run_combinations: False
    use_reranker: True
    predict_lyrics: False

    output_dir: ./assets/generated_outputs_2m

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_varlen_modules.SemanticModuleVarlen
    semantic_ckpt: "/mnt/bn/lyrics-to-song/baseline_models/q4/20231106-2min_varlen/checkpoints/step=184000-tr_loss=0.0000-val_loss_0=4.2460.ckpt"
    mulan_ckpt: infer_from_semantic_ckpt

    # Used for reranker, only loaded if use_reranker=True
    mulan_rewards_ckpt: "/mnt/bn/audio-diffusion/mulan/ongoing/mulan-step=024600-median_rank_1=110-kaggle-minimal.ckpt"

    ar_params:
        coarse_duration: 10
        fine_duration: 4
        coarse_stride: 5
        fine_stride: 3
        coarse_temperature: 0.9
        fine_temperature: 0.8
    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 2.5
        bf16_portion: 0.0

    # Model Settings
    sample_rate: 24000
    duration: 120 # 30
    semantic_temperature: 1.05
    sample_mode: "top_p"
    token2wav_type: diffusion

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 1  # varlength can only do batch size of 1
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>
    lyrics_max_seq_len: null
    dataset_mode: "variable_length"
    enable_punctuation: True

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/model_14_120s_finetune/checkpoints/last-minimal.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    duration: 120
            vocoder:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/soundstream-step=374999-val_sdr=12.9557-minimal.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
        ar_modules:
            coarse:
                hpath: /mnt/bn/audio-diffusion/jt/model_archive/vocalmusic/coarse_flash_llama_wav2vec/bestrq_chroma_coarse_0.7b/checkpoints/step=295000-val_accu_0=17.92.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_coarse
                    cache_dir: !ref <run_opts[cache_dir]>
            fine:
                hpath: /mnt/bn/lyrics-to-song/ashaw/logs/bigmusic/fine/fine_mcc_mix/fixed_posemb_v1/checkpoints/step=206000-val_accu_0=10.44.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_fine
                    cache_dir: !ref <run_opts[cache_dir]>
            soundstream_dec:
                hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
                initializer: !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
                    cache_dir: !ref <run_opts[cache_dir]>
        reranker:
            hpath:
                rewards:
                    style_text: 3.0
                    qualitative: 1.0
                    wer: 1.0
                    #chord: 4.0
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_rewards_ckpt]>
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: "g4"
                    asr:
                        hpath: en_punc
                        initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
                    #chord:
                    #    hpath: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/semi-sup-chord_epoch=103-step=56300.ckpt"
                    #    initializer: !name:recipes.chord.requires.model_initializer.init_chord
                    #chord_lms:
                    #    hpath:
                    #        default: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/default/lm.arpa"
                    #    initializer: !name:recipes.chord.requires.model_initializer.init_chord_lms
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    - !new:recipes.bigmusic.callbacks.mcs_metrics.MCSMetricsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
      beam_size: !ref <extra_params[beam_size]>
      samples_to_save: !ref <extra_params[samples_to_save]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
