---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 4    # set to 4 if using reranker
    prompt_path: {}
    inference_conditions: style_text,lyrics_tokens # style_text|style_audio,lyrics_tokens,vocal_audio|vocal_text,chroma
    max_items: null
    run_combinations: False
    use_reranker: False

    output_dir: ./assets/generated_outputs_30s

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_varlen_xperf_modules.SemanticModuleXperf
    semantic_ckpt: "/mnt/bn/music-ai-unified-repo-lq/lihui/py_demo_server/lyric2song_base/last_semantic_ar.ckpt"
    mulan_ckpt: "/mnt/bn/music-ai-unified-repo-lq/lihui/py_demo_server/lyric2song_base/last_mulan.ckpt"

    # Used for reranker, only loaded if use_reranker=True
    mulan_rewards_ckpt: "/opt/tiger/sami/models/mulan/mulan-step=024600-median_rank_1=110-kaggle-minimal.ckpt"

    ar_params:
        coarse_duration: 10
        fine_duration: 4
        coarse_stride: 5
        fine_stride: 3
        coarse_temperature: 0.9
        fine_temperature: 0.8
    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 2.5
        bf16_portion: 0.0

    # Model Settings
    sample_rate: 24000
    duration: 30 # 30
    lyrics_max_seq_len: 400 # TODO: switch to 400 for 30s
    semantic_temperature: 1.0
    sample_mode: "gumbel"
    token2wav_type: diffusion

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 28  # set to 4 if using reranker
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/music-ai-unified-repo-lq/lihui/py_demo_server/lyric2song_base/last_diffusion.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
            vocoder:
                hpath: /mnt/bn/music-ai-unified-repo-lq/lihui/py_demo_server/lyric2song_base/last_soundstream.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
        reranker:
            hpath:
                rewards:
                    style_text: 1.0
                    qualitative: 1.0
                    wer: 1.0
                    #structure: 1.0
                    #chord: 4.0
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_ckpt]>
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: "g4"
                    asr:
                        hpath: en_punc
                        initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
