---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 1    # set to 4 if using reranker
    samples_to_save: 1
    prompt_path: "./prompts/zh_100_en_prompt.csv"
    inference_conditions: style_text,speaker_id,lyrics_tokens # style_text|style_audio,lyrics_tokens,vocal_audio|vocal_text,chroma|speaker_id
    max_items: null
    run_combinations: False
    use_reranker: False
    dataset_mode: truncate_length

    output_dir: ./generated_output/conditional

    # Tokenizer
    # En tokenizer in CN hdfs: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/stage3_music_chroma_vq32768x32/checkpoints/step=0070000.ckpt"
    # Zh tokenizer in CN hdfs: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"
    tokenizer_ckpt: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"

    # Diffusion
    # En tokenizer diffusion in CN hdfs: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_14_30s_finetune/checkpoints/last-minimal.ckpt"
    # Zh tokenizer diffusion in CN hdfs: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_16/checkpoints_minimal/last-minimal.ckpt"
    diffusion_ckpt: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_16_2min/checkpoints/last-EMA-0329.ckpt"
    vocoder_ckpt: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/soundstream-step=374999-val_sdr=12.9557.ckpt"
    lyrics_lang: "zh_phone"     # en | zh_phone | zh_wp
    is_zh_token: True           # Set to True only if lyrics_lang is zh_phone or zh_wp. Diffusion model from recipes.diffusion.models.tnt_gru
    mixv2: False                # Set to True for mix UMM token


    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_modules.SemanticModule
    semantic_ckpt: "hdfs:///home/byte_speech_sv/zongyu.yin/logs/decoder_07B_ctiga_zh30s/zh_30s_ctiga_1w/checkpoints/step=026000-val_accu_0=13.08.ckpt"

    # Used for reranker, only loaded if use_reranker=True
    # structure_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/structure_epoch=185-step=93000.ckpt"
    mulan_ckpt: "infer_from_semantic_ckpt"
    mulan_rewards_ckpt: "hdfs://haruna/home/byte_speech_sv/mulan/cn_mulan_ckpt/mulan-step=012800-kaggle-minimal.ckpt"

    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 2.5
        bf16_portion: 0.0

    # Model Settings
    sample_rate: 24000
    duration: 120
    lyrics_max_seq_len: 1800
    semantic_temperature: 1.0
    sample_mode: "top_p"
    sample_thresh: 0.9
    token2wav_type: diffusion

    use_controller_cfg: True       # Set to True to activate style CFG.
    controller_cfg_gamma: 1.0
    controller_cfg_label: "genre"  # mood, scene, sinking,

    cache_dir: .module_cache/bigmusic

run_opts:
    fast_dev_run: False
    precision: 16-mixed
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/bigmusic
    batch_size: 6  # set to 4 if using reranker
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    run_combinations: !ref <extra_params[run_combinations]>
    lyrics_max_seq_len: !ref <extra_params[lyrics_max_seq_len]>
    dataset_mode: !ref <extra_params[dataset_mode]>
    lang: !ref <extra_params[lyrics_lang]>
    enable_punctuation: True

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        diffusion_modules:
            diffusion:
                hpath: !ref <extra_params[diffusion_ckpt]>
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
                    is_zh_token: !ref <extra_params[is_zh_token]>
                    mixv2: !ref <extra_params[mixv2]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    duration: !ref <extra_params[duration]>
            vocoder:
                hpath: !ref <extra_params[vocoder_ckpt]>
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
                    version: "24k_125hz_dim32_baseline"
        reranker:
            hpath:
                rewards:
                    style_text: 1.0
                    # qualitative: 1.0
                    qualitative_cn: 1.0 # use qualitative_cn for chinese mulan, qualitative for english mulan
                    wer: 1.0
                required_modules:
                    # mulan: # English Mulan
                    #     hpath: hdfs:///home/byte_speech_sv/bigmusic/models/mulan/mulan-step=024600-median_rank_1=110-kaggle-minimal.ckpt
                    #     initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                    #         version: "g4"
                    mulan:
                        hpath: hdfs://haruna/home/byte_speech_sv/mulan/cn_mulan_ckpt/mulan-step=012800-kaggle-minimal.ckpt
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            cache_dir: !ref <run_opts[cache_dir]>
                            version: "Chinese"
                    asr:
                        # hpath: en_punc
                        hpath: zh
                        initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsSAOnlineCallback
      asr_model_path: zh-CN
    - !new:recipes.bigmusic.callbacks.mir_metrics.MIRTagMetricsSAOnlineCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
      beam_size: !ref <extra_params[beam_size]>
      samples_to_save: !ref <extra_params[samples_to_save]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    use_distributed_sampler: False # for multi-gpu inference
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
