---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 4    # set to 4 if using reranker
    prompt_path: "/mnt/bn/audio-diffusion/data/musiclm_text_prompt/text_prompt_collection_2.0_20230817.csv"
    inference_conditions: style_text,duration # style_text|style_audio,lyrics_tokens,vocal_audio|vocal_text,chroma
    max_items: null
    use_reranker: True

    output_dir: ./assets/generated_outputs_2m

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_varlen_modules.SemanticModuleVarlen
    semantic_ckpt: "/mnt/bn/audio-diffusion/ducle/logs/semantic_model_instrumental_07B/mcc40m_vad_2min_varlen_aws/checkpoints/step=210000.ckpt"
    mulan_ckpt: infer_from_semantic_ckpt

    # Used for reranker, only loaded if use_reranker=True
    mulan_rewards_ckpt: "/mnt/bn/audio-diffusion/mulan/ongoing/mulan-step=024600-median_rank_1=110-kaggle-minimal.ckpt"

    diffusion_params:
        num_chunks: 1
        diffusion_steps: 25
        schedule_slope: 2.5
        guidance_scale: 2.5
        bf16_portion: 0.0

    # Model Settings
    sample_rate: 24000
    duration: 120 # 30|45|60|75|90|105|120
    semantic_temperature: 1.0
    sample_mode: "top_p"
    token2wav_type: diffusion

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 1  # set to 1 if using reranker

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:recipes.bigmusic.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    extra_params: !ref <extra_params>

pl_datamodule: !new:recipes.bigmusic.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/model_14_120s_finetune/checkpoints/last.ckpt
                initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
            sampler:
                hpath: null
                initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    duration: 120
            vocoder:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/soundstream-step=374999-val_sdr=12.9557.ckpt
                initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
        ar_modules:
            coarse:
                hpath: /mnt/bn/audio-diffusion/jt/model_archive/vocalmusic/coarse_flash_llama_wav2vec/bestrq_chroma_coarse_0.7b/checkpoints/step=295000-val_accu_0=17.92.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_coarse
                    cache_dir: !ref <run_opts[cache_dir]>
            fine:
                hpath: /mnt/bn/lyrics-to-song/ashaw/logs/bigmusic/fine/fine_mcc_mix/fixed_posemb_v1/checkpoints/step=206000-val_accu_0=10.44.ckpt
                initializer: !name:recipes.bigmusic.utils.model_initializer.init_fine
                    cache_dir: !ref <run_opts[cache_dir]>
            soundstream_dec:
                hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
                initializer: !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
                    cache_dir: !ref <run_opts[cache_dir]>
        reranker:
            hpath:
                rewards:
                    style_text: 2.0
                    qualitative: 1.0
                    nonvocal: 1.0
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_rewards_ckpt]>
                        initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: "g4"
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    - !new:recipes.bigmusic.callbacks.mcs_metrics.MCSMetricsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
