---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']
_checkpointing: !ref <run_opts[checkpointing]>

data_params:
    sample_rate: 24000
    duration: 10
    wav2vec_codebook_size: 1024
    mulan_codebook_size: 1024
    soundstream_codebook_size: 1024
    mulan_codebook_shared: False
    num_coarse: 4
    num_fine: 8

# training parameters
training_params:
    max_steps: 1000000
    batch_size: 144
    learning_rate: 4.0e-4
    warmup_steps: 10000
    cycle_steps: 500000
    weight_decay: 0.01
    shuffle_buffer: 512
    gradient_clip_val: 1.0

ckpt_path: null
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]

# running parameters
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: semantic_llama
    version: mcc40m
    cache_dir: .module_cache/musiclm
    precision: "16-mixed"
    num_workers: 6
    accelerator: auto
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

mcc_a_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/a.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

mcc_b_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/b.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

mcc_c_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/c.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

mcc_d_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/d.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

mcc_e_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/e.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

mcc_f_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/f.tsv"
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.5
    resampled: True
    shardshuffle: True

combined_train_dataset: !new:recipes.musiclm.datamodules.webdataset.RandomSample
    datasets:
        - !ref <mcc_a_train_dataset>
        - !ref <mcc_b_train_dataset>
        - !ref <mcc_c_train_dataset>
        - !ref <mcc_d_train_dataset>
        - !ref <mcc_e_train_dataset>
        - !ref <mcc_f_train_dataset>
    probabilities: [1, 1, 1, 1, 1, 1]

train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <combined_train_dataset>
    pipeline:
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>

validation_dataset: !new:recipes.musiclm.datasets.karaoke.KaraokeDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-0131.tar"
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self
    sample_rate: !ref <data_params[sample_rate]>
    duration: !ref <data_params[duration]>
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    audio_key: "acc.npy"
    sample_range_key: "acc_sample_range.npy"
    min_volume_threshold: 0.05
    is_train: False

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.WebDataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <training_params[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

model_config: !new:samantha.models.LlamaConfig
    vocab_size: !ref <data_params[mulan_codebook_size]> * 12 + <data_params[wav2vec_codebook_size]> + 1
    n_embd: 1024
    n_layer: 24
    n_head: 16
    logit_num: !ref <data_params[wav2vec_codebook_size]>

model_cls: !name:samantha.models.Llama
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <training_params[learning_rate]>
    warmup_steps: !ref <training_params[warmup_steps]>
    cycle_steps: !ref <training_params[cycle_steps]>
    min_lr: !ref <training_params[learning_rate]> * 0.1

pl_module: !new:recipes.musiclm.lightning.modules.SemanticModule
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <data_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/g4/checkpoints/mulan-step=044800-median_rank_1=170-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/mulan/kmeans_minibatch_codebook-mulan1b_g4_170-1024x12.npy
            - !name:recipes.musiclm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <run_opts[cache_dir]>
        wav2vec:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/semantic.jit.pt
            - !name:recipes.musiclm.requires.model_initializer.init_wav2vec
              cache_dir: !ref <run_opts[cache_dir]>
        semantic_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/centroids_epoch_10.npy
            - !name:recipes.musiclm.requires.model_initializer.init_semantic_centers
              cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 50
    max_steps: !ref <training_params[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    val_check_interval: 3000
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
