---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

hp: !include:hparams_x480.yaml

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: coarse
    version: 0.2
    precision: 32
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .cache
    profiler: simple
    flash_attn: null
    batch_size: 2
    num_workers: 8

predict_dataset: !new:recipes.audio_lm.datasets.dataset.InferenceDataset
    csv_path: "/mnt/bn/audio-diffusion/data/google_prompts/google_prompts.csv"

# dataloader configuration
predict_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle: False
    drop_last: False
    pin_memory: False

# datamodule configuration
pl_datamodule: !new:recipes.audio_lm.lit_modules.DataModule
    predict_dataloader: !ref <predict_dataloader>

pl_module: !new:recipes.audio_lm.lit_modules.lit_inference.InferenceModule
    semantic_ckpt: "/mnt/bn/zongyu-lq/ckpts/musiclm/semantic_sparse_mulan247_429M_epoch=79-step=313000-accu=38.00.ckpt"
    coarse_ckpt: "/mnt/bn/zongyu-lq/logs/coarse_sparse_mulan247/434M/checkpoints/epoch=09-step=156000-accu=30.36.ckpt"
    fine_ckpt: "/mnt/bn/zongyu-lq/ckpts/musiclm/epoch=03-step=193000-accu=18.92.ckpt"
    extra_params: !ref <hp>
    out_dir: "./generated_output"
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/dongguo/mulan/gpt_texts/MuLan/MCC-GPT-N2M-0329-128V100/checkpoints/mulan-step=033600-median_rank_0=247-kaggle.ckpt
            - !name:recipes.audio_lm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "247"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/dongguo/mulan/codebook/kmeans_minibatch_codebook-mulan249-1024x12.npy
            - !name:recipes.audio_lm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <run_opts[cache_dir]>
        # w2v:
        #     - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.0
        #     - !name:recipes.audio_lm.requires.model_initializer.init_w2v
        #       cache_dir: !ref <run_opts[cache_dir]>
        sound_stream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.audio_lm.requires.model_initializer.init_sound_stream_decoder
              cache_dir: !ref <run_opts[cache_dir]>

# logger: !new:pytorch_lightning.loggers.TensorBoardLogger
#     save_dir: !ref <run_opts[tensorboard_dir]>
#     name: !ref <run_opts[log_name]>
#     version: !ref <run_opts[version]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    # logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 1
    strategy: !ref <run_opts[strategy]>
    max_epochs: 1
    precision: !ref <run_opts[precision]>
