---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

# training parameters
training_params:
  model_name: "7B"
  vocab_size: 32000
  seq_len: 1024
  max_steps: 600000
  batch_size: 32
  micro_batch_size: 8
  learning_rate: 6.0e-6
  warmup_steps: 2000
  weight_decay: 0.1
  betas: (0.9, 0.95)
  gradient_clip_val: 1.0


ckpt_path: null

# running parameters
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
  fast_dev_run: False
  tensorboard_dir: !ref <log_dir>
  log_name: byteformers_example
  version: llama
  precision: bf16-mixed
  num_workers: 0
  accelerator: auto

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.byteformers_example.datamodules.token_dataset.TokenDataModule
  data_fp: "input.txt"
  tokenizer: !ref <tokenizer>
  seq_len: !ref <training_params[seq_len]>
  batch_size: !ref <training_params[batch_size]>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: True

tokenizer: !new:recipes.byteformers_example.tokenizer.LlamaTokenizer
  model_path: "output/tokenizer.model"

pl_module: !new:recipes.byteformers_example.modules.language_modeling.LanguageModelingModule
  model_name: !ref <training_params[model_name]>
  vocab_size: !ref <training_params[vocab_size]>
  seq_len: !ref <training_params[seq_len]>
  weight_decay: !ref <training_params[weight_decay]>
  betas: !ref <training_params[betas]>
  learning_rate: !ref <training_params[learning_rate]>
  warmup_steps: !ref <training_params[warmup_steps]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>
  default_hp_metric: False

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'loss/valid'
  mode: 'min'
  save_last: True

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: 'step'

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

transformer_layer_cls: !name:samantha.byteformers.models.llama.LlamaBlock
auto_wrap_policy: !name:torch.distributed.fsdp.wrap.transformer_auto_wrap_policy
  transformer_layer_cls: [!ref <transformer_layer_cls>]

strategy: !new:pytorch_lightning.strategies.FSDPStrategy
  auto_wrap_policy: !ref <auto_wrap_policy>
  activation_checkpointing: !ref <transformer_layer_cls>

flops_profiler: !new:samantha.callbacks.flops_profiler.FlopsProfilerCallback
generate_text: !new:recipes.byteformers_example.callbacks.generate_text.GenerateText
  tokenizer: !ref <tokenizer>
  check_every_n_steps: 1000


trainer: !new:pytorch_lightning.Trainer
  strategy: !ref <strategy>
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: 'auto'
  num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
  deterministic: False
  enable_model_summary: True
  log_every_n_steps: 50
  max_steps: !ref <training_params[max_steps]>
  precision: !ref <run_opts[precision]>
  accumulate_grad_batches: !ref <training_params[micro_batch_size]>
  # gradient_clip_val: !ref <training_params[gradient_clip_val]>
  val_check_interval: 1000
  check_val_every_n_epoch: null  # required now that we use an IterableDataset
  num_sanity_val_steps: 0
  callbacks:
    - !ref <checkpoint>
    - !ref <lr_monitor>
  plugins: !ref <plugins>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
