---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 2023
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
# log_dir: hdfs://harunava/home/byte_speech_sv/weituo/mulan_exp #!apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
log_dir: /mnt/bn/audio-diffusion/mulan_exp #!apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
llama_weights_path: /mnt/bn/mm-data/user/xuchen.song/models/llama-7b
llama_tokenizer_path: /mnt/bn/mm-data/user/xuchen.song/models/llama-7b

run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: llama_mulan
    log_every_n_steps: 10
    version: llama_mulan_test
    precision: "bf16-mixed"
    num_workers: 4
    accelerator: auto
    strategy: ddp_find_unused_parameters_true
    enable_activation_ckpt: True
    num_steps: 600000
    val_check_interval: 200
    batch_size: 40
    # sample_buffer_size: 600
    shuffle_buffer: 600
    val_batch_size: 128
    spec_aug: True
    text_encoder: llama-lora
    music_encoder: double-mut
    emb_dim: 2048
    seq_len: 400
    learning_rate: 4.e-5
    weight_decay: 5.e-4
    temperature: 0.1  # temperature in Multiview Coding loss
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    use_supcontrast: False
    use_flatclr: False
    gather_batches: True

extra_params:
    sample_rate: 24000
    duration: 10
    wav2vec_codebook_size: 1024
    wav2vec_frame_rate: 25
    mulan_codebook_size: 1024
    mulan_num_rvq: 12

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################


mcc_n2m_dataset: !new:recipes.mulan.dataset.mcc.MCCN2MDatasetApril
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True


mcc3m_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: "mcc3.5m"
    audio_type: vocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

pgc_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: mcc600k
    audio_type: vocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

metacritic_vocal_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: metacritic
    audio_type: vocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

metacritic_nonvocal_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: metacritic
    audio_type: nonvocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

everynoise_vocal_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: everynoise
    audio_type: vocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

everynoise_nonvocal_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: everynoise
    audio_type: nonvocal
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True

tt_video_tag_dataset: !new:recipes.mulan.dataset.tt_video_tag.TTVDataset
    name: ttv
    mode: train
    tokenizer_name: llama
    seq_len: !ref <run_opts[seq_len]>
    tok_path: !ref <llama_tokenizer_path>
    resampled: True
    use_pipe: True

train_datasets:
    mcc_n2m: !ref <mcc_n2m_dataset>
    3m_vocal: !ref <mcc3m_dataset>
    pgc_vocal: !ref <pgc_dataset>
    meta_vocal: !ref <metacritic_vocal_dataset>
    meta_nonvocal: !ref <metacritic_nonvocal_dataset>
    every_vocal: !ref <everynoise_vocal_dataset>
    every_nonvocal: !ref <everynoise_nonvocal_dataset>
    tt_video_tag: !ref <tt_video_tag_dataset> 

# selected_dataset_names: [mcc_n2m,3m_vocal, pgc_vocal, meta_vocal, every_vocal]
# weights: [0.6, 0.6, 0.2, 0.1, 0.1]

# selected_dataset_names: [karaoke, mcc_gpt, aed_gpt, mcc_n2m]
# weights: [0.1, 0.2, 0.1, 0.6]
selected_dataset_names: [mcc_n2m]
weights: [1.0]

train_dataset: !new:samantha.dataio.dataset.MultiIterableDataset
    datasets: !apply:recipes.mulan.dataset.utils.select_datasets
        - !ref <train_datasets>
        - !ref <selected_dataset_names>
    weights: !ref <weights>
    num_samples: 10_000_000
    seed: !ref <seed>

kaggle_val_0: !new:recipes.mulan.dataset.val.TextMusicDataset
    path: data/kaggle
    csv_name: kaggle_val_meta.csv
    text_key: text
    tok_path: !ref <llama_tokenizer_path>

kaggle_val_1: !new:recipes.mulan.dataset.val.TextMusicDataset
    path: data/kaggle
    csv_name: kaggle_val_meta.csv
    text_key: aspect_list
    tok_path: !ref <llama_tokenizer_path>

val_dataset: [!ref <kaggle_val_0>, !ref <kaggle_val_1>]

pl_datamodule: !new:recipes.mulan.modules.pl_datamodule.MuLanMMEDataModule
    train_dataset: !ref <train_dataset>
    val_dataset: !ref <val_dataset>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True


pl_module: !new:recipes.mulan.modules.pl_module.LitMuLanModule
    music_encoder: !ref <run_opts[music_encoder]>
    text_encoder: !ref <run_opts[text_encoder]>
    emb_dim: !ref <run_opts[emb_dim]>
    spec_aug: !ref <run_opts[spec_aug]>
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    temperature: !ref <run_opts[temperature]>
    use_supcontrast: !ref <run_opts[use_supcontrast]>
    use_flatclr: !ref <run_opts[use_flatclr]>
    gather_batches: !ref <run_opts[gather_batches]>
    model_path: !ref <llama_weights_path>

logger:
    - !new:pytorch_lightning.loggers.TensorBoardLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <log_dir>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: median_rank_0
      mode: min
      filename: mulan-{step:06d}-{median_rank_0:.0f}-kaggle
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: median_rank_1
      mode: min
      filename: mulan-{step:06d}-{median_rank_1:.0f}-kaggle
    - !new:recipes.mulan.modules.ema.EMA
      decay: 0.999

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: True
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    use_distributed_sampler: False
    logger: !ref <logger>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    precision: !ref <run_opts[precision]>
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
