---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: last

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [ !ref <seed> ]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision [ 'high' ]

extra_params:
  sample_rate: 24000
  frame_rate: 25
  n_mels_tgt: 160
  hop_length: 240
  feature_cmvn: "recipes/datasets/mcc/MixDataModule_SpeechTransform.stats.pt"
  tokenizer: "bert-base-multilingual-uncased"


# running parameters
run_opts:
  fast_dev_run: False
  cache_dir: .module_cache/umm
  hdfs_log_dir: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/renyi/samantha_ckpts"
  log_dir: logs
  log_name: voc
  version: !ref _1
  precision: "32"
  num_workers: 4
  accelerator: auto
  warmup_steps: 2000
  max_steps: 10000000
  val_check_interval: 5000
  ckpt_interval: 10000
  batch_size: 4
  learning_rate: 1.0e-4
  cycle_steps: 100000
  weight_decay: 0.1
  shuffle_buffer: 8000
  gradient_clip_val: 0.0
  checkpointing: False
  tensorboard_dir: !ref <run_opts[log_dir]>

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.mcc.mix_mkii.MixMSSDataModule
  data_ids: [ 1004 ]
  data_weights: [ 1 ]
  shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
  sample_rate: !ref <extra_params[sample_rate]>
  batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
  num_workers: !ref <run_opts[num_workers]>
  max_num_crops: null
  min_duration: 3
  max_duration: 90
  normalize_audio: False
  tokenizer: !ref <extra_params[tokenizer]>
  frame_rate: !ref <extra_params[frame_rate]>

pl_module: !new:recipes.umm.modules.vocoder_task.MelGANVocoder
  model_hp: !ref <model_hp>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>
#    - !new:pytorch_lightning.loggers.wandb.WandbLogger
#        save_dir: !ref <run_opts[log_dir]>
#        project: !ref <run_opts[log_name]>
#        name: !ref <run_opts[version]>
#    - !new:pytorch_lightning.loggers.TensorBoardLogger
#        save_dir: !ref <run_opts[tensorboard_dir]>
#        name: !ref <run_opts[log_name]>
#        version: !ref <run_opts[version]>

callbacks:
  - !new:samantha.callbacks.HDFSModelCheckpoint
    hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
    monitor: step
    save_top_k: 500
    every_n_train_steps: !ref <run_opts[ckpt_interval]>
    mode: max
    filename: "{step:07d}"
    save_last: True
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'

plugins:
  - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: "ddp_find_unused_parameters_true"
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: "auto"
  num_nodes: !apply:os.getenv [ "ARNOLD_WORKER_NUM", 1 ]
  deterministic: False
  enable_model_summary: True
  log_every_n_steps: 100
  max_steps: !ref <run_opts[max_steps]>
  precision: !ref <run_opts[precision]>
  accumulate_grad_batches: 1
  gradient_clip_val: !ref <run_opts[gradient_clip_val]>
  val_check_interval: !ref <run_opts[val_check_interval]>
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0
  limit_val_batches: 1
  sync_batchnorm: True
  benchmark: False
  callbacks: !ref <callbacks>
  plugins: !ref <plugins>

model_hp:
  resblock: "1"
  upsample_rates: [ 6,5,4,2 ]
  upsample_kernel_sizes: [ 12,11,8,4 ]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [ 3,7,11 ]
  resblock_dilation_sizes: [ [ 1,3,5 ], [ 1,3,5 ], [ 1,3,5 ] ]

  use_pitch_embed: false
  use_fm_loss: false
  use_ms_stft: true
  use_cond_disc: false
  avg_disc_loss: true
  use_univnet_disc: false
  nsf_type: none

  use_subband_stft_loss: false
  hop_size: !ref <extra_params[hop_length]>
  fft_size: 1200
  win_size: 1200
  audio_num_mel_bins: 160
  audio_sample_rate: 24000
  fmin: 0
  fmax: 12000
  subband_stft_loss_params:
    fft_sizes: [ 384, 683, 171 ]  # List of FFT size for STFT-based loss.
    hop_sizes: [ 30, 60, 10 ]     # List of hop size for STFT-based loss
    win_lengths: [ 150, 300, 60 ] # List of window length for STFT-based loss.
    window: "hann_window"       # Window function for STFT-based loss

  mpd:
    periods: [ 2,3,5,7,11 ]
    kernel_size: 5
    stride: 3
    use_spectral_norm: False
    lReLU_slope: 0.2
  use_mrd: true
  mrd:
    resolutions: [ [ 1024, 120, 600 ], [ 2048, 240, 1200 ], [ 512, 50, 240 ] ] # (filter_length, hop_length, win_length)
    use_spectral_norm: False
    lReLU_slope: 0.2
  lambda_mel: 5.0
  lambda_cdisc: 4.0
  lambda_adv: 2.0
  lambda_mrd: 1.0
  lambda_msd: 1.0
  lambda_mpd: 1.0

  generator_scheduler_params:
    step_size: 1000
    gamma: 0.999
  discriminator_scheduler_params:
    step_size: 1000
    gamma: 0.999
  max_updates: 6000000
  melgan_config:
    "n_mel_channels": 160
    "n_residual_layers": 4
    "ndf": 16
    "num_D": 3
    "n_layers_D": 4
    "downsamp_factor": 4
    "lambda_feat": 0.0
    "cond_disc": false
    "batch_size": 8
    "seq_len": 100
    "epochs": 1000
    "log_interval": 100
    "save_interval": 5000
    "n_test_samples": 5
    "sampling_rate": 24000
    "num_band": 1
    "pretrain_steps": 0
    "multi_resolution": 0
    "frame_shift": 240
    "load_D": 1
    "up_sample": [
      5,
      4,
      4,
      3,
    ]
    "use_lsgan": 1
    "sub_dis": 1
    "run_hdfs": 0
    "offset": 0
    "single_stft": 0
    "use_interpolate": 0
    "use_time_loss": 1
    "use_mel_loss": 1
    "use_F_dis": 0
    "use_sbd": 0
    "use_melnorm": 0
    "lr": 0.0005
    "num_workers": 0
    "use_pitch_condition": 0
    "dim_pitch_condition": 1
    "mode_pitch_condition": "singgan_torch"
    "use_aug_pitch": 0
    "backbone_resampling": "librosa_kaiser_best"
    "use_msg_gan": 0
    "use_pitch_prediction": 0
    "use_speaker_prediction": 0
    "tf_start_step": 0
    "tf_end_step": 0
    "tf_start_ratio": 0.0
    "tf_end_ratio": 0.0
    "lambda_log_pitch": 0.4
    "lambda_voiced": 1.0
    "loss_pitch": 1.0
    "loss_speaker": 1.0
    "loss_stft": 0.0
    "tf": 1
    "noise_index": 1.0
    "nr": 0
    use_tanh: true
    res_layers: 1
    all_noise: false
  ngf: 96
  adam_b1: 0.8
  adam_b2: 0.99
  lr: 0.0001
  disc_lr: 0.0001
  max_samples: 48000