---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 2023
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# data configuration
save_path: logs
hdfs_save_path: null  # hdfs://harunava/home/byte_speech_sv/jingsonggao
filename: music_emb
compress: True

# running parameters
ckpt_path: null

log_dir: logs
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: MuLan
    version: '0.1'
    precision: 32
    num_workers: 4
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    enable_activation_ckpt: True
    batch_size: 128
    text_encoder: bert-base-uncased
    music_encoder: MIT/ast-finetuned-audioset-10-10-0.4593
    spec_aug: False
    learning_rate: 4.e-5
    weight_decay: 5.e-4
    temperature: 0.1  # temperature in Multiview Coding loss

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset: !new:recipes.mulan.dataset.infer.MuLanInferDataset
    meta_path: 15m_filter_trim_retrieval_pool_30k.txt

# datamodule configuration
pl_datamodule: !new:recipes.mulan.modules.pl_datamodule.MuLanInferDataModule
    predict_dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>

# model configuration
model_cls: !name:samantha.stage.pipeline.ModelPipeline
    input_names:
        train: [input_ids, attention_mask, token_type_ids, audio]
        predict: [audio]
    output_names:
        train: [text_embed, music_embed]
        predict: [music_embed]
    pipeline:
        train: [text_encoder, music_encoder]
        predict: [music_encoder]
    stages:
        text_encoder: !name:recipes.mulan.models.text_encoder.TextEncoder
            takes: [input_ids, attention_mask, token_type_ids]
            provides: [text_embed]
            text_encoder: !ref <run_opts[text_encoder]>
        music_encoder: !name:recipes.mulan.models.music_encoder.MusicEncoder
            takes: [audio]
            provides: [music_embed]
            music_encoder: !ref <run_opts[music_encoder]>
            sample_rate: 24000
            spec_aug: !ref <run_opts[spec_aug]>

pl_module: !new:recipes.mulan.modules.pl_module.LitMuLanModule
    model_cls: !ref <model_cls>
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    temperature: !ref <run_opts[temperature]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

callbacks:
    - !new:recipes.mulan.modules.callbacks.MuLanInferWriter
      save_path: !ref <save_path>
      hdfs_save_path: !ref <hdfs_save_path>
      filename: !ref <filename>
      compress: !ref <compress>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: True
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    replace_sampler_ddp: False
    logger: !ref <logger>
    callbacks: !ref <callbacks>
    precision: !ref <run_opts[precision]>
