---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: 10
    lyrics_codebook_size: 80
    lyrics_max_seq_len: 150
    chroma_vocab_size: 13 # 12 + silence
    chroma_max_seq_len: 60 # 12 + silence
    soundstream_codebook_size: 1024
    soundstream_frame_rate: 50
    mulan_codebook_size: 1024
    extra_seq_length_padding: 512
    mulan_num_rvq: 12
    special_tokens_size: 16
    num_coarse: 4
    num_fine: 8
    dataset_type: mixture_only # conditional_vocals|multitask|mixture_only
    vocal_condition_p: 0.5
    chroma_condition_p: 0.5

    mulan_vocab_size: !ref <extra_params[mulan_num_rvq]> * <extra_params[mulan_codebook_size]>
    soundstream_vocab_size: !ref <extra_params[soundstream_codebook_size]> * <extra_params[num_coarse]>

    vocab_size: !ref <extra_params[lyrics_codebook_size]> + <extra_params[mulan_vocab_size]> + <extra_params[soundstream_vocab_size]> + <extra_params[chroma_vocab_size]> + <extra_params[extra_seq_length_padding]> + <extra_params[special_tokens_size]>
    soundstream_seq_length: !ref <extra_params[soundstream_frame_rate]> * <extra_params[num_coarse]> * <extra_params[duration]>
    max_seq_length: !ref <extra_params[lyrics_max_seq_len]> + <extra_params[mulan_num_rvq]> + <extra_params[soundstream_seq_length]> + <extra_params[chroma_max_seq_len]> + <extra_params[extra_seq_length_padding]> + <extra_params[special_tokens_size]>

    pretrained_path: null # for loading state dicts

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: mulan_phoneme_coarse_conditional
    version: conditional_v0
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 16
    accelerator: auto
    max_steps: 1000000
    batch_size: 28
    learning_rate: 4.0e-4
    warmup_steps: 2000
    cycle_steps: 200000
    weight_decay: 0.01
    shuffle_buffer: 50
    gradient_clip_val: 1.0

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

lyrics_tokenizer: !new:recipes.l2v.datasets.tokenizers.phoneme_tokenizer.PhonemeTokenizer
    allow_unknown: False

lyrics_collator: !new:recipes.l2v.datasets.lyrics.LyricsCollator
    lyrics_padding_value: !ref <lyrics_tokenizer.pad_id>
    lyrics_max_seq_len: !ref <extra_params[lyrics_max_seq_len]>
    audio_max_seq_len: !ref <extra_params[duration]> * <extra_params[sample_rate]>

pl_datamodule: !apply:recipes.l2v.datasets.lyrics.LyricsDataModule.from_dataset_type
    batch_size: !ref <run_opts[batch_size]>
    sample_rate: !ref <extra_params[sample_rate]>
    sample_duration: !ref <extra_params[duration]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    lyrics_max_seq_len: !ref <extra_params[lyrics_max_seq_len]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    dataset_type: !ref <extra_params[dataset_type]>

model_config: !new:transformers.LlamaConfig
    vocab_size: !ref <extra_params[vocab_size]>
    hidden_size: 768
    intermediate_size: 3072
    num_hidden_layers: 12
    num_attention_heads: 12
    hidden_act: "silu"
    max_position_embeddings: !ref <extra_params[max_seq_length]>
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[soundstream_vocab_size]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.l2v.lightning.lyrics_modules.EmbedMulanPhonemeCoarseModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        # mulan:
        #     - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/g4/checkpoints/mulan-step=044800-median_rank_1=170-kaggle.ckpt
        #     - !name:recipes.musiclm.requires.model_initializer.init_mulan
        #       cache_dir: !ref <run_opts[cache_dir]>
        #       version: "g4"
        # v1.3 - try running if results look good
        # mulan:
        #     - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
        #     - !name:recipes.musiclm.requires.model_initializer.init_mulan
        #       cache_dir: !ref <run_opts[cache_dir]>
        #       version: "g4"
        # Mulan Latest Vocal
        # mulan:
        #     - /mnt/bn/audio-diffusion/mulan_exp/MuLan_large/mulan_mme_0701_supcon/checkpoints/mulan-step=006600-median_rank_0=228-kaggle.ckpt
        #     - !name:recipes.musiclm.requires.model_initializer.init_mulan
        #       cache_dir: !ref <run_opts[cache_dir]>
        #       version: "g4"
        # Mulan Vocal - 180
        mulan:
            hpath: /mnt/bn/audio-diffusion/mulan_exp/MuLan_large/mulan_0705_mmme/checkpoints/mulan-step=005000-median_rank_0=180-kaggle.ckpt
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "g4"
        soundstream:
            hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            initializer: !name:recipes.musiclm.requires.model_initializer.init_soundstream
                cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      save_last: True
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    # - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: 4000
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0  # skip validation sanity checks so we don't run into hdfs file close errors
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
