---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']
_checkpointing: False

extra_params:
    sample_rate: 24000
    duration: 10
    wav2vec_embed_dim: 1024
    wav2vec_frame_rate: 25
    lyrics_codebook_size: 80
    lyrics_max_seq_len: 150
    special_tokens_size: 16
    mulan_embed_dim: 512
    mulan_seq_len: 1
    dataset_type: mixture_only # conditional_vocals|multitask|mixture_only
    semantic_type: "best_rq"
    semantic_layer_idx: 12

    vocab_size: !ref <extra_params[lyrics_codebook_size]> + <extra_params[special_tokens_size]>
    max_seq_length: !ref <extra_params[lyrics_max_seq_len]> + <extra_params[special_tokens_size]> + <extra_params[mulan_seq_len]> + <extra_params[wav2vec_frame_rate]> * <extra_params[duration]>
# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_embed
    version: v0
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 16
    accelerator: auto
    val_check_interval: 5000
    max_steps: 1000000
    batch_size: 80
    learning_rate: 3.0e-4
    warmup_steps: 2000
    cycle_steps: 200000
    weight_decay: 0.01
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    shuffle_buffer: 50
    gradient_clip_val: 1.0

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################


lyrics_tokenizer: !new:recipes.l2v.datasets.tokenizers.phoneme_tokenizer.PhonemeTokenizer
    allow_unknown: False

lyrics_collator: !new:recipes.l2v.datasets.lyrics.LyricsCollator
    lyrics_padding_value: !ref <lyrics_tokenizer.pad_id>
    lyrics_max_seq_len: !ref <extra_params[lyrics_max_seq_len]>
    audio_max_seq_len: !ref <extra_params[duration]> * <extra_params[sample_rate]>

pl_datamodule: !apply:recipes.l2v.datasets.lyrics.LyricsDataModule.from_dataset_type
    dataset_type: !ref <extra_params[dataset_type]>
    batch_size: !ref <run_opts[batch_size]>
    sample_rate: !ref <extra_params[sample_rate]>
    sample_duration: !ref <extra_params[duration]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    lyrics_max_seq_len: !ref <extra_params[lyrics_max_seq_len]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

model_config: !new:transformers.LlamaConfig
    vocab_size: !ref <extra_params[vocab_size]>
    hidden_size: !ref <extra_params[wav2vec_embed_dim]>
    intermediate_size: 3072
    num_hidden_layers: 16
    num_attention_heads: 16
    hidden_act: "silu"
    max_position_embeddings: !ref <extra_params[max_seq_length]>
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[wav2vec_embed_dim]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.l2v.lightning.lyrics_modules.LyricsSemanticEmbedModule
    checkpointing: !ref <_checkpointing>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    # criterion_cls: !name:torch.nn.MSELoss
    criterion_cls: !name:torch.nn.HuberLoss
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        # wav2vec:
        #     - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/semantic.jit.pt
        #     - !name:recipes.musiclm.requires.model_initializer.init_wav2vec
        #       cache_dir: !ref <run_opts[cache_dir]>
        best_rq_minz:
            - null
            - !name:recipes.musiclm.requires.model_initializer.init_best_rq_minz
              cache_dir: null

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 50
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_loss_0:.4f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
