---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: 30
    lyrics_codebook_size: 400
    lyrics_max_seq_len: 400
    semantic_codebook_size: 32_768
    semantic_frame_rate: 25
    mulan_embed_dim: 512
    hidden_size: 1536
    semantic_type: bestrq
    pretrained_path: "/mnt/bn/audio-diffusion/qq/logs/semantic_model_mulan_text_07B_sft/billboard-skipnogenre-js/checkpoints/last.ckpt"
    # Inference params
    semantic_temperature: 1.0
    sample_mode: "gumbel"
    beam_size: 2
    decoder_type: "diffusion"
    diffusion_steps: 10
    bf16_portion: 1.0
    # RL training params
    add_ref_to_beam: False
    ce_weight: 0.1
    seq_weight: 10
    positive_phrase: "cd quality, catchy, memorable"
    negative_phrase: "noisy, boring, forgettable"
    use_chord_eos: False
    rewards:
        "mulan_sim": 1.0
        "wer": 1.0
        "style_text_sim": 1.0
        "loudness_sim": 1.0
        "qualitative_sim": 1.0
        "chord": 1.0
        "structure": 1.0
    # Logging params
    log_num_val_samples: 10
    log_num_val_beam_samples: 1

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_model_mulan_rlhf
    version: billboard_rl
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 4
    accelerator: auto
    max_steps: 5000
    batch_size: 3
    learning_rate: 1.0e-6
    warmup_steps: 100
    cycle_steps: 5000
    weight_decay: 0.01
    shuffle_buffer: 50
    buckets_in_sec: [20, 25, 30] # TODO: Tune for CPU usage and diversity
    use_dynamic_batch: False
    include_intro: True
    max_seg_per_track: 3
    gradient_clip_val: 1.0
    val_check_interval: 250
    save_last: False
    # Supporting models
    mulan_ckpt: "/mnt/bn/audio-diffusion/mulan/ongoing/mulan-step=014000-median_rank_1=160-kaggle.ckpt"
    bestrq_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt"
    diffusion_ckpt: "/mnt/bn/audio-diffusion/wtl/diffusion/model_14_30s_finetune/checkpoints/last.ckpt"
    vocoder_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/soundstream-step=374999-val_sdr=12.9557.ckpt"
    chord_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/semi-sup-chord_epoch=103-step=56300.ckpt"
    chord_lms:
        #default: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/default/lm.arpa"
        blues: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/blues+country/lm.arpa"
        country: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/blues+country/lm.arpa"
        indie: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/pop+indie+indie_pop/lm.arpa"
        indie_pop: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/pop+indie+indie_pop/lm.arpa"
        k_pop: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/pop+indie+indie_pop/lm.arpa"
        pop: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/pop+indie+indie_pop/lm.arpa"
        rnb_soul: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/rnb_soul/lm.arpa"
        rock: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/rock/lm.arpa"
    structure_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/structure_epoch=185-step=93000.ckpt"

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.mix.SFTBilloardWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_in_sec: !ref <run_opts[buckets_in_sec]>
    use_dynamic_batch: !ref <run_opts[use_dynamic_batch]>
    include_intro: !ref <run_opts[include_intro]>
    max_seg_per_track: !ref <run_opts[max_seg_per_track]>
    use_pipe: True

model_config: !new:transformers.LlamaConfig
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    hidden_size: !ref <extra_params[hidden_size]>
    intermediate_size: 4128
    num_hidden_layers: 24
    num_attention_heads: 12
    hidden_act: "silu"
    max_position_embeddings: 4096 # hardcoded long sequence length for positional encoder
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.SemanticRLModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    extra_params: !ref <extra_params>
    required_modules:
        # Mulan mix - 160
        mulan:
            hpath: !ref <run_opts[mulan_ckpt]>
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "g4"
        bestrq:
            hpath: !ref <run_opts[bestrq_ckpt]>
            initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                cache_dir: !ref <run_opts[cache_dir]>
        sampler:
            hpath: null
            initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                cache_dir: !ref <run_opts[cache_dir]>
                duration: !ref <extra_params[duration]>
        diffusion:
            hpath: !ref <run_opts[diffusion_ckpt]>
            initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                cache_dir: !ref <run_opts[cache_dir]>
        vocoder:
            hpath: !ref <run_opts[vocoder_ckpt]>
            initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                cache_dir: !ref <run_opts[cache_dir]>
        chord:
            hpath: !ref <run_opts[chord_ckpt]>
            initializer: !name:recipes.chord.requires.model_initializer.init_chord
                cache_dir: !ref <run_opts[cache_dir]>
        chord_lms:
            hpath: !ref <run_opts[chord_lms]>
            initializer: !name:recipes.chord.requires.model_initializer.init_chord_lms
                cache_dir: !ref <run_opts[cache_dir]>
        structure:
            hpath: !ref <run_opts[structure_ckpt]>
            initializer: !name:recipes.structure.requires.model_initializer.init_structure
                cache_dir: !ref <run_opts[cache_dir]>
        asr:
            hpath: en_punc
            initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr
        #non_vocal_mulan:
        #    hpath: hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
        #    initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
        #        cache_dir: !ref <run_opts[cache_dir]>
        #        version: "g4"
        #        prefix: "non_vocal_"

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    #- !new:pytorch_lightning.loggers.wandb.WandbLogger
    #  save_dir: !ref <run_opts[log_dir]>
    #  project: !ref <run_opts[log_name]>
    #  name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      save_last: !ref <run_opts[save_last]>
      monitor: step
      mode: max
      filename: "{step:06d}"
      every_n_train_steps: !ref <run_opts[val_check_interval]>
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 25
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
