---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: "last"

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision:
    !apply:torch.set_float32_matmul_precision ["high"]

extra_params:
    lyrics_seq_len: 2000
    leadsheet_seq_len: 5000
    n_embd: 384
    n_layer: 8
    n_head: 8
    n_inner: 512

# running parameters
run_opts:
    train_id: 1838
    val_id: 1839
    fast_dev_run: False
    arnold_output: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_dir: !apply:os.getenv ["LOG_DIR", "logs"]
    version: base
    # cache_dir: .module_cache/musiclm
    precision: "16-mixed"
    num_workers: 32
    accelerator: auto
    max_steps: 200000
    batch_size: 100
    learning_rate: 3.0e-4
    warmup_steps: 2000
    cycle_steps: 80000
    weight_decay: 0.1
    shuffle_buffer: 100
    gradient_clip_val: 1.0
    val_check_interval: 4000
    save_interval: 8000

data_config:
    !new:recipes.bigmusic.datasets.symbolic_music.fl_p2vm_codec.FLP2VMCodec.Config
    lyrics_seq_len: !ref <extra_params[lyrics_seq_len]>
    leadsheet_seq_len: !ref <extra_params[leadsheet_seq_len]>

indexer: !apply:recipes.bigmusic.datasets.symbolic_music.base_codec.get_indexer
    config: !ref <data_config>
vocab_size: !apply:len
    - !ref <indexer>

pl_datamodule:
    !apply:recipes.bigmusic.datasets.symbolic_music.fl_p2vm_codec.FLP2VMCodec.get_datamodule
    config: !ref <data_config>
    train_id: !ref <run_opts[train_id]>
    val_id: !ref <run_opts[val_id]>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle_buffer: !ref <run_opts[shuffle_buffer]>

# pl_datamodule: !apply:recipes.bigmusic.datasets.symbolic_music.fl_p2vm_codec.FLP2VMCodec.get_datamodule
#     config: !ref <data_config>
#     train_id: !ref <run_opts[train_id]>
#     val_id: !ref <run_opts[val_id]>
#     batch_size: !ref <run_opts[batch_size]>
#     num_workers: !ref <run_opts[num_workers]>
#     shuffle_buffer: !ref <run_opts[shuffle_buffer]>

model_config: !new:transformers.GPT2Config
    vocab_size: !ref <vocab_size>
    max_position_embeddings: 0
    use_cache: False
    n_positions: 0 # No absolute position embedding
    num_logits: !ref <vocab_size>
    n_embd: !ref <extra_params[n_embd]>
    n_layer: !ref <extra_params[n_layer]>
    n_head: !ref <extra_params[n_head]>
    n_inner: !ref <extra_params[n_inner]>
    use_rms_norm: True
    activation_function: "swiglu"
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.0
    layer_norm_epsilon: 1e-6
    initializer_range: 0.02
    rescale_prenorm_residual: False
    rms_norm: True
    rotary_emb_fraction: 1.0
    rotary_emb_interleaved: True
    rotary_emb_compat: "default" #"byteformer"
    tie_word_embeddings: False
    qkv_proj_bias: False
    out_proj_bias: False
    mlp_fc1_bias: False
    mlp_fc2_bias: False
    use_flash_attn: True
    fused_bias_fc: True
    fused_mlp: False
    fused_dropout_add_ln: True
    residual_in_fp32: True

model_cls: !name:samantha.models.ctiga.gpt.GPTLMHeadModel
    config: !ref <model_config>

## For debug
# model_cls: !name:recipes.bigmusic.lightning.symbolic_music_modules.DebugModel
#     vocab_size: !ref <vocab_size>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls:
    !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module:
    !new:recipes.bigmusic.lightning.symbolic_music_modules.Lyrics2SymbolicMusicModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    required_modules: {}
    extra_params: !ref <extra_params>

## Setting to my own log_dir would cause some hdfs issues that I have no idea how to fix
logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[arnold_output]>
      name: !ref <run_opts[version]>
      default_hp_metric: False
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[arnold_output]>
      project: chaonan99
      name: !ref <run_opts[version]>

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !apply:os.path.join
          - !ref <run_opts[log_dir]>
          - !ref <run_opts[version]>
      monitor: step
      save_top_k: 10
      save_last: True
      every_n_train_steps: 1000
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_loss_0:.4f}"

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO
      # profiler: !new:pytorch_lightning.profilers.PyTorchProfiler
      #     schedule: !apply:torch.profiler.schedule
      #         wait: 0
      #         warmup: 50
      #         active: 10
      #         repeat: 1
      #         skip_first: 100


trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0 # skip validation sanity checks so we don't run into hdfs file close errors
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
    # profiler: !ref <profiler>
