---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null
seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision:
    !apply:torch.set_float32_matmul_precision ["high"]

extra_params:
    sample_rate: 24000
    lyrics_codebook_size: 2000
    speaker_codebook_size: 100
    audio_codebook_size: 32_768
    semantic_codebook_size: 33_768
    semantic_frame_rate: 25
    semantic_type: bestrq
    train_conditions: "style_category,speaker_id,lyrics_tokens"
    prepare_input_types: []
    input_embedders: [tag_categorical, speaker_id, lyrics_tokens]
    tag_taxonomy_lang: "SA" # Zh, SA
    tag_dropout_rate: 0.1
    line_break_dropout_rate: 0
    section_tag_dropout_rate: 0
    use_mcc_gender: False
    # mulan_embed_dim: 512
    hidden_size: 1536
    intermediate_size: 4352
    num_hidden_layers: 24
    num_attention_heads: 12
    pretrained_path: null
    tokenizer_path: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"
    # mulan_path: "hdfs://haruna/home/byte_speech_sv/mulan/cn_mulan_ckpt/mulan-step=012800-kaggle-minimal.ckpt"
    segment_max_leadsheet_len: !ref <run_opts[segment_max_leadsheet_len]>
    leadsheet_codec: !ref <leadsheet_codec>

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: logs
    hdfs_log_dir: "hdfs:///home/byte_speech_sv/zhongyi.huang/logs"
    log_name: lyric2symbolic2song_zh_sft
    version: debug
    cache_dir: .module_cache/bigmusic
    precision: "16"
    num_workers: 6
    accelerator: auto
    max_steps: 10000
    val_check_interval: 1000
    batch_size: 10
    learning_rate: 1.0e-4
    warmup_steps: 200
    cycle_steps: 4000       # If use 1 GPU to run SFT, about 1.5K steps is an epoch.
    weight_decay: 0.05
    shuffle_buffer: 0   # 100
    gradient_clip_val: 1.0
    buckets_in_sec: [30, 40, 50, 60]
    use_dynamic_batch: False
    max_seg_per_track: 3
    segment_method: "random"
    infer_structure_tags: False
    read_structure_tags: True
    region: "CN"
    lyrics_field: "lyrics"
    lyrics_confidence: 0.7  # SA ASR confidence
    lyrics_tokenizer: "tts_chinese_frontend_model"
    segment_max_phone_len: 600
    segment_max_leadsheet_len: 2000
    parquet_dataset_ids: [2192]
    parquet_dataset_weights: [1]
    sinking_threshold: 0.51
    validation_parquet_dataset_ids: 2191
    quality_filter: True
    stems: "vocal,piano,guitar,bass,drums"

data_config:
    !new:recipes.bigmusic.datasets.symbolic_music.fl_p2t5_codec.FLP2T5Codec.Config
    lyrics_seq_len: !ref <run_opts[segment_max_phone_len]>
    leadsheet_seq_len: !ref <run_opts[segment_max_leadsheet_len]>
    stems: !ref <run_opts[stems]>
    include_utterance_phoneme_tokens: False
    include_phoneme: True
    include_section_indicator_each_bar: True
    include_drum_events: True

leadsheet_codec:
    !new:recipes.bigmusic.datasets.symbolic_music.fl_p2t5_codec.FLP2T5Codec
    config: !ref <data_config>

indexer: !apply:recipes.bigmusic.datasets.symbolic_music.base_codec.get_indexer
    config: !ref <data_config>
remi_leadsheet_codebook_size: !apply:len
    - !ref <indexer>

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.mix.MixVocalWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_in_sec: !ref <run_opts[buckets_in_sec]>
    use_dynamic_batch: !ref <run_opts[use_dynamic_batch]>
    max_seg_per_track: !ref <run_opts[max_seg_per_track]>
    tokenizer: !ref <run_opts[lyrics_tokenizer]>
    segment_max_phone_len: !ref <run_opts[segment_max_phone_len]>
    segment_max_leadsheet_len: !ref <run_opts[segment_max_leadsheet_len]>
    region: !ref <run_opts[region]>
    conditions: !ref <extra_params[train_conditions]>
    lyrics_field: !ref <run_opts[lyrics_field]>
    lyrics_confidence: !ref <run_opts[lyrics_confidence]>
    read_structure_tags: !ref <run_opts[read_structure_tags]>
    infer_structure_tags: !ref <run_opts[infer_structure_tags]>
    segment_method: !ref <run_opts[segment_method]>
    parquet_dataset_ids: !ref <run_opts[parquet_dataset_ids]>
    parquet_dataset_weights: !ref <run_opts[parquet_dataset_weights]>
    validation_parquet_dataset_ids: !ref <run_opts[validation_parquet_dataset_ids]>
    sinking_threshold: !ref <run_opts[sinking_threshold]>
    quality_filter: !ref <run_opts[quality_filter]>
    frame_rate: !ref <extra_params[semantic_frame_rate]>
    tag_taxonomy_lang: !ref <extra_params[tag_taxonomy_lang]>
    line_break_dropout_rate: !ref <extra_params[line_break_dropout_rate]>
    section_tag_dropout_rate: !ref <extra_params[section_tag_dropout_rate]>
    leadsheet_codec: !ref <leadsheet_codec>
    normalize_audio: True

model_config: !new:transformers.GPT2Config
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    max_position_embeddings: 0
    use_cache: False
    n_positions: 0 # No absolute position embedding
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS
    n_embd: !ref <extra_params[hidden_size]>
    n_layer: !ref <extra_params[num_hidden_layers]>
    n_head: !ref <extra_params[num_attention_heads]>
    n_inner: !ref <extra_params[intermediate_size]>
    use_rms_norm: True
    activation_function: "swiglu"
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.0
    layer_norm_epsilon: 1e-6
    initializer_range: 0.02
    rescale_prenorm_residual: False
    rms_norm: True
    rotary_emb_fraction: 1.0
    rotary_emb_interleaved: True
    rotary_emb_compat: "default" #"byteformer"
    tie_word_embeddings: False
    qkv_proj_bias: False
    out_proj_bias: False
    mlp_fc1_bias: False
    mlp_fc2_bias: False
    use_flash_attn: True
    fused_bias_fc: True
    fused_mlp: False
    fused_dropout_add_ln: True
    residual_in_fp32: True

model_cls: !name:samantha.models.ctiga.gpt.GPTLMHeadModel
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls:
    !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module:
    !new:recipes.bigmusic.lightning.semantic_modules.SemanticModuleExtendedTarget
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        bestrq:
            # US UMM-chroma-Zh stage 3
            hpath: !ref <extra_params[tokenizer_path]>
            initializer:
                !name:recipes.umm.requires.model_initializer.init_stage3
                cache_dir: !ref <run_opts[cache_dir]>
        # Mulan mix - 110
        # mulan:
        #     hpath: !ref <extra_params[mulan_path]>
        #     initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
        #         cache_dir: !ref <run_opts[cache_dir]>
        #         version: "Chinese"
        # mulan_tagger:
        #     hpath: null
        #     initializer: !name:recipes.bigmusic.utils.mulan_tag.init_mulan_tagger
        #         cache_dir: !ref <run_opts[cache_dir]>
        #         mulan_tag_type: cn_mir

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 20
      save_last: True
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_accu_0:.2f}"
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 20
      save_last: True
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: "step"
    # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicDataUsageLogger
    #   save_dir: /mnt/bn/audio-diffusion/qq/data_usage_logs
    #   save_every_n_iter: 5000
    # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicAudioDataLogger
    #   sample_rate: !ref <extra_params[sample_rate]>
    #   check_interval: !ref <run_opts[val_check_interval]>
    #   examples_per_batch: 8

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 500
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2 # skip validation sanity checks so we don't run into hdfs file close errors
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
