---
#   | Name  | Type          | Params
# ----------------------------------------
# 0 | model | PipelineModel | 122 M 
# ----------------------------------------
# 122 M     Trainable params
# 0         Non-trainable params
# 122 M     Total params
# 491.359   Total estimated model params size (MB)
# @hanoihantrakul 14APR2024
# This training config exists because Ren Yi, Qingqing and myself were trying to
# ablate the effectiveness of the ConformerUMM, ConvUMM and DualUMM on the 
# downstream ZH Lyrics2Song task.
# 
# We wanted to train from scratch Stage1, Stage2 and Stage3 model using new data
# from Parquet ID 2255. 
#
# The associated stage1 config is `umm_stage1_2255mixedZHEN.yaml`
# This model has 723M params.
# With batch_size=8 and max_duration=8 I can get 66.20GB GPU utilization.

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: !ref last.ckpt

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    frame_rate: 25
    n_mels: 128
    n_chroma: 12
    n_fft: 2048
    win_length: 2048
    hop_length: 240
    feature_cmvn: "recipes/datasets/mcc/data_ids=794.stats.pt" # we need this because original mkii ConformerUMM normalized using these statistics
    tokenizer: "bert-base-multilingual-uncased" # stage2 apply language tokenizer to both EN and CN

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    hdfs_log_dir: "hdfs:///home/byte_speech_sv/ju-chiang.wang/logs"
    log_dir: logs
    log_name: melrof_2255mixedZHEN
    version: !ref stage3_unfold_<extra_params[tokenizer]>_vq_<config[vq_codebook_size]>x<config[vq_codebook_dim]>
    precision: "16-mixed"
    num_workers: 5
    accelerator: auto
    warmup_steps: 2000
    max_steps: 10000000
    val_check_interval: 5000 # 14APR2024 @hanoihantrakul set limit_train_val_batches=1 so that validation loop is called
    ckpt_interval: 5000
    batch_size: 5
    learning_rate: 1.0e-4
    cycle_steps: 200000
    weight_decay: 0.1
    shuffle_buffer: 800 # 8000 # See above comments on why I picked this number
    gradient_clip_val: 1.0
    checkpointing: False
    use_avg_pool: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################


pl_datamodule: !new:recipes.datasets.mcc.mix_mkii.MixDataModule
    data_ids: [2255, 2375]
    val_data_id: 2255
    data_weights: [10, 1]
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
    num_workers: !ref <run_opts[num_workers]>
    max_num_crops: null
    min_duration: 1
    max_duration: 60 # 12APR2024 Hanoi and Devon Sun and I manually verified this datasert only contains audio lengths between 0-60s.
    normalize_audio: False
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    # collate_fn: !name:recipes.datasets.mcc.mix.collate_audio # 14APR2024 @hanoihantrakul Must turn this off for Stage2 because you need both `audio` and `token` to be passed by default collate_fn
    

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.umm2.modules.lr_scheduler.WarmupCosine
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

config: !new:recipes.umm2.models.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    n_mels: !ref <extra_params[n_mels]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    n_chroma: !ref <extra_params[n_chroma]>
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 24
    num_attention_heads: 8
    max_source_positions: !ref <extra_params[frame_rate]> * <pl_datamodule[max_duration]>
    add_vq: True
    vq_proj_norm: "melrof" 
    vq_proj_noise: 10000
    vq_codebook_size: 32768
    vq_codebook_dim: 64
    vq_layer_idx: 12
    vq_decay: 0.99
    w_loss_mel: 1.0
    w_loss_chroma: 0.5
    w_loss_vq: 0.5
    w_loss_ctc: 1.0
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    vocab_size: 105880
    ctc_blank_id: 105879
    ctc_zero_infinity: True
    use_bn: False
    # melroformer parameter
    use_power_stft: True
    use_avg_pool: !ref <run_opts[use_avg_pool]>
    mel_bands: 16
    num_feature: 128
    use_checkpoint: !ref <run_opts[checkpointing]>
    use_flash_attn: True
    enforce_dropout: 0.1
    out_num_feature: 64

vq_module: !new:recipes.umm2.models.tasks.vq_module.VQ  # BaseStage
    task: "vq"
    loss_weight: !ref <config[w_loss_vq]>
    config: !ref <config>
    takes: [latent]
    provides: [latent, vq_ids, vq_entropy]
    lr_ratio: 0.1

stage1: !new:recipes.umm2.models.tasks.autoencoder_melrof.AE_UMM # BaseStage
    config: !ref <config>
    takes: [audio]
    provides: [audio, mel, latent, vq_ids, vq_entropy] 
    bypasses: [token]
    lr_ratio: 0.1
    insert_modules:
        12 : !ref <vq_module>

mel_head: !name:recipes.umm2.models.tasks.mel_head.Mel_Head # BaseStage
    task: "mel"
    loss_weight: !ref <config[w_loss_mel]>
    config: !ref <config>
    takes: [mel, latent]
    provides: [mel, mel_out]
    use_conv: False
ctc_head: !name:recipes.umm2.models.tasks.ctc_head.CTC_Head # BaseStage
    task: "ctc"
    loss_weight: !ref <config[w_loss_ctc]>
    config: !ref <config>
    takes: [token, latent]
    provides: [text_ids, ctc_out] 
hpss_head: !name:recipes.umm2.models.tasks.hpss_head.HPSS_Head # BaseStage
    task: "hpss"
    loss_weight: !ref <config[w_loss_chroma]>
    config: !ref <config>
    takes: [audio, latent]
    provides: [chroma, chroma_out]
    use_conv: False

stage2: !name:recipes.umm2.models.base.SpanModel
    input_names: [audio, token, mel, latent]
    output_names: [mel, mel_out, text_ids, ctc_out] 
    bypass_names: [vq_ids, vq_entropy, loss_vq]
    spans:
        mel: !ref <mel_head>
        ctc: !ref <ctc_head>
        hpss: !ref <hpss_head>

model: !name:recipes.umm2.models.base.PipelineModel
    input_names: [audio, token]
    output_names: [mel, mel_out, text_ids, ctc_out, vq_ids, vq_entropy] 
    stages:
        - !ref <stage1>
        - !ref <stage2>

required_modules:
    pretrained: 
        ckpt_path: "hdfs://haruna/home/byte_speech_sv/ju-chiang.wang/logs/melrof_2255mixedZHEN/stage2_unfold_mel_ctc_hpss_bert-base-multilingual-uncased/checkpoints/step=0060000.ckpt"
        loader: !name:recipes.umm2.loaders.stage2.ModelLoader
        cache_dir: !ref <run_opts[cache_dir]>


pl_module: !new:recipes.umm2.modules.stages.stage3.Stage3
    config: !ref <config>
    checkpointing: False  # nothing to do with melrof checkpointing, which is implemented in model architecture
    model_cls: !ref <model>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    extra_params: !ref <extra_params>
    required_modules: !ref <required_modules>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 5
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
      save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1 # TODO
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    limit_val_batches: 1 # Turn on 1 batch so that spectrograms from validation dataloader can be plotted
    limit_train_batches: 5000 # 10000 # Consult Colin Wang: forces an epoch to end every 10k steps and prevent OOM # See above comments on why I picked this number
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>