---
# @renyi @hanoihantrakul 27Feb2024
#
# DualUMM V1 is a 3rd generation system that separates the tokens generated for 
# vocals and instrumentals. This is different from the 1st gen ConformerUMM and
# 2nd gen ConvUMM, where the same tokenizer is used for both vocals and 
# instruments. The advantage of this approach is better disentanglement between
# vocals and instrumentals, which is critical for downstream tasks that are
# instrument-only (e.g. SSTK model) or vocal-only (SVS) or both (lyrics2song)
#
# This config is the standard base config for training a DualUMM model. 
# Special details:
# - It requires an MSS model to separate full mix audio into vocals 
#   and instrumentals
# - The code rate is 25Hz. This means vocal tokens are produced at 25Hz
#   and instrumental tokens are produced at 25Hz. A full mix is described
#   by concat [vocal,instrumental] tokens = 50Hz.
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: last

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    frame_rate: 25
    n_mels: 128
    n_mels_tgt: 160
    n_chroma: 12
    n_fft: 2048
    win_length: 2048
    hop_length: 240
    feature_cmvn: "recipes/datasets/mcc/MixDataModule_SpeechTransform.stats.pt"
    tokenizer: "bert-base-multilingual-uncased"

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    hdfs_log_dir: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/renyi/samantha_ckpts"
    log_dir: logs
    log_name: umm_mix
    version: !ref umm_stage3_preclipped_<extra_params[tokenizer]>_<config[vq_type]><config[vq_codebook_size]>x<config[vq_codebook_dim]>
    precision: "32"
    num_workers: 4
    accelerator: auto
    warmup_steps: 2000
    max_steps: 1000000
    val_check_interval: 10000
    ckpt_interval: 10000
    batch_size: 2.0
    learning_rate: 1.0e-4
    cycle_steps: 100000
    weight_decay: 0.0
    shuffle_buffer: 800
    gradient_clip_val: 0.0
    checkpointing: False
    tensorboard_dir: !ref <run_opts[log_dir]>

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.mcc.mix_mkii.MixMSSDataModule
    data_ids: [ 1154 ]
    val_data_id: 1154
    data_weights: [ 1 ]
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
    num_workers: !ref <run_opts[num_workers]>
    max_num_crops: null
    min_duration: 1
    max_duration: 90
    normalize_audio: False
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    audio_perturb: false

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

disc_optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: 0
    betas: [ 0.9, 0.900 ] # TODO
    eps: 0.00000001

scheduler_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.5

config: !new:recipes.umm.models.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    n_mels: !ref <extra_params[n_mels]>
    n_mels_tgt: !ref <extra_params[n_mels_tgt]>
    add_chroma: True
    add_pitch: True
    n_chroma: !ref <extra_params[n_chroma]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    hidden_size: 512
    intermediate_size: 1024
    num_hidden_layers: 12
    add_vq: True
    vq_proj_norm: "bn"
    vq_proj_noise: 10000
    vq_type: "EMAEntropy"
    vq_codebook_size: 16384
    vq_codebook_dim: 32
    vq_decay: 0.99
    vq_layer_idx: 6
    w_loss_mel: 1.0
    w_loss_chroma: 1.0
    w_loss_pitch: 1.0
    w_loss_vq: 1.0
    w_loss_ctc: 1.0
    w_loss_adv: 0.05
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    vocab_size: 105880
    ctc_blank_id: 105879
    ctc_zero_infinity: True
    use_bn: false
    hidden_dropout: 0.0
    activation_dropout: 0.0
    attention_dropout: 0.0
    conformer_conv_dropout: 0.0
    vq_warmup: false
    mss_input: true
    conv_hidden_size: 256
    train_decoder_only: false
    vocal_ref: false
    downsampling: 4
    upsampling: 1
    use_full_input: false

model_cls: !name:recipes.umm.models.dualumm.DualUMMv2
    config: !ref <config>

pl_module: !new:recipes.umm.modules.lit_module_mkii_dual.DualUMMv2
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    disc_optimizer_cls: !ref <disc_optimizer_cls>
    criterion_config: !ref <config>
    extra_params: !ref <extra_params>
    branches: ['vocal', 'inst', 'full']
    adv_branches: ['vocal', 'inst', 'full']
    detach_vocal_to_full: false
    required_modules:
        pretrained:
            ckpt_path: ""
#            ckpt_path: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm_mix/umm_stage2_bert-base-multilingual-cased/checkpoints/step=0060000.ckpt"
            init_fn: !name:recipes.umm.requires.model_initializer.init_pretrained
            cache_dir: !ref <run_opts[cache_dir]>
        rmvpe:
            ckpt_path: "hdfs://haruna/home/byte_speech_sv/user/chenyuanzhe/share/rmvpe.pt"
            init_fn: !name:recipes.umm.requires.model_initializer.init_rmvpe
            cache_dir: !ref <run_opts[cache_dir]>
        pitchpdt:
            ckpt_path: ""
#            ckpt_path: "pretrained/1120_sa_ws_gs_pitchpdt_singlec/model_ckpt_steps_300000.ckpt"
        vocoder:
            ckpt_path: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/renyi/samantha_ckpts/voc/v1/checkpoints/step=4170000.ckpt"
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.TensorBoardLogger
        save_dir: !ref <run_opts[tensorboard_dir]>
        name: !ref <run_opts[log_name]>
        version: !ref <run_opts[version]>
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
        save_dir: !ref <run_opts[log_dir]>
        project: !ref <run_opts[log_name]>
        name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
        hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
        monitor: step
        save_top_k: 500
        every_n_train_steps: !ref <run_opts[ckpt_interval]>
        mode: max
        filename: "{step:07d}"
        save_last: True
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
        dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
        monitor: step
        save_top_k: 3
        every_n_train_steps: !ref <run_opts[ckpt_interval]>
        mode: max
        filename: "{step:06d}"
        save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_true"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    limit_val_batches: 5
    limit_train_batches: 5000
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
