---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    n_mels: 128
    n_chroma: 12
    n_fft: 2048
    win_length: 2048
    hop_length: 240
    vq_syllable_codebook_size: 32768
    vq_chroma_codebook_size: 32768
    soundstream_codebook_size: 1024
    soundstream_frame_rate: 50
    num_coarse: 4

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    log_dir: "logs"
    log_name: umm
    version: !ref mkii_coarse
    precision: "16-mixed" # TODO
    num_workers: 12
    accelerator: auto
    warmup_steps: 2000
    max_steps: 5000000
    val_check_interval: 5000
    ckpt_interval: 10000
    batch_size: 4
    learning_rate: 5.0e-4 # TODO
    cycle_steps: 50000
    weight_decay: 0.1
    shuffle_buffer: 30
    gradient_clip_val: 1.0
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.mcc.mix.VocalWebDataModule
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    region: "CN"
    val_resampled: True
    weights: (1, 1)

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96] # TODO
    eps: 0.00000001

scheduler_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

model_config: !new:transformers.LlamaConfig
    vocab_size: !ref <extra_params[vq_syllable_codebook_size]> + <extra_params[vq_chroma_codebook_size]> + <extra_params[soundstream_codebook_size]> * <extra_params[num_coarse]> + 1
    hidden_size: 1024
    intermediate_size: 2752
    num_hidden_layers: 24
    num_attention_heads: 8
    hidden_act: "silu"
    max_position_embeddings: 6000
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[soundstream_codebook_size]> * <extra_params[num_coarse]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

pl_module: !new:recipes.umm.modules.lit_module.CoarseModule
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        mkii:
            ckpt_path: "hdfs:///home/byte_speech_sv/zongyu.yin/logs/umm/stage4_mkii_vq32768x16_vq32768x16/checkpoints/step=0020000.ckpt"
            init_fn: !name:recipes.umm.requires.model_initializer.init_mkii
            cache_dir: !ref <run_opts[cache_dir]>
        soundstream:
            # ckpt_path: "hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k"
            ckpt_path: "hdfs://haruna/home/byte_speech_sv/user/litang/vqgan_dev/2023-03-24_ss_dev_stft_x480_small_encoder/sound_stream_190k"
            init_fn: !name:recipes.umm.requires.model_initializer.init_soundstream
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    # - !new:pytorch_lightning.loggers.wandb.WandbLogger
    #   save_dir: logs # TODO
    #   project: !ref <run_opts[log_name]>
    #   name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    limit_val_batches: 1
    sync_batchnorm: True
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
