---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    duration: 30
    sample_rate: 24000

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: "logs"
    log_name: umm
    version: !ref pretrain_music_25hz_<model_cls[codebook_config[n_softmax]]>x<model_cls[codebook_config[codebook_size]]>
    precision: "16-mixed"
    num_workers: 6
    accelerator: auto
    max_steps: 1000000
    val_check_interval: 5000
    batch_size: 40
    learning_rate: 4.0e-3
    warmup_steps: 25000
    cycle_steps: 300000
    weight_decay: 0.1
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    shuffle_buffer: 500
    gradient_clip_val: 1.0
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

mcc40m: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/non_vocal_mcc_npy.filtered+audio_metrics_good/mega_index.with_ar_scores/npy_url2idx.txt"
    audio_key: "audio.npy"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    normalize_audio: True
    max_num_crops: 3
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc60m: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/vocal_mcc/mcc_60m_url2index_final.tsv"
    audio_key: "mp3"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    normalize_audio: True
    max_num_crops: 3
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True
    aed_filtered: False
    avoid_vocal: False

train_dataset: !new:samantha.dataio.dataset.MultiIterableDataset
    datasets: [!ref <mcc40m>, !ref <mcc60m>]
    weights: [1, 1]
    seed: !ref <seed>

validation_dataset: !new:recipes.musiclm.datasets.karaoke.KaraokeDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-0131.tar"
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.DataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

model_cls: !name:recipes.umm.models.bestrq.BestRQ
    frontend_config:
        n_mels: 128
        kernel: 5
        conv_dim: [256, 256]
        feature_cmvn: null
        sample_rate: !ref <extra_params[sample_rate]>
        n_fft: 2048
        hop_length: 240
        mask_hop: 0.4
        mask_prob: 0.3
        quantizer_layernorm: False
    encoder_config: !new:recipes.umm.models.flash_conformer.Wav2Vec2ConformerConfig
        hidden_size: 1024
        intermediate_size: 4096
        num_hidden_layers: 24
        num_attention_heads: 8
        max_source_positions: 750
        position_embeddings_type: "rotary"
        layerdrop: 0
        is_causal: False
    codebook_config:
        codebook_dim: 16
        codebook_size: 4096
        n_softmax: 8

pl_module: !new:recipes.umm.modules.lit_module.BestRQ
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 300
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_loss_0:.4f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
