---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 16000
    n_mels: 80
    n_fft: 512
    win_length: 400
    hop_length: 160
    feature_cmvn: "LibriLightWebDataModule_SpeechTransform.stats.pt"

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: "logs"
    log_name: umm
    version: !ref stage1_speech_rq<config[rq_codebook_size]>x<config[rq_codebook_dim]>x<config[rq_codebook_num]>
    precision: "16-mixed" # TODO
    num_workers: 6
    accelerator: auto
    max_steps: 1000000
    val_check_interval: 5000
    batch_size: 24
    learning_rate: 3.0e-4 # TODO
    warmup_steps: 25000
    cycle_steps: 300000
    weight_decay: 0.1
    shuffle_buffer: 500
    gradient_clip_val: 1.0
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.librilight.LibriLightWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    split: "large2"
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96] # TODO
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

config: !new:recipes.umm.models.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    num_channels: !ref <extra_params[n_mels]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    mask_hop: 0.4
    mask_prob: 0.2 # TODO
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 24
    num_attention_heads: 8
    max_source_positions: 750
    rq_codebook_dim: 16
    rq_codebook_size: 4096 # TODO
    rq_codebook_num: 8 # TODO
    add_vq: False

model_cls: !name:recipes.umm.models.umm.PreTrainedModel
    config: !ref <config>

pl_module: !new:recipes.umm.modules.lit_module.Stage1
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.umm.modules.criterion.MaskedCrossEntropy
    extra_params: !ref <extra_params>

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    # - !new:pytorch_lightning.loggers.wandb.WandbLogger
    #   save_dir: logs # TODO
    #   project: !ref <run_opts[log_name]>
    #   name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 300
      every_n_train_steps: !ref <run_opts[val_check_interval]> * 2
      mode: max
      filename: "{step:06d}-{loss:.4f}-{val_loss_0:.4f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.umm.callbacks.log_melspectrogram.LogMaskedMelSpectrogram
      n_examples: 4

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
