---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']
_checkpointing: !ref <run_opts[checkpointing]>

data_params:
    sample_rate: 24000
    duration: 10
    wav2vec_codebook_size: 1024
    mulan_codebook_size: 1024
    soundstream_codebook_size: 1024
    mulan_codebook_shared: False
    wav2vec_frame_rate: 25
    soundstream_frame_rate: 50
    num_coarse: 4
    num_fine: 8
    n_seers: 5

# training parameters
training_params:
    max_steps: 1000000
    batch_size: 8
    learning_rate: 4.0e-4
    warmup_steps: 10000
    cycle_steps: 500000
    weight_decay: 0.01
    shuffle_buffer: 512
    gradient_clip_val: 1.0

ckpt_path: null
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]

# running parameters
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: coarse_seer
    version: playlist
    cache_dir: .module_cache/musiclm
    precision: "16-mixed"
    num_workers: 6
    accelerator: auto
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

karaoke_audio_transforms: !new:recipes.musiclm.transforms.musiclm.MusicLMTransforms
    n_samples: !ref <data_params[duration]> * <data_params[sample_rate]>
    audio_key: "acc.npy"
    sample_range_key: "acc_sample_range.npy"
    min_volume_threshold: 0.0

karaoke_preprocessor: !new:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor
    sample_rate: !ref <data_params[sample_rate]>
    transforms: !ref <karaoke_audio_transforms>

karaoke_train_shards: !new:webdataset.WebDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-{0000..0130}.tar"
    resampled: True
    shardshuffle: True

karaoke_train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <karaoke_train_shards>
    pipeline:
        - !name:webdataset.WebDataset.select
          - !name:samantha.utils.datastructures.select_keys
            keys:
                - "acc.npy"
                - "acc_sample_range.npy"
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <karaoke_preprocessor>
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>
        - !name:webdataset.WebDataset.to_tuple
          - "audio.npy"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[batch_size]>

playlist_audio_transforms: !new:recipes.musiclm.transforms.musiclm.MusicLMTransforms
    n_samples: !ref <data_params[duration]> * <data_params[sample_rate]>
    audio_key: "audio.npy"
    min_volume_threshold: 0.0

playlist_preprocessor: !new:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor
    sample_rate: !ref <data_params[sample_rate]>
    transforms: !ref <playlist_audio_transforms>

playlist_train_shards: !new:webdataset.WebDataset
    urls: "pipe:hdfs dfs -cat /home/byte_speech_sv/mulan/playlist_v5_uio/audio_shards/shards_{0000..2597}.tar"
    resampled: True
    shardshuffle: True

playlist_train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <playlist_train_shards>
    pipeline:
        - !name:webdataset.WebDataset.select
          - !name:samantha.utils.datastructures.select_keys
            keys:
                - "audio.npy"
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <playlist_preprocessor>
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>
        - !name:webdataset.WebDataset.to_tuple
          - "audio.npy"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[batch_size]>

combined_train_dataset: !new:recipes.musiclm.datamodules.webdataset.RandomSample
    datasets:
        - !ref <karaoke_train_dataset>
        - !ref <playlist_train_dataset>
    probabilities:
        - 0.02
        - 0.98

train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <combined_train_dataset>
    pipeline:
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>

validation_web_dataset: !new:webdataset.WebDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-0131.tar"
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self


validation_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <validation_web_dataset>
    pipeline:
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <karaoke_preprocessor>
        - !name:webdataset.WebDataset.to_tuple
          - "audio.npy"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[batch_size]>

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.WebDataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <training_params[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

model_config: !new:samantha.models.SeerConfig
    vocab_size: !ref <data_params[n_seers]> + 1 + <data_params[mulan_codebook_size]> * 12 + <data_params[wav2vec_codebook_size]> + <data_params[soundstream_codebook_size]> * <data_params[num_coarse]>
    n_embd: 1024
    n_layer: 24
    n_head: 16
    n_seers: !ref <data_params[n_seers]>
    n_priors: !ref <data_params[duration]> * <data_params[wav2vec_frame_rate]> + 1 + 12
    seq_len: !ref <data_params[duration]> * <data_params[soundstream_frame_rate]> * <data_params[num_coarse]>
    logit_num: !ref <data_params[soundstream_codebook_size]> * <data_params[num_coarse]>

model_cls: !name:samantha.models.Seer
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <training_params[learning_rate]>
    warmup_steps: !ref <training_params[warmup_steps]>
    cycle_steps: !ref <training_params[cycle_steps]>
    min_lr: !ref <training_params[learning_rate]> * 0.1

pl_module: !new:recipes.musiclm.lightning.modules.SeerCoarseModule
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <data_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/g4/checkpoints/mulan-step=044800-median_rank_1=170-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/mulan/kmeans_minibatch_codebook-mulan1b_g4_170-1024x12.npy
            - !name:recipes.musiclm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <run_opts[cache_dir]>
        wav2vec:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/semantic.jit.pt
            - !name:recipes.musiclm.requires.model_initializer.init_wav2vec
              cache_dir: !ref <run_opts[cache_dir]>
        semantic_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/centroids_epoch_10.npy
            - !name:recipes.musiclm.requires.model_initializer.init_semantic_centers
              cache_dir: !ref <run_opts[cache_dir]>
        soundstream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream
              cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 50
    max_steps: !ref <training_params[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    val_check_interval: 3000
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
