---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: 4
    soundstream_codebook_size: 1024
    soundstream_frame_rate: 50
    num_coarse: 4
    num_fine: 8

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: fine_flash_llama
    version: mcc40m
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 6
    accelerator: auto
    max_steps: 2000000
    batch_size: 16
    learning_rate: 4.0e-4
    warmup_steps: 10000
    cycle_steps: 500000
    weight_decay: 0.01
    sub_shuffle_buffer: 100
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.1
    shuffle_buffer: 600
    gradient_clip_val: 1.0

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

mcc_a_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/a.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc_b_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/b.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc_c_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/c.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc_d_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/d.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc_e_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/e.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

mcc_f_train_dataset: !new:recipes.musiclm.datasets.mcc.MCC40MDataset
    url2index: "/mnt/bn/audio-diffusion/data/genre_balanced_mcc/f.tsv"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[sub_shuffle_buffer]>
    audio_key: "mp3"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    loudness_ratio_threshold: !ref <run_opts[loudness_ratio_threshold]>
    resampled: True
    shardshuffle: True

combined_train_dataset: !new:recipes.musiclm.datamodules.webdataset.RandomSample
    datasets:
        - !ref <mcc_a_train_dataset>
        - !ref <mcc_b_train_dataset>
        - !ref <mcc_c_train_dataset>
        - !ref <mcc_d_train_dataset>
        - !ref <mcc_e_train_dataset>
        - !ref <mcc_f_train_dataset>
    probabilities: [1, 1, 1, 1, 1, 1]

train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <combined_train_dataset>
    pipeline:
        - !name:webdataset.WebDataset.shuffle
          - !ref <run_opts[shuffle_buffer]>

validation_dataset: !new:recipes.musiclm.datasets.karaoke.KaraokeDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-0131.tar"
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    audio_key: "acc.npy"
    sample_range_key: "acc_sample_range.npy"
    min_volume_threshold: !ref <run_opts[min_volume_threshold]>
    is_train: False

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.WebDataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

model_config: !new:transformers.LlamaConfig
    vocab_size: !ref <extra_params[num_coarse]> * <extra_params[soundstream_codebook_size]> + <extra_params[num_fine]> * <extra_params[soundstream_codebook_size]> + 1
    hidden_size: 1024
    intermediate_size: 2752
    num_hidden_layers: 24
    num_attention_heads: 16
    hidden_act: "silu"
    max_position_embeddings: !ref <extra_params[num_coarse]> * <extra_params[soundstream_frame_rate]> * <extra_params[duration]> + <extra_params[num_fine]> * <extra_params[soundstream_frame_rate]> * <extra_params[duration]>
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[num_fine]> * <extra_params[soundstream_codebook_size]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.musiclm.lightning.modules.FineModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        soundstream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream
              cache_dir: !ref <run_opts[cache_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      save_last: True
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: 3000
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
