---

run_opts:
    precision: 32
    strategy: ddp
    ckpt_path: ""
    output_dir: output_wavs
    meta_lst: ""
    num_workers: 1
    seed: 1996
    infer_type: diffusion-vocoder
    use_wvae_vocoder: True
    lang: en
    # v3.5/3.6
    # diffusion_ckpt_path: !applyref:os.getenv ["diffusion_ckpt_path", "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/unified_diffusion/unified_diffusion/ds2441_32xH800_25hzUMM_49hzSS_streaming_chunk392_0522/checkpoints/epoch=00-step=880000-loss=0.66.ckpt"]
    # token_chunk_size: !apply:samantha.utils.envs.getenv_int ["diffusion_token_chunk_size", 200]
    # v4 
    # ConformerUMM_baseline
    # diffusion_ckpt_path: !applyref:os.getenv ["diffusion_ckpt_path", "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/unified_diffusion/unified_diffusion/ds2869_32xH800_25hzUMM_49hzSS_streaming_chunk392_196_0617/checkpoints/epoch=00-step=1130000-loss=0.68.ckpt"]
    # ConformerUMM_2250_2375
    diffusion_ckpt_path: !applyref:os.getenv ["diffusion_ckpt", "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/unified_diffusion/unified_diffusion/ds3416_32xH800_25hzUMM_49hzSS_streaming_chunk392_196_0702/checkpoints/epoch=00-step=1250000-loss=0.68.ckpt"]
    token_chunk_size: !apply:samantha.utils.envs.getenv_int ["diffusion_token_chunk_size", 200]
    token_chunk_overlap: 20
    vocoder_version: !applyref:os.getenv ["vocoder_version", "44.1k_vocal"]
    tokenizer_version: !applyref:os.getenv ["tokenizer_version", "ConformerUMM_2250_2375"]
    sampler: !applyref:os.getenv ["diffusion_sampler", "ddim"]
    batch_size: 1
    without_prefix: !applyref:samantha.utils.envs.getenv_bool ["without_prefix", True]
    concat_context: !applyref:samantha.utils.envs.getenv_bool ["concat_context", True]
    context_duration: 60
    diffusion_drop_rvq_token: -1

seed: !ref <run_opts[seed]>
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# predict_dataset: !new:apps.bigtts.umm.diffusion.datasets.meta_based_dataset.MetaBasedUnit2WavDataset
predict_dataset: !new:recipes.voicebox.datasets.meta_based_dataset.MetaBasedUnit2WavDataset
    meta_lst: !ref <run_opts[meta_lst]>
    lang: !ref <run_opts[lang]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: !ref <run_opts[batch_size]>
    drop_last: False
    collate_fn: !apply:eval ['lambda x: x'] 
    
pl_datamodule: !new:recipes.text2semantic.lit_modules.lit_data.DataModule
    predict_dataloader: !ref <dataloader>

bn_config: !applyref:operator.getitem
    - !include:vocoder_config.yaml
    - !ref <run_opts[vocoder_version]>

tokenizer_config: !applyref:operator.getitem
    - !include:tokenizer_config.yaml
    - !ref <run_opts[tokenizer_version]>

sampler_config: !applyref:operator.getitem
    - !include:sampler_config.yaml
    - !ref <run_opts[sampler]>

mel_config:
    n_fft: 4096
    num_mels: 100
    hop_size: 600
    win_size: 2400
    fmin: 0
    fmax: 12000
    sampling_rate: !ref <bn_config[sample_rate]>
    mel_norm_mean: -4
    mel_norm_std: 7.5
    mel_mask_value: -5

metrics_callbacks:
    - !new:recipes.bigmusic.callbacks.audio_metrics.AudioMetricsCallback
    - !new:recipes.bigmusic.callbacks.fad_mulan_metrics.FADMulanDistanceCallback
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsSAOnlineCallback
      asr_model_path: zh-CN
      transliteration: True
      no_gt_lyrics: True 
    - !new:recipes.bigmusic.callbacks.sdr_metrics.SISDRCallback
    - !new:recipes.sacodec.utils.fix_wer_callback.FixWERCallback
    - !new:recipes.bigmusic.callbacks.audio_metrics.AudioLoundessDiffCallback

diffusion_metrics_callbacks:
    - !new:recipes.bigmusic.callbacks.diffusion_metrics.LatentMeanStdCallback

upload_callbacks:
    - !new:recipes.bigmusic.callbacks.common_callbacks.UploadToEasyCycleCallback

pl_module: !new:apps.bigmusic.umm.diffusion.lit_modules.lit_diffusion_reconstruct_sacodec.ChunkInfer2
    diffusion_ckpt_path: !ref <run_opts[diffusion_ckpt_path]>
    umm_ckpt_path: !ref <tokenizer_config[ckpt_path]>
    vocoder_ckpt_path: ""
    output_dir: !ref <run_opts[output_dir]>
    infer_type: !ref <run_opts[infer_type]>
    umm_frame_rate: !ref <tokenizer_config[frame_rate]>
    mel_frame_rate: !ref <bn_config[frame_rate]>
    mel_config: !ref <mel_config>
    seed: !ref <run_opts[seed]>
    diffusion_precision: "bf16"
    diffusion_nfe: !ref <sampler_config[nfe]>
    diffusion_sampler: !ref <run_opts[sampler]>
    text_cfg_w: !ref <sampler_config[text_cfg_w]>
    rescale_factor: !ref <sampler_config[rescale_factor]>
    use_wvae_vocoder: !ref <run_opts[use_wvae_vocoder]>
    bn_config: !ref <bn_config>
    token_config: !ref <tokenizer_config>
    umm_type: !ref <tokenizer_config[umm_type]>
    without_prefix: !ref <run_opts[without_prefix]>
    concat_context: !ref <run_opts[concat_context]>
    context_duration: !ref <run_opts[context_duration]>
    token_chunk_size: !ref <run_opts[token_chunk_size]>
    token_chunk_overlap: !ref <run_opts[token_chunk_overlap]>
    padding_mode: "token_padding"
    save_prompt: True
    save_diffusion_output: True
    vocoder_chunk_infer: False # switch to True for lower memory usage, lower quality
    mem_efficient: !applyref:samantha.utils.envs.getenv_bool ['mem_efficient', True]
    extra_params: !ref <run_opts>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
    callbacks: !apply:sum [[!ref <metrics_callbacks>, !ref <upload_callbacks>, !ref <diffusion_metrics_callbacks>], []]

