ddim:
  nfe: !apply:samantha.utils.envs.getenv_int ["diffusion_nfe", 10]
  text_cfg_w: !apply:samantha.utils.envs.getenv_float ["diffusion_cfg", 2]

consistency:
  nfe: !apply:samantha.utils.envs.getenv_int ["diffusion_nfe", 4]
  text_cfg_w: !apply:samantha.utils.envs.getenv_float ["diffusion_cfg", 1]
