ddim:
  nfe: !apply:samantha.utils.envs.getenv_int ["diffusion_nfe", 10]
  text_cfg_w: !apply:samantha.utils.envs.getenv_float ["diffusion_cfg", 1.6]
  rescale_factor: !apply:samantha.utils.envs.getenv_float ["diffusion_rescale_factor", 0]
  audio_norm_type: !applyref:os.getenv ["audio_norm_type", "clip"]

ddim_nfe15:
  nfe: !apply:samantha.utils.envs.getenv_int ["diffusion_nfe", 15]
  text_cfg_w: !apply:samantha.utils.envs.getenv_float ["diffusion_cfg", 1.6]
  rescale_factor: !apply:samantha.utils.envs.getenv_float ["diffusion_rescale_factor", 0]
  audio_norm_type: !applyref:os.getenv ["audio_norm_type", "clip"]

consistency:
  nfe: !apply:samantha.utils.envs.getenv_int ["diffusion_nfe", 4]
  text_cfg_w: !apply:samantha.utils.envs.getenv_float ["diffusion_cfg", 1]
  rescale_factor: !apply:samantha.utils.envs.getenv_float ["diffusion_rescale_factor", 0.7]
  audio_norm_type: !applyref:os.getenv ["audio_norm_type", "clip"]
