cache_dir: ".module_cache/vocoder"

44.1k_vocal:
  hop_size: 900
  frame_rate: 49
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 0.1964]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0.0004]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 128
  wav_norm: False
  sample_rate: 44100
  mini_bs: !apply:samantha.utils.envs.getenv_int ["vocoder_mini_bs", 4]
  chunk_size: !apply:samantha.utils.envs.getenv_int ["vocoder_chunk_size", 4]
  major_version: v1
  vocoder_model: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
    checkpoint_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/44.1k_stereo_zh_latent=128_hz=49_kl=1e-6_dataid_2196/checkpoints/last-EMA.ckpt
    version: 44.1k_vocal
    adapt_hopper: True
    cache_dir: !ref <cache_dir>/44.1k_vocal
    sample_rate: 44100


44.1k_sa:
  hop_size: 900
  frame_rate: 49
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 1]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 64
  wav_norm: False
  sample_rate: 44100
  major_version: v1
  vocoder_model: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
    checkpoint_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/44.1k_stereo_zh_latent=64_hz=49_kl=1e-6_v2_freq=2_finetune/checkpoints/last-EMA.ckpt
    version: 44.1k_sa
    adapt_hopper: True
    cache_dir: !ref <cache_dir>/44.1k_sa
    sample_rate: 44100


24k_125hz_dim32_baseline:
  hop_size: 192
  frame_rate: 125
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 1]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 32
  wav_norm: False
  sample_rate: 24000
  major_version: v1
  vocoder_model: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
    checkpoint_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/soundstream-step=374999-val_sdr=12.9557.ckpt
    version: 24k_125hz_dim32_baseline
    adapt_hopper: True
    cache_dir: !ref <cache_dir>/24k_125hz_dim32_baseline
    sample_rate: 24000


32k:
  hop_size: 800
  frame_rate: 40
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 1]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 128
  wav_norm: False
  sample_rate: 32000
  major_version: v1
  vocoder_model: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
      checkpoint_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/32k_stereo_latent=128_hz=40_kl=1e-5_dataid_2196/checkpoints/soundstream-step=870000-val_sdr=11.9673-EMA.ckpt
      version: "32k"
      adapt_hopper: True
      cache_dir: !ref <cache_dir>/32k
      sample_rate: 32000

### Vocoder V2 (SACodec)
vocoder_v2_422:
  # hop_size: 900
  frame_rate: 50
  bn_norm_std: 1
  bn_norm_mean: 0
  bn_padding: -5
  bn_dim: 128
  wav_norm: False
  sample_rate: 44100
  major_version: v2
  vocoder_model: !name:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.init_sacodec
    checkpoint_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/andrew.shaw/sacodec_v5/sacodec_0408_44k_50h_128d_h1536_data8424/checkpoints/sacodec_checkpoint_epoch=0_step=400000_val_loss=1.1710.ckpt
    version: umm
    cache_dir: !ref <cache_dir>/sacodec

sacodec_umm_env:
  # hop_size: 900
  frame_rate: !apply:samantha.utils.envs.getenv_int ["bn_frame_rate", 50]
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 1]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 128
  wav_norm: False
  sample_rate: 44100
  precision: fp32
  # mini_bs: !apply:samantha.utils.envs.getenv_int ["vocoder_mini_bs", 4]
  # chunk_size: !apply:samantha.utils.envs.getenv_int ["vocoder_chunk_size", 4]
  vocoder_model: !name:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.init_sacodec
    checkpoint_path: !applyref:os.getenv ["vocoder_ckpt_path", ""]
    version: umm
    cache_dir: !ref <cache_dir>/sacodec

sacodec_umm_env_fp16:
  # hop_size: 900
  frame_rate: !apply:samantha.utils.envs.getenv_int ["bn_frame_rate", 50]
  bn_norm_std: !apply:samantha.utils.envs.getenv_float ["bn_norm_std", 1]
  bn_norm_mean: !apply:samantha.utils.envs.getenv_float ["bn_norm_mean", 0]
  bn_chunk_size: !apply:samantha.utils.envs.getenv_int ["bn_chunk_size", 100]
  bn_bothside_overlap_size: !apply:samantha.utils.envs.getenv_int ["bn_bothside_overlap_size", 8]
  bn_padding: -5
  bn_dim: 128
  wav_norm: False
  sample_rate: 44100
  major_version: v2
  precision: fp16
  # mini_bs: !apply:samantha.utils.envs.getenv_int ["vocoder_mini_bs", 4]
  # chunk_size: !apply:samantha.utils.envs.getenv_int ["vocoder_chunk_size", 4]
  vocoder_model: !name:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.init_sacodec
    checkpoint_path: !applyref:os.getenv ["vocoder_ckpt_path", ""]
    version: umm
    cache_dir: !ref <cache_dir>/sacodec
