---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: 10
    semantic_codebook_size: 65_536
    semantic_frame_rate: 50
    soundstream_codebook_size: 1024
    soundstream_frame_rate: 50
    hidden_size: 1536
    num_coarse: 4
    semantic_type: bestrq_mkii

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: coarse_flash_llama_wav2vec
    version: coarse_v0
    cache_dir: .module_cache/bestrq_mkii
    precision: "bf16-mixed"
    num_workers: 12
    accelerator: auto
    max_steps: 2000000
    batch_size: 6
    learning_rate: 3.0e-4
    warmup_steps: 10000
    cycle_steps: 500000
    weight_decay: 0.01
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    shuffle_buffer: 20
    gradient_clip_val: 1.0

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# pl_datamodule: !apply:recipes.bigmusic.datasets.lyrics.LyricsDataModule.wav_dataset
#     batch_size: !ref <run_opts[batch_size]>
#     sample_rate: !ref <extra_params[sample_rate]>
#     sample_duration: !ref <extra_params[duration]>
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     num_workers: !ref <run_opts[num_workers]>

pl_datamodule: !apply:recipes.bigmusic.datasets.lyrics.LyricsDataModule.from_dataset_type
    batch_size: !ref <run_opts[batch_size]>
    sample_rate: !ref <extra_params[sample_rate]>
    sample_duration: !ref <extra_params[duration]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    dataset_type: wav_only
    music_types: mixture

model_config: !new:transformers.LlamaConfig
    vocab_size: 1
    hidden_size: !ref <extra_params[hidden_size]>
    intermediate_size: 4128
    num_hidden_layers: 24
    num_attention_heads: 12
    hidden_act: "silu"
    max_position_embeddings: 4096
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[soundstream_codebook_size]> * <extra_params[num_coarse]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.acoustic_modules.CoarseModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        soundstream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream
              cache_dir: !ref <run_opts[cache_dir]>
        mkii:
            hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/logs/umm/stage4_mkii_vq32768x16_vq32768x16/checkpoints/step=0020000.ckpt
            initializer: !name:recipes.umm.requires.model_initializer.init_mkii
                cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      save_last: True
      monitor: tr_loss
      mode: min
      filename: "{step:06d}-{tr_loss:.4f}"
    # - !new:pytorch_lightning.callbacks.LearningRateMonitor
    #   logging_interval: 'step'
    # - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: 5000
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>


# mlx worker launch --type a100-80g -- python3 -m samantha.main fit --config recipes/bigmusic/conf/acoustic_modeling/fine_flash_llama_karaoke_and_playlist.yaml --ckpt_path /mnt/bn/audio-diffusion/ckpts/musiclm/fine_flash_llama/karaoke_and_playlist/checkpoints/last.ckpt
