---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

hp: !include:../hparams.yaml

seed: 1996
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: semantic
    version: 1.0
    precision: 16
    accelerator: auto
    strategy: ddp_find_unused_parameters_false # deepspeed_stage_2_offload, ddp_find_unused_parameters_false
    cache_dir: .module_cache/bark_8192_mhubert_x300_ss
    profiler: simple
    flash_attn: null
    num_epochs: 100
    batch_size: 48
    num_workers: 8
    learning_rate: 0.0003
    weight_decay: 0.1
    checkpointing: false
    n_step_save: 1000
    hdfs_path: null

llama_config: !new:samantha.models.sparse_llama.ModelArgs
    dim: 1024
    n_layers: 24
    n_heads: 16
    vocab_size: 16194
    out_dim: 16194
    multiple_of: 256
    norm_eps: 0.000001
    max_batch_size: 32
    max_seq_len: 4096
    attn_pdrop: 0.1
    resid_pdrop: 0.1
    sparse: false
    checkpointing: !ref <run_opts[checkpointing]>

train_dataset: !new:recipes.bark.datasets.wds_dataset.WDSDataset
    meta_paths:
        - !ref <run_opts[cache_dir]>/tar_list_podcast150h_cn.txt
    tokenizer_cls: !name:transformers.LlamaTokenizer.from_pretrained
        pretrained_model_name_or_path: !ref <run_opts[cache_dir]>/llama_hf
    min_dur: 3
    max_dur: 30

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    drop_last: True
    pin_memory: True
    collate_fn: !name:recipes.bark.datasets.wds_dataset.collate_fn

# datamodule configuration
pl_datamodule: !new:recipes.bark.lit_modules.DataModule
    train_dataloader: !ref <train_dataloader>

# model configuration
model_cls: !name:samantha.models.sparse_llama.LLaMa
    params: !ref <llama_config>

# training module configuration
#optimizer_cls: !name:torch.optim.AdamW
optimizer_cls: !name:deepspeed.ops.adam.FusedAdam # FusedAdam, DeepSpeedCPUAdam
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.95]
    eps: 0.00000001

_steps_per_epoch: !apply:operator.length_hint [!ref <train_dataloader>]
_world_size: !apply:recipes.bark.utils.env.getenv_int ["WORLD_SIZE", 1]
scheduler_cls: !name:recipes.bark.lr_schedulers.musiclm_lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: 2000
    cycle_steps: 400000
    min_lr: !ref <run_opts[learning_rate]> * 0.1

# lightning model setting
pl_module: !new:recipes.bark.lit_modules.v1.semantic.SemanticModule
    model_cls: !name:samantha.models.ctiga_llama.create_ctiga_llama
        - !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.bark.modules.MaskedCrossEntropy
    tokenizer_len: 8000
    n_semantic: 8192
    checkpointing: <run_opts[checkpointing]>
    extra_params: !ref <hp>
    required_modules:
        sound_stream:
            - hdfs://haruna/home/byte_speech_sv/user/congjian/2023-01-17_causal_x300_1024_6book_doubleG_export
            - !name:recipes.bark.requires.model_initializer.init_sound_stream
              cache_dir: !ref <run_opts[cache_dir]>
        mhubert:
            - hdfs://haruna/home/byte_speech_sv/user/litang/bark/2023-05-09_muhubert2.0
            - !name:recipes.bark.requires.model_initializer.init_mhubert
              cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.TensorBoardLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      every_n_train_steps: !ref <run_opts[n_step_save]>
      mode: max
      save_last: True
      save_top_k: 20
      save_on_train_epoch_end: True
      verbose: True
      monitor: accu
      filename: "{epoch:02d}-{step}-{accu:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:samantha.callbacks.hdfs_callback.HdfsSavingCallback
      hdfs_path: !ref <run_opts[hdfs_path]>
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      n_log: !ref <run_opts[n_step_save]>
      async_upload: true
    - !new:samantha.callbacks.timer.Timer

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 1
    strategy: !ref <run_opts[strategy]>
    max_epochs: !ref <run_opts[num_epochs]>
    #limit_train_batches: 100 # debug
    precision: !ref <run_opts[precision]>
    profiler: !ref <run_opts[profiler]>
    callbacks: !ref <callbacks>
    gradient_clip_val: 1.0
    benchmark: true
    plugins: !ref <plugins>

ckpt_path: null
