---

strategy: 'deepspeed'
accelerator_kwargs:
    # only used for deepspeed strategy
    ds_config:
        steps_per_print: 50
        train_micro_batch_size_per_gpu: 1
        prescale_gradients: False
        zero_allow_untested_optimizer: True
        bf16:
            enabled: False
        fp16:
            enabled: True
            loss_scale: 0
            loss_scale_window: 500
            hysteresis: 2
            min_loss_scale: 1
            initial_scale_power: 12
        wall_clock_breakdown: False
        zero_optimization:
            stage: 2
            allgather_partitions: True
            reduce_scatter: True
            overlap_comm: True
            contiguous_gradients: True
optimizer_kwargs:
    optimizer:
        type: "deepspeed.ops.adam.FusedAdam"
        params:
            lr: 1e-4
            betas:
                - 0.9
                - 0.999
            eps: 1.0e-06
            weight_decay: 0.01
            bias_correction: True
            adam_w_mode: True
    scheduler:
        type: "cruise.optim.linear_lr_with_warmup"
        interval: "step"
        params:
            warmup_step_rate: 0.2
