---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

# data configuration
data_dir: './data'

# running parameters
log_dir: 'logs'
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: 'cruise_GPT2'
    version: 'deepspeed'
    precision: 16
    num_workers: 4
    accelerator: 'auto'
    strategy: 'deepspeed'
    enable_activation_ckpt: True

seed: 0

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# training parameters
training_params:
    model: 'gpt2_2B'
    num_epochs: 10
    steps_per_epoch: 300
    batch_size: 32
    seq_len: 1024
    learning_rate: 0.001
    provider: "huggingface"
    model_type: "GPT2LMHead"
    steps_per_print: 50

# dataloader configuration
train_dataloader: !new:recipes.cruise_GPT2.modules.cruise_datamodule.RandomDataloader
    n_steps: !ref <training_params[steps_per_epoch]>
    batch_size: !ref <training_params[batch_size]>
    seq_len: !ref <training_params[seq_len]>

# datamodule configuration
pl_datamodule: !new:recipes.cruise_GPT2.modules.cruise_datamodule.GPTDataModule
    train_dataloader: !ref <train_dataloader>

# training module configuration
pl_module: !new:recipes.cruise_GPT2.modules.cruise_module.GPTLitModule
    model_name: !ref <training_params[model]>
    betas: (0.9, 0.95)
    learning_rate: !ref <training_params[learning_rate]>
    checkpoint: !ref <run_opts[enable_activation_ckpt]>
    provider: !ref <training_params[provider]>
    model_type: !ref <training_params[model_type]>

logger: !new:cruise.trainer.logger.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

trainer: !new:cruise.CruiseTrainer
    accelerator: !ref <run_opts[accelerator]>
    deterministic: False
    strategy: !ref <run_opts[strategy]>
    enable_checkpoint: True
    logger: !ref <logger>
    default_root_dir: !ref <run_opts[tensorboard_dir]>/<run_opts[log_name]>/<run_opts[version]>
    log_every_n_steps: !ref <training_params[steps_per_print]>
    val_check_interval: 0
    gradient_clip_val: 0.1
    max_epochs: !ref <training_params[num_epochs]>
    precision: !ref <run_opts[precision]>
    enable_speedmonitor: True
    seed: !ref <seed>
    enable_profiler: True
    profiler_schedule_kwargs:
        wait: 50
        warmup: 3
        active: 1
        repeat: 1
    accelerator_kwargs:
        ds_config:
            steps_per_print: !ref <training_params[steps_per_print]>
            train_micro_batch_size_per_gpu: !ref <training_params[batch_size]>
            prescale_gradients: False
            zero_allow_untested_optimizer: True
            bf16:
                enabled: False
            fp16:
                enabled: True
                loss_scale: 0
                loss_scale_window: 500
                hysteresis: 2
                min_loss_scale: 1
                initial_scale_power: 12
            wall_clock_breakdown: False
            zero_optimization:
                stage: 1
                allgather_partitions: True
                reduce_scatter: True
                overlap_comm: True
                contiguous_gradients: True
