---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    lyrics_codebook_size: 2000
    speaker_codebook_size: 100
    semantic_codebook_size: 32_768
    semantic_frame_rate: 25
    semantic_type: bestrq
    train_conditions: "style_category,speaker_id,lyrics_tokens"
    prepare_input_types: []
    input_embedders: [tag_categorical, speaker_id, lyrics_tokens]
    tag_taxonomy_lang: 'SA'  # Zh, SA
    tag_dropout_rate: 0.05
    line_break_dropout_rate: 0
    section_tag_dropout_rate: 0
    use_mcc_gender: False
    # LM params
    # mulan_embed_dim: 512
    hidden_size: 1536
    intermediate_size: 4352
    num_hidden_layers: 24
    num_attention_heads: 12
    pretrained_path: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/decoder_07B_zh30s_lowrisk_sa_cat/pretrain_0303_dropout/checkpoints/step=099000-tr_loss=5.2378-val_accu_0=12.58.ckpt"
    tokenizer_path: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"
    # Inference params
    duration: 30
    semantic_temperature: 1.0
    sample_mode: "top_p"
    beam_size: 2
    decoder_type: "diffusion"
    diffusion_steps: 10
    bf16_portion: 0.0
    # RL training params
    add_ref_to_beam: False
    ce_weight: 0.1
    seq_weight: 10
    positive_phrase: "cd quality, catchy, memorable"
    negative_phrase: "noisy, boring, forgettable"
    use_chord_eos: False
    rewards:
        "wer": 1.0
        "mulan_sim": 1.0
        "loudness_sim": 1.0
        # "qualitative_sim": 1.0
    # Logging params
    log_num_val_samples: 10
    log_num_val_beam_samples: 1

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: logs
    hdfs_log_dir: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/yilinzhang/logs"
    log_name: decoder_07B_zh30s_rl
    version: v0
    cache_dir: .module_cache/bigmusic
    precision: "16"
    num_workers: 4
    accelerator: auto
    max_steps: 5000
    val_check_interval: 250
    batch_size: 5
    learning_rate: 5.0e-7
    warmup_steps: 100
    cycle_steps: 5000
    weight_decay: 0.1
    shuffle_buffer: 16
    gradient_clip_val: 1.0
    # Supporting models
    mulan_ckpt: "hdfs:///home/byte_speech_sv/jingsong.gao/mulan_ckpt/mulan-step=024600-median_rank_1=110-kaggle.ckpt"
    bestrq_ckpt: !ref <extra_params[tokenizer_path]>
    diffusion_ckpt: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_16/checkpoints/last.ckpt"
    vocoder_ckpt: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/vocoder/soundstream-step=374999-val_sdr=12.9557.ckpt"
    is_zh_token: True           # Set to True only if lyrics_lang is zh_phone or zh_wp. Diffusion model from recipes.diffusion.models.tnt_gru
    mixv2: False                # Set to True for mix UMM token
    # Dataloader
    buckets_in_sec: [22, 24, 26, 28, 30]
    use_dynamic_batch: False
    max_seg_per_track: 3
    segment_method: "random"
    infer_structure_tags: False
    read_structure_tags: True
    region: "CN"
    lyrics_field: "lyrics"
    lyrics_confidence: 0.75  # SA ASR confidence
    lyrics_tokenizer: "tts_chinese_frontend_model"
    segment_max_phone_len: 400
    parquet_dataset_ids: [1932]  # everynoise : artist = 1 : 1, 10k tracks in total
    parquet_dataset_weights: [1]
    sinking_threshold: 0.51
    quality_filter: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.mix.MixVocalWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_in_sec: !ref <run_opts[buckets_in_sec]>
    use_dynamic_batch: !ref <run_opts[use_dynamic_batch]>
    max_seg_per_track: !ref <run_opts[max_seg_per_track]>
    tokenizer: !ref <run_opts[lyrics_tokenizer]>
    segment_max_phone_len: !ref <run_opts[segment_max_phone_len]>
    region: !ref <run_opts[region]>
    conditions: !ref <extra_params[train_conditions]>
    lyrics_field: !ref <run_opts[lyrics_field]>
    lyrics_confidence: !ref <run_opts[lyrics_confidence]>
    read_structure_tags: !ref <run_opts[read_structure_tags]>
    infer_structure_tags: !ref <run_opts[infer_structure_tags]>
    segment_method: !ref <run_opts[segment_method]>
    parquet_dataset_ids: !ref <run_opts[parquet_dataset_ids]>
    parquet_dataset_weights: !ref <run_opts[parquet_dataset_weights]>
    sinking_threshold: !ref <run_opts[sinking_threshold]>
    quality_filter: !ref <run_opts[quality_filter]>
    frame_rate: !ref <extra_params[semantic_frame_rate]>
    tag_taxonomy_lang: !ref <extra_params[tag_taxonomy_lang]>
    line_break_dropout_rate: !ref <extra_params[line_break_dropout_rate]>
    section_tag_dropout_rate: !ref <extra_params[section_tag_dropout_rate]>
    normalize_audio: True

model_config: !new:transformers.GPT2Config
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    max_position_embeddings: 0
    use_cache: False
    n_positions: 0  # No absolute position embedding
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS
    n_embd: !ref <extra_params[hidden_size]>
    n_layer: !ref <extra_params[num_hidden_layers]>
    n_head: !ref <extra_params[num_attention_heads]>
    n_inner: !ref <extra_params[intermediate_size]>
    use_rms_norm: True
    activation_function: "swiglu"
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.0
    layer_norm_epsilon: 1e-6
    initializer_range: 0.02
    rescale_prenorm_residual: False
    rms_norm: True
    rotary_emb_fraction: 1.0
    rotary_emb_interleaved: True
    rotary_emb_compat: "default" #"byteformer"
    tie_word_embeddings: False
    qkv_proj_bias: False
    out_proj_bias: False
    mlp_fc1_bias: False
    mlp_fc2_bias: False
    use_flash_attn: True
    fused_bias_fc: True
    fused_mlp: False
    fused_dropout_add_ln: True
    residual_in_fp32: True

model_cls: !name:samantha.models.ctiga.gpt.GPTLMHeadModel
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.SemanticRLModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    extra_params: !ref <extra_params>
    required_modules:
        bestrq:
            hpath: !ref <run_opts[bestrq_ckpt]>
            initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                cache_dir: !ref <run_opts[cache_dir]>
        mulan:
            hpath: !ref <run_opts[mulan_ckpt]>
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "g4"
        sampler:
            hpath: null
            initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                cache_dir: !ref <run_opts[cache_dir]>
                duration: !ref <extra_params[duration]>
        diffusion:
            hpath: !ref <run_opts[diffusion_ckpt]>
            initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                cache_dir: !ref <run_opts[cache_dir]>
                is_zh_token: !ref <run_opts[is_zh_token]>
                mixv2: !ref <run_opts[mixv2]>
        vocoder:
            hpath: !ref <run_opts[vocoder_ckpt]>
            initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                cache_dir: !ref <run_opts[cache_dir]>
        asr:
            hpath: zh   # en_punc
            initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback


callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 10
      save_last: True
      monitor: step
      mode: max
      filename: "{step:06d}"
      every_n_train_steps: !ref <run_opts[val_check_interval]>
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 20
      save_last: False
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}-{tr_loss:.4f}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 50
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    limit_val_batches: 10
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
