.auto-wrapper: &auto-wrapper
  only:
    - develop
    - master

.manual-wrapper: &manual-wrapper
  when: manual
  except:
    - develop
    - master

.aed-test: &aed-test
  stage: train_func_test
  when: manual # remove this when error in AED fixed
  script:
    - echo "begin aed model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/aed/*.py | sort --random-sort | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 1000 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs



.asr-test: &asr-test
  stage: train_func_test
  script:
    - echo "begin asr model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/asr/ -name "*.py" -and ! -name "tele_genral_transformer_200kh_1B*" | sort --random-sort | grep -v 'input10k_tog_' | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 500 --train.max_iters 200 --data.global_shuffle 0
    - sleep 5
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - git clean -dxf
    - free -h
    - model=$(find ./configs/asr/ -name "*.py" -and ! -name "tele_genral_transformer_200kh_1B*" | sort --random-sort | grep -v 'input10k_tog_' | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 500 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs


.kws-test: &kws-test
  stage: train_func_test
  script:
    - echo "begin kws model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/kws/*.py | sort --random-sort | head -n 1)
    - python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 1000 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs


.lm-test: &lm-test
  stage: train_func_test
  script:
    - echo "begin lm model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/lm/*.py | sort --random-sort | grep -v 'calc_ppl' | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 1000 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs


.mdd-test: &mdd-test
  stage: train_func_test
  when: manual # remove this when HDFS error in MDD fixed
  script:
    - echo "begin mdd model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/mdd/*.py | sort --random-sort | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 1000 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs


.sid-test: &sid-test
  stage: train_func_test
  when: manual # TODO(zhengyijie): remove this when HDFS error in SID fixed
  script:
    - echo "begin sid model test"
    - pwd
    - git log --oneline -n 3
    - export CUDA_VISIBLE_DEVICES=6,7
    - export DOLPHIN_DISTRIBUTED_FRAMEWORK=torch
    - ps x -o pid,ppid,tty,stat,rss,rsz,time,command
    - free -h
    - model=$(find ./configs/sid/*.py | sort --random-sort | head -n 1)
    - mpirun --allow-run-as-root -np 2 python3 -u train.py --config ${model} --data.max_batch_scale 0 --data.max_batch_size 1000 --train.max_iters 200 --data.global_shuffle 0
  tags:
    - gpu
  artifacts:
    expire_in: 2 hrs

auto-aed-test:
  <<: *auto-wrapper
  <<: *aed-test

manual-aed-test:
  <<: *manual-wrapper
  <<: *aed-test

auto-asr-test:
  <<: *auto-wrapper
  <<: *asr-test

manual-asr-test:
  <<: *manual-wrapper
  <<: *asr-test

auto-kws-test:
  <<: *auto-wrapper
  <<: *kws-test

manual-kws-test:
  <<: *manual-wrapper
  <<: *kws-test

auto-lm-test:
  <<: *auto-wrapper
  <<: *lm-test

manual-lm-test:
  <<: *manual-wrapper
  <<: *lm-test

auto-mdd-test:
  <<: *auto-wrapper
  <<: *mdd-test

manual-mdd-test:
  <<: *manual-wrapper
  <<: *mdd-test

auto-sid-test:
  <<: *auto-wrapper
  <<: *sid-test

manual-sid-test:
  <<: *manual-wrapper
  <<: *sid-test
