---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    beam_size: 8    # set to 1 if not using reranker
    samples_to_save: 1
    save_style_audio: True
    save_mp3: False
    save_semantic_tokens: False
    prompt_path: "/mnt/bn/audio-diffusion/ducle/data/prompts/bgm_eval/prompts_style_audio.test.csv"
    inference_conditions: "style_audio,duration,intensity"
    max_items: null
    use_reranker: True

    output_dir: sstk_out

    # Semantic model
    semantic_cls_path: apps.bigmusic.umm.ar.lightning.semantic_modules.SemanticModule
    semantic_ckpt: "/mnt/bn/audio-diffusion/ducle/logs/semantic_model_instrumental_07B/sstk_vad-unnorm_intensity-control-2dec-mean_sstk-random_sstk-mulan-mae-v2+sstk-umm-nospeech-400k-30s_largerr_3m/checkpoints/step=328000.ckpt"
    mulan_ckpt: "/mnt/bn/audio-diffusion/weituo/sstk_mulan/mulan-step=005000-median_rank_1=83-kaggle.ckpt"
    mulan_version: "sstkmae"

    # For re-ranking
    rewards:
        style_text: 0.0
        style_audio: 1.0
        qualitative: 1.0
        loudness_sim: 1.0
        audio_metrics: 1.0
    positive_phrase: "high quality, catchy, memorable"
    negative_phrase: "noisy, boring, forgettable"

    # For intensity calculation
    intensity_calculation: "mean"
    intensity_hz: 1
    intensity_temperature: 1.0

    diffusion_version: 'sstk_v2'
    diffusion_params:
        window_length: 30 # in second
        vocoder_hz: 125 # 147 for 44.1k
        semantic_hz: 25
        latent_dim: 32 # 128 for 44.1k
        outpainting_overlap: 0.5 #[0, 1]
        diffusion_steps: 50
        schedule_slope: 4.0
        guidance_scale: 2.5
        bf16_portion: 0.0

    vocoder_version: '24k_to_48k_stereo' # this is only needed when sample_rate=44100 or 48000, for 24k its bypassed

    # Model Settings
    sample_rate: 24000  # 48000
    duration: 30 # 30|45|60|75|90|105|120
    semantic_temperature: 1.0
    sample_mode: "top_p"
    sample_thresh: 0.8
    token2wav_type: "diffusion"
    exclude_eos: True

run_opts:
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/musiclm
    batch_size: 1  # set to 28 if not using reranker

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
predict_dataset: !apply:apps.bigmusic.umm.ar.datasets.inference.inference_dataset_from_prompt
    prompt_path: !ref <extra_params[prompt_path]>
    conditions: !ref <extra_params[inference_conditions]>
    max_items: !ref <extra_params[max_items]>
    batch_size: !ref <run_opts[batch_size]>
    extra_params: !ref <extra_params>

pl_datamodule: !new:apps.bigmusic.umm.ar.datasets.lyrics.LyricsDataModule
    predict_dataset: !ref <predict_dataset>
    num_workers: 0

pl_module: !new:apps.bigmusic.umm.ar.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: /mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt
                initializer: !name:samantha.models.umm.model_initializer.init_stage3
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/24k_v2/diffusion-step=600000-EMA.ckpt
                #hpath: /mnt/bn/audio-diffusion/wtl/diffusion/sstk/44.1k_mono_v1/diffusion-step=470000-EMA.ckpt
                initializer: !name:apps.bigmusic.umm.diffusion_tools.models.diffusion_model.utils.init_diffusion
                    cache_dir: !ref <run_opts[cache_dir]>
                    sstk: True
                    sample_rate: !ref <extra_params[sample_rate]>
                    version: !ref <extra_params[diffusion_version]>
            sampler:
                hpath: null
                initializer: !name:apps.bigmusic.umm.diffusion_tools.models.diffusion_sampler.init_sampler
                    cache_dir: !ref <run_opts[cache_dir]>
                    params: !ref <extra_params[diffusion_params]>
            vocoder:
                hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/24k_v1/soundstream-step=1240000-val_sdr=12.5666-EMA.ckpt
                # hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/24k_v1_to_44.1k_stereo/soundstream-step=1490000-val_sdr=4.9540-EMA.ckpt  # for 24k to 44.1k stereo upsample
                # hpath: /mnt/bn/audio-diffusion/wtl/vocoder/sstk/44.1k_mono_v1/soundstream-step=1410000-val_sdr=16.7701-EMA.ckpt # for 44.1k
                initializer: !name:apps.bigmusic.umm.diffusion_tools.models.vocoder_model.utils.init_vocoder
                    cache_dir: !ref <run_opts[cache_dir]>
                    sample_rate: !ref <extra_params[sample_rate]>
                    adapt_hopper: True
                    version: !ref <extra_params[vocoder_version]>
        reranker:
            hpath:
                rewards: !ref <extra_params[rewards]>
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_ckpt]>
                        initializer: !name:apps.bigmusic.umm.ar.requires.model_initializer.init_mulan
                            version: !ref <extra_params[mulan_version]>
            initializer: !name:apps.bigmusic.umm.ar.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>
                sample_rate: !ref <extra_params[sample_rate]>

callbacks:
    - !new:apps.bigmusic.umm.ar.callbacks.save_outputs.SaveOutputsCallback
      beam_size: !ref <extra_params[beam_size]>
      samples_to_save: !ref <extra_params[samples_to_save]>
      save_style_audio: !ref <extra_params[save_style_audio]>
      save_mp3: !ref <extra_params[save_mp3]>
      save_semantic_tokens: !ref <extra_params[save_semantic_tokens]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    use_distributed_sampler: False # for multi-gpu inference
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    #callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
    callbacks: !ref <callbacks>
