---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null # last

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

# running parameters
run_opts:
    log_dir: "logs"
    log_name: mi-1
    version: v1_billboard_lyricscond # v0_LyricsDataModule_mcc60m_2M_vocal_mixed_text_audio_CondMusicTag
    # hdfs_log_dir: hdfs://haruna/home/byte_data_seed/lf_lq/speech/data/js/logs/
    hdfs_log_dir: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/data/js/logs
    precision: 16-mixed
    num_workers: 8
    accelerator: auto
    max_steps: 200000
    batch_size: 20
    shuffle_buffer: 50
    gradient_clip_val: 1.0
    val_check_interval: 5000
    ckpt_interval: 5000

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

lyric_tokenizer: !new:samantha.transforms.tokenizers.phoneme.LyricPhonemeTokenizer

pl_datamodule: !new:recipes.datasets.billboard.BillboardLyricsDataModule
    sample_rate: !ref <config[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    min_words: 5
    max_words: 400
    min_seconds: 2
    max_seconds: !ref <config[max_seconds]>
    resampled: True
    shardshuffle: True
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    padding_strategy: pad # TODO UMM might expect it differently?
    lyric_tokenizer: !ref <lyric_tokenizer>

# pl_datamodule: !new:recipes.datasets.mel_spectrogram.CombinedMelDataModule
#     sample_rate: !ref <config[sample_rate]>
#     hop_size: 240
#     train_url2index: data/music/converted/converted_all_BillboardLyricsDataModule_SpeechTransform/train/0/url2index.txt
#     validation_url2index: data/music/converted/converted_all_BillboardLyricsDataModule_SpeechTransform/train/0/url2index.txt
#     batch_size: !ref <run_opts[batch_size]>
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     min_seconds: 2
#     max_seconds: 30
#     resampled: True
#     shardshuffle: True
#     num_workers: !ref <run_opts[num_workers]>
#     pin_memory: True

# lyrics_tokenizer: !new:samantha.transforms.tokenizers.phoneme.LyricPhonemeTokenizer

# pl_datamodule: !new:recipes.datasets.preprocessed.mel_spectrogram.CombinedMelDataModule
#     lyrics_tokenizer: !ref <lyrics_tokenizer>
#     sample_rate: !ref <config[sample_rate]>
#     hop_size: 240
#     train_url2index: data/music/converted/converted_all_LyricsDataModule_SpeechTransform/train/0/url2index.txt
#     validation_url2index: data/music/converted/converted_all_LyricsDataModule_SpeechTransform/validation/0/url2index.txt
#     batch_size: !ref <run_opts[batch_size]>
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     min_seconds: 1
#     max_seconds: 30
#     resampled: True
#     shardshuffle: True
#     num_workers: !ref <run_opts[num_workers]>
#     pin_memory: True

# genre balanced: mcc60m_2M_vocal_mixed_text_audio
# andrew: mcc60m_vocalB_style_mixed_text_audio
# pl_datamodule: !apply:recipes.bigmusic.datasets.lyrics.LyricsDataModule.from_dataset_type
#     dataset_types: mcc60m_2M_vocal_mixed_text_audio
#     batch_size: !ref <run_opts[batch_size]>
#     sample_rate: !ref <config[sample_rate]>
#     sample_duration: [15, 20, 25, 30]
#     shuffle_buffer_size: 0 # TODO why?
#     lyrics_max_seq_len: 400
#     num_workers: !ref <run_opts[num_workers]>
#     pin_memory: True
#     resampled: True
#     shardshuffle: True
#     max_num_segments: 10 # default is 10

config: !new:recipes.mi1.models.mi1.MI1Config
    sample_rate: 24000
    max_seconds: 30
    n_layer: 24
    n_head: 12
    n_embd: 1536
    n_inner: 4352
    learning_rate: 3.0e-5
    warmup_steps: 5000
    cycle_steps: 80000
    weight_decay: 0.01
    betas: [0.9, 0.99] # [0.9, 0.98]
    lyric_tokenizer: !ref <lyric_tokenizer>
    top_k_music_tags: 5


pl_module: !new:recipes.mi1.models.mi1.MI1
    config: !ref <config>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
      save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
    # - !new:recipes.mi1.callbacks.demo.AudioDemo

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

# profiler: !new:pytorch_lightning.profilers.PyTorchProfiler
#     schedule: !apply:torch.profiler.schedule
#         wait: 0
#         warmup: 50
#         active: 10
#         repeat: 1
#         skip_first: 100
#     profile_memory: True
#     with_stack: True


trainer: !new:pytorch_lightning.Trainer
    # profiler: !ref <profiler>
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: False
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1 # TODO
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
