---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

report_test: True

ckpt_path: null # last

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

# running parameters
run_opts:
    log_dir: "logs"
    log_name: mi-1_music_tagging
    version: sft_v0_lr1.0e-4_precision32
    hdfs_log_dir: hdfs://haruna/home/byte_data_seed/lf_lq/speech/data/js/logs/
    # hdfs_log_dir: hdfs://haruna/home/byte_data_seed_us/hdd_va/speech/data/js/logs
    precision: 32
    num_workers: 8
    accelerator: auto
    max_steps: 30000
    batch_size: 32
    shuffle_buffer: 200
    gradient_clip_val: 1.0
    val_check_interval: 5000
    ckpt_interval: 5000

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# pl_datamodule: !new:recipes.datasets.mir.tagging.CombinedTaggingDataModule
#     duration: !ref <config[duration]>
#     batch_size: !ref <run_opts[batch_size]>
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     resampled: False
#     shardshuffle: False
#     num_workers: !ref <run_opts[num_workers]>

# pl_datamodule: !new:recipes.datasets.preprocessed.generic.GenericPreprocessedDataModule
#     sample_rate: !ref <config[sample_rate]>
#     train_url2index: data/music/converted/CombinedTaggingDataModule_MI1_MusicTagging/train/url2index.txt
#     validation_url2index: data/music/converted/CombinedTaggingDataModule_MI1_MusicTagging/validation/url2index.txt
#     test_url2index: data/music/converted/CombinedTaggingDataModule_MI1_MusicTagging/test/url2index.txt
#     batch_size: !ref <run_opts[batch_size]>
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     resampled: False
#     shardshuffle: False
#     num_workers: !ref <run_opts[num_workers]>

pl_datamodule: !new:recipes.datasets.mir.music_sft.MusicSFTDataModule
    sample_rate: !ref <config[sample_rate]>
    duration: !ref <config[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    resampled: True
    shardshuffle: True
    num_workers: !ref <run_opts[num_workers]>

config: !new:recipes.mi1.models.tagging.MI1_MusicTaggingConfig
    sample_rate: 24000
    duration: 30
    learning_rate: 1.0e-4

audio_tokenizer: !new:recipes.mi1.models.tokenizers.UMMTokenizer

pl_module: !new:recipes.mi1.models.tagging.MI1_MusicTaggingMusicSFT
    config: !ref <config>
    audio_tokenizer: !ref <audio_tokenizer>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
      save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO


trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: False
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1 # TODO
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
