---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1996
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

num_node: !applyref:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
gpu_per_node: !applyref:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_GPU", 1]
num_gpu: !applyref:operator.mul [!ref <num_node>, !ref <gpu_per_node>]
device_type: !applyref:re.sub ["-SXM.*$", "", !applyref:re.sub ["NVIDIA-", "", !applyref:os.getenv ["ARNOLD_DEVICE_TYPE", "NVIDIA-H800"]]]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    data_id: 8424
    val_data_id: 2124
    resume_ckpt_path:

    batch_size: null
    num_workers: 20
    learning_rate: 0.00005
    weight_decay: 0.001
    checkpointing: False
    n_step_save: 20000
    batch_total_tokens: 22050000 # 44100 * 500 # batch = 500 / 60 ~ 8
    # batch_total_tokens: 26460000 # 44100 * 600 # batch = 10
    accumulate_grad_batches: 1

    use_url_lst: False
    target: bn
    prompt_feature: bn
    ctx_feature: bn
    use_textprefix: False
    use_prompt: False
    use_unet_style_skip_connect: true
    val_output_samples_dir: /mnt/bn/ashaw-lq/logs/latent2wav

    token_audio_freq: 24000
    umm_frame_rate: 25
    bn_hop_size: 900
    bn_audio_freq: 44100
    bn_frame_rate: 50

    window_left: 8
    window_right: 4
    window_type: "blockwise"

    max_audio_length: 60
    min_audio_length: 4

    log_dir: logs
    hdfs_path: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/andrew.shaw/sacodec"
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: unified_diffusion_sacodec
    version: !ref ds<run_opts[data_id]>_<device_type>x<num_gpu>_<run_opts[umm_frame_rate]>hzUMM_<run_opts[bn_frame_rate]>hzSS_streaming_chunk<run_opts[window_left]>x<run_opts[window_right]>_<run_opts[max_audio_length]>s

    log_every_n_steps: 1000
    val_check_interval: 20000
    n_token: 32769
    tokenizer_pad: !applyref:operator.sub # not used
        - !ref <run_opts[n_token]>
        - 1
    tokenizer_version: "ConformerUMM_Unified_TTS_ROPE"
    # token_embed_dim: 512

bn_config: # 40hz
    bn_dim: 128
    hop_size: !ref <run_opts[bn_hop_size]>
    bn_norm_std: 1
    bn_norm_mean: 0
    bn_padding: -5
    pad_trim: False
    silence_bn_path: recipes/voicebox/vocoder/silence_wvae/v3_40hz/silence_wvae.npy

model_config: !new:recipes.voicebox.diffusion_modules.llama_ldm.ModelArgs
    in_channels: !ref <bn_config[bn_dim]>
    out_channels: !ref <bn_config[bn_dim]>
    prompt_mel_dim: !ref <bn_config[bn_dim]>
    # token_embed_dim: !ref <run_opts[token_embed_dim]>
    n_token: !ref <run_opts[n_token]>
    token_upscales: [2]
    token_downscales: []
    # token_upscales: [7,7]
    # token_downscales: [5,5]
    llama_provider: ctiga
    target: !ref <run_opts[target]>
    prompt_feature: !ref <run_opts[prompt_feature]>
    ctx_feature: !ref <run_opts[ctx_feature]>
    local_cond_dim: 256
    time_embed_dim: 256
    encoder_dim: 1536
    encoder_n_layers: 24
    encoder_n_heads: 24
    use_prompt: !ref <run_opts[use_prompt]>
    use_textprefix: !ref <run_opts[use_textprefix]>
    causal: False
    use_window_mask: True
    window_type: !ref <run_opts[window_type]>
    window_size:
        - !apply:max
          - !apply:operator.mul
            - !ref <run_opts[bn_frame_rate]>
            - !ref <run_opts[window_left]>
          - -1
        - !apply:max
          - !apply:operator.mul
            - !ref <run_opts[bn_frame_rate]>
            - !ref <run_opts[window_right]>
          - -1
    local_cond_project_type: linear
    use_unet_style_skip_connect: !ref <run_opts[use_unet_style_skip_connect]>
    rf_sigma_distribution: lognorm
    target_type: rectified-flow

train_dataset: !new:recipes.voicebox.datasets.voicebox_promptmel_dataset_dpo.VoiceBoxParquetDataset
    data_id: !ref <run_opts[data_id]>
    drop_last: False
    batcher_config:
        # buckets: !apply:eval ["list(range(49, 3100, 49))"]
        buckets: !new:list
            - !new:range
              - !applyref:operator.mul
                - !ref <run_opts[min_audio_length]>
                - !ref <run_opts[bn_audio_freq]>
              - !applyref:operator.mul
                - !applyref:operator.add
                  - !ref <run_opts[max_audio_length]>
                  - 10
                - !ref <run_opts[bn_audio_freq]>
              - !applyref:operator.mul
                - 8
                - !ref <run_opts[bn_audio_freq]>
        dynamic_batch: True
        maximum_bucket_size: !ref <run_opts[batch_total_tokens]>
        length_fn: !apply:eval ["lambda x: x[\"win_wav\"].shape[-1]"]  # seq.shape
    bn_config: !ref <bn_config>
    umm_frame_rate: !ref <run_opts[umm_frame_rate]>
    token_audio_freq: !ref <run_opts[token_audio_freq]>
    bn_audio_freq: !ref <run_opts[bn_audio_freq]>
    shuffle_buffer_size: 0
    dataset_cls: "PerferrenceDataset"

val_dataset: !new:recipes.voicebox.datasets.voicebox_promptmel_dataset_otf.VoiceBoxParquetDataset
    data_id: !ref <run_opts[val_data_id]>
    drop_last: False
    batcher_config:
        buckets: !new:list
            - !new:range
              - !applyref:operator.mul
                - 30
                - !ref <run_opts[bn_audio_freq]>
              - !applyref:operator.mul
                - !applyref:operator.add
                  - !ref <run_opts[max_audio_length]>
                  - 10
                - !ref <run_opts[bn_audio_freq]>
              - !applyref:operator.mul
                - 15
                - !ref <run_opts[bn_audio_freq]>
        dynamic_batch: True
        maximum_bucket_size: !ref <run_opts[batch_total_tokens]>
        length_fn: !apply:eval ["lambda x: x[\"wav\"].shape[-1]"]  # seq.shape
    bn_config: !ref <bn_config>
    umm_frame_rate: !ref <run_opts[umm_frame_rate]>
    token_audio_freq: !ref <run_opts[token_audio_freq]>
    bn_audio_freq: !ref <run_opts[bn_audio_freq]>
    shuffle_buffer_size: 0


# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: !ref <run_opts[batch_size]>
    collate_fn: !new:recipes.voicebox.datasets.voicebox_promptmel_dataset_dpo.VoiceBoxCollator
    pin_memory: True

val_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <val_dataset>
    num_workers: 2
    batch_size: !ref <run_opts[batch_size]>
    collate_fn: !new:recipes.voicebox.datasets.voicebox_promptmel_dataset_otf.VoiceBoxCollator
    pin_memory: True

# datamodule configuration
pl_datamodule: !new:recipes.voicebox.lit_modules.DataModule
    train_dataloader: !ref <train_dataloader>
    val_dataloader: !ref <val_dataloader>

model_cls: !name:recipes.voicebox.diffusion_modules.llama_ldm.LlamaDiffusion
    hp: !ref <model_config>

optimizer_cls: !name:deepspeed.ops.adam.FusedAdam
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.95]
    eps: 0.0000001

_steps_per_epoch: !apply:operator.length_hint [!ref <train_dataloader>]
_world_size: !apply:samantha.utils.envs.getenv_int ["WORLD_SIZE", 1]
scheduler_cls: !name:recipes.bark.lr_schedulers.musiclm_lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: 1000
    cycle_steps: 500000
    min_lr: !ref <run_opts[learning_rate]> * 0.1

# lightning model setting
pl_module: !new:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.VoiceBoxModule
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    checkpointing: !ref <run_opts[checkpointing]>
    resume_ckpt_path: !ref <run_opts[resume_ckpt_path]>
    criterions: ["l2_wo_reduction"]
    required_modules:
        vocoder:
            hpath: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/andrew.shaw/sacodec_v5/sacodec_vB_44k_50h_128d_umm_rope_b2_vocal_h1536_ummdimfix_pretrain/checkpoints/sacodec_checkpoint_epoch=0_step=180000_val_loss=1.1525.ckpt
            initializer: !name:recipes.voicebox.lit_modules.lit_diffusion_voicebox_sacodec.init_sacodec
                cache_dir: .module_cache/vocoder/sacodec
                version: umm
        tokenizer: !applyref:operator.getitem
            - !include:tokenizer.yaml
            - !ref <run_opts[tokenizer_version]>
    diffusion_sample_rate: !ref <run_opts[bn_audio_freq]>
    val_output_samples_dir: !ref <run_opts[val_output_samples_dir]>/<run_opts[log_name]>/<run_opts[version]>
    bn_config: !ref <bn_config>
    umm_dropout: 0.1
    umm_pad: !ref <run_opts[tokenizer_pad]> # not used
    dpo_train: False
    dpo_loss_type: 'sigmoid'
    dpo_beta: 1.0
    dpo_condition_sync: True

logger:
    - !new:pytorch_lightning.loggers.TensorBoardLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      hdfs_path: !ref <run_opts[hdfs_path]>/<run_opts[log_name]>/<run_opts[version]>
      every_n_train_steps: !ref <run_opts[n_step_save]>
      mode: min
      save_last: True
      save_top_k: 20
      save_on_train_epoch_end: True
      verbose: True
      monitor: loss
      filename: "{epoch:02d}-{step}-{loss:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:samantha.callbacks.timer.Timer

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: False
    logger: !ref <logger>
    accelerator: 'auto'
    devices: 'auto'
    num_nodes: !ref <num_node>
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    strategy: ddp_find_unused_parameters_false # deepspeed_stage_2_offload, ddp_find_unused_parameters_false
    max_epochs:
    precision: bf16
    profiler: simple
    callbacks: !ref <callbacks>
    gradient_clip_val: 0.2
    benchmark: false
    accumulate_grad_batches: !ref <run_opts[accumulate_grad_batches]>
    plugins: !ref <plugins>
    sync_batchnorm: True
    limit_val_batches: 10
    val_check_interval: !ref <run_opts[val_check_interval]>
    num_sanity_val_steps: 0

ckpt_path: null
