---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']
_checkpointing: False

extra_params:
    sample_rate: 24000
    duration: 10
    semantic_duration: 10
    semantic_stride: 5
    wav2vec_codebook_size: 1024
    wav2vec_frame_rate: 25
    mulan_codebook_size: 1024
    mulan_num_rvq: 12
    ce_weight: 0.1
    seq_weight: 10
    beam_size: 4
    semantic_temperature: 1.0
    diffusion_steps: 25
    sample_mode: "gumbel"
    semantic_type: "wav2vec"
    decoder_type: "diffusion"
    mulan_force_cfg: 1 # 1 = mulan context is not used for diffusion inference. 0 = use mulan context
    rewards:
        "mulan_sim": 1.0
        "energy_std": 1.0
    log_num_val_samples: 25
    log_num_val_beam_samples: 1

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_flash_llama_rlhf
    version: seqtrain_diffusion_text_only
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 8
    accelerator: auto
    val_check_interval: 250
    max_steps: 1000000
    batch_size: 12
    learning_rate: 6.0e-6  # Adjust according to batch size
    warmup_steps: 1000
    cycle_steps: 5000
    weight_decay: 0.01
    shuffle_buffer: 256
    gradient_clip_val: 1.0
    seq_len: 400

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

train_dataset: !new:recipes.musiclm.datasets.text.PromptsDataset
    prompts_fnames:
        - "/mnt/bn/audio-diffusion/data/bad_case_prompts/hanoi_prompts_20230809.csv"
        - "/mnt/bn/audio-diffusion/data/google_prompts/text_prompt_collection_20230713.csv"
        - "/mnt/bn/audio-diffusion/data/google_prompts/text_prompt_collection_20230728.csv"

validation_dataset: !new:recipes.mulan.dataset.mme.MMEDataset
    name: human_labelled_5k_valid
    audio_type: nonvocal
    seq_len: !ref <run_opts[seq_len]>
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self
    resampled: False
    use_pipe: True

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.DataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    train_keys: "text"
    val_keys: "audio,text"
    predict_keys: "audio,text"
    return_dict: True
    pin_memory: True

model_config: !new:transformers.LlamaConfig
    vocab_size: !ref <extra_params[wav2vec_codebook_size]> + <extra_params[mulan_num_rvq]> * <extra_params[mulan_codebook_size]> + 1
    hidden_size: 1536
    intermediate_size: 4608
    num_hidden_layers: 24
    num_attention_heads: 12
    hidden_act: "silu"
    max_position_embeddings: !ref <extra_params[mulan_num_rvq]> + <extra_params[wav2vec_frame_rate]> * <extra_params[duration]>
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[wav2vec_codebook_size]>

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.musiclm.lightning.rlhf.SemanticSequenceTrainingModule
    checkpointing: !ref <_checkpointing>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    extra_params: !ref <extra_params>
    seed_model: "/mnt/bn/audio-diffusion/ducle/logs/semantic_flash_llama/mcc40m_conservative_filtered_vad2/checkpoints/step=091000-tr_loss=2.4243-val_loss_0=2.8712.ckpt"
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/dongguo/mulan/codebook/kmeans_minibatch_codebook-mulan1b_g4_mix_127-1024x12.npy
            - !name:recipes.musiclm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <run_opts[cache_dir]>
        diffusion:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/diffusion/model_11/checkpoints/diffusion-step=459999.ckpt
            - !name:recipes.diffusion.rl_inference.init_diffusion
              cache_dir: !ref <run_opts[cache_dir]>
        vocoder:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/soundstream/dac_vae_125hz_24k/checkpoints/soundstream-step=592799-val_sdr=12.1354.ckpt
            - !name:recipes.diffusion.rl_inference.init_vocoder
              cache_dir: !ref <run_opts[cache_dir]>
        wav2vec:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/semantic.jit.pt
            - !name:recipes.musiclm.requires.model_initializer.init_wav2vec
              cache_dir: !ref <run_opts[cache_dir]>
        semantic_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/centroids_epoch_10.npy
            - !name:recipes.musiclm.requires.model_initializer.init_semantic_centers
              cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 50
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:recipes.musiclm.callbacks.checkpoints.ModelCheckpointSaveStep0
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 10
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
