---

seed_everything: 44568

model_checkpoint: &model_checkpoint
  hdfs_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhaohang.ai/train_logs/bigmusic/pt/seed_modes/1b5
  monitor: step
  save_top_k: -1
  save_last: True
  every_n_train_steps: 10000

wandb: &wandb
  project: bigmusic
  name: seed_models_train

trainer:
  accelerator: gpu
  max_steps: 150000
  default_root_dir: lightning_logs
  precision: bf16-mixed
  log_every_n_steps: 10
  # default_root_dir: "hdfs://harunawl/home/byte_data_seed_wl/user/xieshuangyi/train/bigmusic/exps"
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        <<: *wandb
  callbacks:
    - class_path: samantha.callbacks.Timer
    - class_path: samantha.callbacks.HDFSModelCheckpoint
      init_args:
        <<: *model_checkpoint
model:
  emb_config:
    config_path: "apps/bigmusic/pl_tasks/embeder.yaml"
    extra_params:
      embedding_dim: 1536 # = model.network.hidden_size, P6Dense need 1536
      text_codebook_size: 0 # = model.network.text_vocab_size
  emb_path: null
  hf_model_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhaohang.ai/models/qwen2.5-1.5b-p6d  # P6Dense
  network_config:
    _flash_attn_kernel_implementation: fa3  # default, lego, fa3
    _rms_norm_implementation: bumi  # torch, bumi
    _rope_implementation: bumi  # torch, bumi
    _swiglu_kernel_implementation: bumi  # torch, bumi
  optimizer_kwargs:
    optimizer:
      lr: 3e-4
      betas:
        - 0.9
        - 0.98
      eps: 1.0e-08
      weight_decay: 0.01
      fused: true
    lr_scheduler:
      warmup_step_rate: 0.1
      lr_decay_rate: 0.5
      lr_end: 1.0e-5


ckpt_path: null