---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

data_params:
    length_seconds: 3
    sample_rate: 24000
    acoustic_frame_rate: 80
    semantic_frame_rate: 25
    n_validation_samples: 385
    shard_lists:
        [
            "/mnt/bn/audio-diffusion/data/karaoke_for_singsong_mulan149_local.txt",
            "/mnt/bn/audio-diffusion/data/resso_mss_mulan149_shard_list.v3.txt",
        ]
    shard_list_probs: [0.5, 0.5]

# training parameters
training_params:
    max_steps: 1000000
    batch_size: 2
    valid_batch_size: 2
    base_lr: 0.0004
    warmup_steps: 5000
    hold_steps: 50000
    decay_steps: 3000000
    weight_decay: 0.00000001
    shuffle_buffer: 150

acoustic_params:
    start_channel: 2
    end_channel: 6

ckpt_path: null

log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]

# running parameters
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "musiclm_fine"
    version: "karaoke_resso_acc"
    precision: 32
    num_workers: 10
    accelerator: "auto"

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

encoder_transform:
    !new:recipes.audio_diffusion.modules.transforms.encoder.SoundStreamTransform
    sample_rate: !ref <data_params[sample_rate]>

coarse_transforms:
    !new:recipes.audio_diffusion.modules.transforms.musiclm.FineTransforms
    length_seconds: !ref <data_params[length_seconds]>
    audio_sample_rate: !ref <data_params[sample_rate]>
    audio_key: "acc.npy"
    sample_range_key: "acc_sample_range.npy"
    min_volume_threshold: 0.01

preprocessor:
    !new:recipes.audio_diffusion.modules.preprocess.WebDatasetBufferPreprocessor
    sample_rate: !ref <data_params[sample_rate]>
    transforms: !ref <coarse_transforms>

train_web_dataset:
    !new:recipes.audio_diffusion.modules.datasets.webdataset_ext.MultiWebDataset
    urls:
        !apply:recipes.audio_diffusion.conf.parse_shard_list.get_train_shards
        - !ref <data_params[shard_lists]>
    probs: !ref <data_params[shard_list_probs]>

validation_web_dataset: !new:webdataset.WebDataset
    urls:
        !apply:recipes.audio_diffusion.conf.parse_shard_list.get_validation_shards
        - !ref <data_params[shard_lists]>
    nodesplitter: !name:recipes.audio_diffusion.helper.return_self
    shardshuffle: True

train_dataset:
    !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <train_web_dataset>
    pipeline:
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.audio_diffusion.modules.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <preprocessor>
        - !name:webdataset.WebDataset.to_tuple
          - "audio"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[batch_size]>

validation_dataset:
    !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <validation_web_dataset>
    pipeline:
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[shuffle_buffer]>
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.audio_diffusion.modules.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <preprocessor>
        - !name:webdataset.WebDataset.to_tuple
          - "audio"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[valid_batch_size]>
        - !name:webdataset.WebDataset.with_epoch
          - !ref <data_params[n_validation_samples]>

pl_datamodule:
    !new:recipes.audio_diffusion.modules.pl_datamodule.WebDataModule
    train_dataset: !ref <train_dataset>
    validation_dataset: !ref <validation_dataset>
    batch_size: !ref <training_params[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

# model configuration
model:
    !new:recipes.audio_diffusion.modules.model_types.musiclm_transformer.FineTransformerDecoder
    acoustic_codebook_size: 1024
    transformer_emb_dim: 1024
    transformer_heads: 16
    transformer_layers: 14
    transformer_ff_dim: 4096
    acoustic_seq_len:
        !ref <data_params[acoustic_frame_rate]> * <data_params[length_seconds]>
    start_channel: !ref <acoustic_params[start_channel]>
    end_channel: !ref <acoustic_params[end_channel]>

# training module configuration
optimizer_class: !name:torch.optim.AdamW
    lr: !ref <training_params[base_lr]>
    weight_decay: !ref <training_params[weight_decay]>
    betas: (0.9, 0.98)

scheduler_class:
    !name:recipes.audio_diffusion.modules.lr_scheduler.TriStageLR
    warmup_steps: !ref <training_params[warmup_steps]>
    hold_steps: !ref <training_params[hold_steps]>
    decay_steps: !ref <training_params[decay_steps]>

pl_module:
    !new:recipes.audio_diffusion.modules.pl_module.MusicLMFineModule
    acoustic_token_model: !ref <model>
    optimizer_class: !ref <optimizer_class>
    scheduler_class: !ref <scheduler_class>
    cuda_transforms: !ref <encoder_transform>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "loss/valid"
    mode: "min"
    save_last: True

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: False
    log_every_n_steps: 20
    max_steps: !ref <training_params[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    auto_scale_batch_size: None
    gradient_clip_val: 10.0
    val_check_interval: 1000
    check_val_every_n_epoch: null  # required now that we use an IterableDataset
    track_grad_norm: 2
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD

profiler:
    enabled: False
    max_steps: 30
