---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 2023
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    prompt_path: "/mnt/bn/audio-diffusion/data/google_prompts/text_prompt_collection_20230728.csv"
    output_dir: generated_output/text_prompt_collection_20230728
    model_dir: recipes/diffusion/assets

    rl_finetuned_semantic: False
    semantic_ckpt: "/mnt/bn/audio-diffusion/ducle/logs/semantic_flash_llama/mcc40m_filtered_705m/checkpoints/step=081000-tr_loss=2.4451-val_loss_0=2.8561.ckpt"
    diffusion_ckpt_2_0: "hdfs://harunava/home/byte_speech_sv/weitsung.lu/diffusion/model_11_MCCVAD_ensemble_1.0/checkpoints/diffusion-step=153999.ckpt"
    diffusion_ckpt_2_1: "hdfs://harunava/home/byte_speech_sv/weitsung.lu/diffusion/model_11_MCCVAD_ensemble_1.0/checkpoints/diffusion-step=153999.ckpt"
    diffusion_ckpt_2_2: "hdfs://harunava/home/byte_speech_sv/weitsung.lu/diffusion/model_11_MCCVAD_ensemble_1.1/checkpoints/diffusion-step=049999.ckpt"
    diffusion_ckpt_2_3: "hdfs://harunava/home/byte_speech_sv/weitsung.lu/diffusion/model_11_MCCVAD_ensemble_2.3/checkpoints/diffusion-step=024999.ckpt"
    vocoder_ckpt: "hdfs://harunava/home/byte_speech_sv/weitsung.lu/soundstream/dac_vae_125hz_24k/checkpoints/soundstream-step=592799-val_sdr=12.1354.ckpt"

    sample_rate: 24000
    duration: 10
    num_rounds: 2
    semantic_duration: 10
    semantic_stride: 5
    wav2vec_codebook_size: 1024
    mulan_codebook_size: 1024
    mulan_num_rvq: 12
    wav2vec_frame_rate: 25
    semantic_temperature: 1.0
    diffusion_steps: 25
    bf16_portion: 0.0
    schedule_slope: 2.5
    guidance_scale: 2.5
    sample_mode: "gumbel"
    save_semantic_samples: False
    save_cosine_similarity: False
    generate_vocal: False

    diffusion_condition: ['semantic', 'mulan']

run_opts:
    fast_dev_run: False
    precision: 32
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    batch_size: 10
    num_workers: 2

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset: !apply:recipes.musiclm.datasets.inference.InferenceDataset.from_prompt_path
    prompt_path: !ref <extra_params[prompt_path]>

# dataloader configuration
predict_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle: False
    drop_last: False
    pin_memory: False

# datamodule configuration
pl_datamodule: !new:recipes.musiclm.datamodules.lit_datamodule.DataModule
    predict_dataloader: !ref <predict_dataloader>

pl_module: !new:recipes.diffusion.modules.pl_module_inference.InferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/v1.3_g4mix_127/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <extra_params[model_dir]>
              version: "g4"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/dongguo/mulan/codebook/kmeans_minibatch_codebook-mulan1b_g4_mix_127-1024x12.npy
            - !name:recipes.musiclm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <extra_params[model_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
