---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: null

# running parameters
log_dir: logs
asset_dir: recipes/diffusion/assets

run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "diffusion"
    version: "0.1"
    strategy: ddp_find_unused_parameters_false #!new:pytorch_lightning.strategies.ddp.DDPStrategy static_graph: True
    precision: bf16
    log_every_n_steps: 10
    num_steps: 6000000
    save_every_n_train_steps: 1000
    val_check_interval: 1000
    val_output_samples_dir: "generated_samples"

training_params:
    sample_rate: 24000
    noise_range: [0.0, 1.0]
    train_batch_size: 16
    train_num_workers: 8
    val_batch_size: 8
    val_num_workers: 4
    gradient_clip_val: 1.0
    learning_rate: 0.00008
    weight_decay: 0.005
    n_audio_samples: 240000
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    sample_buffer_size: 500

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# dataloader configuration
playlist_audio_transforms: !new:recipes.musiclm.transforms.musiclm.MusicLMTransforms
    n_samples: !ref <training_params[n_audio_samples]>
    audio_key: "audio.npy"
    min_volume_threshold: 0.05

playlist_preprocessor: !new:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor
    sample_rate: !ref <training_params[sample_rate]>
    transforms: !ref <playlist_audio_transforms>

playlist_train_shards: !new:webdataset.WebDataset
    urls: "pipe:hdfs dfs -cat /home/byte_speech_sv/mulan/playlist_v5_uio/audio_shards/shards_{0000..2597}.tar"
    resampled: True
    shardshuffle: True

train_dataset: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
    wds_dataset: !ref <playlist_train_shards>
    pipeline:
        - !name:webdataset.WebDataset.select
          - !name:samantha.utils.datastructures.select_keys
            keys:
                - "audio.npy"
        - !name:webdataset.WebDataset.decode
        - !name:webdataset.WebDataset.compose
          - !name:recipes.musiclm.preprocess.WebDatasetBufferPreprocessor.train_buffer_preprocessor
            - !ref <playlist_preprocessor>
        - !name:webdataset.WebDataset.shuffle
          - !ref <training_params[sample_buffer_size]>
        - !name:webdataset.WebDataset.to_tuple
          - "audio"
        - !name:webdataset.WebDataset.batched
          - !ref <training_params[train_batch_size]>

val_dataset: !new:recipes.diffusion.dataset.google_prompt_val.GooglePromptVal
    num_samples: 80

# datamodule configuration
pl_datamodule: !new:recipes.diffusion.modules.pl_datamodule_playlist.DataModule
    train_dataset: !ref <train_dataset>
    val_dataset: !ref <val_dataset>
    train_batch_size: !ref <training_params[train_batch_size]>
    val_batch_size: !ref <training_params[val_batch_size]>
    train_num_workers: !ref <training_params[train_num_workers]>
    val_num_workers: !ref <training_params[val_num_workers]>
    sample_buffer_size: !ref <training_params[sample_buffer_size]>
    num_steps_per_val: 4

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>

scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.diffusion.utils.lr_schedulers.lr_lambda
        warmup_steps: 0
        decay_factor: 0.5
        decay_interval: 200000

pl_module: !new:recipes.diffusion.modules.pl_module_v2.DiffusionModule
    seed: !ref <seed>
    diffusion_model: !new:recipes.diffusion.models.tnt_v2.TNTDiffusionNetwork
        input_dim: 65
        latent_dim: 32
        feature_dim: 1024
        context_dim: 1
        depth: 20
        segment_size: 64
        segment_stride: 32
        dropout: 0
        mulan_cfg_prob: 0.20
        use_checkpoint: False
    input_dim: 65
    num_chunks: 1
    chunk_length: 1250
    noise_range: !ref <training_params[noise_range]>
    sample_rate: !ref <training_params[sample_rate]>
    asset_dir: !ref <asset_dir>
    model_name: model
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    mulan_model:
        model_path: /home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
    mulan_centers:
        model_path: /home/byte_speech_sv/dongguo/mulan/codebook/kmeans_minibatch_codebook-mulan1b_g4_mix_127-1024x12.npy
    vocoder_model:
        model_path: hdfs://harunava/home/byte_speech_sv/weitsung.lu/soundstream/dac_vae_125hz_24k_v2_part2/checkpoints/soundstream-step=374999-val_sdr=12.9557.ckpt
    val_output_samples_dir: !ref <run_opts[val_output_samples_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: step
    mode: max
    save_top_k: 5
    every_n_train_steps: !ref <run_opts[save_every_n_train_steps]>
    save_last: True
    filename: diffusion-{step:06d}

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    num_sanity_val_steps: 0
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: auto
    devices: auto
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    precision: !ref <run_opts[precision]>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    use_distributed_sampler: False
    sync_batchnorm: True
    logger: !ref <logger>
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !new:recipes.diffusion.utils.ema.EMA
          decay: 0.999
    plugins: !ref <plugins>
