---

run_opts:
    precision: 32
    strategy: ddp
    ckpt_path: ""
    output_dir: output_wavs
    meta_lst: ""
    num_workers: 4
    seed: 1996
    diffusion_ckpt_path: ""
    umm_ckpt_path: ""
    vocoder_ckpt_path: ""
    umm_frame_rate: 25
    mel_frame_rate: 80
    infer_type: diffusion-vocoder
    use_wvae_vocoder: False
    lang: en

predict_dataset: !new:apps.bigtts.umm.diffusion.datasets.meta_based_dataset.MetaBasedUnit2WavDataset
    meta_lst: !ref <run_opts[meta_lst]>
    lang: !ref <run_opts[lang]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:samantha.dataio.lite.lite_datamodule.LiteDataModule
    predict_dataloader: !ref <dataloader>

bn_config: # 40hz wvae 3.1
    hop_size: 600
    bn_norm_std: 15
    bn_norm_mean: 0
    bn_padding: -2
    wvae_encoder_path: hdfs://haruna/home/byte_speech_sv/user/liuzhengxi/WaveVAE3.0/torchscript/wavevae_encoder_z1_%d.pt
    wvae_decoder_path: hdfs://haruna/home/byte_speech_sv/user/liuzhengxi/WaveVAE3.0/torchscript/wavevae_decoder_z1_%d.pt
    wvae_version: 3.1
    wvae_cache_dir: .module_cache
    wvae_encoder_hop_size: 300
    wvae_encoder_win_size: 1200

mel_config: # ibigvgan config.
    n_fft: 4096
    num_mels: 100
    hop_size: 600
    win_size: 2400
    fmin: 0
    fmax: 12000
    sampling_rate: 24000
    mel_norm_mean: -4
    mel_norm_std: 7.5
    mel_mask_value: -5

# mel_config: # 80hz ibigvgan config.
#     n_fft: 2048
#     num_mels: 80
#     hop_size: 300
#     win_size: 1024
#     fmin: 0
#     fmax: 8000
#     sampling_rate: 24000
#     mel_norm_mean: -4.5
#     mel_norm_std: 7
#     mel_mask_value: -5

pl_module: !new:apps.bigtts.umm.diffusion.lit_modules.lit_diffusion_reconstruct.ChunkInfer
    diffusion_ckpt_path: !ref <run_opts[diffusion_ckpt_path]>
    umm_ckpt_path: !ref <run_opts[umm_ckpt_path]>
    vocoder_ckpt_path: !ref <run_opts[vocoder_ckpt_path]>
    output_dir: !ref <run_opts[output_dir]>
    infer_type: !ref <run_opts[infer_type]>
    umm_frame_rate: !ref <run_opts[umm_frame_rate]>
    mel_frame_rate: !ref <run_opts[mel_frame_rate]>
    mel_config: !ref <mel_config>
    seed: !ref <run_opts[seed]>
    diffusion_precision: "bf16"
    diffusion_nfe: 10
    diffusion_sampler: "ddim"
    use_wvae_vocoder: !ref <run_opts[use_wvae_vocoder]>
    bn_config: !ref <bn_config>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
