---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    frame_rate: 40
    n_mels: 128
    n_chroma: 50
    n_fft: 2048
    win_length: 2048
    hop_length: 150
    feature_cmvn: "apps/bigtts/umm/umm/data/BigTTS_data_id=207.stats.new.pt"
    tokenizer: "wordpiece_multilingual"

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    hdfs_log_dir: "hdfs://haruna/home/byte_speech_sv/user/litang/umm_ar/40hz/logs"
    log_dir: logs
    log_name: umm
    version: !ref umm_stage3_<extra_params[tokenizer]>_pitch_vq<config[vq_codebook_size]>x<config[vq_codebook_dim]>_<config[vq_type]>_id<pl_datamodule[data_id]>_wobn_40hz
    precision: "32"
    num_workers: 3
    accelerator: auto
    warmup_steps: 2000
    max_steps: 1000000
    val_check_interval: 0
    ckpt_interval: 5000
    batch_size: 2
    learning_rate: 3.0e-5
    cycle_steps: 30000
    weight_decay: 0.1
    shuffle_buffer: 8000
    gradient_clip_val: 1.0
    checkpointing: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:apps.bigtts.umm.umm.data.mix.ParquetDataModule
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
    num_workers: !ref <run_opts[num_workers]>
    region: "CN"
    weights: [1, 20, 1]
    max_num_crops: null
    min_duration: 1
    max_duration: 90
    normalize_audio: False
    use_pipe: False
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    data_id: 440

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96] # TODO
    eps: 0.00000001

scheduler_cls: !name:samantha.optim.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

config: !new:samantha.models.umm.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    n_mels: !ref <extra_params[n_mels]>
    add_chroma: False
    add_pitch: True
    n_chroma: !ref <extra_params[n_chroma]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    hidden_size: 1024
    intermediate_size: 4096
    num_pre_layers: 12
    num_post_layers: 12
    num_hidden_layers: 24
    num_attention_heads: 8
    max_source_positions: 2500
    add_vq: True
    vq_layer_idx: 12
    add_weighted_sum: False
    vq_proj_norm: "bn"
    vq_proj_noise: 10000
    vq_type: "EMAEntropy"
    vq_codebook_size: 16384
    vq_codebook_dim: 32
    vq_decay: 0.99
    w_loss_mel: 1.0
    w_loss_chroma: 1.0
    w_loss_pitch: 1.0
    w_loss_vq: 1.0
    w_loss_ctc: 1.0
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    vocab_size: 105880
    ctc_blank_id: 105879
    use_bn: False
    hidden_dropout: 0.0
    activation_dropout: 0.0
    attention_dropout: 0.0
    conformer_conv_dropout: 0.0

# model_cls: !name:samantha.models.umm.umm_mk4.Stage3
model_cls: !name:samantha.models.umm.umm_mkii.Stage3
    config: !ref <config>

pl_module: !new:samantha.models.umm.lit_module.Stage3Improved
    checkpointing: !ref <run_opts[checkpointing]>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:samantha.criterion.criterion.CTCPitchMelLoss
        config: !ref <config>
    extra_params: !ref <extra_params>
    required_modules:
        pretrained:
            ckpt_path: "hdfs://haruna/home/byte_speech_sv/user/litang/umm_ar/25hz/logs/umm/umm_stage2_wordpiece_multilingual_pitch_id440_wobn_a100ft/checkpoints/step=002000.ckpt"
            init_fn: !name:samantha.models.umm.model_initializer.init_pretrained
            cache_dir: !ref <run_opts[cache_dir]>
        rmvpe:
            ckpt_path: "hdfs://haruna/home/byte_speech_sv/user/chenyuanzhe/share/rmvpe.pt"
            init_fn: !name:samantha.models.umm.model_initializer.init_rmvpe
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:samantha.models.umm.callbacks.log_spectrogram.LogSpectrogram
      n_examples: 3

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2
    limit_val_batches: 1
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
