---
# @hanoihantrakul 17OCT2024
# YAML for launching FrozenUMM-Mel-Decoder Job.
# This configuration inherits the adversarial loss for ConvUMM-GAN family of tokenizers.
# I use the default setting which I knew worked for that model and adapt it for
# for training this FrozenUMM-Mel-Decoder.
#
# This config trains on data 2196 which is the same one used to train Wei-Tsung's vocoder in 44.1khz.
# I have resampled the audio to 24000 to test using the griffin lim and other pretrained vocoders like vocos. 

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: last

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000 # 44100 # sample rate for dataloader and mel decoding
    frame_rate: 25 # frame rate of the tokenizer

    # @hanoihantrakul 11NOV: stereo vs mono control
    n_channels: 2 # supports 1 (mono) or 2 (stereo)
    return_complex: False 

    # @hanoihantrakul 24OCT2024: experimenting with losses
    w_loss_l1: 1.0 # default ConvUMM-GAN w_loss_adv : 1.0
    w_loss_ssim: 1.0 # default ConvUMM-GAN w_loss_adv : 1.0
    w_loss_adv: 0.05 # default ConvUMM-GAN w_loss_adv : 0.05

    # @hanoihantrakul 28OCT2024: experimenting with decoder parameter size
    latent_dim_in: 32 # 1 channel produces tokens of 32 dims. 2 channel produces a concat sequence of 64dims.
    num_conv_layers: 4 # default ConvUMM-GAN mel head: 4
    conv_hidden_size: 256 # default ConvUMM-GAN mel head: 256
    hidden_size: 1024 # default ConvUMM-GAN mel head: 1024

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm_mel_decoder
    hdfs_log_dir: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/hanoi.hantrakul/logs"
    log_dir: logs
    log_name: umm_mel_decoder
    version: !ref 24khz_stereo_mel_decoder_MonoToStereoDecoding_l1-<extra_params[w_loss_l1]>_ssim-<extra_params[w_loss_ssim]>_adv-<extra_params[w_loss_adv]>_num_conv_layers-<extra_params[num_conv_layers]>_conv_hidden_size-<extra_params[conv_hidden_size]>hidden_size-<extra_params[hidden_size]>
    precision: "32" # changed from "16-mixed" because ConvUMM-GAN and DualUMM used "32"
    num_workers: 4
    accelerator: auto
    warmup_steps: 2000
    max_steps: 1000000
    val_check_interval: 5000
    ckpt_interval: 5000
    batch_size: 20 
    learning_rate: 1.0e-4 # Changed from 3.0e-4 to match ConvUMM-GAN
    cycle_steps: 200000
    weight_decay: 0.1
    shuffle_buffer: 800 # 8000 
    gradient_clip_val: 0.0 # Changed from 1.0 because GAN training does not support this
    # checkpointing: False # This must be turned off when `ddp_find_unused_parameters_true` is used


################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# pl_datamodule: !new:recipes.datasets.mcc.mix_mkii.MixDataModule
#     data_ids: [2255] #[2255] # @hanoihantrakul 17OCT2024 2255 is 24khz mono. 5495 is 44100hz stereo.
#     data_weights: [1]
#     shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
#     sample_rate: !ref <extra_params[sample_rate]>
#     batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
#     num_workers: !ref <run_opts[num_workers]>
#     max_num_crops: null
#     min_duration: 1
#     max_duration: 60 # 12APR2024 Hanoi and Devon Sun and I manually verified this dataset only contains audio lengths between 0-60s.
#     normalize_audio: False
#     tokenizer: null
#     frame_rate: !ref <extra_params[frame_rate]>
#     collate_fn: !name:recipes.datasets.mcc.mix.collate_audio # @hanoihantrakul 17OCT2024 Only audio data is needed in this mel decoder

# 12NOV2024 @hanoihantrakul: I copied these settings from https://code.byted.org/seed/samantha/blob/wtl/dev/vocoder/recipes/soundstream/conf/default_vae_shutterstock_44.1k.yaml#L56

pl_datamodule: !new:recipes.diffusion.dataset.parquet_dataset.ParquetDataModule
    train_data_id: 2196
    valid_data_id: 2196 # 2124
    train_batch_size: !ref <run_opts[batch_size]>
    valid_batch_size: 8
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    n_channels: !ref <extra_params[n_channels]>
    dataset_samplerate: !ref <extra_params[sample_rate]>
    audio_duration: 40.0
    prefetch_factor: 16

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

optimizer_disc_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: 0
    betas: [ 0.9, 0.900 ] 
    eps: 0.00000001

scheduler_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.5 # adopted from ConvUMM-GAN

config: !new:recipes.umm.models.umm_mel_decoder.UMMMelDecoderConfig
    training_sample_rate: 24000
    n_mel_bins_out: 160 # default ConvUMM-GAN mel head: 160
    n_mel_channels_out: !ref <extra_params[n_channels]>
    return_complex: !ref <extra_params[return_complex]>
    latent_dim_in: !ref <extra_params[latent_dim_in]>
    num_conv_layers: !ref <extra_params[num_conv_layers]>
    conv_hidden_size: !ref <extra_params[conv_hidden_size]>
    hidden_size: !ref <extra_params[hidden_size]>
    w_loss_l1: !ref <extra_params[w_loss_l1]>
    w_loss_ssim: !ref <extra_params[w_loss_ssim]>
    w_loss_adv: !ref <extra_params[w_loss_adv]>

model_cls: !name:recipes.umm.models.umm_mel_decoder.UMMMelDecoderV2
    config: !ref <config>

pl_module: !new:recipes.umm.modules.lit_module_umm_mel_decoder.UMMMelDecoderTrainingTaskV2
    config: !ref <config>
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    optimizer_disc_cls: !ref <optimizer_disc_cls>
    scheduler_cls: !ref <scheduler_cls>
    required_modules:
        pretrained:
            ckpt_path: "hdfs:///home/byte_speech_sv/hanoi.hantrakul/logs/umm_conformer_2255mixedZHEN_tts_rope/umm_stage3_2255mixedZHEN_2375Speech_tts_rope_bert-base-multilingual-uncased/checkpoints/step=100000.ckpt"
            init_fn: !name:recipes.umm.requires.model_initializer.init_stage3
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:07d}"
      save_last: True
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_true"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    limit_val_batches: 1
    limit_train_batches: 10000 # Consult Colin Wang: forces an epoch to end every 10k steps and prevent OOM
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>