---

################################################################################
##########                      APP CONFIGURATION                    ##########
################################################################################

submodule_name: 'bigmusic'

repo:
  func_path: 'recipes.serving.handler.instrumental'
  preload_model_func_name: 'preload_models'

inputs:
  -
    source: 'payload'
    type: 'str'
    name: 'prompt'
  -
    source: 'payload'
    type: 'str'
    name: 'audio_prompt'
  -
    source: 'payload'
    type: 'str'
    name: 'duration'
  -
    source: 'payload'
    type: 'str'
    name: 'chorus'

outputs:
  -
    destination: 'data'
    name: 'audio'
  -
    destination: 'payload'
    name: 'sample_rate'
    type: 'int'
  -
    destination: 'payload'
    name: 'urls'
    type: 'str'
  -
    destination: 'payload'
    name: 'message'
    type: 'str'
