---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 42
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: debug
    version: 0.3
    precision: 16
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/llm_debug/
    profiler: simple
    flash_attn: null
    num_epochs: 100
    batch_size: 1
    num_workers: 8
    learning_rate: 0.0003
    weight_decay: 0.1
    checkpointing: False

hp:
    max_token_lens: 2048
    audio_tokens_num: 1024
    phone_tokens_num: 5140
    mask_input_for_train: false
    mask_input_for_val: true
    lr: !ref <run_opts[learning_rate]>
    weight_decay: 0.1

_checkpointing: !ref <run_opts[checkpointing]>

# gpt hyper-config
gpt_config: !new:transformers.GPT2Config
    vocab_size: 6217
    n_positions: 2048
    n_ctx: 2048
    n_embd: 1024
    n_layer: 12
    n_head: 16
    activation_function: gelu_new
    resid_pdrop: 0.1
    embd_pdrop: 0.1
    attn_pdrop: 0.1
    layer_norm_epsilon: 0.00001
    initializer_range: 0.02
    c_attn_bias: False
    pos_type: "rope_attn" # learnable, rope, rope_attn
    qk_bias: False
    # train_len for block sparse attention
    sparse_attn: False
    train_len: 2048
    layout_fn: "default_layout_fn"
    mask_file: "default_block_mask.npy"
    use_cache: !apply:operator.not_ [!ref <_checkpointing>]
    summary_type: 'mean'
    summary_use_proj: True
    summary_activation: None
    summary_proj_to_labels: True
    summary_first_dropout: 0.1
    bos_token_id: 184
    eos_token_id: 184
    pad_token_id: 0


collator: !new:recipes.text2semantic.datasets.ValleCollator
    tokenizer_pad: 0

# datamodule configuration
pl_datamodule: !new:recipes.text2semantic.lit_modules.DataModule
    train_dataloader: !ref <train_dataloader>
    predict_dataloader: !ref <predict_dataloader>

# model configuration
model_cls: !name:recipes.text2semantic.modules.GPT2LMHeadSparseModel
    config: !ref <gpt_config>
    flash_attn: !ref <run_opts[flash_attn]>
    logit_num: !ref <gpt_config[vocab_size]>
    use_cond: False
    cond_dim: 128
    cond_type: linear

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.95]
    eps: 0.00000001