---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision:
  !apply:torch.set_float32_matmul_precision ["high"]

extra_params:
  network_cfg: "apps/bigmusic/mariana_tasks/conf/v5_m8_680m_new_emb.yaml"
  skip_sos: False # Audio continuation needs to skip audio SOS
  stop_eos: True # stop generation in case of EOS

  samples_to_save: 1
  output_dir: ./generated_output/conditional

  # Semantic model
  semantic_cls_path: apps.bigmusic.mariana_tasks.semantic_seed_train.SemanticLlmModel
  emb_path: "emb.pt"
  llm_path: "llm.pt"
  predict_step_seed: 1234
  inference:
      use_cache: True
      use_cuda_graph: True
      cuda_graph_max_bsz: !ref <extra_params[beam_size]> * <run_opts[batch_size]> * 2  # bsz times 2 for cfg
      cuda_graph_max_seqlen: 10240

  # Model Settings
  sample_rate: 44100
  duration: 240
  lyrics_max_seq_len: 4000
  semantic_frame_rate: 25

  # AR sampling hparams
  semantic_temperature: 0.6 # 0.6 for sobv4. 0.8 for sobv2
  sample_mode: "top_p" # top_p, adaptive_sampling, gumbel
  sample_thresh: 0.9
  target_top_k: 100
  beam_size: 1

  # Sampling
  use_step_out_blank: True
  step_out_blank_logic: "v4"
  step_out_blank_max_len: 200
  repetition_penalty: 1.6
  emit_eos_thresh_secs: 5 # Force to emit EOS after reaching specific duration
  exclude_eos_thresh_secs: 1 # Suppress EOS until threshold before reaching specific duration
  exclude_eos_first_secs: 20 # Suppress eos prediction in the beginning.

  # CFG
  use_controller_cfg: True # Set to True to activate style CFG.
  controller_cfg_gamma: 3.0

  # Cache
  cache_dir: .module_cache/bigmusic

run_opts:
  fast_dev_run: False
  precision: bf16
  accelerator: auto
  strategy: auto
  cache_dir: .module_cache/bigmusic
  batch_size: 1
  num_workers: 8

  enable_groundtruth: False

token2wav_config:
  !apply:hyperpyyaml.load_hyperpyyaml [
    !apply:open [
      !apply:os.getenv [
        "token2wav_config",
        "apps/bigmusic/umm/diffusion/conf/2024Q2/infer_generation_streaming.yaml",
      ],
      "r",
    ],
  ]

data:
  predict_dataset_ids: [10495]
  predict_dataset_weights: [1]

  predict_batcher:
    type: "SimpleBatcher"
    batch_size: !ref <run_opts[batch_size]>

  predict_item_transform:
    - type: ConvertMetaToDict
    - type: GetItem
      in_key: meta.raw.tags_music
      out_key: tags_music
      convert_str_to_dict: True
    - type: GetItem
      in_key: meta.raw.duration
      out_key: duration
    - type: GetItem
      in_key: meta.raw.lyrics
      out_key: lyrics
    - type: GetItem
      in_key: meta.raw.freeform_text
      out_key: freeform_text
    - type: GetItem
      in_key: meta.raw.extra
      out_key: extra
      convert_str_to_dict: True
    - type: GetItem
      in_key: extra.text_category
      out_key: text_category
    - type: GetItem
      in_key: extra.index
      out_key: index
    - type: GetItem
      in_key: meta.raw.structure
      out_key: structure
    - type: GetFrontendResults
      out_key: frontend_results
    - type: GetItem
      in_key: tags_music.speaker_id
      out_key: speaker_id
    - type: TempoParser  # for the tempo xval embedder
      in_key: extra.mir_info.tempo  # -1
      out_key: tempo
      dropout_rate: 0.0
    - type: PromptToSongSliceTransformParquet
      phoneme_vocab: v1
      style_tag_vocab: v2
      use_cfg: True
      standardize: True
      cfg_items:
        [
          "genre",
          "genre_extra",
          "mood",
          "speaker",
          "lyrics",
          "scene",
          "voice",
          "sinking",
          "freeform_text",
          "line_break",
          "instrument",
        ]

    # flatten style_input_ids and its cfg counterpart
    - type: "ConvertDictToList"
      in_key: style_input_ids
      out_key: style_input_ids
      list_order:
        [
          "genre",
          "genre_extra",
          "extra",
          "mood",
          "scene",
          "vocal_gender",
          "vocal_timbre",
          "language",
          "is_sinking",
          "instrument",
          "tempo",
          "key",
          "mode",
        ]
    - type: "ConvertDictToList"
      in_key: style_input_ids_cfg
      out_key: style_input_ids_cfg
      list_order:
        [
          "genre",
          "genre_extra",
          "extra",
          "mood",
          "scene",
          "vocal_gender",
          "vocal_timbre",
          "language",
          "is_sinking",
          "instrument",
          "tempo",
          "key",
          "mode",
        ]

    # style_text is no longer used in the embedding module, but it is still required by the callbacks
    - type: "ConvertDictToList"
      in_key: style_tags
      out_key: style_text
      list_order:
        [
          "genre",
          "genre_extra",
          "extra",
          "mood",
          "scene",
          "vocal_gender",
          "vocal_timbre",
          "language",
          "is_sinking",
          "instrument",
          "tempo",
          "key",
          "mode",
        ]

    # slice_duration is required by SemanticLlmModel to determine the number of tokens to generate
    - type: "RenameKey"
      in_key_list: ["duration"]
      out_key_list: ["slice_duration"]
      in_place: true

    # These fields are no longer used in the embedding module, but they are still required by the callbacks
    - type: AddField
      key: conditions
      value: style_text,freeform_text,speaker_id,lyrics_tokens

    # Audio is None
    - type: "CalculateToken"
      token_rate: 25
      phoneme_tokens_key: "phoneme_tokens"
      audio_length_out_key: "target_tokens_length"
      lyrics_length_out_key: "lyrics_tokens_length"
      total_token_length: "num_total_tokens"
      sample_rate: 24000

    - type: "CalculateToken"
      token_rate: 25
      phoneme_tokens_key: "phoneme_tokens_cfg"
      audio_length_out_key: "target_tokens_length_cfg"
      lyrics_length_out_key: "lyrics_tokens_length_cfg"
      total_token_length: "num_total_tokens_cfg"
      sample_rate: 24000

    - type: "SanityCheck"
      keys:
        [
          "uttid",
          "style_tags",
          "style_tags_cfg",
          "style_input_ids",
          "style_input_ids_cfg",
          "style_text",
          "freeform_text",
          "freeform_text_cfg",
          "phoneme_tokens",
          "phoneme_tokens_cfg",
          "slice_duration",
          "structure",
          "lyrics_tokens_length",
          "lyrics_tokens_length_cfg",
          "speaker_id",
          "speaker_id_cfg",
          "tempo",  # for the tempo xval embedder
        ]

  predict_batch_transform:
    - type: TokenCoffCollate
      in_key: "phoneme_tokens"
      token_key: "input_ids"
      coff_key: "coffs"
      token_output_key: "lyrics_tokens"
      coff_output_key: "lyrics_coffs"
      max_phone_len: 4000

    - type: TokenCoffCollate
      in_key: "phoneme_tokens_cfg"
      token_key: "input_ids"
      coff_key: "coffs"
      token_output_key: "lyrics_tokens_cfg"
      coff_output_key: "lyrics_coffs_cfg"
      max_phone_len: 4000

    - type: NestListCollate
      key_list:
        [
          "uttid",
          "style_tags",
          "style_tags_cfg",
          "style_input_ids",
          "style_input_ids_cfg",
          "style_text",
          "freeform_text",
          "freeform_text_cfg",
          "phoneme_tokens.tokens",
          "phoneme_tokens_cfg.tokens",
          "conditions",
          "text_category",
          "index",
          "structure",
          "lyrics",
        ]
      to_tensor: False

    - type: NestListCollate
      key_list:
        [
          "lyrics_tokens_length",
          "lyrics_tokens_length_cfg",
          "num_total_tokens",
          "slice_duration",
          "speaker_id",
          "speaker_id_cfg",
          "tempo",  # for the tempo xval embedder
        ]
      to_tensor: True

pl_datamodule: !new:samantha.dataio.bigmusic.lite.MusicLiteDataModule
  predict_dataset_ids: !ref <data[predict_dataset_ids]>
  predict_dataset_weights: !ref <data[predict_dataset_weights]>
  predict_item_transform: !ref <data[predict_item_transform]>
  predict_batch_transform: !ref <data[predict_batch_transform]>
  predict_batcher: !ref <data[predict_batcher]>

pl_module: !new:apps.bigmusic.mariana_tasks.inference.SemanticInferenceModule
  semantic_cls_path: !ref <extra_params[semantic_cls_path]>
  extra_params: !ref <extra_params>
  required_modules:
    diffusion_modules:
      diffusion:
        hpath:
          !apply:operator.getitem [!ref <token2wav_config>, "diffusion_config"]
        initializer:
          !name:apps.bigmusic.umm.diffusion.requires.model_initializer.init_diffusion
          cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    # ===== base callback. Must be placed in front of all callbacks. =====
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
    - !new:recipes.bigmusic.callbacks.common_callbacks.UploadToEasyCycleCallback
      space_name: null
      expires: null
    - !new:recipes.bigmusic.callbacks.common_callbacks.ASRCallback
      asr_model_path: zh-CN
    - !new:recipes.bigmusic.callbacks.common_callbacks.ForceAlignCallback
    # ====================================================================
    # ===== features =====================================================
    - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsSAOnlineCallback
      asr_model_path: zh-CN
      transliteration: True
    - !new:recipes.bigmusic.callbacks.mir_metrics.MIRTagMetricsSAOnlineCallback
callbacks:
  - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
    beam_size: !ref <extra_params[beam_size]>
    samples_to_save: !ref <extra_params[samples_to_save]>
    save_style_audio: False # style_audio is usually downloaded and saved separately, no need to save
    save_mode: upload_keep_wav #upload and keep local wav
trainer: !new:pytorch_lightning.Trainer
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  accelerator: !ref <run_opts[accelerator]>
  devices: "auto"
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  deterministic: False
  enable_model_summary: True
  use_distributed_sampler: False # for multi-gpu inference
  strategy: !ref <run_opts[strategy]>
  # strategy: !new:pytorch_lightning.strategies.DDPStrategy
  #     timeout: !new:datetime.timedelta
  #     seconds: 7200
  precision: !ref <run_opts[precision]>
  callbacks: !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
