FROM hub.byted.org/compile/lab.speech.torch1.5.1_compile:e2170ef456ffb0f67f8b16a8087b957e
LABEL maintainer="Jacob Jiang <Jiangbo.jacob@bytedance.com>"
ARG http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG no_proxy="byted.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"

# install dependencies
# Apex
RUN git clone --recursive https://github.com/nvidia/apex.git &&\
    cd apex && git reset --hard 4ef930c1c884fdca5f472ab2ce7cb9b505d26c1a &&\
    python3 setup.py install --cuda_ext --cpp_ext && cd .. && rm -rf apex

# warp-transducer
RUN export CFLAGS="-I$CUDA_HOME/include $CFLAGS" && git clone --recursive https://github.com/HawkAaron/warp-transducer.git && cd warp-transducer && mkdir build && cd build && \
cmake -DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME .. && make -j && cd ../pytorch_binding/ && \
python3 setup.py install && cd ../../

# install falconclaw
RUN pip3 install \
    --trusted-host bytedpypi.byted.org http://luban-source.byted.org/repository/scm/lab.speech.falconclaw_1.0.5.85.tar.gz

# install falconpai
RUN pip3 install http://luban-source.byted.org/repository/scm/lab.speech.falconpai_1.0.12.1.tar.gz \
    --trusted-host bytedpypi.byted.org

# install panther
RUN cd /tmp && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.tensorflow_onnx_panther_1.0.0.8.tar.gz && \
    tar -xvf lab.speech.tensorflow_onnx_panther_1.0.0.8.tar.gz && \
    pip3 install \
        --no-cache-dir \
        \
        --trusted-host bytedpypi.byted.org \
        tf2onnx-1.9.2-py3-none-any.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_1.5.1.0.tar.gz && \
    tar -xvf lab.speech.panther_arnold_1.5.1.0.tar.gz && \
    cd cuda10.2_torch1.5 && \
    pip3 install \
        --no-cache-dir \
        \
        --trusted-host bytedpypi.byted.org \
        panther_gpu-1.5.1-cp37-cp37m-linux_x86_64.whl && \
    rm -rf /tmp/* /root/.cache

# install byteslim
RUN cd /tmp && wget http://luban-source.byted.org/repository/scm/lab.speech.byteslim_1.0.0.35.tar.gz \
    && tar -xvf lab.speech.byteslim_1.0.0.35.tar.gz \
    && pip3 install byteslim-1.0.0-py3-none-any.whl \
    --trusted-host bytedpypi.byted.org

# install kenlm
pip3 install https://github.com/kpu/kenlm/archive/master.zip
