FROM hub.byted.org/base/lab.pytorch2.staging:2.1.0.post0
LABEL maintainer="liyong.0517 <liyong.0517@bytedance.com>"

ARG http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG no_proxy="byted.org"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
    cd /tmp && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.1-1_all.deb && \
    sudo dpkg -i cuda-keyring_1.1-1_all.deb && \
    rm -f cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install \
        -yq --no-install-recommends \
        cuda-nsight-systems-11-7 && \
    apt install \
        -yq --no-install-recommends \
        libmkl-rt \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        openssh-server \
        netbase patchelf \
        git vim krb5-user \
        libcairo2-dev \
        clang-format \
        libsndfile1 ffmpeg tmux \
        git-lfs python3-tk \
        libsndfile-dev sox && \
    cd /tmp && \
    wget \
        https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    rm -f cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install -y cuda-nsight-systems-11-7 && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install \
        --no-cache-dir \
        pip --upgrade && \
    pip3 install \
        --no-cache-dir \
        pytorch-lightning==2.0.0 \
        hyperpyyaml==1.2.0 \
        Command==0.1.0 \
        setuptools==64.0.3 \
        ninja==1.11.1 \
        PyYAML==6.0 \
        mkl==2023.1.0 \
        mkl-include==2023.1.0 \
        mkl-devel==2023.1.0 \
        cmake==3.26.3 \
        cffi==1.15.1 \
        typing==3.7.4.3 \
        typing-extensions==4.5.0 \
        future==0.18.3 \
        protobuf==3.20.3 \
        bytedtos==1.1.9 \
        addict==2.4.0 \
        yapf==0.33.0 \
        sox==1.4.1 \
        cython==0.29.34 \
        black==22.10.0 \
        fairseq==0.12.2 \
        retry==0.9.2 \
        eventlet==0.33.3 \
        pytest-runner==6.0.0 \
        cxxfilt==0.3.0 \
        mpi4py==3.1.4 \
        pre-commit==2.21.0 \
        wget==3.2 \
        pytest==6.2.1 \
        pytest-cov==2.12.1 \
        ConfigArgParse==1.5.3 \
        tensorboard==2.12.2 \
        onnx==1.13.1 \
        absl-py==1.4.0 && \
    pip3 install \
        --no-deps \
        --no-cache-dir \
        numba==0.56.4 && \
    pip3 install \
        --no-cache-dir \
        pip --upgrade && \
    pip3 install \
        --no-cache-dir \
        pycairo==1.23.0 \
        six==1.16.0 \
        click==8.1.3 requests==2.28.1 \
        dataclasses==0.6 \
        psutil==5.9.5 cloudpickle==1.6.0 \
        kaldi_io==0.9.5 \
        librosa==0.10.0.post2 \
        subword-nmt==0.3.8 \
        fairseq==0.12.2 \
        scipy==1.10.1 \
        pydantic==1.10.7 \
        pillow==9.5.0 \
        scikit-learn==1.2.2 \
        SoundFile==0.12.1 \
        tqdm==4.65.0 \
        PySoundFile==0.9.0.post1 \
        matplotlib==3.7.1 \
        webrtcvad==2.0.10 \
        openpyxl==3.1.2 \
        transformers==4.28.1 \
        colorednoise==2.1.0 \
        torch_stft==0.1.4 \
        jieba==0.42.1 \
        pypinyin==0.48.0 \
        kaldiio==2.18.0 \
        soxbindings==1.2.3 \
        streamz==0.6.4 \
        pandas==1.5.3 \
        datasets==2.5.1 \
        byted-janus==0.1.6.post6 \
        torchaudio-augmentations==0.2.1 \
        einops==0.6.1 \
        zhon==1.1.5 \
        byted-cruise==0.5.0 && \
    pip3 install -U \
        --no-cache-dir \
        byted-dataloader

ARG PANTHER_VERSION=1.7.5.58
ARG FALCONCLAW_VERSION=1.0.5.129
ARG ONNX_VERSION=1.0.0.8
ARG OPENFST_VERSION=1.0.0.8
ARG ASR_EVAL_TOOL_VERSION=1.0.0.61
ARG I18N_TEXT_FORMAT_VERSION=1.0.0.95

# 2. install falconclaw && panther && lego
RUN \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.openfst_python_$OPENFST_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.falconclaw_$FALCONCLAW_VERSION.tar.gz && \
    cd /tmp && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    tar -xvf lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        tf2onnx-1.9.2-py3-none-any.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    tar -xvf lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        *torch*/panther_gpu*.whl && \
    pip3 install \
        --no-cache-dir \
      'http://luban-source.byted.org/repository/scm/data.aml.lego_ops_th20_cu117_cudnn850_abi0_sdist_1.0.0.25.tar.gz' && \
    rm -rf /tmp/* /root/.cache

# 3. install asr_eval_tool
RUN \
    mkdir -p /tmp/py_pkg.asr_eval_tool && \
    cd /tmp/py_pkg.asr_eval_tool && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    tar -xvf lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    rm lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    cd src/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd ../.. && \
    python3 setup.py bdist_wheel && \
    pip3 install --force-reinstall dist/asr_eval_tool-$ASR_EVAL_TOOL_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.asr_eval_tool

# install xformers
RUN git clone https://github.com/facebookresearch/xformers.git && cd xformers && git checkout 6425fd0cacb1a6579aa2f0c4a570b737cb10e9c3 \
    && git submodule update --init --recursive && cd .. \
    && XFORMERS_DISABLE_FLASH_ATTN=1 pip3 install -v --disable-pip-version-check --no-cache-dir ./xformers

# 4. add tools and env
#  4.1 HDFS env
#  4.2 ssh config
RUN mkdir -p /var/run/sshd
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new
RUN echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new
RUN mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config
#  4.3 common_tools for compile image
RUN mkdir -p /opt/common_tools
ENV PATH "/opt/common_tools:/opt/tiger/typhoon-blade:$PATH"
ADD ./dockerfile/krb5.conf /etc/krb5.conf
# 4.4 add hdfs env
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"
