FROM hub.byted.org/compile/lab.speech.torch1.8.1_compile:230316
# At dolphin image build stage, PANTHER_VERSION and FALCONCLAW_VERSION
# will be updated by building args;
# FALCONCLAW_VERSION and ONNX_VERSION are rarely updated, but they can
# be updated by building args if necessary;
ARG PANTHER_VERSION=1.7.4.18
ARG FALCONPAI_VERSION=1.1.30.0
ARG FALCONCLAW_VERSION=1.0.5.93
ARG ONNX_VERSION=1.0.0.8
ARG ASR_EVAL_TOOL_VERSION=1.0.0.61
ARG I18N_TEXT_FORMAT_VERSION=1.0.0.95
ARG BUILD_REGION=cn

# 1. add deps
RUN pip3 install \
        --no-cache-dir \
        --upgrade pip && \
    pip3 install \
        --no-cache-dir \
        addict==2.4.0 \
        yapf==0.31.0 \
        sox==1.4.1 \
        kaldi_io==0.9.4 \
        librosa==0.8.1 \
        openfst_python==1.7.3 \
        subword-nmt==0.3.7 \
        cython==0.29.24 \
        black==22.10.0 \
        fairseq==0.12.2 \
        pylint==2.15.4 \
        retry==0.9.2 \
        eventlet==0.26.1 \
        scipy==1.7.1 \
        pytest-runner==5.3.1 \
        numba==0.48.0 \
        cxxfilt==0.3.0 \
        filelock==3.3.2 \
        mpi4py==3.1.2 \
        pydantic==1.7.2 \
        pillow==8.4.0 \
        scikit-learn==1.0.2 \
        SoundFile==0.10.3.post1 \
        tqdm==4.62.1 \
        PySoundFile==0.9.0.post1 \
        matplotlib==3.5.1 \
        pandas==1.3.5 \
        webrtcvad==2.0.10 \
        openpyxl==3.0.10 \
        transformers==4.21.0 \
        colorednoise==2.0.0 \
        byted-janus==0.1.6.post6 \
        pytorch-lightning==1.6.5 \
        pypesq==1.2.4 \
        torch_stft==0.1.4 && \
    pip3 install \
        --no-cache-dir \
        pre-commit==2.20.0 \
        wget==3.2 \
        jieba==0.42.1 && \
    pip3 install \
        --no-cache-dir \
        pypinyin==0.47.1 && \
    pip3 install \
        --no-cache-dir \
        kaldiio==2.17.2 && \
    pip3 install \
        --no-cache-dir \
        soxbindings==1.2.2 && \
    pip3 install -U \
        --no-cache-dir \
        byted-dataloader && \
    pip3 install \
        --no-cache-dir \
        streamz==0.5.1 \
        pytest==6.2.1 \
        pytest-cov==2.12.1 \
        ConfigArgParse==1.4.1 \
        absl-py==0.12.0

# 2. install falconpai && falconclaw && panther && bytedlego-ops
ARG LEGO_LOC=tosv
RUN \
    MAX_JOBS=2 pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.falconpai_$FALCONPAI_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.falconclaw_$FALCONCLAW_VERSION.tar.gz && \
    cd /tmp && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    tar -xvf lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        tf2onnx-1.9.2-py3-none-any.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    tar -xvf lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        *torch*/panther_gpu*.whl && \
    if [ "$BUILD_REGION" = "cn" ] ; \
        then pip3 install --no-cache-dir https://$LEGO_LOC.byted.org/obj/asr-tele-backup/resources/bytedlego_ops-0.0.0-py2.py3-none-any.whl ; \
        else pip3 install --no-cache-dir http://$LEGO_LOC.byted.org/obj/lab-speech-data-labelling/resources/bytedlego_ops-0.0.0-py2.py3-none-any.whl ; \
    fi && \
    rm -rf /tmp/* /root/.cache

# 3. install asr_eval_tool
RUN \
    mkdir -p /tmp/py_pkg.asr_eval_tool && \
    cd /tmp/py_pkg.asr_eval_tool && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    tar -xvf lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    rm lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    cd src/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd ../.. && \
    python3 setup.py bdist_wheel && \
    pip3 install --force-reinstall dist/asr_eval_tool-$ASR_EVAL_TOOL_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.asr_eval_tool

# 4. add hdfs env
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"
ENV NVIDIA_DISABLE_REQUIRE=1

# 5. install kenlm
ARG http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG no_proxy="byted.org"
RUN pip3 install https://github.com/kpu/kenlm/archive/master.zip
