---

run_opts:
    precision: 32
    strategy: ddp
    ckpt_path: epoch=00-step=55000-kl_loss=0.82.ckpt
    output_dir: output_wavs
    meta_lst: /mnt/bn/jcong5/workspace3/samantha-vb-zhuo/recipes/voicebox/testset/librilight/meta.out
    num_workers: 4
    seed: 1996
    inference_type: content_editing
    use_speaker_encoder: True

predict_dataset: !new:recipes.voicebox.datasets.meta_based_dataset.MetaBasedDataset
    meta_lst: !ref <run_opts[meta_lst]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:recipes.text2semantic.lit_modules.lit_data.DataModule
    predict_dataloader: !ref <dataloader>

pl_module: !new:recipes.voicebox.lit_modules.lit_infer.VoiceBoxInfer
    ckpt_path: !ref <run_opts[ckpt_path]>
    output_dir: !ref <run_opts[output_dir]>
    seed: !ref <run_opts[seed]>
    inference_type: !ref <run_opts[inference_types]>
    audio_model_inference_config:
        use_guidance: true
        guidence_strength: 0.3
        atol: 0.0001
        rtol: 0.0001
        nfe: 32
    mel_config: # HifiGAN config
        n_fft: 1024
        num_mels: 80
        hop_size: 256
        win_size: 1024
        fmin: 0
        fmax: 8000
        sampling_rate: 22050
    mel_norm_mean: -5.8843
    mel_norm_std: 2.2615

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
