---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

# data configuration
data_dir: !apply:os.getenv ["DATA_DIR", "data"]
ckpt_path: null

# running parameters
# log_dir: 'logs'
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "audio_diffusion"
    version: "resnet"
    precision: 32
    num_workers: 16
    accelerator: "auto"

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
demo_params:
    demo_every_n_steps: 500
    num_demos: 16

data_params:
    sample_rate: 44100
    sample_length: 44100
    stereo_data: False
    truncate_data: True

# training parameters
training_params:
    num_epochs: 50000
    batch_size: 160
    base_lr: 0.00005
    max_lr: 0.0012
    weight_decay: 0.0001

# dataset configuration
train_dataset:
    !new:recipes.audio_diffusion.modules.datasets.RawAudioDataset
    path: !ref <data_dir>
    sample_rate: !ref <data_params[sample_rate]>
    sample_length: !ref <data_params[sample_length]>
    stereo_data: !ref <data_params[stereo_data]>
    truncate: !ref <data_params[truncate_data]>

# datamodule configuration
pl_datamodule:
    !new:recipes.audio_diffusion.modules.pl_datamodule.DataModule
    train_dataloader_attr:
        dataset: !ref <train_dataset>
        num_workers: !ref <run_opts[num_workers]>
        shuffle: True
        drop_last: True
        pin_memory: True
    batch_size: !ref <training_params[batch_size]>

# model configuration
model:
    !new:recipes.audio_diffusion.modules.model_types.res_net_1d.ResNet1d
    num_signal_channels: 1

# training module configuration
optimizer_class: !name:torch.optim.AdamW
    lr: !ref <training_params[base_lr]>
    weight_decay: !ref <training_params[weight_decay]>

scheduler_class: !name:torch.optim.lr_scheduler.CyclicLR
    base_lr: !ref <training_params[base_lr]>
    max_lr: !ref <training_params[max_lr]>
    mode: exp_range
    gamma: 0.95
    cycle_momentum: False

pl_module:
    !new:recipes.audio_diffusion.modules.pl_module.DiffusionLitModule
    model: !ref <model>
    optimizer_class: !ref <optimizer_class>
    scheduler_class: !ref <scheduler_class>
    diffusion_scheme: !new:recipes.audio_diffusion.modules.diffusion_schemes.EDMScheme

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "loss/train"
    mode: "min"
    save_last: True

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"

generate_demo:
    !new:recipes.audio_diffusion.modules.demo_callbacks.diffusion.GenerateDemo
    demo_every_n_steps: !ref <demo_params[demo_every_n_steps]>
    num_demos: !ref <demo_params[num_demos]>
    sample_rate: !ref <data_params[sample_rate]>
    sample_length: !ref <data_params[sample_length]>
    stereo: !ref <data_params[stereo_data]>

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: False
    log_every_n_steps: 1
    max_epochs: !ref <training_params[num_epochs]>
    precision: !ref <run_opts[precision]>
    auto_scale_batch_size: "binsearch"
    gradient_clip_val: 0.1
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !ref <generate_demo>
################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
