---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__convert: !apply:recipes.mir2.utils.musicfm_adapt.convert_nas_to_hdfs_in_glob []

# running parameters
run_opts:
  fast_dev_run: False
  hdfs_log_dir: "hdfs:///home/byte_speech_sv/ju-chiang.wang/umm_multi"
  log_name: 'mir_multitask'
  version: 'umm_3395'
  # precision: 16-mixed
  precision: 32
  log_dir: !apply:os.getenv ["LOG_DIR", "logs"]
  accelerator: 'auto'
  num_workers: 5
  pin_memory: True
  val_dataset_split_size: 3000
  tasks: ['beat', 'chord', 'structure', 'key']
  tasks_weight: [0.3, 0.3, 0.9, 0.5]
  bar_sync_chord: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
train_params:
  learning_rate: 0.001
  max_epochs: -1
  batch_size: 6
  scheduler_patience: 20
  scheduler_decay_factor: 0.9
  devices: 'auto'
  shuffle_buffer: 100
  num_iter: 100 # total number is num_workers * num_iter

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 24000            # sampling rate for audio
  sample_len: 24.0                # data-loader duration in sec for input  #{24 or 6}
  task_sample_len: [6.0, 12.0, 24.0, 12.0]    # model duration in sec for task
  hop_factor: 6

labels:
  beat_label_hop: 0.02
  chord_label_hop: 0.1
  structure_label_hop: 0.2
  key_label_hop: 2
  task_label_hops: [0.02, 0.1, 0.2, 2.0]
  task_n_timesteps: [300, 120, 120, 6]  # 6 / 0.02, 12 / 0.1
  foundation_hz: 25

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

# local_cache_dir: "/mnt/bn/audio-diffusion/pretrained_models/musicfm/"
# stat_path: !new:recipes.mir2.utils.helper.HdfsFileWrapper
#   file_path: "hdfs://haruna/home/byte_speech_sv/haonanchen/logs/musicfm/playlist_classic_stats.json"
#   local_cache_dir: !ref <local_cache_dir>
# model_path: !new:recipes.mir2.utils.helper.HdfsFileWrapper
#   file_path: "hdfs://haruna/home/byte_speech_sv/haonanchen/logs/musicfm/FM7.pt"
#   local_cache_dir: !ref <local_cache_dir>
# frontend: !new:recipes.mir_benchmark.models.frontend.Frontend
#   model:
#     !new:recipes.icassp.models.musicfm_25Hz.MusicFM25Hz
#     encoder_depth: 12
#     is_flash: False
#     stat_path: !ref <stat_path>
#     model_path: !ref <model_path>
#   layer_ix: 12
#   is_update: True

config: !new:recipes.umm2.models.config.UMMConfig
  feature_cmvn: "recipes/datasets/mcc/data_ids=794.stats.pt"
  sample_rate: !ref <audio[sampling_rate]>
  n_mels: 128
  n_fft: 2048
  win_length: 2048
  hop_length: 240
  hidden_size: 1024
  intermediate_size: 4096
  num_hidden_layers: 24
  num_attention_heads: 8
  max_source_positions: 2500
  tokenizer: null
  frame_rate: 25
  use_bn: False


frontend: !new:recipes.mir2.models.umm_ft.UMM # umm not frozen
  config: !ref <config>
  takes: [audio]
  provides: [latent]
  bypasses: []

transpose: !new:recipes.mir2.models.utils.TransposeStage

backend: !new:recipes.mir_benchmark.models.multitask_probing.MultitaskProbingStage
  n_channel: 1024
  foundation_hz: !ref <labels[foundation_hz]>
  tasks: !ref <run_opts[tasks]>  # include all task names
  label_hops: !ref <labels[task_label_hops]> # include all label_hops
  resamples: !ref <labels[task_n_timesteps]> # include all n_timesteps

# model: !new:sami_ai.core.BaseModel
#   input_names: [audio]
#   output_names: [output]
#   stages:
#       - !ref <frontend>
#       - !ref <backend>

model: !new:recipes.mir2.models.utils.PipelineModelTupleWrapper
  input_names: [audio]
  output_names: [output]
  stages:
    - !ref <frontend>
    - !ref <transpose>
    - !ref <backend>

required_modules:
  pretrained:
    ckpt_path: "hdfs://haruna/home/byte_speech_sv/ju-chiang.wang/logs/umm2_conformer_2255mixedZHEN/stage1_4096x16x8/checkpoints/step=0580000.ckpt"
    # ckpt_path: "hdfs://haruna/home/byte_speech_sv/ju-chiang.wang/logs/umm2_conformer_2255mixedZHEN/stage2_hpss_onset_2255mixedZHEN_optim_mem_bert-base-multilingual-uncased/checkpoints/step=0250000.ckpt"
    # loader: !name:recipes.umm2.loaders.stage1.ModelLoader
    loader: !name:recipes.umm2.loaders.stage1.ModelLoader
    cache_dir: ".module_cache/umm"

# pl_module: !new:recipes.mir_benchmark.pl_modules.multitask_finetune_pl.LitFinetuneMultitask
pl_module: !new:recipes.mir2.pl_modules.musicfm_pl_umm2.MusicFMPLUMM2
  model: !ref <model>
  tasks: !ref <run_opts[tasks]>
  tasks_weight: !ref <run_opts[tasks_weight]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[task_sample_len]>
  label_hop: !ref <labels[task_label_hops]>
  joint_hop_factor: !ref <audio[hop_factor]>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  val_dataset_split_size: !ref <run_opts[val_dataset_split_size]>
  required_modules: !ref <required_modules>

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

beat_preprocessor: !new:recipes.mir_benchmark.utils.beat_processor.BeatPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <labels[beat_label_hop]>

beat_train_urls: !apply:recipes.mir_benchmark.utils.concat_beat_data.concatenate_dataset ["train"]
beat_train_dataset: !new:webdataset.WebDataset
  urls: !ref <beat_train_urls>
  resampled: True

beat_train_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <beat_train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.beat_processor.BeatPreprocessor.train_batch_preprocess
        - !ref <beat_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio.npy beats.pickle tempo_label"]
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

beat_val_urls: !apply:recipes.mir_benchmark.utils.concat_beat_data.concatenate_dataset ["validation"]
beat_val_dataset: !new:webdataset.WebDataset
  urls: !ref <beat_val_urls>
  nodesplitter: !name:webdataset.shardlists.split_by_node

beat_val_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <beat_val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.beat_processor.BeatPreprocessor.val_preprocess
        - !ref <beat_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["__key__ audio.npy beats.pickle tempo_label orig_beats dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

chord_preprocessor: !new:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <labels[chord_label_hop]>

chord_train_urls: !apply:recipes.mir_benchmark.utils.concat_chord_data.concatenate_dataset ["train"]
chord_train_dataset: !new:webdataset.WebDataset
  urls: !ref <chord_train_urls>
  resampled: True

chord_train_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <chord_train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor.train_batch_preprocess
        - !ref <chord_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio chord_root chord_triad chord_note chord_ignore"]
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

chord_val_urls: !apply:recipes.mir_benchmark.utils.concat_chord_data.concatenate_dataset ["validation"]
chord_val_dataset: !new:webdataset.WebDataset
  urls: !ref <chord_val_urls>
  nodesplitter: !name:webdataset.shardlists.split_by_node

chord_val_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <chord_val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor.val_preprocess
        - !ref <chord_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["__key__ audio chord_root chord_triad chord_note chord_ignore dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

structure_preprocessor: !new:recipes.mir_benchmark.utils.structure_processor.StructurePreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <labels[structure_label_hop]>

structure_train_urls: !apply:recipes.mir_benchmark.utils.concat_structure_data.concatenate_dataset ["train"]
structure_train_dataset: !new:webdataset.WebDataset
  urls: !ref <structure_train_urls>
  resampled: True

structure_train_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <structure_train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.structure_processor.StructurePreprocessor.train_batch_preprocess
        - !ref <structure_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio boundary_label function_label"]
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

structure_val_urls: !apply:recipes.mir_benchmark.utils.concat_structure_data.concatenate_dataset ["validation"]
structure_val_dataset: !new:webdataset.WebDataset
  urls: !ref <structure_val_urls>
  nodesplitter: !name:webdataset.shardlists.split_by_node

structure_val_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <structure_val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.structure_processor.StructurePreprocessor.val_preprocess
        - !ref <structure_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["__key__ audio boundary_interval function_label dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

key_preprocessor: !new:recipes.mir_benchmark.utils.key_processor.KeyPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  label_hop: !ref <labels[key_label_hop]>

key_train_urls: !apply:recipes.mir_benchmark.utils.concat_key_data.concatenate_dataset ["train"]
key_train_dataset: !new:webdataset.WebDataset
  urls: !ref <key_train_urls>
  resampled: True

key_train_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <key_train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.key_processor.KeyPreprocessor.train_batch_preprocess
        - !ref <key_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio key_label"]
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

key_val_urls: !apply:recipes.mir_benchmark.utils.concat_key_data.concatenate_dataset ["validation"]
key_val_dataset: !new:webdataset.WebDataset
  urls: !ref <key_val_urls>
  nodesplitter: !name:webdataset.shardlists.split_by_node

key_val_transformed: !apply:sami_ai.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <key_val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.key_processor.KeyPreprocessor.val_preprocess
        - !ref <key_preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["__key__ audio key_label dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

train_transformed: !new:recipes.musiclm.datamodules.webdataset.ConcatDatasetsWithinBatch
  datasets:
    - !ref <beat_train_transformed>
    - !ref <chord_train_transformed>
    - !ref <structure_train_transformed>
    - !ref <key_train_transformed>

val_transformed: !new:recipes.musiclm.datamodules.webdataset.ConcatDatasetsWithinBatch
  datasets:
    - !ref <beat_val_transformed>
    - !ref <chord_val_transformed>
    - !ref <structure_val_transformed>
    - !ref <key_val_transformed>

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <train_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

val_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

# datamodule configuration
pl_datamodule: !new:recipes.mir_benchmark.pl_modules.pl_datamodule.BaseDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <val_dataloader>
  sampling_rate: !ref <audio[sampling_rate]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger:
  - !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ".module_cache/tagging"
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
  - !new:pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: !ref <run_opts[log_dir]>
    project: !ref <run_opts[log_name]>
    name: !ref <run_opts[version]>


callbacks:
  - !new:samantha.callbacks.HDFSModelCheckpoint
    hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
    monitor: step
    save_top_k: 10
    save_last: True
    every_n_train_steps: 1000
    mode: max
    filename: "{step:06d}-{train_loss:.4f}-{val_summary:.4f}"
  # - !new:pytorch_lightning.callbacks.ModelCheckpoint
  #   every_n_epochs: 1
  #   mode: "max"
  #   save_last: True
  #   save_top_k: 3
  #   monitor: val_summary
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: "ddp_find_unused_parameters_true"
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  gradient_clip_val: 1
  deterministic: False
  callbacks: !ref <callbacks>
  plugins: !ref <plugins>
