---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: null

# running parameters
log_dir: logs
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "soundstream"
    version: "24k_transformer"
    strategy: ddp_find_unused_parameters_true #!new:pytorch_lightning.strategies.ddp.DDPStrategy static_graph: True
    precision: 16
    log_every_n_steps: 10
    num_steps: 6000000
    val_check_interval: 200
    val_output_samples_dir: "generated_samples"

training_params:
    sample_rate: 24000
    train_batch_size: 72
    train_num_workers: 4
    val_batch_size: 24
    val_num_workers: 4
    learning_rate: 0.0002
    weight_decay: 0.005
    input_chunk_samples: 24000

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# dataloader configuration
mcc_dataset: !new:recipes.soundstream.dataset.mcc.MCCDataset
    music_len: !ref <training_params[input_chunk_samples]> #128 + 256*128
    mode: train
    resampled: True

train_datasets:
    mcc_dataset: !ref <mcc_dataset>

selected_dataset_names: [mcc_dataset]
weights: [1]

train_dataset: !new:samantha.dataio.dataset.MultiIterableDataset
    datasets: !apply:recipes.mulan.dataset.utils.select_datasets
        - !ref <train_datasets>
        - !ref <selected_dataset_names>
    weights: !ref <weights>
    num_samples: 10_000_000
    seed: !ref <seed>

val_dataset: !new:recipes.soundstream.dataset.mcc.MCCDataset
    music_len: 240000 
    mode: val
    resampled: True

# datamodule configuration
pl_datamodule: !new:recipes.soundstream.modules.pl_datamodule.SoundstreamDataModule
    train_dataset: !ref <train_dataset>
    val_dataset: !ref <val_dataset>
    train_batch_size: !ref <training_params[train_batch_size]>
    val_batch_size: !ref <training_params[val_batch_size]>
    train_num_workers: !ref <training_params[train_num_workers]>
    val_num_workers: !ref <training_params[val_num_workers]>
    sample_buffer_size: 200
    num_steps_per_val: 4

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>

gen_lr_scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.soundstream.utils.lr_schedulers.lr_lambda 
        warmup_steps: 0
        decay_factor: 0.5
        decay_interval: 200000
    
dis_lr_scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.soundstream.utils.lr_schedulers.lr_lambda 
        warmup_steps: 0
        decay_factor: 0.5
        decay_interval: 200000

pl_module: !new:recipes.soundstream.modules.pl_module_transformer_vae.VocoderModule
    seed: !ref <seed>
    generator: !new:recipes.soundstream.models.transformer.TransformerKL
        window_size: 64
        hop_size: 32
        encoder_dim: 512
        encoder_heads: 8
        encoder_resample_rates: [2, 4, 4, 1]
        encoder_resample_interval: 4
        decoder_dim: 512
        decoder_heads: 8
        decoder_resample_rates: [1, 4, 4, 2]
        decoder_resample_interval: 4
        attn_dropout: 0.1
        ff_dropout: 0.1
        use_checkpoint: True
    discriminator: !new:recipes.soundstream.models.modules.ms_tfd.MultiScaleSTFTDiscriminator
        filters: 32
        pretrain: False
    balancer: !new:recipes.soundstream.utils.balancer.Balancer
        ema_averager: !name:recipes.soundstream.utils.balancer.EMA
        weights:
            generator_loss: 1.0  #/7  7
            kl_loss: 0.0007
            sc_loss: 7.0 #50
            mag_loss: 7.0 # 50  
            fmap_loss: 9.0 # 20  /33 = 66
            wav_loss: 0
        scale_gradients: False
        deny_list: [kl_loss]
    generator_warmup_steps: 0
    sample_rate: !ref <training_params[sample_rate]>
    input_chunk_samples: !ref <training_params[input_chunk_samples]> 
    hop_samples: 12000 
    valid_batch_size: !ref <training_params[val_batch_size]>
    val_output_samples_dir: !ref <run_opts[val_output_samples_dir]>
    optimizer_cls: !ref <optimizer_cls>
    gen_lr_scheduler_cls: !ref <gen_lr_scheduler_cls>
    dis_lr_scheduler_cls: !ref <dis_lr_scheduler_cls>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_sdr
    mode: max
    save_top_k: 5
    save_last: True
    filename: soundstream-{step:06d}-{val_sdr:.4f}

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    num_sanity_val_steps: 0
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: auto
    devices: auto
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    precision: !ref <run_opts[precision]>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    use_distributed_sampler: False
    sync_batchnorm: True
    logger: !ref <logger>
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !new:recipes.soundstream.utils.ema.EMA
            decay: 0.999
            cpu_offload: False

    plugins: !ref <plugins>
