---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 42
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: null

# running parameters
log_dir: logs
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "soundstream"
    version: "24k_vae"
    strategy: ddp_find_unused_parameters_true #!new:pytorch_lightning.strategies.ddp.DDPStrategy static_graph: True
    precision: 32
    log_every_n_steps: 10
    num_steps: 6000000
    val_check_interval: 1000
    val_output_samples_dir: "generated_samples"

training_params:
    sample_rate: 24000
    train_batch_size: 16
    train_num_workers: 6
    val_batch_size: 12
    val_num_workers: 4
    learning_rate: 0.00005
    weight_decay: 0.005
    input_chunk_samples: 24000
    sample_buffer_size: 256


################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# dataloader configuration
short_form_dataset: !new:recipes.mulan.dataset.short_form.ShortFormDataset
    resampled: True

long_form_dataset: !new:recipes.mulan.dataset.long_form.LongFormDataset
    resampled: True

audioset_dataset: !new:recipes.mulan.dataset.audioset.AudioSetDataset
    resampled: True

ecals_dataset: !new:recipes.mulan.dataset.ecals.ECALSDataset
    resampled: True

karaoke_dataset: !new:recipes.mulan.dataset.karaoke.KaraokeDataset
    resampled: True

playlist_dataset: !new:recipes.mulan.dataset.playlist.PlaylistDataset
    resampled: True

mcc_gpt_dataset: !new:recipes.mulan.dataset.mcc.MCCGPTGenDataset
    resampled: True

aed_gpt_dataset: !new:recipes.mulan.dataset.mcc.AEDGPTGenDataset
    resampled: True

mcc_n2m_dataset: !new:recipes.mulan.dataset.mcc.MCCN2MDataset
    resampled: True

tt_query_dataset: !new:recipes.mulan.dataset.tt_query.TTQueryDataset
    resampled: True

train_datasets:
    short_form: !ref <short_form_dataset>
    long_form: !ref <long_form_dataset>
    audio_set: !ref <audioset_dataset>
    ecals: !ref <ecals_dataset>
    karaoke: !ref <karaoke_dataset>
    playlist: !ref <playlist_dataset>
    mcc_gpt: !ref <mcc_gpt_dataset>
    aed_gpt: !ref <aed_gpt_dataset>
    mcc_n2m: !ref <mcc_n2m_dataset>
    tt_query: !ref <tt_query_dataset>


selected_dataset_names: [short_form, long_form, ecals, playlist, mcc_n2m, tt_query]
weights: [0.2, 0.1, 0.1, 0.2, 0.2, 0.2]

train_dataset: !new:samantha.dataio.dataset.MultiIterableDataset
    datasets: !apply:recipes.mulan.dataset.utils.select_datasets
        - !ref <train_datasets>
        - !ref <selected_dataset_names>
    weights: !ref <weights>
    num_samples: 10_000_000
    seed: !ref <seed>

val_dataset: !new:recipes.soundstream.dataset.mcc.MCCDataset
    music_len: 240000 
    mode: val
    resampled: True

# datamodule configuration
pl_datamodule: !new:recipes.soundstream.modules.pl_datamodule.SoundstreamDataModule
    train_dataset: !ref <train_dataset>
    val_dataset: !ref <val_dataset>
    train_batch_size: !ref <training_params[train_batch_size]>
    val_batch_size: !ref <training_params[val_batch_size]>
    train_num_workers: !ref <training_params[train_num_workers]>
    val_num_workers: !ref <training_params[val_num_workers]>
    sample_buffer_size: !ref <training_params[sample_buffer_size]>
    num_steps_per_val: 4

# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>

gen_lr_scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.soundstream.utils.lr_schedulers.lr_lambda 
        warmup_steps: 0
        decay_factor: 0.5
        decay_interval: 200000
    
dis_lr_scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.soundstream.utils.lr_schedulers.lr_lambda 
        warmup_steps: 0
        decay_factor: 0.5
        decay_interval: 200000

pl_module: !new:recipes.soundstream.modules.pl_module_vae.VocoderModule
    seed: !ref <seed>
    generator: !new:recipes.soundstream.models.vqgan.VQGAN_KL_new
        latent_dim: 32
        downsample_rates: [2, 3, 4, 8]
        upsample_rates: [8, 4, 3 ,2]
        encoder_base_dim: 96
        decoder_base_dim: 2560
    discriminator: !new:recipes.soundstream.models.modules.discriminator.MultiScaleSTFTDiscriminator
        filters: 48
    generator_warmup_steps: 0
    lambda_generator_loss: 1.0
    sample_rate: !ref <training_params[sample_rate]>
    val_output_samples_dir: !ref <run_opts[val_output_samples_dir]>
    optimizer_cls: !ref <optimizer_cls>
    gen_lr_scheduler_cls: !ref <gen_lr_scheduler_cls>
    dis_lr_scheduler_cls: !ref <dis_lr_scheduler_cls>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_sdr
    mode: max
    save_top_k: 5
    save_last: True
    filename: soundstream-{step:06d}-{val_sdr:.4f}

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    num_sanity_val_steps: 0
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: auto
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    precision: !ref <run_opts[precision]>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    use_distributed_sampler: False
    sync_batchnorm: True
    logger: !ref <logger>
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !new:recipes.soundstream.utils.ema.EMA
            decay: 0.999
            cpu_offload: False

    plugins: !ref <plugins>
