---

# 22AUG2024 @hanoihantrakul
# This model is like `conf/2024_Q2_conf_archives/conformer_tts_rope/umm_stage2_conformer_tts_rope_mixedZHEN2255.yaml`
# but I remove the pitch loss. This is to ablate whether pitch_loss is affecting the E2E WER.
# At the time of writing ConformerUMM_2255_2375 has best WER (0.178) compared to ConformerUMM_2255_2375_TTS_ROPE (0.231).
# The worse WER could be coming from presence of pitch_loss
#
# This model is 723M params.

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 555
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    frame_rate: 25
    n_mels: 128 # this is the mel-128 transform for the spectrogram loss
    n_mels_tgt: 160 # this is the mel-160 transform for the pretrained pitch detector
    n_chroma: 12 # @hanoih: this should be 12. Not sure why TTS folks use 50
    n_fft: 2048
    win_length: 2048
    hop_length: 240
    feature_cmvn: "recipes/datasets/mcc/data_ids=794.stats.pt" # we need this because original mkii ConformerUMM normalized using these statistics
    tokenizer: "bert-base-multilingual-uncased" # stage2 apply language tokenizer to both EN and CN
    

# running parameters
run_opts:
    fast_dev_run: False
    cache_dir: .module_cache/umm
    hdfs_log_dir: "hdfs:///home/byte_speech_sv/hanoi.hantrakul/logs"
    log_dir: logs
    log_name: umm_conformer_2255mixedZHEN_tts_rope
    version: !ref umm_stage2_2255mixedZHEN_tts_rope_no_pitch_<extra_params[tokenizer]>
    precision: "16-mixed"
    num_workers: 3
    accelerator: auto
    warmup_steps: 2000
    max_steps: 1000000
    val_check_interval: 10000 # 14APR2024 @hanoihantrakul set limit_train_val_batches=1 so that validation loop is called
    ckpt_interval: 10000
    batch_size: 8 # 
    learning_rate: 1.0e-4
    cycle_steps: 30000 # 200000 # 5JUL2024 @hanoihantrakul: these settings were chosen by Li Tang in the reference Stage2 Job
    weight_decay: 0.1
    shuffle_buffer: 800 # 8000 
    gradient_clip_val: 1.0
    checkpointing: False
    num_spectrogram_val_samples_for_plotting: 8 # As of 13APR2024 This new flag controls the number of spectrograms from the validation dataset to plot to Merlin

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.datasets.mcc.mix_mkii.MixDataModule
    data_ids: [2255]
    val_data_id: 2255
    data_weights: [1]
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]> * <pl_datamodule[max_duration]> * <extra_params[sample_rate]>
    num_workers: !ref <run_opts[num_workers]>
    max_num_crops: null
    min_duration: 1
    max_duration: 60 # 12APR2024 Hanoi and Devon Sun and I manually verified this datasert only contains audio lengths between 0-60s.
    normalize_audio: False
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    # collate_fn: !name:recipes.datasets.mcc.mix.collate_audio # 14APR2024 @hanoihantrakul Must turn this off for Stage2 because you need both `audio` and `token` to be passed by default collate_fn

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96] # TODO
    eps: 0.00000001

scheduler_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.5 # 5JUL2024 @hh this is slightly different from `umm_stage2_2255mixedZHEN.yaml`. I follow Li Tang's config.

config: !new:recipes.umm.models.config.UMMConfig
    feature_cmvn: !ref <extra_params[feature_cmvn]>
    sample_rate: !ref <extra_params[sample_rate]>
    n_mels: !ref <extra_params[n_mels]>
    n_mels_tgt: !ref <extra_params[n_mels_tgt]>
    add_ctc: True # 5JUL2024 @hanoih There is a EN and CN speech. CTC turned on.
    add_pitch: False # 22AUG2024 @hanoih Try turnig this off to see if WER E2E improves
    add_chroma: True # 5JUL2024 @hanoih unlike TTS version, we turn chroma on
    n_chroma: !ref <extra_params[n_chroma]>
    n_fft: !ref <extra_params[n_fft]>
    win_length: !ref <extra_params[win_length]>
    hop_length: !ref <extra_params[hop_length]>
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 24
    num_attention_heads: 8
    max_source_positions: 2500
    #add_vq: False
    #vq_codebook_size: 32768
    #vq_codebook_dim: 32
    #vq_decay: 0.99
    w_loss_mel: 1.0
    w_loss_chroma: 1.0
    #w_loss_pitch: 1.0
    #w_loss_vq: 1.0
    w_loss_ctc: 1.0
    tokenizer: !ref <extra_params[tokenizer]>
    frame_rate: !ref <extra_params[frame_rate]>
    vocab_size: 105880
    ctc_blank_id: 105879
    ctc_zero_infinity: True
    use_bn: False
    ### 5JUL2024 @hanoihantrakul According to the Merlin Job Li Tang uses the following settings `first_conformer`, `act_fn`, `mask_mel`, `rope_enhance_pos`
    first_conformer: True 
    act_fn: "gelu" 
    mask_mel: False  
    rope_enhance_pos: 7500 # 29JUN2024 @hanoihantrakul Li Tang explained this figure means the position embedding is valid up to 300s. At the time writing, the longest TTS speech segment is 90s.
    ### 

model_cls: !name:recipes.umm.models.umm_mkii.Stage2 # instead of `umm_mkii_tts_rope.Stage2TTSRope` 
    config: !ref <config>

pl_module: !new:recipes.umm.modules.lit_module.Stage2 # instead of `lit_module_mkii_tts_rope.Stage2TTSRope
    checkpointing: !ref <run_opts[checkpointing]> 
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.umm.modules.criterion.UMMLoss # instead of `criterion.UMMLossPitchSupervised`
        config: !ref <config>
    extra_params: !ref <extra_params>
    required_modules:
        pretrained:
            # @hanoih 22AUG2024: can reuse the stage1 checkpoint   
            ckpt_path: "hdfs:///home/byte_speech_sv/hanoi.hantrakul/logs/umm_conformer_2255mixedZHEN_tts_rope/umm_stage1_rq_tts_rope_4096x16x8/checkpoints/step=0300000.ckpt"
            init_fn: !name:recipes.umm.requires.model_initializer.init_pretrained
            cache_dir: !ref <run_opts[cache_dir]>

logger:
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[log_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: !ref <run_opts[log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
      monitor: step
      save_top_k: 500
      every_n_train_steps: !ref <run_opts[ckpt_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:recipes.umm.callbacks.log_spectrogram.LogSpectrogram
      n_examples: 3

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    limit_val_batches: 1
    limit_train_batches: 5000 # 10000 # Consult Colin Wang: forces an epoch to end every 10k steps and prevent OOM
    sync_batchnorm: True
    benchmark: False
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
