---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    lyrics_codebook_size: 400
    semantic_codebook_size: 32_768
    semantic_frame_rate: 25
    semantic_type: bestrq
    mulan_embed_dim: 512
    hidden_size: 1536
    intermediate_size: 4128
    num_hidden_layers: 24
    num_attention_heads: 12
    pretrained_path: null

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_model_mulan_text_07B
    version: v0
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 8
    accelerator: auto
    max_steps: 1000000
    val_check_interval: 2000
    batch_size: 12
    learning_rate: 3.0e-4
    warmup_steps: 2000
    cycle_steps: 100000
    weight_decay: 0.01
    shuffle_buffer: 0
    gradient_clip_val: 1.0
    buckets_in_sec: [20, 25, 30]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.mix.MixWebDataModule
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_in_sec: !ref <run_opts[buckets_in_sec]>

model_config: !new:transformers.LlamaConfig
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    hidden_size: !ref <extra_params[hidden_size]>
    intermediate_size: !ref <extra_params[intermediate_size]>
    num_hidden_layers: !ref <extra_params[num_hidden_layers]>
    num_attention_heads: !ref <extra_params[num_attention_heads]>
    hidden_act: "silu"
    max_position_embeddings: 4096
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.MixSemanticModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        bestrq:
            # US UMM-chroma stage 3
            hpath: hdfs://harunava/home/byte_speech_sv/zongyu.yin/logs/umm/stage3_music_chroma_vq32768x32/checkpoints/step=0030000.ckpt
            initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                cache_dir: !ref <run_opts[cache_dir]>
        # Mulan mix - 160
        mulan:
            hpath: /mnt/bn/audio-diffusion/mulan/ongoing/mulan-step=014000-median_rank_1=160-kaggle.ckpt
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "g4"

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      save_top_k: 50
      save_last: True
      monitor: val_accu_0
      mode: max
      filename: "{step:06d}-{val_accu_0:.2f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    # - !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback
    # - !new:recipes.umm.callbacks.log_melspectrogram.LogMelSpectrogram
    #   n_examples: 4

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 500
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2  # skip validation sanity checks so we don't run into hdfs file close errors
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
