---

seed: 42
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: null

max_seq_len: 256
batch_size: 64
num_workers: 16
log_name: "nano_gpt/default"
version: !applyref:samantha.utils.experiment.get_version_name
log_dir: "/mnt/bn/janne-research-xl/logs"
hdfs_log_dir: !ref "hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/data/js/logs/<log_name>/<version>"

tokenizer: !new:samantha.transforms.tokenizers.character.CharacterTokenizer

pl_datamodule: !new:recipes.research.test_lab.shakespeare.ShakespeareDataModule
  data_fp: "input.txt"
  tokenizer: !ref <tokenizer>
  max_seq_len: !ref <max_seq_len>
  batch_size: !ref <batch_size>
  num_workers: !ref <num_workers>
  pin_memory: True

pl_module: !new:recipes.research.test_lab.nano_gpt.NanoGPT
  config: !new:recipes.research.test_lab.nano_gpt.NanoGPTConfig
    model_type: llama # gpt
    vocab_size: 65
    max_seq_len: !ref <max_seq_len>
    n_embd: 384
    n_head: 6
    n_layer: 6
    learning_rate: 1.0e-4 # with baby networks can afford to go a bit higher
    dropout: 0.2
    warmup_steps: 100
    weight_decay: 0.1
    betas: [0.9, 0.99]
    use_rotary_embeddings: True
    attention_kwargs:
      enable_flash_2: False
      enable_flash: True
      enable_mem_efficient: False
      enable_math: False

###
### Callbacks
###
text_generation: !new:recipes.research.test_lab.callback.TextGenerationCallback

logger:
  - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: !ref <log_dir>
    name: !ref <log_name>
    version: !ref <version>
    default_hp_metric: False
  - !new:pytorch_lightning.loggers.WandbLogger
    save_dir: !ref <log_dir>
    project: !apply:samantha.utils.experiment.wandb_sanitize [!ref <log_name>]
    name: !apply:samantha.utils.experiment.wandb_sanitize [!ref <version>]

checkpoint: !new:samantha.callbacks.HDFSModelCheckpoint
  hdfs_path: !ref <hdfs_log_dir>
  monitor: step
  save_top_k: 100
  save_last: True
  every_n_train_steps: !ref <trainer[val_check_interval]>
  mode: max
  filename: "{step:06d}"

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: 'step'

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: ddp_find_unused_parameters_false
  sync_batchnorm: True
  logger: !ref <logger>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  enable_model_summary: True
  max_epochs: -1
  max_steps: 100000
  precision: bf16-mixed
  val_check_interval: 500
  limit_val_batches: 100
  check_val_every_n_epoch: null
  gradient_clip_val: null
  accumulate_grad_batches: 1
  callbacks:
    - !ref <checkpoint>
    - !ref <lr_monitor>
    - !ref <text_generation>
  plugins: !ref <plugins>
