project = 'librispeech_rnnt'
runner = 'RNNTRunner'
data = dict(
    chunk_size=20,
    use_lid=False,
    use_recombine=1,
    use_code_switch=1,
    use_eos=False,
    use_bpe=True,
    data_root=[
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/other/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/smb_gogokid/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/feiyu/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr_2nd/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/xingfuli/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/dongchedi/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/input/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/Datatang_child_2000h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/Huiting_child_1000h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/general_18000h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/h_child_100h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/video_live_54000h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/video_live_6wh',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/voice_input_ByteTalk_60h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/voice_input_first_chn_eng_4500h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/voice_input_second_ximalaya_1_6500h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/voice_input_second_ximalaya_2_4300h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/voice_input_third_2_27000h'
    ],
    train_file_list=[
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(128)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(128)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(16)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["sub_{}".format(i) for i in range(199)]',
        '["sub_{}".format(i) for i in range(50)]',
        '["sub_{}".format(i) for i in range(443)]',
        '["sub_{}".format(i) for i in range(6)]',
        '["sub_{}".format(i) for i in range(1149)]',
        '["sub_{}".format(i) for i in range(1332)]',
        '["sub_{}".format(i) for i in range(4)]',
        '["sub_{}".format(i) for i in range(230)]',
        '["sub_{}".format(i) for i in range(343)]',
        '["sub_{}".format(i) for i in range(230)]',
        '["sub_{}".format(i) for i in range(1437)]'
    ],
    train_domain_list=[
        '[0 for i in range(256)]',
        '[0 for i in range(128)]',
        '[0 for i in range(256)]',
        '[0 for i in range(128)]',
        '[0 for i in range(32)]',
        '[0 for i in range(32)]',
        '[0 for i in range(16)]',
        '[0 for i in range(256)]',
        '[1 for i in range(199)]',
        '[1 for i in range(50)]',
        '[2 for i in range(443)]',
        '[1 for i in range(6)]',
        '[3 for i in range(1149)]',
        '[3 for i in range(1332)]',
        '[4 for i in range(4)]',
        '[4 for i in range(230)]',
        '[4 for i in range(343)]',
        '[4 for i in range(230)]',
        '[4 for i in range(1437)]'
    ],
    valid_data_root=[
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/Datatang_child_2000h',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/'
    ],
    valid_file_list=[
        '["sub_199"]', '["input/cv"]', '["video/cv"]', '["other/cv"]',
        '["smb_gogokid/cv"]', '["feiyu/cv"]'
    ],
    valid_domain_list=['[1]', '[4]', '[3]', '[0]', '[0]', '[0]'],
    meta_data_root=
    'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/liangzhenlin/dolphin/data_wav/Datatang_child_2000h',
    meta_file='meta',
    fbank_dim=80,
    fetch_block_size=300,
    bucket_schedule=
    '50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,2000',
    bucket_schedule_val=
    '50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,2000',
    bucket_schedule_key='fbank',
    batch_means_tokens=1,
    max_batch_size=48000,
    max_batch_scale=20,
    shuffle=True,
    drop_last=False,
    train_item_transform=[
        dict(type='PickleParser'),
        dict(type='WavParser'),
        dict(type='KaldiFbank', dither=1.0, dynamic_dither=True),
        dict(type='LabelLengthFilter', in_out_ratio=4),
        dict(type='DomainAdd'),
        dict(type='BPE', use_eos=False),
        dict(type='CMVN', key='fbank'),
        dict(type='AppendFeatureDim', total_dim=80),
        dict(
            type='DynamicTimeMask',
            time_mask_size=20,
            time_mask_block=60,
            replace_with_zero=False,
            inplace=True,
            time_mask_num_dither=1),
        dict(
            type='FreqMask',
            freq_mask_size=27,
            freq_mask_num=1,
            inplace=True,
            replace_with_zero=False)
    ],
    valid_item_transform=[
        dict(type='PickleParser'),
        dict(type='WavParser'),
        dict(type='KaldiFbank', dither=0.0),
        dict(type='LabelLengthFilter', in_out_ratio=4),
        dict(type='DomainAdd'),
        dict(type='BPE', use_eos=False),
        dict(type='AppendFrames', frame=12),
        dict(type='CMVN', key='fbank'),
        dict(type='AppendFeatureDim', total_dim=80)
    ],
    batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='FbankCollate', fbank_dim=80),
        dict(type='CharCollate', need_adapt_target=True),
        dict(type='PreCharCollate'),
        dict(type='DomainCollate')
    ],
    inference_batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='RefLabelCollate'),
        dict(type='FbankCollate', fbank_dim=80),
        dict(type='DomainCollate')
    ],
    prefetch_worker_num=4)
solution = dict(
    type='base_rnnt_solution',
    rnnt_type='BaseRnntModel',
    front_end_type='TimeReduceLSTMP',
    domain_num=10,
    input_concat_size=4,
    downsampling_size=4,
    acoustic_backbone_type='LSTMPBackbone',
    backbone_memory_size=512,
    backbone_hidden_size=1024,
    backbone_layer_num=5,
    backbone_bilstm=False,
    backbone_residual=True,
    dropout=0.1,
    head_type='RnntBaseHead',
    head_hidden_size=768,
    head_lowrank_size=512,
    layer_norm_after=True,
    predictor_type='LSTMPredictor',
    predictor_emb_size=512,
    predictor_lstm_hidden_size=1024,
    predictor_lstm_layer_num=2,
    predictor_dropout_factor=0.0,
    jointer_type='ShallowJointer',
    jointer_hidden_size=768,
    concate_U=1,
    jointer_simple_fusion=0,
    adaptive_head_size=968,
    adaptive_tail_size=200,
    adaptive_tail_groups=60,
    criterion_type='RnntAdaptiveCE',
    cer_update_freq=200,
    label_smooth_factor=0.1,
    reorder_dict_by_freq=True,
    xavier_init=False,
    mtl_type='ctc',
    mtl_head='HybridCEHead',
    backbone_mask=1,
    encoder_fix_steps=0)
work_dir = './demo'
train = dict(
    resume='latest.pth',
    resume_optimizer=True,
    max_epochs=9,
    max_iters=1200000,
    lr_scheduler=dict(
        by_epoch=False,
        warmup='linear',
        warmup_iters=5000,
        warmup_ratio=0.001,
        warmup_by_epoch=False,
        policy='valid',
        gamma=0.7),
    checkpoint_config=dict(interval=10000, max_keep_ckpts=20),
    curriculum_end_epoch=0,
    curriculum_length=520,
    save_root='./demo',
    save_dir='domain_id',
    save_name='lstm_rnnt_ctc_domain_id',
    amp_level='O1')
valid = dict(interval=20000)
inference = dict(
    bucket_schedule=
    '5,50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,2000,5000,10000,50000,100000',
    test_sets='test/ev_teacher_homework_comment_20200609_730',
    domain=2,
    beam_size=10,
    lm_path='',
    lm_weight=1.0,
    blk_scale=1.0,
    blank_thresh=1.0,
    len_penalty_scale=0.01)
nnlm = dict(lm_type='')
optimizer = dict(
    type='FusedAdam',
    lr=5e-05,
    betas=(0.9, 0.999),
    eps=1e-08,
    weight_decay=1e-05)
optimizer_config = dict(
    grad_clip=dict(max_norm=20, norm_type=2),
    max_grad_clip=5.0,
    bmuf_config=dict(
        block=200,
        block_lr=0.5,
        block_momentum=0.9,
        warmup_steps=5000,
        use_nesterov=True,
        average_sync=True))
criterion = None
super_criterion = None
log_level = 'INFO'
log_config = dict(
    interval=200,
    reset_flag=True,
    hooks=[dict(type='TensorboardLoggerHook'),
           dict(type='TextLoggerHook')])
