data = dict(
        data_root='hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele_2ch/real/',
    train_file_list='["train_sub{}".format(i) for i in range(16)]',
    valid_file_list='["cv_feiyu"]',
    meta_file="meta",
    fbank_dim=80,
    chunk_size=200,
    use_lid=False,
    fetch_block_size=200,
    bucket_schedule='50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,2000',
    bucket_schedule_key='fbank',
    batch_means_tokens=1,
    max_batch_size=10240,
    shuffle=True,
    drop_last=False,
    use_recombine=1,
    use_code_switch=1,
    use_eos=False,
    use_bpe=True,
    train_item_transform=[
        dict(type='PickleParser'),
        dict(type='BPE', use_eos=False, key='label1'),
        dict(type='BPE', use_eos=False, key='label2'),
        dict(type='CMVN', key='fbank'),
        dict(type='CMVN', key='fbank1'),
        dict(type='CMVN', key='fbank2'),
        dict(type='DynamicTimeMask', time_mask_size=20, time_mask_block=60,
             replace_with_zero=False, inplace=True, time_mask_num_dither=1, key='fbank'),
        dict(type='FreqMask', freq_mask_size=27, freq_mask_num=1,
             replace_with_zero=False, inplace=True),
        # No TimeWarp, equal to time_warp_size = -1
    ],
    valid_item_transform=[
        dict(type='PickleParser'),
        dict(type='BPE', use_eos=False, key='label1'),
        dict(type='BPE', use_eos=False, key='label2'),
        dict(type='CMVN', key='fbank'),
        dict(type='CMVN', key='fbank1'),
        dict(type='CMVN', key='fbank2'),
    ],
    batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='ListCollate', key='overlap_st'),
        dict(type='ListCollate', key='overlap_et'),
        dict(type='FbankCollate', fbank_dim=80, key='fbank'),
        dict(type='FbankCollate', fbank_dim=80, key='fbank1'),
        dict(type='FbankCollate', fbank_dim=80, key='fbank2'),
        dict(type='CharCollate', key='char1'),
        dict(type='CharCollate', key='char2'),
        dict(type='PreCharCollate', key='char1', adaptive_tgt_key='adaptive_tgt_indices1'),
        dict(type='PreCharCollate', key='char2', adaptive_tgt_key='adaptive_tgt_indices2'),
    ],
    inference_batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='FbankCollate', fbank_dim=80, key='fbank'),
        dict(type='RefLabelCollate', key='label1'),
        dict(type='RefLabelCollate', key='label2'),
    ])
project = 'tel_2ch_rnnt'
runner = 'DualChannelRunner'
solution = dict(
    type='base_rnnt_solution',
    rnnt_type='RnntDualChannelModel',
    front_end_type='VGGPosFrontEnd',
    #input_concat_size=8,
    downsampling_size=4,
    #fsmn_left_kernel_size=20,
    #fsmn_right_kernel_size=1,
    #fsmn_dilation=2,
    acoustic_backbone_type='OfflineTransformerBackbone',
    acoustic_backbone_sd_type='OfflineTransformerBackbone',
    backbone_topology='[-1]*10',
    backbone_weight_scale=1.0,
    backbone_memory_size=512,
    backbone_hidden_size=2048,
    self_attn_heads=8,
    self_attn_dropout=0.1,
    dropout=0.1,
    self_attn_activation_dropout=0,
    self_attn_layer_norm_before=1,
    self_attn_activation_fn='relu',
    head_type='RnntBaseHead',
    head_hidden_size=640,
    head_lowrank_size=512,
    predictor_type='LSTMPredictor',
    predictor_emb_size=640,
    predictor_lstm_hidden_size=1024,
    predictor_lstm_layer_num=2,
    predictor_dropout_factor=0.15,
    jointer_type='ShallowJointer',
    jointer_hidden_size=640,
    concate_U=1,
    jointer_simple_fusion=0,
    adaptive_head_size=968,
    adaptive_tail_size=200,
    adaptive_tail_groups=60,
    criterion_type='RnntDualChannelAdaptiveCE',
    cer_update_freq=100,
    label_smooth_factor=0.0,
    reorder_dict_by_freq=True,
    mask_loss=True,
    mtl_type='ctc',
    mtl_head='HybridCEHead')
work_dir = './demo'
train = dict(
    resume='latest.pth',
    resume_optimizer=True,
    max_epochs=9,
    max_iters=300000,
    lr_scheduler=dict(
        by_epoch=False,
        warmup='linear',
        warmup_iters=5000,
        warmup_ratio=0.001,
        warmup_by_epoch=False,
        policy='valid',
        gamma=0.5),
    checkpoint_config=dict(interval=10000, max_keep_ckpts=-1),
    curriculum_end_epoch=0,
    curriculum_length=520,
    #remote_save_root='hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/saved_models/dolphin/',
    save_root='./demo',
    save_dir='tel_2ch_rnnt',
    save_name='rnnt_transformer_base',
    amp_level='O1')
valid = dict(interval=10000)
inference = dict(
    test_sets='test_feiyu',
    beam_size=10,
    lm_path='',
    lm_weight=1.0,
    blk_scale=1.0,
    len_penalty_scale=0.01)
nnlm = dict(lm_type='')
optimizer = dict(
    type='FusedAdam',
    lr=0.0001,
    betas=(0.9, 0.999),
    eps=1e-08,
    weight_decay=1e-5)
optimizer_config = dict(
    grad_clip=dict(max_norm=20, norm_type=2),
    max_grad_clip=5.0,
    bmuf_config=dict(
        block=200,
        block_lr=0.5,
        block_momentum=0.9,
        warmup_steps=5000,
        average_params=True,
        use_nesterov=True))
criterion = None
super_criterion = None
log_level = 'INFO'
log_config = dict(
    interval=200,
    reset_flag=True,
    hooks=[dict(type='TensorboardLoggerHook'),
           dict(type='TextLoggerHook')])
