project = 'tel_rnnt_1B'
runner = 'TelRunner'
data = dict(
    data_root=[
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/video/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/other/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/smb_gogokid/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/feiyu/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/xingfuli/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/dongchedi/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/input/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/feiyu_9th/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/video_2nd/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/feiyu_10th/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr_2nd/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr_3rd/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/feiyu_11th/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/ivr_4th/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/caijing/tts_num/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/caijing/number_selected/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/caijing/xinshen_3rd/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/caijing/shuxiang_selected/',
        'hdfs://haruna/home/byte_arnold_hl_speech_asr/user/huanglu.thu19/datasets/dolphin/tele/xiansuotong_noise_multi_pad/',
    ],
    train_file_list=[
        '["train_sub{}".format(i) for i in range(512)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(128)]',
        '["train_sub{}".format(i) for i in range(1024)]',
        '["train_sub{}".format(i) for i in range(128)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(16)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(1024)]',
        '["train_sub{}".format(i) for i in range(64)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(256)]',
        '["train_sub{}".format(i) for i in range(8)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(24)]',
        '["train_sub{}".format(i) for i in range(32)]',
        '["train_sub{}".format(i) for i in range(4)]',
        '["train_sub{}".format(i) for i in range(8)]',
        '["train_sub{}".format(i) for i in range(256)]',
    ],
    valid_file_list=[
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
        '["cv"]',
    ],
    meta_file="meta",
    fbank_dim=80,
    global_shuffle=False,
    chunk_size=20,
    use_lid=False,
    fetch_block_size=300,
    bucket_schedule='50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,1800,1900,2000',
    bucket_schedule_val='50,100,200,300,400,500,600,700,800,900,1000,1200,1400,1600,1800,1900,2000',
    bucket_schedule_key='fbank',
    batch_means_tokens=1,
    max_batch_size='11322,11022,11089,11122,11389,11322,11389,11056,11022,10789,10022,10056,10456,10056,9050,9050,9056',
    prefetch_worker_num=6,
    next_retry=10240,
    shuffle=True,
    drop_last=False,
    use_recombine=True,
    use_code_switch=False,
    use_eos=False,
    use_bpe=True,
    train_item_transform=[
        dict(type='PickleParser'),
        dict(type='WavParser'),
        dict(type='VolumePerturbation', p=1.0),
        dict(type='KaldiFbank', dither=1.0, dynamic_dither=True),
        dict(type='LabelLengthFilter', in_out_ratio=4),
        dict(type='BPE', use_eos=False, skip_list=['<pad>']),
        dict(type='CMVN', key='fbank'),
        dict(type='AppendFeatureDim', total_dim=80),
        dict(
            type='DynamicTimeMask',
            time_mask_size=20,
            time_mask_block=60,
            replace_with_zero=False,
            inplace=True,
            time_mask_num_dither=1),
        dict(
            type='FreqMask',
            freq_mask_size=27,
            freq_mask_num=1,
            replace_with_zero=False,
            inplace=True)
    ],
    valid_item_transform=[
        dict(type='PickleParser'),
        dict(type='WavParser'),
        dict(type='KaldiFbank', dither=0.0),
        dict(type='LabelLengthFilter', in_out_ratio=4),
        dict(type='BPE', use_eos=False, skip_list=['<pad>']),
        dict(type='CMVN', key='fbank'),
        dict(type='AppendFeatureDim', total_dim=80),
    ],
    batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='FbankCollate', fbank_dim=80),
        dict(type='CharCollate', need_adapt_target=True),
        dict(type='PreCharCollate')
    ],
    inference_batch_transform=[
        dict(type='ListCollate', key='uttid'),
        dict(type='RefLabelCollate'),
        dict(type='FbankCollate', fbank_dim=80)
    ])
solution = dict(
    type='base_rnnt_solution',
    rnnt_type='BaseRnntModel',
    front_end_type='VGGPosFrontEnd',
    input_concat_size=8,
    downsampling_size=4,
    acoustic_backbone_type='OfflineTransformerBackbone',
    fused_transformer=True,
    num_chkpt_layers=0,
    squeeze_mem=True,
    backbone_topology='[[-1,-1,1]]*48',
    backbone_layer_gap=100,
    backbone_weight_scale=1.0,
    backbone_memory_size=1280,
    backbone_hidden_size=5120,
    self_attn_heads=16,
    self_attn_dropout=0.1,
    dropout=0.1,
    self_attn_activation_dropout=0,
    self_attn_layer_norm_before=1,
    self_attn_activation_fn='relu',
    head_type='RnntBaseHead',
    head_hidden_size=1024,
    head_lowrank_size=512,
    predictor_type='LSTMPredictor',
    predictor_emb_size=1024,
    predictor_lstm_hidden_size=2048,
    predictor_lstm_layer_num=3,
    predictor_dropout_factor=0.1,
    jointer_type='ShallowJointer',
    jointer_hidden_size=1024,
    concate_U=1,
    jointer_simple_fusion=0,
    adaptive_head_size=968,
    adaptive_tail_size=200,
    adaptive_tail_groups=60,
    criterion_type='RnntAdaptiveCE',
    cer_update_freq=500,
    label_smooth_factor=0.0,
    reorder_dict_by_freq=True,
    mtl_type='ctc',
    mtl_head='HybridCEHead',
    backbone_clamp_inf=True,
    mtl_clamp=True,
    head_clamp=True,
    backbone_pool_type='Conv1dTimeReduce')
work_dir = './demo'
train = dict(
    resume='latest.pth',
    resume_optimizer=True,
    grad_accum_step=4,
    lazy_init=True,
    fuse_last_bucket=8,
    max_epochs=9,
    check_loss=True,
    max_iters=2000000,
    lr_scheduler=dict(
        by_epoch=False,
        warmup='linear',
        warmup_iters=10000,
        warmup_ratio=0.001,
        warmup_by_epoch=False,
        policy='valid',
        gamma=0.85,
        key='cer',
    ),
    checkpoint_config=dict(interval=10000, max_keep_ckpts=200),
    curriculum_end_epoch=0,
    curriculum_length=520,
    save_root='./demo',
    save_dir='tele_general_20211207',
    save_name='transformer_rnnt_tele_1B_ddp',
    amp_level='O1')
valid = dict(interval=10000)
inference = dict(
    resume='latest.pth',
    test_sets='../test/tele_general_test_20191025_20000',
    beam_size=10,
    lm_path='',
    lm_weight=1.0,
    blk_scale=1.0,
    len_penalty_scale=0.01)
optimizer = dict(
    type='FusedAdam',
    lr=1e-4,
    betas=(0.9, 0.999),
    eps=1e-08,
    weight_decay=1e-3)
optimizer_config = dict(
    grad_clip=dict(max_norm=20, norm_type=2),
    max_grad_clip=5.0,
    enable_oss=True,
    )
log_config = dict(
    interval=100,)
