---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: null

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    duration: 120
    sample_rate: 24000
    lyrics_codebook_size: 400
    semantic_codebook_size: 32_768
    semantic_frame_rate: 25
    semantic_type: bestrq
    mulan_embed_dim: 512
    hidden_size: 1536
    intermediate_size: 4128
    num_hidden_layers: 24
    num_attention_heads: 12
    pretrained_path: "/mnt/bn/audio-diffusion/ducle/logs/semantic_model_instrumental_07B/sstk_eval_sft_short_umm+mix_mulan_110_2m/checkpoints/step=010000.ckpt"
    # Inference params
    semantic_temperature: 1.0
    sample_mode: "gumbel"
    beam_size: 2
    decoder_type: "diffusion"
    diffusion_steps: 10
    bf16_portion: 0.0
    # RL training params
    add_ref_to_beam: False
    ce_weight: 0.1
    seq_weight: 10
    positive_phrase: "cd quality, catchy, memorable"
    negative_phrase: "noisy, boring, forgettable"
    rewards:
        "mulan_sim": 1.0
        #"nonvocal": 1.0
        "style_text_sim": 1.0
        "loudness_sim": 1.0
        "qualitative_sim": 1.0
    # Logging params
    log_num_val_samples: 10
    log_num_val_beam_samples: 1

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_model_instrumental_07B
    version: sstk_eval_rl
    cache_dir: .module_cache/musiclm
    precision: "bf16-mixed"
    num_workers: 4
    accelerator: auto
    max_steps: 3000
    val_check_interval: 100
    batch_size: 1
    learning_rate: 1.0e-6
    warmup_steps: 50
    cycle_steps: 5000
    weight_decay: 0.05
    shuffle_buffer: 16
    gradient_clip_val: 1.0
    normalize_audio: True
    avoid_vocal: True
    max_vocal_threshold: 0.8
    text_type: "short"
    max_num_crops: 1
    crop_step_size: 30.0
    use_pipe: False
    mulan_ckpt: "/mnt/bn/audio-diffusion/mulan/ongoing/mulan-step=024600-kaggle.ckpt"
    bestrq_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/umm_stage3_music_chroma_vq32768x32/step=0030000.ckpt"
    diffusion_ckpt: "/mnt/bn/audio-diffusion/wtl/diffusion/model_14_120s_finetune/checkpoints/last.ckpt"
    vocoder_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/soundstream-step=374999-val_sdr=12.9557.ckpt"

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.instrumental.InstrumentalWebDataModule
    dataset_name: "SSTK_EVAL_US"
    val_split: "SSTK_EVAL_US"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    normalize_audio: !ref <run_opts[normalize_audio]>
    aed_filtered: False
    avoid_sound_effect: False
    avoid_vocal: !ref <run_opts[avoid_vocal]>
    max_vocal_threshold: !ref <run_opts[max_vocal_threshold]>
    text_type: !ref <run_opts[text_type]>
    max_num_crops: !ref <run_opts[max_num_crops]>
    crop_step_size: !ref <run_opts[crop_step_size]>
    use_pipe: !ref <run_opts[use_pipe]>

model_config: !new:transformers.LlamaConfig
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    hidden_size: !ref <extra_params[hidden_size]>
    intermediate_size: !ref <extra_params[intermediate_size]>
    num_hidden_layers: !ref <extra_params[num_hidden_layers]>
    num_attention_heads: !ref <extra_params[num_attention_heads]>
    hidden_act: "silu"
    max_position_embeddings: 4096
    initializer_range: 0.02
    rms_norm_eps: 1e-6
    use_cache: False
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS

model_cls: !name:samantha.models.flash_llama.LlamaForCausalLM
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.SemanticRLModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            hpath: !ref <run_opts[mulan_ckpt]>
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "g4"
        bestrq:
            hpath: !ref <run_opts[bestrq_ckpt]>
            initializer: !name:recipes.umm.requires.model_initializer.init_stage3
                cache_dir: !ref <run_opts[cache_dir]>
        sampler:
            hpath: null
            initializer: !name:recipes.diffusion.inference_from_text_lyrics2song.init_sampler
                cache_dir: !ref <run_opts[cache_dir]>
                duration: !ref <extra_params[duration]>
        diffusion:
            hpath: !ref <run_opts[diffusion_ckpt]>
            initializer: !name:recipes.diffusion.models.diffusion_model.utils.init_diffusion
                cache_dir: !ref <run_opts[cache_dir]>
        vocoder:
            hpath: !ref <run_opts[vocoder_ckpt]>
            initializer: !name:recipes.diffusion.models.vocoder_model.utils.init_vocoder
                cache_dir: !ref <run_opts[cache_dir]>
        asr:
            hpath: en_punc
            initializer: !name:recipes.bigmusic.utils.metrics_asr.init_asr

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    #- !new:pytorch_lightning.loggers.wandb.WandbLogger
    #  save_dir: !ref <run_opts[log_dir]>
    #  project: !ref <run_opts[log_name]>
    #  name: !ref <run_opts[version]>


# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 20
      save_last: True
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicDataUsageLogger
    #   save_dir: /mnt/bn/audio-diffusion/qq/data_usage_logs
    #   save_every_n_iter: 5000
    # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicAudioDataLogger
    #   sample_rate: !ref <extra_params[sample_rate]>
    #   check_interval: !ref <run_opts[val_check_interval]>
    #   examples_per_batch: 8

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 10
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 2
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: 0
    check_val_every_n_epoch: null
    num_sanity_val_steps: 0
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
