ARG REGION

FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu122 as Aliyun_VA
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu122 as US-East
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu122 as US-East-Red
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu122 as Aliyun_SG
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu122 as China-North-LF

ENV http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ENV https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ENV no_proxy="byted.org,anaconda.org"

FROM ${REGION}

LABEL maintainer="Gao Lu <gaolu.e820@bytedance.com>"

ENV PYTORCH_CUDA_ALLOC_CONF expandable_segments:True
ENV CUBLASLT_WORKSPACE_SIZE 32768
# Temporary solution, more investigation needed.
ENV NCCL_PROTO ^LL128

ENV DEBIAN_FRONTEND noninteractive
ENV LD_LIBRARY_PATH /opt/tiger/native_libhdfs/lib/native:$LD_LIBRARY_PATH
ENV ARNOLD_HDFS_NATIVE 1
ENV ARNOLD_HDFS_CELER 1
ENV INFSEC_HADOOP_ENABLED 1
ENV CPP_HDFS_CONF /opt/tiger/arnold/hdfs_client/conf/celer_us/core-site.xml:/opt/tiger/arnold/hdfs_client/conf/celer_us/hdfs-site.xml

ENV ARNOLD_SORT_IP 1
ENV NCCL_IB_QPS_PER_CONNECTION 5
ENV NCCL_IB_TIMEOUT 23
ENV SPEECH_USE_SYSTEM_TRITON 1
ENV PANTHER_PLIR_EXCLUDE_OPS batch_gemm_fwd,batch_gemm_bwd
ENV TORCH_NCCL_AVOID_RECORD_STREAMS 1

RUN apt update && \
    apt install \
        -yq --no-install-recommends \
        libucx0 \
        libmkl-rt \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        openssh-server \
        netbase \
        patchelf \
        git \
        vim \
        krb5-user \
        libcairo2-dev \
        clang-format \
        libsndfile1 \
        ffmpeg \
        tmux \
        git-lfs \
        python3-tk \
        libsndfile-dev \
        apt-transport-https \
        libpam-krb5 \
        screen \
        zip \
        espeak \
        espeak-ng \
        fonts-arphic-ukai \
        sox \
        libsox-dev && \
    cd /tmp && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && rm -f cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install -y cuda-nsight-compute-12-2 \
                   cuda-nsight-systems-12-2 \
                   libcudnn8=8.9.7.29-1+cuda12.2 \
                   libcudnn8-dev=8.9.7.29-1+cuda12.2 && \
    rm -f /usr/lib/x86_64-linux-gnu/libcudnn_*static.a && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir pip==24.0 && \
    pip3 install \
        --no-cache-dir \
        pytorch-lightning==2.2.2 \
        hyperpyyaml==1.2.0 \
        Command==0.1.0 \
        yamllint==1.26.3 \
        ninja==1.11.1 \
        PyYAML==6.0 \
        mkl==2023.1.0 \
        mkl-include==2023.1.0 \
        mkl-devel==2023.1.0 \
        cmake==3.26.3 \
        cffi==1.15.1 \
        typing==3.7.4.3 \
        typing-extensions==4.5.0 \
        future==0.18.3 \
        bytedtos==1.1.9 \
        addict==2.4.0 \
        yapf==0.33.0 \
        sox==1.4.1 \
        cython==0.29.34 \
        black==24.2.0 \
        retry==0.9.2 \
        eventlet==0.33.3 \
        cxxfilt==0.3.0 \
        pre-commit==3.6.2 \
        pre-commit-hooks==4.5.0 \
        wget==3.2 \
        pytest==7.1.2 \
        pytest-cov==3.0.0 \
        pytest-datadir==1.3.1 \
        pytest-mock==3.8.2 \
        pytest-runner==6.0.0 \
        ConfigArgParse==1.5.3 \
        pybind11==2.12.0 \
        pyahocorasick \
        lac \
        paddlepaddle==2.5.2 \
        absl-py==1.4.0 && \
    pip3 install \
        --no-cache-dir \
        antlr4-python3-runtime==4.9.* \
        webdataset==0.2.48 \
        deepspeed==0.11.1 \
        h5py==3.8.0 \
        pydub==0.25.1 \
        bytedance.easycycle==1.1.8 \
		librosa==0.9.2 \
        torchlibrosa==0.1.0 && \
    pip3 install \
        --no-cache-dir \
        pycairo==1.23.0 \
        tensorboard==2.13.0 \
        onnx==1.13.1 \
        onnxruntime==1.7.0 \
        six==1.16.0 \
        click==8.1.3 \
        flake8==7.0.0 \
        psutil==5.9.5 \
        cloudpickle==1.6.0 \
        isort==5.12.0 \
        subword-nmt==0.3.8 \
        fairseq==0.12.2 \
        scipy==1.10.1 \
        pydantic==1.10.7 \
        scikit-learn==1.2.2 \
        SoundFile==0.12.1 \
        tqdm==4.65.0 \
        PySoundFile==0.9.0.post1 \
        matplotlib==3.7.1 \
        webrtcvad==2.0.10 \
        openpyxl==3.1.2 \
        colorednoise==2.1.0 \
        torch_stft==0.1.4 \
        jieba==0.42.1 \
        pypinyin==0.48.0 \
        kaldiio==2.18.0 \
        soxbindings==1.2.3 \
        streamz==0.6.4 \
        datasets==2.5.1 \
        byted-janus==0.1.6.post6 \
        torchaudio-augmentations==0.2.1 \
        einops==0.6.1 \
        zhon==1.1.5

ARG CRUISE_VERSION=1.0.0.2808
ARG PANTHER_VERSION=1.7.14.256
ARG FALCONCLAW_VERSION=1.0.5.129
ARG ONNX_VERSION=1.0.0.22
ARG OPENFST_VERSION=1.0.0.8
ARG ASR_EVAL_TOOL_VERSION=1.0.0.125
ARG SPEECH_EVALS_VERSION=1.0.0.14
ARG I18N_TEXT_FORMAT_VERSION=1.0.0.112
ARG S3A_VERSION=1.0.0.58
ARG DATALOADER_VERSION=1.0.0.160
ARG BUMI_VERSION=1.2.1.14
ARG TRITON_VERSION=1.0.0.6
ARG MARIANA_FMHA_PLUS_VERSION=1.0.0.17
# https://github.com/facebookresearch/xformers.git:6425fd0
ARG XFORMERS_VERSION=1.0.0.7
# https://github.com/google-research/bleurt.git:cebe7e6
ARG BLEURT_VERSION=1.0.0.5
# https://github.com/NVIDIA/apex.git:23c1f86
ARG APEX_VERSION=1.0.0.2

# 2. install falconclaw && panther && dataloader
RUN \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/data.aml.cruise_$CRUISE_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.openfst_python_$OPENFST_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.falconclaw_$FALCONCLAW_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/seed.speech.bumi_$BUMI_VERSION.tar.gz && \
    cd /tmp && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    tar -xvf lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        tf2onnx-1.9.3-py3-none-any.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    tar -xvf lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        *torch*/panther_gpu*.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.arnold.dataloader_$DATALOADER_VERSION.tar.gz && \
    tar -xvf lab.arnold.dataloader_$DATALOADER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        byted_dataloader*cp39*.whl && \
    strip -g /usr/local/lib/python3.9/dist-packages/openfst_python/*.so* && \
    rm -rf /tmp/* /root/.cache

# install s3a
RUN pip3 uninstall -y s3a \
    && wget http://luban-source.byted.org/repository/scm/lab_audio.seed.s3a_$S3A_VERSION.tar.gz \
    && mkdir tmp.s3a \
    && tar -xvf lab_audio.seed.s3a_$S3A_VERSION.tar.gz -C tmp.s3a \
    && pip3 install --no-cache-dir tmp.s3a/s3a-0.0.1-cp39-cp39-linux_x86_64.whl \
    && rm -fr tmp.s3a lab_audio.seed.s3a_$S3A_VERSION.tar.gz

# install mariana related dependencies
RUN pip3 install --no-cache-dir bytedfeather==0.2.0 rich==13.3.5 sentencepiece==0.1.99

# 3. install asr_eval_tool
RUN \
    mkdir -p /tmp/py_pkg.asr_eval_tool && \
    cd /tmp/py_pkg.asr_eval_tool && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    tar -xvf lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    rm lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    cd src/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd ../.. && \
    python3 setup.py bdist_wheel && \
    pip3 install --no-cache-dir --force-reinstall dist/asr_eval_tool-$ASR_EVAL_TOOL_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.asr_eval_tool

# install speech_evals
RUN \
    mkdir -p /tmp/py_pkg.speech_evals && \
    cd /tmp/py_pkg.speech_evals && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    tar -xvf lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    rm lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    cd speech_evals/lib/process/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd /tmp/py_pkg.speech_evals && \
    python3 setup.py bdist_wheel && \
    pip3 install --no-cache-dir --force-reinstall dist/speech_evals-$SPEECH_EVALS_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.speech_evals

# install flash_attn_plus
RUN \
    mkdir -p /tmp/py_mariana_fmha_plus && \
    cd /tmp/py_mariana_fmha_plus && \
    wget http://luban-source.byted.org/repository/scm/data.speech.flash_attn_plus_$MARIANA_FMHA_PLUS_VERSION.tar.gz && \
    tar -zxf data.speech.flash_attn_plus_$MARIANA_FMHA_PLUS_VERSION.tar.gz && \
    pip3 install --no-cache-dir --no-deps fmha_plus*.whl && \
    rm -rf /tmp/py_mariana_fmha_plus

# install xformers
# RUN git clone https://github.com/facebookresearch/xformers.git && cd xformers && git checkout 6425fd0cacb1a6579aa2f0c4a570b737cb10e9c3 \
#     && git submodule update --init --recursive && cd .. \
#     && XFORMERS_DISABLE_FLASH_ATTN=1 pip3 install -v --disable-pip-version-check --no-cache-dir ./xformers \
#     && rm -rf ./xformers
RUN mkdir -p /tmp/py_xformers && \
    cd /tmp/py_xformers && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$XFORMERS_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$XFORMERS_VERSION.tar.gz && \
    pip3 install --no-cache-dir xformers*.whl && \
    rm -rf /tmp/py_xformers

# 4. add tools and env
# 4.1 HDFS env
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"
# 4.2 ssh config
RUN mkdir -p /var/run/sshd && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config
# 4.3 for kinit
ADD ./scripts/krb5.conf /etc/krb5.conf

RUN pip3 uninstall -y pyarrow && pip3 install --no-cache-dir fsspec==2023.6.0 pyarrow==12.0.0 && \
    pip3 install --no-cache-dir ruamel.yaml==0.17.24

RUN pip3 install \
        --no-cache-dir \
        --index-url https://bytedpypi.byted.org/simple \
        ffmpeg-python \
        jsonschema \
        attrs==23.1.0 \
        nltk \
        fire \
        mypy \
        lz4 \
        bytedredis \
        rouge \
        pexpect \
        bytedlaplace \
        blobfile \
        langdetect \
        openai \
        tiktoken \
        langchain \
        backoff \
        pyzstd \
        accelerate==0.31.0 && \
    pip3 install \
        --no-cache-dir \
        --index-url https://bytedpypi.byted.org/simple \
        easydict \
        sacrebleu \
        editdistance \
        torch_complex \
        omegaconf \
        pyvad \
        peft \
        ipython \
        phonemizer \
        pyworld \
        Path \
        coqpit \
        trainer \
        pot \
        rotary_embedding_torch \
        vector_quantize_pytorch \
        jiwer \
        mir_eval \
        soft-moe-pytorch \
        tensorflow_io \
        speechbrain \
        thriftpy2==0.4.16

# Transformer Engine
# flash-attn incompatable, test required.
# RUN pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

# Install bleurt.
# RUN pip3 install unbabel-comet && \
#     cd /opt/tiger && \
#     rm -rf bleurt && \
#     git clone https://github.com/google-research/bleurt.git && \
#     cd bleurt && \
#     pip3 install . && \
#     pip3 install protobuf==3.20.0 && \
#     pip3 install jsonargparse==4.14.1 && \
#     pip3 install transformers==4.35.0
RUN mkdir -p /tmp/py_bleurt && \
    cd /tmp/py_bleurt && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$BLEURT_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$BLEURT_VERSION.tar.gz && \
    pip3 install --no-cache-dir BLEURT*.whl && \
    pip3 install protobuf==3.20.0 && \
    pip3 install jsonargparse==4.14.1 && \
    pip3 install transformers==4.35.0 && \
    rm -rf /tmp/py_bleurt

# Add apex
# RUN export MAX_JOBS=32 && \
#     git clone https://github.com/NVIDIA/apex.git && \
#     cd apex && sed -i 's|check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)||g' setup.py && \
#     pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
#     cd .. && \
#     rm -rf apex
RUN mkdir -p /tmp/py_apex && \
    cd /tmp/py_apex && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$APEX_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$APEX_VERSION.tar.gz && \
    pip3 install --no-cache-dir apex*.whl && \
    rm -rf /tmp/py_apex

RUN pip3 install --no-cache-dir mpi4py

# Install triton 3.0 which well performs on H800
RUN mkdir -p /tmp/py_triton && \
    cd /tmp/py_triton && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.triton_$TRITON_VERSION.tar.gz && \
    tar -xvf seed.speech.triton_$TRITON_VERSION.tar.gz && \
    pip3 uninstall -y pytorch-triton && \
    pip3 install --no-cache-dir triton*.whl && \
    rm -rf /tmp/py_triton /root/.cache

# Upgrade Python Pillow
RUN pip install --upgrade "pillow>=10.0.1"

# INSTALL AWS RELATED LIBS
ARG EFA_INSTALLER_VERSION=1.29.0
ARG AWS_OFI_NCCL_VERSION=v1.7.4-aws

RUN apt update -y \
    && apt purge -y \
        libmlx5-1 \
        ibverbs-utils \
        libibverbs-dev \
        libibverbs1 \
    && apt install -y --allow-unauthenticated \
        kmod \
        build-essential \
        curl \
        autoconf \
        libtool \
        gdb \
        automake \
        python3-distutils \
        cmake \
        pciutils \
        libopenmpi-dev \
        environment-modules \
        tcl \
        libnl-3-200 \
        libnl-3-dev \
        libnl-route-3-200 \
        libnl-route-3-dev \
        dkms \
    && rm -rf /var/lib/apt/lists/*

RUN cd $HOME \
    && curl -O "https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz" \
    && tar -xf $HOME/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz \
    && cd aws-efa-installer \
    && apt install -y ./DEBS/UBUNTU2004/x86_64/rdma-core/*.deb \
    && apt install -y ./DEBS/UBUNTU2004/x86_64/*.deb \
    && cd - \
    && rm -fr aws-efa-installer $HOME/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz

## INSTALL AWS-OFI-NCCL PLUGIN
#
# The plugin is NOT enabled by default. You need to add `/opt/amazon/efa/lib` to
# LD_LIBRARY_PATH yourself.
RUN git clone "https://github.com/aws/aws-ofi-nccl.git" /opt/aws-ofi-nccl \
    && cd /opt/aws-ofi-nccl \
    && git checkout ${AWS_OFI_NCCL_VERSION} \
    && ./autogen.sh \
    && ./configure --prefix=/opt/amazon/efa/ \
       --with-libfabric=/opt/amazon/efa/ \
       --with-cuda=/usr/local/cuda \
       --with-mpi=/opt/amazon/openmpi/ \
       --enable-platform-aws \
    && make && make install \
    && rm -fr /opt/aws-ofi-nccl \
    && rm -rf /etc/ld.so.conf.d/efa.conf && ldconfig

# Samantha-specific settings.
COPY ./scripts/samantha.bashrc /etc/samantha.bashrc
ENV BASH_ENV=/etc/samantha.bashrc

# hack for pl 2.2 requires wandb>=0.12.10
COPY ./scripts/setup_wandb.sh .
RUN bash ./setup_wandb.sh
