ARG REGION

FROM aliyun-va-hub.byted.org/compile/seed.speech.pytorch2:159c9e2f0fb158d293de72e25644d07b as aliyun_va
FROM use-hub.byted.org/compile/seed.speech.pytorch2:159c9e2f0fb158d293de72e25644d07b as us-east
FROM hub.tiktoke.org/compile/seed.speech.pytorch2:159c9e2f0fb158d293de72e25644d07b as us-east-red
FROM aliyun-sin-hub.byted.org/compile/seed.speech.pytorch2:159c9e2f0fb158d293de72e25644d07b as aliyun_sg
FROM hub.byted.org/compile/seed.speech.pytorch2:159c9e2f0fb158d293de72e25644d07b as china-north-lf

ENV http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ENV https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ENV no_proxy="byted.org,anaconda.org"

FROM ${REGION}

# multi-stage build, env are independent; hdfs-stdenv need env $REGION;
ARG REGION

ENV PYTORCH_CUDA_ALLOC_CONF expandable_segments:True
ENV CUBLASLT_WORKSPACE_SIZE 32768
# Temporary solution, more investigation needed.
# ENV NCCL_PROTO ^LL128

ENV DEBIAN_FRONTEND noninteractive
ENV LD_LIBRARY_PATH /opt/tiger/native_libhdfs/lib/native:$LD_LIBRARY_PATH
ENV ARNOLD_HDFS_NATIVE 1
ENV ARNOLD_HDFS_CELER 1
ENV INFSEC_HADOOP_ENABLED 1
ENV CPP_HDFS_CONF /opt/tiger/arnold/hdfs_client/conf/celer_us/core-site.xml:/opt/tiger/arnold/hdfs_client/conf/celer_us/hdfs-site.xml

ENV ARNOLD_SORT_IP 1
ENV NCCL_IB_QPS_PER_CONNECTION 5
ENV NCCL_IB_TIMEOUT 23
ENV SPEECH_USE_SYSTEM_TRITON 1
ENV PANTHER_PLIR_EXCLUDE_OPS batch_gemm_fwd,batch_gemm_bwd
ENV TORCH_NCCL_AVOID_RECORD_STREAMS 1

ARG CRUISE_VERSION=1.0.0.3341
ARG PANTHER_VERSION=1.7.14.312
ARG OPENFST_VERSION=1.0.0.8
ARG ASR_EVAL_TOOL_VERSION=1.0.0.125
# For torch 2.4
ARG SPEECH_EVALS_VERSION=1.0.0.34
ARG I18N_TEXT_FORMAT_VERSION=1.0.0.112
ARG S3A_VERSION=1.0.0.5
ARG BUMI_VERSION=1.4.0.14
ARG TRITON_VERSION=1.0.0.102
ARG MARIANA_FMHA_PLUS_VERSION=1.0.0.18
# https://github.com/facebookresearch/xformers.git:6425fd0
ARG XFORMERS_VERSION=1.0.0.15
# https://github.com/google-research/bleurt.git:cebe7e6
ARG BLEURT_VERSION=1.0.0.14
# https://github.com/NVIDIA/apex.git:23c1f86
ARG APEX_VERSION=1.0.0.12
# https://code.byted.org/security/bytedkms
ARG BYTEDKMS_VERSION=1.0.0.16
# libsox.so
ARG LIBSOX_VERSION=1.0.0.18

RUN apt-get update && \
    apt-get install \
        -yq --no-install-recommends \
        libc6 \
        libucx0 \
        libmkl-rt \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        openssh-server \
        netbase \
        patchelf \
        git \
        vim \
        krb5-user \
        libcairo2-dev \
        clang-format \
        libsndfile1 \
        ffmpeg \
        tmux \
        git-lfs \
        python3-tk \
        libsndfile-dev \
        apt-transport-https \
        libpam-krb5 \
        screen \
        zip \
        espeak \
        espeak-ng \
        fonts-arphic-ukai \
        sox \
        libsox-dev \
        iproute2 \
        elfutils && \
    cd /tmp && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && rm -f cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-nsight-compute-12-4 \
                   cuda-nsight-systems-12-4 && \
    rm -f /usr/lib/x86_64-linux-gnu/libcudnn_*static.a && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install pip==24.0 && \
    pip3 install \
        --no-cache-dir \
        hyperpyyaml==1.2.0 \
        Command==0.1.0 \
        yamllint==1.26.3 \
        ninja==1.11.1 \
        PyYAML==6.0 \
        mkl==2023.1.0 \
        mkl-include==2023.1.0 \
        mkl-devel==2023.1.0 \
        cmake==3.26.3 \
        cffi==1.15.1 \
        typing==3.7.4.3 \
        typing-extensions==4.5.0 \
        future==0.18.3 \
        bytedtos==1.1.9 \
        addict==2.4.0 \
        yapf==0.33.0 \
        sox==1.4.1 \
        cython==0.29.34 \
        black==24.2.0 \
        retry==0.9.2 \
        eventlet==0.33.3 \
        cxxfilt==0.3.0 \
        pre-commit==3.6.2 \
        pre-commit-hooks==4.5.0 \
        wget==3.2 \
        pytest==7.1.2 \
        pytest-cov==3.0.0 \
        pytest-datadir==1.3.1 \
        pytest-mock==3.8.2 \
        pytest-runner==6.0.0 \
        ConfigArgParse==1.5.3 \
        pybind11==2.12.0 \
        pyahocorasick \
        lac \
        paddlepaddle==2.5.2 \
        absl-py==1.4.0 && \
    pip3 install \
        --no-cache-dir \
        antlr4-python3-runtime==4.9.* \
        webdataset==0.2.48 \
        deepspeed \
        h5py==3.8.0 \
        pydub==0.25.1 \
        bytedance.easycycle==1.1.29 \
		librosa==0.9.2 \
        torchlibrosa && \
    pip3 install \
        --no-cache-dir \
        pycairo==1.23.0 \
        tensorboard==2.13.0 \
        onnx \
        onnxruntime \
        six==1.16.0 \
        click==8.1.3 \
        flake8==7.0.0 \
        psutil==5.9.5 \
        cloudpickle==1.6.0 \
        isort==5.12.0 \
        subword-nmt==0.3.8 \
        fairseq==0.12.2 \
        scipy==1.10.1 \
        pydantic==1.10.7 \
        scikit-learn==1.2.2 \
        SoundFile==0.12.1 \
        tqdm==4.65.0 \
        PySoundFile==0.9.0.post1 \
        matplotlib==3.7.1 \
        webrtcvad==2.0.10 \
        openpyxl==3.1.2 \
        colorednoise==2.1.0 \
        torch_stft \
        jieba==0.42.1 \
        pypinyin==0.48.0 \
        kaldiio==2.18.0 \
        soxbindings==1.2.3 \
        streamz==0.6.4 \
        datasets==2.5.1 \
        byted-janus==0.1.6.post6 \
        torchaudio-augmentations \
        einops==0.6.1 \
        zhon==1.1.5 && \
    pip3 install \
        --no-cache-dir \
        byted-omnistore \
        byted-dataloader==0.5.4 \
        emoji \
        zhconv

RUN pip3 install \
        --no-cache-dir \
        pytorch-lightning==2.4.0 \
        py-spy \
        gpustat

# 2. install falconclaw && panther && dataloader
# install bytedkms==3.2.10, bytedkms must installed before cruise.
RUN \
    mkdir -p /tmp/py_bytedkms && \
    cd /tmp/py_bytedkms && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$BYTEDKMS_VERSION.tar.gz && \
    tar -zxf seed.speech.scm_packer_$BYTEDKMS_VERSION.tar.gz && \
    pip3 install --no-cache-dir --no-deps bytedkms*.whl && \
    rm -rf /tmp/py_bytedkms

RUN pip3 install --no-cache-dir --use-pep517 \
        http://luban-source.byted.org/repository/scm/data.aml.cruise_$CRUISE_VERSION.tar.gz

RUN pip3 install --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.openfst_python_$OPENFST_VERSION.tar.gz

RUN pip3 install --no-cache-dir \
        http://luban-source.byted.org/repository/scm/seed.speech.bumi_$BUMI_VERSION.tar.gz

RUN mkdir -p /tmp/py_pkg.panther && \
    cd /tmp/py_pkg.panther && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    tar -xvf lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    pip3 install --no-cache-dir *torch*/panther_gpu*.whl && \
    rm -rf /tmp/* /root/.cache

RUN pip3 uninstall -y s3a \
    && wget http://luban-source.byted.org/repository/scm/lab_audio.seed.s3a_torch24_$S3A_VERSION.tar.gz \
    && mkdir tmp.s3a \
    && tar -xvf lab_audio.seed.s3a_torch24_$S3A_VERSION.tar.gz -C tmp.s3a \
    && pip3 install --no-cache-dir tmp.s3a/s3a-$S3A_VERSION-cp311-cp311-linux_x86_64.whl \
    && rm -fr tmp.s3a lab_audio.seed.s3a_torch24_$S3A_VERSION.tar.gz

# install mariana related dependencies
RUN pip3 install --no-cache-dir bytedfeather==0.2.0 rich==13.3.5 sentencepiece==0.1.99

# 3. install asr_eval_tool
RUN \
    mkdir -p /tmp/py_pkg.asr_eval_tool && \
    cd /tmp/py_pkg.asr_eval_tool && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    tar -xvf lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    rm lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    cd src/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd ../.. && \
    python3 setup.py bdist_wheel && \
    pip3 install --no-cache-dir --force-reinstall dist/asr_eval_tool-$ASR_EVAL_TOOL_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.asr_eval_tool

# install speech_evals
RUN \
    mkdir -p /tmp/py_pkg.speech_evals && \
    cd /tmp/py_pkg.speech_evals && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    tar -xvf lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    rm lab.speech.speech_evals_$SPEECH_EVALS_VERSION.tar.gz && \
    cd speech_evals/lib/process/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd /tmp/py_pkg.speech_evals && \
    python3 setup.py bdist_wheel && \
    pip3 install --no-cache-dir --force-reinstall dist/speech_evals-$SPEECH_EVALS_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.speech_evals

# install flash_attn_plus
RUN \
    mkdir -p /tmp/py_mariana_fmha_plus && \
    cd /tmp/py_mariana_fmha_plus && \
    wget http://luban-source.byted.org/repository/scm/data.speech.flash_attn_plus_$MARIANA_FMHA_PLUS_VERSION.tar.gz && \
    tar -zxf data.speech.flash_attn_plus_$MARIANA_FMHA_PLUS_VERSION.tar.gz && \
    pip3 install --no-cache-dir --no-deps fmha_plus*.whl && \
    rm -rf /tmp/py_mariana_fmha_plus

# install xformers
RUN mkdir -p /tmp/py_xformers && \
    cd /tmp/py_xformers && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$XFORMERS_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$XFORMERS_VERSION.tar.gz && \
    pip3 install --no-cache-dir xformers*.whl && \
    rm -rf /tmp/py_xformers

# 4. add tools and env
# 4.1 HDFS env
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"
# 4.2 ssh config
RUN mkdir -p /var/run/sshd && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config
# 4.3 for kinit
ADD ./scripts/krb5.conf /etc/krb5.conf

RUN pip3 uninstall -y pyarrow && pip3 install --no-cache-dir fsspec==2023.6.0 pyarrow==12.0.0 && \
    pip3 install --no-cache-dir ruamel.yaml==0.17.24

RUN pip3 install \
        --no-cache-dir \
        --index-url https://bytedpypi.byted.org/simple \
        ffmpeg-python \
        jsonschema \
        attrs \
        nltk \
        fire \
        mypy \
        lz4 \
        bytedredis \
        rouge \
        pexpect \
        blobfile \
        langdetect \
        openai \
        tiktoken \
        langchain \
        backoff \
        pyzstd \
        accelerate
RUN pip3 install \
        --no-cache-dir \
        --index-url https://bytedpypi.byted.org/simple \
        easydict \
        sacrebleu \
        editdistance \
        torch_complex \
        omegaconf==2.3.0 \
        hydra-core==1.3.2 \
        pyvad \
        peft \
        ipython \
        phonemizer \
        pyworld \
        Path \
        coqpit \
        trainer \
        pot \
        rotary_embedding_torch \
        vector_quantize_pytorch \
        jiwer \
        mir_eval \
        soft-moe-pytorch \
        tensorflow_io \
        speechbrain \
        thriftpy2==0.4.16

# Install bleurt.
RUN mkdir -p /tmp/py_bleurt && \
    cd /tmp/py_bleurt && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$BLEURT_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$BLEURT_VERSION.tar.gz && \
    pip3 install --no-cache-dir BLEURT*.whl && \
    pip3 install protobuf==3.20.0 && \
    pip3 install jsonargparse==4.14.1 && \
    pip3 install transformers==4.35.0 && \
    rm -rf /tmp/py_bleurt

# Add apex
RUN mkdir -p /tmp/py_apex && \
    cd /tmp/py_apex && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$APEX_VERSION.tar.gz && \
    tar -xvzf seed.speech.scm_packer_$APEX_VERSION.tar.gz && \
    pip3 install --no-cache-dir apex*.whl && \
    rm -rf /tmp/py_apex

RUN pip3 install --no-cache-dir mpi4py

# Install triton 3.0 which well performs on H800
RUN mkdir -p /tmp/py_triton && \
    cd /tmp/py_triton && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.triton_$TRITON_VERSION.tar.gz && \
    tar -xvf seed.speech.triton_$TRITON_VERSION.tar.gz && \
    pip3 uninstall -y pytorch-triton && \
    pip3 install --no-cache-dir triton*.whl && \
    rm -rf /tmp/py_triton /root/.cache

# Upgrade Python Pillow
RUN pip install --upgrade "pillow>=10.0.1"
RUN pip3 install \
        --no-cache-dir \
        --index-url https://bytedpypi.byted.org/simple \
        huggingface-hub==0.24.6

# Fix libsox.so issue.
RUN \
    mkdir -p /tmp/libsox && \
    cd /tmp/libsox && \
    wget http://luban-source.byted.org/repository/scm/seed.speech.scm_packer_$LIBSOX_VERSION.tar.gz && \
    tar -zxf seed.speech.scm_packer_$LIBSOX_VERSION.tar.gz && \
    rm /usr/lib/x86_64-linux-gnu/libsox.so && \
    mv libsox.so /usr/lib/x86_64-linux-gnu/libsox.so && \
    rm -rf /tmp/libsox

# Samantha-specific settings.
COPY ./scripts/samantha.bashrc /etc/samantha.bashrc
ENV BASH_ENV=/etc/samantha.bashrc

# hack for pl 2.2 requires wandb>=0.12.10
RUN pip3 install byted_wandb
COPY ./scripts/setup_wandb_311.sh .
RUN bash ./setup_wandb_311.sh

# Make debugging easier.
COPY ./scripts/scm_install.py /usr/bin/scm_install
RUN chmod +x /usr/bin/scm_install
