ARG REGION

FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu118 as Aliyun_VA
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu118 as US-East
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu118 as US-East-Red
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu118 as Aliyun_SG
FROM hub.byted.org/base/lab.pytorch2.staging:v2.1.0.u9.cu118 as China-North-LF

ENV LD_LIBRARY_PATH /opt/tiger/native_libhdfs/lib/native:$LD_LIBRARY_PATH
ENV ARNOLD_HDFS_NATIVE 1
ENV ARNOLD_HDFS_CELER 1
ENV INFSEC_HADOOP_ENABLED 1
ENV CPP_HDFS_CONF /opt/tiger/arnold/hdfs_client/conf/celer_us/core-site.xml:/opt/tiger/arnold/hdfs_client/conf/celer_us/hdfs-site.xml
ENV TORCH_CUDNN_V8_API_LRU_CACHE_LIMIT 100000

FROM ${REGION}
LABEL maintainer="Gao Lu <gaolu.e820@bytedance.com>"

ARG http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG https_proxy="http://sys-proxy-rd-relay.byted.org:8118"
ARG no_proxy="byted.org"
ENV DEBIAN_FRONTEND noninteractive

RUN pip3 uninstall -y pytorch-triton

RUN apt update && \
    apt install \
        -yq --no-install-recommends \
        libmkl-rt \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        openssh-server \
        netbase patchelf \
        git vim krb5-user \
        libcairo2-dev \
        clang-format \
        libsndfile1 ffmpeg tmux \
        git-lfs python3-tk \
        libsndfile-dev sox libsox-dev && \
    cd /tmp && \
    wget \
        https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    rm -f cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install -y cuda-nsight-systems-11-7 && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install \
        --no-cache-dir \
        pip --upgrade && \
    pip3 install \
        --no-cache-dir \
        pytorch-lightning==2.0.0 \
        hyperpyyaml==1.2.0 \
        Command==0.1.0 \
        yamllint==1.26.3 \
        ninja==1.11.1 \
        PyYAML==6.0 \
        mkl==2023.1.0 \
        mkl-include==2023.1.0 \
        mkl-devel==2023.1.0 \
        cmake==3.26.3 \
        cffi==1.15.1 \
        typing==3.7.4.3 \
        typing-extensions==4.5.0 \
        future==0.18.3 \
        bytedtos==1.1.9 \
        addict==2.4.0 \
        yapf==0.33.0 \
        sox==1.4.1 \
        cython==0.29.34 \
        black==22.10.0 \
        fairseq==0.12.2 \
        retry==0.9.2 \
        eventlet==0.33.3 \
        cxxfilt==0.3.0 \
        pre-commit==2.21.0 \
        wget==3.2 \
        pytest==7.1.2 \
        pytest-cov==3.0.0 \
        pytest-datadir==1.3.1 \
        pytest-mock==3.8.2 \
        pytest-runner==6.0.0 \
        ConfigArgParse==1.5.3 \
        absl-py==1.4.0 && \
    pip3 install \
        --no-cache-dir \
        antlr4-python3-runtime==4.9.* \
        webdataset==0.2.48 \
        deepspeed==0.11.1 \
        h5py==3.8.0 \
        pydub==0.25.1 \
        bytedance.easycycle==1.1.0.post7 \
		librosa==0.9.2 \
        torchlibrosa==0.1.0 && \
    pip3 install \
        --no-cache-dir \
        pycairo==1.23.0 \
        tensorboard==2.13.0 \
        onnx==1.13.1 \
        onnxruntime==1.7.0 \
        six==1.16.0 \
        click==8.1.3 \
        flake8==4.0.1 \
        dataclasses==0.6 \
        psutil==5.9.5 \
        cloudpickle==1.6.0 \
        isort==5.10.1 \
        subword-nmt==0.3.8 \
        fairseq==0.12.2 \
        scipy==1.10.1 \
        pydantic==1.10.7 \
        scikit-learn==1.2.2 \
        SoundFile==0.12.1 \
        tqdm==4.65.0 \
        PySoundFile==0.9.0.post1 \
        matplotlib==3.7.1 \
        webrtcvad==2.0.10 \
        openpyxl==3.1.2 \
        transformers==4.35.0 \
        colorednoise==2.1.0 \
        torch_stft==0.1.4 \
        jieba==0.42.1 \
        pypinyin==0.48.0 \
        kaldiio==2.18.0 \
        soxbindings==1.2.3 \
        streamz==0.6.4 \
        datasets==2.5.1 \
        byted-janus==0.1.6.post6 \
        torchaudio-augmentations==0.2.1 \
        einops==0.6.1 \
        zhon==1.1.5

ARG CRUISE_VERSION=1.0.0.2007
ARG PANTHER_VERSION=1.7.11.98
ARG FALCONCLAW_VERSION=1.0.5.129
ARG ONNX_VERSION=1.0.0.22
ARG OPENFST_VERSION=1.0.0.8
ARG ASR_EVAL_TOOL_VERSION=1.0.0.87
ARG I18N_TEXT_FORMAT_VERSION=1.0.0.95
ARG S3A_VERSION=1.0.0.41
ARG DATALOADER_VERSION=1.0.0.160

# 2. install falconclaw && panther && dataloader
RUN \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/data.aml.cruise_$CRUISE_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.openfst_python_$OPENFST_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        http://luban-source.byted.org/repository/scm/lab.speech.falconclaw_$FALCONCLAW_VERSION.tar.gz && \
    cd /tmp && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    tar -xvf lab.speech.tensorflow_onnx_panther_$ONNX_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        tf2onnx-1.9.3-py3-none-any.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    tar -xvf lab.speech.panther_arnold_$PANTHER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        *torch*/panther_gpu*.whl && \
    wget http://luban-source.byted.org/repository/scm/lab.arnold.dataloader_$DATALOADER_VERSION.tar.gz && \
    tar -xvf lab.arnold.dataloader_$DATALOADER_VERSION.tar.gz && \
    pip3 install \
        --no-cache-dir \
        byted_dataloader*cp39*.whl && \
    strip -g /usr/local/lib/python3.9/dist-packages/openfst_python/*.so* && \
    rm -rf /tmp/* /root/.cache

# install s3a
RUN pip3 uninstall -y s3a \
    && wget http://luban-source.byted.org/repository/scm/lab_audio.seed.s3a_$S3A_VERSION.tar.gz \
    && mkdir tmp.s3a \
    && tar -xvf lab_audio.seed.s3a_$S3A_VERSION.tar.gz -C tmp.s3a \
    && pip3 install --no-cache-dir tmp.s3a/s3a-0.0.1-cp39-cp39-linux_x86_64.whl \
    && rm -fr tmp.s3a lab_audio.seed.s3a_$S3A_VERSION.tar.gz

# install mariana related dependencies
RUN pip3 install --no-cache-dir bytedfeather==0.2.0 rich==13.3.5 sentencepiece==0.1.99

# 3. install asr_eval_tool
RUN \
    mkdir -p /tmp/py_pkg.asr_eval_tool && \
    cd /tmp/py_pkg.asr_eval_tool && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    tar -xvf lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    rm lab.speech.asr_eval_tool_$ASR_EVAL_TOOL_VERSION.tar.gz && \
    cd src/I18N_text_format && \
    wget http://luban-source.byted.org/repository/scm/lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    tar -xvf lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    rm lab.speech.I18N_text_format_$I18N_TEXT_FORMAT_VERSION.tar.gz && \
    touch __init__.py && \
    cd ../.. && \
    python3 setup.py bdist_wheel && \
    pip3 install --no-cache-dir --force-reinstall dist/asr_eval_tool-$ASR_EVAL_TOOL_VERSION-py3-none-any.whl && \
    rm -rf /tmp/py_pkg.asr_eval_tool

# install xformers
RUN git clone https://github.com/facebookresearch/xformers.git && cd xformers && git checkout 6425fd0cacb1a6579aa2f0c4a570b737cb10e9c3 \
    && git submodule update --init --recursive && cd .. \
    && XFORMERS_DISABLE_FLASH_ATTN=1 pip3 install -v --disable-pip-version-check --no-cache-dir ./xformers \
    && rm -rf ./xformers

# 4. add tools and env
# 4.1 HDFS env
ENV LIBHDFS_OPTS "-Xms4g -Xmx16g -Dhadoop.root.logger=${HADOOP_ROOT_LOGGER:-ERROR,console}"
# 4.2 ssh config
RUN mkdir -p /var/run/sshd && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config
# 4.3 for kinit
ADD ./scripts/krb5.conf /etc/krb5.conf

# uninstall triton for issues:
# triton was installed by xformers, but we have pytorch-triton instead.
# howerver, uninstall triton would remove triton's lib, we must force reinstall it
# TODO: fix it with xfromers

RUN pip3 uninstall -y pyarrow && pip3 install --no-cache-dir fsspec==2023.6.0 pyarrow==12.0.0 && \
    pip3 install --no-cache-dir ruamel.yaml==0.17.24

RUN pip3 install \
    --no-cache-dir \
    --index-url https://bytedpypi.byted.org/simple \
    ffmpeg-python \
    jsonschema \
    attrs==23.1.0 \
    nltk \
    fire \
    mypy \
    lz4 \
    bytedredis \
    rouge \
    pexpect \
    bytedlaplace \
    blobfile \
    langdetect \
    openai \
    tiktoken \
    langchain \
    backoff \
    pyzstd \
    accelerate

################### AWS #########################
ARG EFA_INSTALLER_VERSION=1.27.0
ARG AWS_OFI_NCCL_VERSION=aws
ARG NCCL_TESTS_VERSION=v2.19.3-1

RUN apt-get update -y \
    && apt-get purge -y libmlx5-1 ibverbs-utils libibverbs-dev libibverbs1 \
    && apt-get update -y \
    && apt-get install -y --allow-unauthenticated \
    git \
    gcc \
    vim \
    kmod \
    openssh-client \
    openssh-server \
    build-essential \
    curl \
    autoconf \
    libtool \
    gdb \
    automake \
    python3-distutils \
    cmake \
    pciutils \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -y && apt install -y libopenmpi-dev
RUN pip install mpi4py

RUN apt-get update -y && apt-get install -y environment-modules tcl libnl-3-200 libnl-3-dev libnl-route-3-200 libnl-route-3-dev

RUN cd $HOME \
    && curl -O "https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz" \
    && tar -xf $HOME/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz \
    && cd aws-efa-installer \
    && apt install -y ./DEBS/UBUNTU2004/x86_64/rdma-core/*.deb \
    && apt install -y ./DEBS/UBUNTU2004/x86_64/*.deb \
    && cd - \
    && rm -fr aws-efa-installer $HOME/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz


###################################################
## Install NCCL
RUN git clone --branch ${NCCL_TESTS_VERSION} --depth 1 "https://github.com/NVIDIA/nccl.git" /opt/nccl \
    && cd /opt/nccl \
    && make -j src.build CUDA_HOME=/usr/local/cuda \
    NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_60,code=sm_60"

###################################################
## Install AWS-OFI-NCCL plugin
RUN git clone "https://github.com/aws/aws-ofi-nccl.git" /opt/aws-ofi-nccl \
    && cd /opt/aws-ofi-nccl \
    && git checkout ${AWS_OFI_NCCL_VERSION} \
    && ./autogen.sh \
    && ./configure --prefix=/opt/aws-ofi-nccl/install \
       --with-libfabric=/opt/amazon/efa/ \
       --with-cuda=/usr/local/cuda \
       --with-mpi=/opt/amazon/openmpi/ \
       --enable-platform-aws \
    && make && make install
