---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
run_opts:
  fast_dev_run: False
  precision: 16-mixed
  accelerator: 'auto'
  batch_size: 16

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
train_params:
  learning_rate: 0.0001
  scheduler_patience: 20
  scheduler_decay_factor: 0.7
  devices: 'auto'

extra_params:
  final_pooling: True
  tag_types: ['quality']
  input_audio: "/mnt/bn/bigmusic-lf/user/ju-chiang.wang/validation/test_audio/"
  output_path: "/mnt/bn/bigmusic-lf/user/ju-chiang.wang/validation/test_result/"


################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 24000        # sampling rate for audio
  sample_len: 30.0             # duration in sec for input  #{24 or 6}

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################


# datamodule configuration
pl_datamodule: !new:recipes.mir2.pl_modules.pl_datamodule.BaseDataModule
  train_dataloader: None
  val_dataloader: None
  test_dataloader: None
  sampling_rate: !ref <audio[sampling_rate]>
  audio_dir: !ref <extra_params[input_audio]>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

config: !new:recipes.umm2.models.config.UMMConfig
  feature_cmvn: "recipes/datasets/mcc/data_ids=794.stats.pt"
  sample_rate: !ref <audio[sampling_rate]>
  n_mels: 128
  n_fft: 2048
  win_length: 2048
  hop_length: 240
  hidden_size: 1024
  intermediate_size: 4096
  num_hidden_layers: 24
  num_attention_heads: 8
  max_source_positions: 2500
  tokenizer: null
  frame_rate: 25
  use_bn: False

frontend: !new:recipes.mir2.models.umm_ft.UMM # umm not frozen
  config: !ref <config>
  takes: [audio]
  provides: [latent]

backend: !new:recipes.mir2.models.tagging_umm2.TaggingProbingStage
  task: "tagging"
  takes: [latent]
  provides: [tag_pred]
  final_pooling: !ref <extra_params[final_pooling]>
  n_channel: !ref <config[hidden_size]>
  tag_map: !apply:recipes.mir2.parquet_dataset.vocab_index.quality_tags
  tag_types: !ref <extra_params[tag_types]>

model: !new:recipes.umm2.models.base.PipelineModel
  input_names: [audio]
  output_names: [tag_pred]
  stages:
    - !ref <frontend>
    - !ref <backend>

required_modules:
  pretrained:
    ckpt_path: "hdfs://haruna/home/byte_speech_sv/ju-chiang.wang/logs/umm2_conformer_2255mixedZHEN/stage1_4096x16x8/checkpoints/step=0580000.ckpt"
    #ckpt_path: "hdfs://haruna/home/byte_speech_sv/ju-chiang.wang/logs/umm2_conformer_2255mixedZHEN/stage2_hpss_onset_2255mixedZHEN_optim_mem_bert-base-multilingual-uncased/checkpoints/step=0250000.ckpt"
    loader: !name:recipes.umm2.loaders.stage1.ModelLoader
    cache_dir: ".module_cache/umm"

pl_module: !new:recipes.mir2.pl_modules.tagging_pl_umm2.LitTagging
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  infer_batch_size: !ref <run_opts[batch_size]>
  tag_map: !apply:recipes.mir2.parquet_dataset.vocab_index.quality_tags
  tag_types: !ref <extra_params[tag_types]>
  final_pooling: !ref <extra_params[final_pooling]>
  required_modules: !ref <required_modules>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

prediction_writer: !new:recipes.mir2.pl_modules.callbacks.prediction_writer.TaggingWriter
  output_dir: !ref <extra_params[output_path]>

trainer: !new:pytorch_lightning.Trainer
  strategy: ddp_find_unused_parameters_true
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  callbacks: !ref <prediction_writer>
