---

run_opts:
    seed: 1996
    src_lang: "zh"
    tgt_lang: "zh"
    num_workers: 1
    meta_lst: ""
    precision: 32
    strategy: ddp

umm_opts: !new:apps.bigtts.umm.ar.infer.ar_diffusion_inference.UMMOptions
    ckpt_path: null
    version: 0.6.2
    frame_rate: 25

ar_opts: !new:apps.bigtts.umm.ar.infer.ar_diffusion_inference.AROptions
    ckpt_path: null
    precision: fp16-mixed
    output_path: null
    temperature: 0.9
    thresh: 0.9
    mode: naive
    max_blank_length: 5
    max_repeat_times: 1
    step_out_blank: v2
    version: merge_v2
    icl_mode: "continuation"
    eos_weight: 1.0

diffusion_opts: !new:apps.bigtts.umm.ar.infer.ar_diffusion_inference.DiffusionOptions
    ckpt_path: null
    precision: fp16-mixed
    output_path: null
    mel_frame_rate: 40
    save_prompt: False
    nfe: 10
    sampler: ddim
    text_cfg_w: 1
    bn_config:
        hop_size: 600
        bn_norm_std: 2
        bn_norm_mean: 0
        bn_padding: -5
        wvae_encoder_path: /mnt/bn/jdy-lq-2/bigtts-nar/pretrain_model/wvae_3.1/wavevae_encoder_z1_%d.pt
        wvae_decoder_path: /mnt/bn/jdy-lq-2/bigtts-nar/pretrain_model/wvae_3.1/wavevae_decoder_z1_%d.pt
        wvae_version: 3.1
        wvae_cache_dir: .module_cache
        wvae_encoder_hop_size: 300
        wvae_encoder_win_size: 1200
    use_phone_lang: False

predict_dataset: !new:apps.bigtts.umm.ar.data.bigtts_test.ICLMetaDataset
    meta_lst: !ref <run_opts[meta_lst]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:samantha.dataio.lite.lite_datamodule.LiteDataModule
    predict_dataloader: !ref <dataloader>

pl_module: !new:apps.bigtts.umm.ar.infer.ar_diffusion_inference.ARDiffusionInference
    sample_rate: 24000
    seed: !ref <run_opts[seed]>
    src_lang: !ref <run_opts[src_lang]>
    tgt_lang: !ref <run_opts[tgt_lang]>
    umm_opts: !ref <umm_opts>
    ar_opts: !ref <ar_opts>
    diffusion_opts: !ref <diffusion_opts>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
