---

run_opts:
    precision: 32
    strategy: ddp
    num_workers: 4
    seed: 1996
    meta_lst: ""
    umm_ckpt_path: ""
    semantic_model_path: ""
    output_path: ""
    src_lang: "zh"
    tgt_lang: "zh"
    temperature: 0.9
    thresh: 0.9
    mode: "naive"
    max_blank_length: 5
    max_repeat_times: 1
    step_out_blank: v2
    version: merge_v2
    icl_mode: "continuation"
    use_spk_id: False
    spk2id: apps/bigtts/umm/ar/data/dict/spk2id.parquet.json
    speaker_name: ""
    use_spk_tag: False
    tag_id: 2
    use_bpe: False
    bpe_type: llama
    bpe_dir: ""
    use_text_lang_embedding: False
    textlang2id: "apps/bigtts/umm/ar/data/dict/textlang2id.json"
    use_offline_splittext: False
    offline_splittext_path: ""
    use_pre_utt: True

predict_dataset: !new:apps.bigtts.umm.ar.data.bigtts_test.ICLMetaDatasetShortform
    meta_lst: !ref <run_opts[meta_lst]>
    use_offline_splittext: !ref <run_opts[use_offline_splittext]>
    offline_splittext_path: !ref <run_opts[offline_splittext_path]>

dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    num_workers: !ref <run_opts[num_workers]>
    batch_size: null
    drop_last: False

pl_datamodule: !new:samantha.dataio.lite.lite_datamodule.LiteDataModule
    predict_dataloader: !ref <dataloader>

pl_module: !new:apps.bigtts.umm.ar.infer.pl_module_bigtts_ar.SemanticInference
    seed: !ref <run_opts[seed]>
    umm_ckpt_path: !ref <run_opts[umm_ckpt_path]>
    semantic_model_path: !ref <run_opts[semantic_model_path]>
    output_path: !ref <run_opts[output_path]>
    src_lang: !ref <run_opts[src_lang]>
    tgt_lang: !ref <run_opts[tgt_lang]>
    temperature: !ref <run_opts[temperature]>
    thresh: !ref <run_opts[thresh]>
    mode: !ref <run_opts[mode]>
    max_blank_length: !ref <run_opts[max_blank_length]>
    max_repeat_times: !ref <run_opts[max_repeat_times]>
    step_out_blank: !ref <run_opts[step_out_blank]>
    version: !ref <run_opts[version]>
    icl_mode: !ref <run_opts[icl_mode]>
    use_spk_id: !ref <run_opts[use_spk_id]>
    spk2id: !ref <run_opts[spk2id]>
    speaker_name: !ref <run_opts[speaker_name]>
    use_spk_tag: !ref <run_opts[use_spk_tag]>
    tag_id: !ref <run_opts[tag_id]>
    use_bpe: !ref <run_opts[use_bpe]>
    bpe_type: !ref <run_opts[bpe_type]>
    bpe_dir: !ref <run_opts[bpe_dir]>
    use_text_lang_embedding: !ref <run_opts[use_text_lang_embedding]>
    textlang2id: !ref <run_opts[textlang2id]>
    use_pre_utt: !ref <run_opts[use_pre_utt]>

trainer: !new:pytorch_lightning.Trainer
    accelerator: "auto"
    devices: "auto"
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    max_epochs: 1
