---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
  fast_dev_run: False
  tensorboard_dir: !ref <log_dir>
  log_name: 'vocal_melody_finetune_bestrq_hop'
  version: '300k'
  precision: 16-mixed
  accelerator: 'auto'
  num_workers: 4
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
train_params:
  learning_rate: 0.0005
  max_epochs: -1
  batch_size: 20
  scheduler_patience: 20
  scheduler_decay_factor: 0.5
  devices: 'auto'
  shuffle_buffer: 500
  num_iter: 100 # total number is num_workers * num_iter

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 24000        # sampling rate for audio
  sample_len: 6.0             # duration in sec for input  #{24 or 6}
  label_hop: 0.02             # hop len in sec for label/activation curve  #{0.01 or 0.02}
  n_timesteps: 300

labels:
    label_resolution: 0.02
    label_hop_sec: 3

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.mir_benchmark.utils.vocal2midi_processor.Vocal2midiPreprocessor
  - !ref <audio[sample_len]>
  - !ref <audio[sampling_rate]>
  - !ref <audio[label_hop]>

urls: !apply:recipes.mir_benchmark.utils.concat_vocal2midi_data.concatenate_dataset ["train"]
train_dataset: !new:webdataset.WebDataset
  urls: !ref <urls>
  resampled: True

train_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.vocal2midi_processor.Vocal2midiPreprocessor.train_batch_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio note_labels onset_labels"]
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

val_urls: !apply:recipes.mir_benchmark.utils.concat_vocal2midi_data.concatenate_dataset ["validation"]
val_dataset: !new:webdataset.WebDataset 
  urls: !ref <val_urls>
  nodesplitter: !name:recipes.mir_benchmark.utils.utils.split_by_node

val_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.vocal2midi_processor.Vocal2midiPreprocessor.val_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio note_seq dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

test_urls: !apply:recipes.mir_benchmark.utils.concat_vocal2midi_data.concatenate_dataset ["test"]
test_dataset: !new:webdataset.WebDataset 
  urls: !ref <test_urls>
  nodesplitter: !name:recipes.mir_benchmark.utils.utils.split_by_node

test_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <test_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.vocal2midi_processor.Vocal2midiPreprocessor.val_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio note_seq dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <train_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

val_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

test_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <test_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

# datamodule configuration
pl_datamodule: !new:recipes.beat.pl_modules.pl_datamodule.BeatDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

frontend: !new:recipes.mir_benchmark.models.frontend.Frontend
  model:
    !new:recipes.musicfm.models.best_rq_25hz_hop.BEST_RQ
      codebook_dim: 16
      codebook_size: 8192
      hop_length: 960
      n_fft: 2047
      n_mels: 128
      conv_dim: 512
      encoder_dim: 1024
      encoder_depth: 24
      mask_hop: 0.4
      mask_prob: 0.6
      is_flash: True
      stat_path: "/mnt/bn/audio-diffusion/pretrained_models/musicfm/playlist_stats.json"
      model_path: "/mnt/bn/audio-diffusion/pretrained_models/musicfm/hop25_300k.pt"
  layer_ix: 24
  is_update: True

backend: !new:recipes.mir_benchmark.models.vocal2midi_probing.Vocal2midiProbingStage
  n_channel: 1024
  resample: !ref <audio[n_timesteps]>
  provides: [p_vocal, o_vocal]

model: !new:samantha.core.BaseModel
  input_names: [wavs]
  output_names: [p_vocal, o_vocal]
  stages:
      - !ref <frontend>
      - !ref <backend>

optimizer_class: !name:torch.optim.Adam
    lr: !ref <train_params[learning_rate]>

pl_module: !new:recipes.mir_benchmark.pl_modules.vocal2midi_pl.Vocal2MidiModule
    model: !ref <model>
    lr: !ref <train_params[learning_rate]>
    loss_function: !new:torch.nn.BCEWithLogitsLoss
    model_batch_size: !ref <train_params[batch_size]>
    optimizer_class: !ref <optimizer_class>
    target_sample_rate: !ref <audio[sampling_rate]>
    audio_duration: !ref <audio[sample_len]>
    label_time_resolution: !ref <labels[label_resolution]>
    label_hop_sec: !ref <labels[label_hop_sec]>
    scheduler_patience: !ref <train_params[scheduler_patience]>
    scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

trainer: !new:pytorch_lightning.Trainer
  strategy: "deepspeed_stage_2"
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  profiler: simple
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      every_n_epochs: 1
      mode: "max"
      monitor: "onset_pitch_f1"
