---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 2023
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
log_dir: logs
asset_dir: recipes/diffusion/assets
checkpoint_path: null

run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "diffusion"
    version: "mss"
    strategy: ddp_find_unused_parameters_false #!new:pytorch_lightning.strategies.ddp.DDPStrategy static_graph: True
    precision: 32
    log_every_n_steps: 10
    num_steps: 6000000
    limit_val_batches: 10
    save_every_n_train_steps: 1000
    val_check_interval: 1000
    val_output_samples_dir: "generated_samples"

training_params:
    stage: finetune
    sample_rate: 44100
    target_source: vocals
    noise_range: [0, 1.0]
    dataloader_batch_size: 8
    train_batch_size: 16
    train_num_workers: 8
    val_batch_size: 8
    val_num_workers: 4
    gradient_clip_val: 1.0
    learning_rate: 0.00008
    weight_decay: 0.005
    data_cache_duration: 8
    training_duration: 6.96 # 1024 emb size for accerlation
    min_volume_threshold: 0.05
    loudness_ratio_threshold: 0.2
    sample_buffer_size: 10

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# dataloader configuration
pl_datamodule: !new:recipes.diffusion.dataset.mss.MSSDataModule
    num_workers: !ref <training_params[train_num_workers]>
    pin_memory: True
    train_dataset: !new:recipes.diffusion.dataset.mss.CommonWebDataset
        train_webdataset_list: [musdb18hq_hdfs]
        chunk_len_s: !ref <training_params[data_cache_duration]>
        sampling_rate: !ref  <training_params[sample_rate]>
        seed: !ref <seed>
        shuffle: True
        batch_size: !ref <training_params[dataloader_batch_size]>
        resampled: True
        sample_buffer_size: !ref <training_params[sample_buffer_size]>
    
# training module configuration
optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>

scheduler_cls: !name:torch.optim.lr_scheduler.LambdaLR
    lr_lambda: !name:recipes.diffusion.utils.lr_schedulers.lr_lambda
        warmup_steps: 0
        decay_factor: 0.9
        decay_interval: 200000

# pl_module: !apply:recipes.diffusion.modules.pl_module_mulan_free.DiffusionModule.load_from_checkpoint
#     checkpoint_path: !ref <checkpoint_path>
pl_module: !new:recipes.diffusion.modules.pl_module_mss.DiffusionModule
    seed: !ref <seed>
    stage: !ref <training_params[stage]>
    diffusion_model: !new:recipes.diffusion.models.tnt_mss.TNTDiffusionNetwork
        input_dim: 256
        output_dim: 128
        feature_dim: 1024
        context_dim: 128
        depth: 16
        segment_size: 32
        segment_stride: 32
        dropout: 0
        cfg_prob: 0.1
        use_checkpoint: False
    target_dim: 128
    num_chunks: 1
    chunk_length: 1024 # 147 * s length for diffusion
    noise_range: !ref <training_params[noise_range]>
    sample_rate: !ref <training_params[sample_rate]>
    asset_dir: !ref <asset_dir>
    sources: [vocals, drums, bass, other]
    target_source: !ref <training_params[target_source]>
    sample_pool_size: 128
    train_batch_size: !ref <training_params[train_batch_size]>
    sample_length: !ref <training_params[sample_rate]> * <training_params[training_duration]>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    vocoder_model:
        model_path: soundstream-step=153999-val_sdr=12.7618.ckpt
    val_output_samples_dir: !ref <run_opts[val_output_samples_dir]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: step
    mode: max
    save_top_k: 5
    every_n_train_steps: !ref <run_opts[save_every_n_train_steps]>
    save_last: True
    filename: diffusion-{step:06d}

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    num_sanity_val_steps: 2
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: auto
    devices: auto
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    max_steps: !ref <run_opts[num_steps]>
    limit_val_batches: !ref <run_opts[limit_val_batches]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    precision: !ref <run_opts[precision]>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    use_distributed_sampler: False
    sync_batchnorm: True
    logger: !ref <logger>
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !new:recipes.diffusion.utils.ema.EMA
          decay: 0.999
    plugins: !ref <plugins>


# recipes/diffusion/bootstrap.sh fit -c recipes/diffusion/conf/mcc60m_bestrq.yaml --run_opts.version mcc60m_bestrq_v1 --log_dir /mnt/bn/lyrics-to-song/ashaw/logs/diffusion
