---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision:
    !apply:torch.set_float32_matmul_precision ["high"]

extra_params:
    skip_sos: True
    app_type: svs
    exclude_ids: True
    beam_size: 1 # set to 4 if using reranker
    prompt_path: "./assets/svs/svs_prompt"
    inference_conditions: "leadsheet_tokens,prefix_audio" # style_text|style_audio,lyrics_tokens,vocal_audio|vocal_text,chroma
    time_format: "start,duration,merge_sil,merge_rest"
    max_items: null
    run_combinations: False
    use_reranker: False


    output_dir: ./generated_output/svs_infer_zh

    # Tokenizer
    # En tokenizer in CN hdfs: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/stage3_music_chroma_vq32768x32/checkpoints/step=0070000.ckpt"
    # Zh tokenizer in CN hdfs: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"
    tokenizer_ckpt: "hdfs:///home/byte_speech_sv/zongyu.yin/logs/umm_mix/umm_stage3_preclipped_bert-base-multilingual-uncased_None32768x32/checkpoints/step=0330000.ckpt"

    # Diffusion
    # En tokenizer diffusion in CN hdfs: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_14_30s_finetune/checkpoints/last.ckpt"
    # Zh tokenizer diffusion in CN hdfs: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/wtl/diffusion/model_16/checkpoints/last.ckpt"
    diffusion_ckpt: "hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/unified_diffusion/unified_diffusion/h800_ds1198_with_prompt_lr1e_5_0120/checkpoints/epoch=00-step=800000-loss=0.14.ckpt"
    vocoder_ckpt: ""
    lyrics_lang: "zh_phone" # en | zh_phone | zh_wp
    is_zh_token: True # Set to True only if lyrics_lang is zh_phone or zh_wp. Diffusion model from recipes.diffusion.models.tnt_gru

    # Semantic model
    semantic_cls_path: recipes.bigmusic.lightning.semantic_modules.SemanticModule
    semantic_ckpt: null

    # Used for reranker, only loaded if use_reranker=True
    # structure_ckpt: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/structure_epoch=185-step=93000.ckpt"
    mulan_ckpt: "hdfs://haruna/home/byte_speech_sv/jingsong.gao/mulan_ckpt/mulan-step=024600-median_rank_1=110-kaggle-minimal.ckpt"

    diffusion_params:
        infer_type: diffusion-vocoder
        umm_ckpt_path: !ref <extra_params[tokenizer_ckpt]>
        umm_frame_rate: 25
        mel_frame_rate: 40
        seed: !ref <seed>
        diffusion_precision: "bf16"
        diffusion_nfe: 10
        diffusion_sampler: "ddim"
        text_cfg_w: 0.5
        use_wvae_vocoder: True
        umm_type: "UMM_music"

        bn_config: # 40hz wvae 3.1
            hop_size: 600
            bn_norm_std: 15
            bn_norm_mean: 0
            bn_padding: -5
            bn_dim: 64
            wvae_encoder_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/assets/vocoder/20240112/wavevae_encoder.pt
            wvae_decoder_path: hdfs://haruna/home/byte_data_seed/lf_lq/speech/user/zhangshuo/bigmusic/assets/vocoder/20240112/wavevae_decoder.pt
            wvae_version: 3.1
            wvae_cache_dir: .module_cache
            wvae_encoder_hop_size: 300
            wvae_encoder_win_size: 1200

        mel_config: # ibigvgan config.
            n_fft: 4096
            num_mels: 100
            hop_size: 600
            win_size: 2400
            fmin: 0
            fmax: 12000
            sampling_rate: 24000
            mel_norm_mean: -4
            mel_norm_std: 7.5
            mel_mask_value: -5


    # Model Settings
    sample_rate: 24000
    duration: 30 # 30
    lyrics_max_seq_len: 0 # TODO: switch to 400 for 30s
    semantic_temperature: 1.0
    sample_mode: "gumbel" # gumbel | top_p
    token2wav_type: ar-diffusion-vocoder
    lyrics_tokenizer: "sami_tts_frontend_precompute"
    cache_dir: !ref <run_opts[cache_dir]>
    infer_tag: ""
    input_txt_pattern: !ref <run_opts[input_txt_pattern]>

run_opts:
    wds_dataset_urls: []
    wds_dataset_weights: []
    wds_validation_dataset_urls:
        [
            "hdfs://haruna/home/byte_speech_sv/zhongyi.huang/svs_dataset/24000hz/test_v2/url2index.txt",
        ]
    parquet_dataset_ids: [708]
    parquet_dataset_weights: [1]
    buckets_in_sec: [1, 3, 5, 10, 15, 20, 25, 30]
    segment_max_phone_len: 0
    segment_max_leadsheet_len: 2500
    fast_dev_run: False
    precision: 16
    accelerator: auto
    strategy: auto
    cache_dir: .module_cache/bigmusic
    batch_size: 1 # set to 4 if using reranker
    num_workers: 8
    shuffle_buffer: 0
    use_dynamic_batch: False
    max_seg_per_track: 3
    segment_method: "random"
    include_intro: False
    style_prompt_path: "" # "./1.wav"
    target_spkr_name: "" # set to Todd|Luke if only use specific spkr for infer
    use_empty_spkr_id: False # True if want to use 0 as all spkr_id, but keep spkr_id placeholder prefix
    use_empty_style_audio: False # True if want to use zeros-array as style_audio, but keep spkr_id placeholder prefix
    vocal_prompt_duration: -1 # -1 for full prompt, 10.0 will fix duration to 10s(for mulan inference)
    vocal_prompt_number: 1
    input_txt_pattern: ""
    leadsheet_align_mode: 'concat'

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset:
    !apply:recipes.bigmusic.datasets.inference.inference_svs_dataset_from_prompt
    sample_rate: !ref <extra_params[sample_rate]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_in_sec: !ref <run_opts[buckets_in_sec]>
    use_dynamic_batch: !ref <run_opts[use_dynamic_batch]>
    max_seg_per_track: !ref <run_opts[max_seg_per_track]>
    lyrics_tokenizer: !ref <extra_params[lyrics_tokenizer]>
    segment_max_phone_len: !ref <run_opts[segment_max_phone_len]>
    segment_max_leadsheet_len: !ref <run_opts[segment_max_leadsheet_len]>
    include_intro: !ref <run_opts[include_intro]>
    segment_method: !ref <run_opts[segment_method]>
    wds_dataset_urls: !ref <run_opts[wds_dataset_urls]>
    wds_dataset_weights: !ref <run_opts[wds_dataset_weights]>
    parquet_dataset_ids: !ref <run_opts[parquet_dataset_ids]>
    parquet_dataset_weights: !ref <run_opts[parquet_dataset_weights]>
    wds_validation_dataset_urls: !ref <run_opts[wds_validation_dataset_urls]>
    conditions: !ref <extra_params[inference_conditions]>
    style_prompt_path: !ref <extra_params[prompt_path]>
    target_spkr_name: !ref <run_opts[target_spkr_name]>
    use_empty_spkr_id: !ref <run_opts[use_empty_spkr_id]>
    use_empty_style_audio: !ref <run_opts[use_empty_style_audio]>
    vocal_prompt_duration: !ref <run_opts[vocal_prompt_duration]>
    vocal_prompt_number: !ref <run_opts[vocal_prompt_number]>
    input_txt_pattern: !ref <run_opts[input_txt_pattern]>
    time_format: !ref <extra_params[time_format]>
    leadsheet_align_mode: !ref <run_opts[leadsheet_align_mode]>

pl_datamodule: !new:recipes.bigmusic.datasets.svs.DataModule
    predict_dataset: !ref <predict_dataset>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: 0

pl_module: !new:recipes.bigmusic.lightning.inference.SemanticInferenceModule
    semantic_cls_path: !ref <extra_params[semantic_cls_path]>
    extra_params: !ref <extra_params>
    required_modules:
        bestrq_modules:
            bestrq:
                hpath: !ref <extra_params[tokenizer_ckpt]>
                initializer:
                    !name:recipes.umm.requires.model_initializer.init_stage3
                    cache_dir: !ref <run_opts[cache_dir]>
        diffusion_modules:
            diffusion:
                hpath: !ref <extra_params[diffusion_ckpt]>
                initializer:
                    !name:recipes.voicebox.lit_modules.lit_diffusion_reconstruct.prepare_diffusion_model_for_bigmusic
                    cache_dir: !ref <run_opts[cache_dir]>
                    params: !ref <extra_params[diffusion_params]>

        reranker:
            hpath:
                rewards:
                    style_text: 1.0
                    qualitative: 1.0
                    wer: 1.0
                    #structure: 1.0
                    #chord: 4.0
                required_modules:
                    mulan:
                        hpath: !ref <extra_params[mulan_ckpt]>
                        initializer:
                            !name:recipes.musiclm.requires.model_initializer.init_mulan
                            version: "g4"
                    #structure:
                    #    hpath: !ref <extra_params[structure_ckpt]>
                    #    initializer: !name:recipes.structure.requires.model_initializer.init_structure
                    #chord:
                    #    hpath: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/semi-sup-chord_epoch=103-step=56300.ckpt"
                    #    initializer: !name:recipes.chord.requires.model_initializer.init_chord
                    #chord_lms:
                    #    hpath:
                    #        default: "/mnt/bn/audio-diffusion/ducle/data/billboard_v1_chords_allsegs_genre_prefix/default/lm.arpa"
                    #    initializer: !name:recipes.chord.requires.model_initializer.init_chord_lms
            initializer: !name:recipes.bigmusic.utils.reranker.init_reranker
                cache_dir: !ref <run_opts[cache_dir]>

# separating out additional_callbacks so auto_eval can disable metrics
additional_callbacks:
    # - !new:recipes.bigmusic.callbacks.wer_metrics.RelativeWERMetricsCallback
    # - !new:recipes.bigmusic.callbacks.wer_metrics.WERMetricsCallback
    # - !new:recipes.bigmusic.callbacks.mcs_metrics.MCSMetricsCallback
    - !new:recipes.bigmusic.callbacks.pitch_metrics.PitchMetricsCallback
    # - !new:recipes.bigmusic.callbacks.save_outputs.SaveVideoCallback
callbacks:
    - !new:recipes.bigmusic.callbacks.save_outputs.SaveOutputsCallback
    - !new:recipes.bigmusic.callbacks.save_outputs.MergeFullSongCallback

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: "auto"
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
    callbacks:
        !apply:operator.add [!ref <additional_callbacks>, !ref <callbacks>]
