---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: 

# running parameters
run_opts:
  fast_dev_run: False
  tensorboard_dir: 'hdfs://harunava/home/byte_speech_sv/amy/log/'
  log_name: 'chord'
  version: '0.1'
  precision: 32
  accelerator: 'auto'
  num_workers: 4
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

train_params:
  learning_rate: 0.001
  max_epochs: -1
  batch_size: 128
  shuffle_buffer: 1000
  scheduler_patience: 10
  scheduler_decay_factor: 0.8
  devices: 'auto'
  num_iter: 100

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 16000       # sampling rate for audio
  sample_len: 12.0           # duration in sec for input  #{24 or 6}
  sample_hop: 1              # hop len in sec for input
  hop_length: 500            # hop length to calculate spectrogram
  n_fft: 2048                # number of fft to calculate spectrogram
  augmentation: False        # {true, false} use data augmentation
  input_feature: "hcqt"      # input feature type {mel, hcqt}
  do_time_augmentation: False  # use time stretching augmentation
  do_cqt_augmentation: True
  pitch_shift: False
  semitone_scale: 1

################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.chord.preprocess.common.ChordPreprocessor
  target_duration_sec: !ref <audio[sample_len]>
  sampling_rate: !ref <audio[sampling_rate]>
  hop_length: !ref <audio[hop_length]>
  chord_pool: !ref <model_params[chord_pool]>
  resnet_pools: !ref <model_params[resnet_pools]>
  chunk_per_sample: 5

# dataloader configuration
train_dataloader: !apply:recipes.chord.utils.dataset.get_train_dataset
  dataset_names: ["mingus"]
  preprocessor: !ref <preprocessor>
  shuffle_buffer: !ref <train_params[shuffle_buffer]> 
  batch_size: !ref <train_params[batch_size]>
  num_iter: !ref <train_params[num_iter]>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  to_tuple: "audio chord_root chord_triad chord_note chord_ignore"

val_dataloader: !apply:recipes.chord.utils.dataset.get_validation_dataset
  dataset_names: ["jaychou"]
  preprocessor: !ref <preprocessor>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>

# datamodule configuration
pl_datamodule: !new:recipes.chord.pl_modules.pl_datamodule.ChordDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

model_params:
  resnet_pools: [[2, 2]]
  chord_pool: [2]
  n_channel: 128

tcn_model_stage: !new:recipes.chord.models.tcn.TCNStage
  sample_rate: !ref <audio[sampling_rate]>
  n_fft: !ref <audio[n_fft]>
  hop_length: !ref <audio[hop_length]>
  input_feature: !ref <audio[input_feature]>
  resnet_pools: !ref <model_params[resnet_pools]>
  n_channel: !ref <model_params[n_channel]>
  dropout_rate: 0.1

chord_classifier_stage: !new:recipes.chord.models.classifier.ChordClassifierStage
  n_channel: !ref <model_params[n_channel]>
  chord_pool: !ref <model_params[chord_pool]>

model: !new:samantha.core.BaseModel
  input_names: [audio, aug_hop_size]
  output_names: [chord_root, chord_triad]
  stages:
    - !ref <tcn_model_stage>
    - !ref <chord_classifier_stage>

pl_module: !new:recipes.chord.pl_modules.pl_module.LitChord
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  hop_length: !ref <audio[hop_length]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  chord_pool: !ref <model_params[chord_pool]>
  resnet_pools: !ref <model_params[resnet_pools]>
  do_cqt_augmentation: !ref <audio[do_cqt_augmentation]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

callbacks:
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    every_n_epochs: 1
    mode: "max"
    save_last: True
    monitor: major_minor
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'
  - !new:recipes.chord.pl_modules.callbacks.prediction_writer.ChordWriter
    output_path: null

trainer: !new:pytorch_lightning.Trainer
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  strategy: "ddp_find_unused_parameters_true"
  max_epochs: !ref <train_params[max_epochs]>
  callbacks: !ref <callbacks>
