---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1996
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
run_opts:
    log_dir: logs
    hdfs_path: None
    fast_dev_run: False
    tensorboard_dir: !ref <run_opts[log_dir]>
    log_name: semantic
    version: 1.0
    precision: "bf16-mixed"
    accelerator: auto
    strategy: ddp_find_unused_parameters_true # deepspeed_stage_2_offload, ddp_find_unused_parameters_false
    cache_dir: ./.cache_dir
    profiler: simple
    flash_attn: null
    num_epochs: 100
    batch_size: 16
    num_workers: 8
    g_learning_rate: 0.00005
    g_weight_decay: 0.001
    d_learning_rate: 0.00005
    d_weight_decay: 0.01
    checkpointing: False
    n_step_save: 10000
    batch_total_tokens: 30000
    urls: null
    data_id: null
    valid_data_id: null
    accumulate_grad_batches: 1
    resume_ckpt_path: null
    use_url_lst: False
    target: bn
    prompt_feature: bn
    ctx_feature: bn
    use_unet_style_skip_connect: true

model_config: !new:samantha.models.speechdit.ModelArgs
    in_channels: 64
    out_channels: 64
    prompt_mel_dim: 64
    llama_provider: ctiga
    target: !ref <run_opts[target]>
    prompt_feature: !ref <run_opts[prompt_feature]>
    ctx_feature: !ref <run_opts[ctx_feature]>
    local_cond_dim: 512
    time_embed_dim: 256
    encoder_dim: 1024
    encoder_n_layers: 24
    encoder_n_heads: 16
    encoder_n_kv_heads: null
    mlp_extend: null
    causal: False
    use_window_mask: False
    use_qk_norm: head
    window_type: "elemwise" # elemwise, blockwise
    use_unet_style_skip_connect: !ref <run_opts[use_unet_style_skip_connect]>
    flashattn_version: "2"

bn_config: # 40hz wvae 3.1
    hop_size: 600
    bn_norm_std: 2
    bn_norm_mean: 0
    bn_padding: 0
    sampling_rate: 24000

item_transform: !new:apps.bigtts.speechdit.datasets.transform.Transform1
    max_length: 60
    use_text: True
    cfg_drop_rate: 0
    text_drop_id: 1
    bn_config: !ref <bn_config>
    masking: !new:samantha.dataio.lite.utils.masking.WavMasking
      p_drop_x: 0
      p_drop_audio_frames: (0.3, 0.7)
      padding_value: !ref <bn_config[bn_padding]>
      p_drop_from_0_duration_frame: 0.333
      p_drop_from_end_frame: 0.5

item_composer: !new:samantha.dataio.lite.compose.Compose
    transforms: [!ref <item_transform>]

collator: !new:apps.bigtts.speechdit.datasets.collator.Collator1
    bn_config: !ref <bn_config>
    bn_padding: !ref <bn_config[bn_padding]>

collator_composer: !new:samantha.dataio.lite.compose.BatchCompose
    transforms: [!ref <collator>]

train_parquet_dataset: !new:samantha.dataio.parquet.parquet_dataset.ParquetDataset
    data_id: !ref <run_opts[data_id]>
    resampled: True
    sample_shuffle_buffer_size: 2048
    item_transform: !ref <item_composer>
    batch_size_in_worker: 32
    yield_state: True

train_batcher: !new:samantha.dataio.batching.BucketBatcher
    buckets: !apply:eval ["list(range(40, 2500, 60))"]
    dynamic_batch: True
    maximum_bucket_size: !ref <run_opts[batch_total_tokens]>
    length_fn: !apply:eval ["lambda x: x[\"bn\"].shape[1]"]  # seq.shape

train_dataset: !new:cruise.data_module.lite.batch_dataset.BatchDataset
    dataset: !ref <train_parquet_dataset>
    batch_transform: !ref <collator_composer>
    batcher: !ref <train_batcher>
    drop_last: False

# dataloader configuration
train_dataloader: !new:cruise.data_module.lite.dataloader.LiteCruiseDataLoader
    dataset: !ref <train_dataset>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    prefetch_factor: 32
    batch_prefetch_factor: 32

# datamodule configuration
pl_datamodule: !new:samantha.dataio.lite.lite_datamodule.LiteDataModule
    train_dataloader: !ref <train_dataloader>

model_cls: !name:samantha.models.speechdit.Diffusion
    hp: !ref <model_config>

disc_cls: !name:apps.bigtts.speechdit.modules.discriminator.MultiTransformer
    n_blocks: 12
    input_dim: 1024
    hidden_dim: 256
    n_layers: 4
    n_heads: 16

optimizer_g_cls: !name:deepspeed.ops.adam.FusedAdam
    lr: !ref <run_opts[g_learning_rate]>
    weight_decay: !ref <run_opts[g_weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.0000001

optimizer_d_cls: !name:deepspeed.ops.adam.FusedAdam
    lr: !ref <run_opts[d_learning_rate]>
    weight_decay: !ref <run_opts[d_weight_decay]>
    betas: [0.9, 0.96]
    eps: 0.0000001

scheduler_g_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[g_learning_rate]>
    warmup_steps: 10000
    cycle_steps: 100000
    min_lr: !ref <run_opts[g_learning_rate]> * 0.5

scheduler_d_cls: !name:recipes.umm.modules.lr_scheduler.WarmupCosine
    init_lr: !ref <run_opts[d_learning_rate]>
    warmup_steps: 10000
    cycle_steps: 100000
    min_lr: !ref <run_opts[d_learning_rate]> * 0.5

_steps_per_epoch: !apply:operator.length_hint [!ref <train_dataloader>]
_world_size: !apply:samantha.utils.envs.getenv_int ["WORLD_SIZE", 1]

criterions:
    pseudohuber: !new:samantha.criterion.masked_loss.MaskedPseudoHuberLoss
      c: 1

pl_module: !new:apps.bigtts.speechdit.lit_modules.lit_distill.AdvDistill
    model_cls: !ref <model_cls>
    disc_cls: !ref <disc_cls>
    optimizer_g_cls: !ref <optimizer_g_cls>
    optimizer_d_cls: !ref <optimizer_d_cls>
    scheduler_g_cls: !ref <scheduler_g_cls>
    scheduler_d_cls: !ref <scheduler_d_cls>
    resume_ckpt_path: !ref <run_opts[resume_ckpt_path]>
    criterions: !ref <criterions>
    t_dist: !name:samantha.models.speechdit.LogitNormalDistribution
      mean: 1
      std: 1
    g_clip_grad_norm: 1
    d_clip_grad_norm: 1

logger:
    - !new:pytorch_lightning.loggers.TensorBoardLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
    - !new:pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: !ref <run_opts[tensorboard_dir]>
      project: !ref <run_opts[log_name]>
      name: !ref <run_opts[version]>

callbacks:
    - !new:samantha.callbacks.HDFSModelCheckpoint
      hdfs_path: !ref <run_opts[hdfs_path]>
      every_n_train_steps: !ref <run_opts[n_step_save]>
      mode: min
      save_last: True
      save_top_k: 100
      save_on_train_epoch_end: True
      verbose: True
      monitor: step
      filename: "{epoch:02d}-{step}-{loss:.3f}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'
    - !new:samantha.callbacks.timer.Timer

plugins:
    - !new:samantha.plugins.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    log_every_n_steps: 100
    strategy: !ref <run_opts[strategy]>
    max_epochs: !ref <run_opts[num_epochs]>
    precision: !ref <run_opts[precision]>
    profiler: !ref <run_opts[profiler]>
    callbacks: !ref <callbacks>
    benchmark: false
    accumulate_grad_batches: !ref <run_opts[accumulate_grad_batches]>
    plugins: !ref <plugins>
    sync_batchnorm: True
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]

ckpt_path: null
