---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
ckpt_path: null

# running parameters
log_dir: logs
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: "[template]"
    version: "0.1"
    precision: 32
    log_every_n_steps: 10
    max_epochs: 2
    batch_size: 128
    num_workers: 4
    val_batch_size: 128
    val_num_workers: 4
    # Append more parameters here

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# dataloader configuration
train_dataset: !new:recipes.template.no_sami_engine.dataset.train.TrainDataset
    param1: value1
    param2: value2

val_dataset: !new:recipes.template.no_sami_engine.dataset.val.ValDataset
    param1: value1
    param2: value2

train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle: True
    drop_last: True
    pin_memory: True

val_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <val_dataset>
    batch_size: !ref <run_opts[val_batch_size]>
    num_workers: !ref <run_opts[val_num_workers]>
    pin_memory: True

# datamodule configuration
pl_datamodule: !new:recipes.template.no_sami_engine.modules.pl_datamodule.TemplateDataModule
    train_dataloader: !ref <train_dataloader>
    val_dataloader: !ref <val_dataloader>

# training module configuration
optimizer_cls: !name:torch.optim.SGD
    lr: !ref <training_params[learning_rate]>
    weight_decay: !ref <training_params[weight_decay]>
    nesterov: True

scheduler_cls: !name:torch.optim.lr_scheduler.StepLR
    step_size: 100
    gamma: 0.5

pl_module: !new:recipes.template.no_sami_engine.modules.pl_module.TemplateModule
    model_name: model
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: acc/val
    mode: max
    save_last: True

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: auto
    devices: auto
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False  # warning: setting to True can cause slowdowns
    enable_model_summary: True
    max_epochs: !ref <run_opts[max_epochs]>
    precision: !ref <run_opts[precision]>
    log_every_n_steps: !ref <run_opts[log_every_n_steps]>
    logger: !ref <logger>
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
