---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: "last"

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision:
  !apply:torch.set_float32_matmul_precision ["high"]

extra_params:
  sample_rate: 24000
  spkr_codebook_size: 8192
  lyrics_codebook_size: 21130 # 21128 bert-chinese + 2 lyric ebos
  leadsheet_codebook_size: 512 # 1 + 6*10 + 88 + 1 + len(phoneme) + 4speical tokens = 419
  mulan_path: hdfs://haruna/home/byte_speech_sv/jingsong.gao/mulan_ckpt/mulan-step=024600-median_rank_1=110-kaggle.ckpt
  semantic_codebook_size: 32_768
  semantic_frame_rate: 25
  semantic_type: bestrq
  mulan_embed_dim: 512
  hidden_size: 1536
  intermediate_size: 4352
  num_hidden_layers: 24
  num_attention_heads: 12
  cache_dir: !ref <run_opts[cache_dir]>
  pretrained_path: null
  tokenizer_path: "hdfs://haruna/home/byte_speech_sv/zongyu.yin/logs/umm/umm_stage3_zh_dw1-1-0_wordpiece_vq32768x16-layer12/checkpoints/step=070000.ckpt"
  conditions: "leadsheet_tokens"
  time_format: "start,duration,merge_sil,merge_rest"
  input_embedders: ["leadsheet_tokens", "prefix_audio"]

# running parameters
run_opts:
  fast_dev_run: False
  log_dir: logs
  hdfs_log_dir: "hdfs:///home/byte_speech_sv/zhongyi.huang/logs"
  log_name: semantic_svs_sft_ctiga_zh
  version: debug
  cache_dir: .module_cache/bigmusic
  precision: "16"
  num_workers: 24
  accumulate_grad_batches: 1
  accelerator: auto
  audio_key: vocal
  max_steps: 200000
  val_check_interval: 2000
  batch_size: 9
  learning_rate: 1.0e-6
  warmup_steps: 2000
  cycle_steps: 30000
  weight_decay: 0.01
  shuffle_buffer: 50 # 100
  gradient_clip_val: 1.0
  buckets_in_sec: [1, 3, 5, 10, 15, 20, 25, 30, 32, 35, 40, 45]
  language: ["ZH"] # ['ZH', 'EN']
  use_dynamic_batch: False
  max_seg_per_track: 3
  segment_method: "random"
  region: "CN"
  lyrics_tokenizer: "zh_wordpiece"
  segment_max_phone_len: 0
  segment_max_leadsheet_len: 1500
  include_intro: False
  wds_dataset_urls: []
  wds_validation_dataset_urls: []
  wds_dataset_weights: []
  parquet_dataset_ids: [1268]
  parquet_validation_dataset_ids: [1269]
  parquet_dataset_weights: [1]
  target_spkr_name: "" # set to 'Todd,Zach' if only use specific spkr for training
  use_empty_spkr_id: False # True if want to use 0 as all spkr_id, but keep spkr_id placeholder prefix
  use_empty_style_audio: False # True if want to use zeros-array as style_audio, but keep spkr_id placeholder prefix
  normalize_audio: False
  leadsheet_align_mode: 'concat'

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

pl_datamodule: !new:recipes.bigmusic.datasets.svs.SVSFinetuneWebDataModule
  sample_rate: !ref <extra_params[sample_rate]>
  batch_size: !ref <run_opts[batch_size]>
  shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: True
  buckets_in_sec: !ref <run_opts[buckets_in_sec]>
  use_dynamic_batch: !ref <run_opts[use_dynamic_batch]>
  max_seg_per_track: !ref <run_opts[max_seg_per_track]>
  lyrics_tokenizer: !ref <run_opts[lyrics_tokenizer]>
  segment_max_phone_len: !ref <run_opts[segment_max_phone_len]>
  segment_max_leadsheet_len: !ref <run_opts[segment_max_leadsheet_len]>
  include_intro: !ref <run_opts[include_intro]>
  segment_method: !ref <run_opts[segment_method]>
  wds_dataset_urls: !ref <run_opts[wds_dataset_urls]>
  wds_dataset_weights: !ref <run_opts[wds_dataset_weights]>
  parquet_dataset_ids: !ref <run_opts[parquet_dataset_ids]>
  parquet_dataset_weights: !ref <run_opts[parquet_dataset_weights]>
  parquet_validation_dataset_ids: !ref <run_opts[parquet_validation_dataset_ids]>
  wds_validation_dataset_urls: !ref <run_opts[wds_validation_dataset_urls]>
  conditions: !ref <extra_params[conditions]>
  target_spkr_name: !ref <run_opts[target_spkr_name]>
  use_empty_spkr_id: !ref <run_opts[use_empty_spkr_id]>
  use_empty_style_audio: !ref <run_opts[use_empty_style_audio]>
  time_format: !ref <extra_params[time_format]>
  language: !ref <run_opts[language]>
  normalize_audio: !ref <run_opts[normalize_audio]>
  semantic_frame_rate: !ref <extra_params[semantic_frame_rate]>
  leadsheet_align_mode: !ref <run_opts[leadsheet_align_mode]>


model_config: !new:transformers.GPT2Config
  vocab_size: 1 # placeholder. Embedding table gets removed on load
  max_position_embeddings: 0
  use_cache: False
  n_positions: 0 # No absolute position embedding
  num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS
  n_embd: !ref <extra_params[hidden_size]>
  n_layer: !ref <extra_params[num_hidden_layers]>
  n_head: !ref <extra_params[num_attention_heads]>
  n_inner: !ref <extra_params[intermediate_size]>
  use_rms_norm: True
  activation_function: "swiglu"
  resid_pdrop: 0.0
  embd_pdrop: 0.0
  attn_pdrop: 0.0
  layer_norm_epsilon: 1e-6
  initializer_range: 0.02
  rescale_prenorm_residual: False
  rms_norm: True
  rotary_emb_fraction: 1.0
  rotary_emb_interleaved: True
  rotary_emb_compat: "default" #"byteformer"
  tie_word_embeddings: False
  qkv_proj_bias: False
  out_proj_bias: False
  mlp_fc1_bias: False
  mlp_fc2_bias: False
  use_flash_attn: True
  fused_bias_fc: True
  fused_mlp: False
  fused_dropout_add_ln: True
  residual_in_fp32: True

model_cls: !name:samantha.models.ctiga.gpt.GPTLMHeadModel
  config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
  lr: !ref <run_opts[learning_rate]>
  weight_decay: !ref <run_opts[weight_decay]>
  betas: [0.9, 0.96]
  eps: 0.00000001

scheduler_cls:
  !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
  init_lr: !ref <run_opts[learning_rate]>
  warmup_steps: !ref <run_opts[warmup_steps]>
  cycle_steps: !ref <run_opts[cycle_steps]>
  min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.SemanticModule
  checkpointing: False
  model_cls: !ref <model_cls>
  optimizer_cls: !ref <optimizer_cls>
  scheduler_cls: !ref <scheduler_cls>
  criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
  extra_params: !ref <extra_params>
  required_modules:
    mulan:
      # Mulan mix - 110
      hpath: !ref <extra_params[mulan_path]>
      initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
        cache_dir: !ref <run_opts[cache_dir]>
        version: "g4"
    bestrq:
      # US UMM-chroma-Zh stage 3
      hpath: !ref <extra_params[tokenizer_path]>
      initializer: !name:recipes.umm.requires.model_initializer.init_stage3
        cache_dir: !ref <run_opts[cache_dir]>

logger:
  - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False
  - !new:pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: !ref <run_opts[log_dir]>
    project: !ref <run_opts[log_name]>
    name: !ref <run_opts[version]>

callbacks:
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 20
    save_last: True
    monitor: val_accu_0
    mode: max
    filename: "{step:06d}-{tr_loss:.4f}-{val_accu_0:.2f}"
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 0
    save_last: True
    monitor: step
    every_n_train_steps: !ref <run_opts[val_check_interval]>
    mode: max
  - !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: step
    save_last: False
    save_top_k: 10
    every_n_train_steps: 8000
    mode: max
    filename: "{step:06d}-{tr_loss:.4f}-{val_loss_0:.4f}"
  - !new:samantha.callbacks.HDFSModelCheckpoint
    hdfs_path: !ref <run_opts[hdfs_log_dir]>/<run_opts[log_name]>/<run_opts[version]>
    monitor: step
    save_top_k: 20
    save_last: True
    every_n_train_steps: 4000
    mode: max
    filename: "{step:06d}-{tr_loss:.4f}-{val_accu_0:.2f}"
  - !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicDataUsageLogger
  #   save_dir: /mnt/bn/audio-diffusion/qq/data_usage_logs
  #   save_every_n_iter: 5000
  # - !new:recipes.bigmusic.callbacks.data_logger.BigMusicAudioDataLogger
  #   sample_rate: !ref <extra_params[sample_rate]>
  #   check_interval: !ref <run_opts[val_check_interval]>
  #   examples_per_batch: 8

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: "ddp_find_unused_parameters_false"
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  devices: "auto"
  num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
  deterministic: False
  enable_model_summary: True
  log_every_n_steps: 100
  max_steps: !ref <run_opts[max_steps]>
  precision: !ref <run_opts[precision]>
  accumulate_grad_batches: !ref <run_opts[accumulate_grad_batches]>
  gradient_clip_val: !ref <run_opts[gradient_clip_val]>
  val_check_interval: !ref <run_opts[val_check_interval]>
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0 # skip validation sanity checks so we don't run into hdfs file close errors
  callbacks: !ref <callbacks>
  plugins: !ref <plugins>
