---

seed: 42
__set_seed: !apply:recipes.research.seed_everything [!ref <seed>, True]  # NOTE: This also seeds all workers individually (https://arc.net/l/quote/euoaupkf)
ckpt_path: null

channels: 2
duration: 0.88236
batch_size: 8
num_workers: 4
sample_rate: 44100
log_name: audio_codec/default
version: !applyref:samantha.utils.experiment.get_version_name
log_dir: "/mnt/bn/janne-research-xl/logs"
hdfs_log_dir: !ref "hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/data/js/logs/<log_name>/<version>"

hq_audio: !new:recipes.research.dataset.collection.HQAudioParquetDataset
  sample_rate: !ref <sample_rate>
  channels: !ref <channels>
  segment_duration: !ref <duration>
  resampled: True
  shardshuffle: True

billboard_v2: !new:recipes.research.dataset.collection.Billboardv2WebDataset
  sample_rate: !ref <sample_rate>
  channels: !ref <channels>
  segment_duration: !ref <duration>
  resampled: True
  shardshuffle: True

musdb_train: !new:recipes.research.dataset.collection.MusDBTrainAudioFolderDataset
  sample_rate: !ref <sample_rate>
  segment_duration: !ref <duration>
  channels: !ref <channels>

musdb_test: !new:recipes.research.dataset.collection.MusDBTestAudioFolderDataset
  sample_rate: !ref <sample_rate>
  segment_duration: !ref <duration>
  channels: !ref <channels>

pl_datamodule: !new:samantha.data.audio.dataset.AudioFolderDataModule
  train_datasets:
    - !ref <hq_audio>
    - !ref <billboard_v2>
    - !ref <musdb_train>
  validation_datasets:
    - !ref <musdb_test>
  test_datasets:
    - !ref <musdb_test>
  batch_size: !ref <batch_size>
  shuffle: null
  num_workers: !ref <num_workers>
  batch_drop_duplicates: True

pl_module: !new:recipes.research.audio_codec.AudioCodec
  config: !new:recipes.research.audio_codec.AudioCodecConfig
    sample_rate: !ref <sample_rate>

ema: !new:samantha.callbacks.ema.EMA
  decay: 0.9999
  validate_original_weights: False
  every_n_steps: 1

logger:
  - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: !ref <log_dir>
    name: !ref <log_name>
    version: !ref <version>
    default_hp_metric: False
  - !new:pytorch_lightning.loggers.WandbLogger
    save_dir: !ref <log_dir>
    project: !apply:samantha.utils.experiment.wandb_sanitize [!ref <log_name>]
    name: !apply:samantha.utils.experiment.wandb_sanitize [!ref <version>]

checkpoint: !new:samantha.callbacks.HDFSModelCheckpoint
  hdfs_path: !ref <hdfs_log_dir>
  monitor: step
  save_top_k: 100
  save_last: True
  every_n_train_steps: !ref <trainer[val_check_interval]>
  mode: max
  filename: "{step:06d}"

model_summary: !new:pytorch_lightning.callbacks.ModelSummary
  max_depth: 3

# progress_bar: !new:pytorch_lightning.callbacks.TQDMProgressBar
#   refresh_rate: 20

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: 'step'

data_monitor: !new:recipes.research.dataset.data_monitor.DataMonitor
  hdfs_log_dir: !ref <hdfs_log_dir>

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: ddp_find_unused_parameters_true
  sync_batchnorm: True
  logger: !ref <logger>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  enable_model_summary: True
  max_epochs: -1
  max_steps: 2000000
  precision: 32
  val_check_interval: 5000
  limit_val_batches: 50
  callbacks:
    - !ref <ema>
    - !ref <model_summary>
    # - !ref <progress_bar>
    - !ref <checkpoint>
    - !ref <lr_monitor>
    - !ref <data_monitor>
  plugins: !ref <plugins>
