---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

data_params:
    sample_rate: 16000
    # duration: 10

# training parameters
training_params:
    max_steps: 1000000
    batch_size: 80
    base_lr: 4.0e-4
    warmup_steps: 3000
    hold_steps: 30000
    decay_steps: 3000000
    weight_decay: 0.01
    betas: (0.9, 0.98)
    shuffle_buffer: 200
    gradient_clip_val: 1.0


ckpt_path: null

# running parameters
# log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
log_dir: "logs"
run_opts:
    fast_dev_run: False
    tensorboard_dir: !ref <log_dir>
    log_name: soundstormv2
    version: baseline
    precision: 16-mixed
    num_workers: 6
    accelerator: auto

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    DATA CONFIGURATION                  ##########
################################################################################


# pl_datamodule: !new:recipes.datasets.billboard_hot200.BillboardHot200WebDataModule
#     sample_rate: !ref <data_params[sample_rate]>
#     duration: !ref <data_params[duration]>
#     split: "full"
#     batch_size: !ref <training_params[batch_size]>
#     shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
#     num_workers: !ref <run_opts[num_workers]>
#     pin_memory: True

pl_datamodule: !new:recipes.datasets.librilight.LibriLightWebDataModule
    sample_rate: !ref <data_params[sample_rate]>
    split: "large"
    batch_size: !ref <training_params[batch_size]>
    shuffle_buffer_size: !ref <training_params[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    buckets_sec:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 8
        - 10


################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################


# training module configuration
optimizer_class: !name:torch.optim.AdamW
    lr: !ref <training_params[base_lr]>
    weight_decay: !ref <training_params[weight_decay]>
    betas: !ref <training_params[betas]>
    fused: False

scheduler_class: !name:samantha.optim.lr_scheduler.TriStageLR
    warmup_steps: !ref <training_params[warmup_steps]>
    hold_steps: !ref <training_params[hold_steps]>
    decay_steps: !ref <training_params[decay_steps]>

masking_scheme: !new:recipes.soundstorm2.lightning.masking_scheme.SoundStormMaskingScheme
    sample_q_uniformly: True
    sample_t: True

# masking_scheme: !new:recipes.soundstorm2.lightning.masking_scheme.DucMaskingScheme
#     coarse_layers: 4
#     mask_all_fine: False
#     coarse_prob: null

audio_model: !new:recipes.soundstorm2.lightning.soundstream.SoundStreamSpeech24k

config: !new:recipes.soundstorm2.lightning.soundstorm.SoundStormConfig
    sample_rate: !ref <data_params[sample_rate]>
    n_embd: 1536
    n_head: 12
    n_layer: 12
    masking_scheme: !ref <masking_scheme>
    fine_quantizer_embedding_dropout: True
    conditioning_dropout: null
    attention_kwargs:
        enable_flash: True
        enable_mem_efficient: True  # only for V100


pl_module: !new:recipes.soundstorm2.lightning.soundstorm.SoundStorm
    config: !ref <config>
    audio_model: !ref <audio_model>
    optimizer_class: !ref <optimizer_class>
    scheduler_class: !ref <scheduler_class>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[tensorboard_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>
    default_hp_metric: False

checkpoint: !new:pytorch_lightning.callbacks.ModelCheckpoint
    monitor: 'loss/valid'
    mode: 'min'
    save_last: True

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'

audio_demo: !new:recipes.soundstorm2.callbacks.audio_demo.AudioDemo
    sample_rate: !ref <data_params[sample_rate]>
    max_demos_per_step: 1

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 50
    max_steps: !ref <training_params[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <training_params[gradient_clip_val]>
    val_check_interval: 1000
    check_val_every_n_epoch: null  # required now that we use an IterableDataset
    num_sanity_val_steps: 0
    callbacks:
        - !ref <checkpoint>
        - !ref <lr_monitor>
        - !ref <audio_demo>
    plugins: !ref <plugins>

################################################################################
##########                    PREDICTION CONFIGURATION                ##########
################################################################################
# TBD

################################################################################
##########                      EXPORT CONFIGURATION                  ##########
################################################################################
# TBD
