---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    prompt_path: "/mlx/users/zongyu.yin/playground/text_prompts_for_quick_evaluation.txt"
    output_dir: generated_output/quick_evaluation_semantic_embed_diffusion_step34k
    semantic_ckpt: "/mnt/bn/zongyu-lq/logs/semantic_diffusion_flash_gpt2/karaoke/checkpoints/step=034000-tr_loss=-0.7400-val_loss_0=-0.6652.ckpt"
    coarse_ckpt: "/mnt/bn/zongyu-lq/logs/coarse_gpt2/karaoke_wav2vec_cross_attn/checkpoints/step=041000-val_accu_0=24.35.ckpt"
    fine_ckpt: "/mnt/bn/zongyu-lq/logs/fine_flash_llama/mcc40m/checkpoints/step=120000-val_accu_0=11.06.ckpt"
    sample_rate: 24000
    num_diffusion_steps: 1000
    duration: 10
    num_rounds: 1
    semantic_duration: 10
    coarse_duration: 10
    fine_duration: 4
    semantic_stride: 5
    coarse_stride: 5
    fine_stride: 3
    wav2vec_embed_dim: 1024
    mulan_embed_dim: 1024
    soundstream_codebook_size: 1024
    wav2vec_frame_rate: 25
    soundstream_frame_rate: 50
    num_coarse: 4
    num_fine: 8
    semantic_temperatue: 1.0
    coarse_temperature: 0.9
    fine_temperature: 0.8
    sample_mode: "gumbel"
    guidance_scale: 4

run_opts:
    fast_dev_run: False
    precision: 32
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/musiclm
    batch_size: 10
    num_workers: 1

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset: !apply:recipes.musiclm.datasets.inference.InferenceDataset.from_prompt_path
    prompt_path: !ref <extra_params[prompt_path]>

# dataloader configuration
predict_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    shuffle: False
    drop_last: False
    pin_memory: False

# datamodule configuration
pl_datamodule: !new:recipes.musiclm.datamodules.lit_datamodule.DataModule
    predict_dataloader: !ref <predict_dataloader>

pl_module: !new:recipes.musiclm.lightning.inference.InferenceDiffusionModule
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/gpt_all/checkpoints/mulan-step=036000-median_rank_0=127-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        soundstream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
              cache_dir: !ref <run_opts[cache_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
