---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    gt_infer_mode: "semantic->coarse->fine"  # ["mulan->semantic->coarse->fine", "semantic->coarse->fine", "coarse->fine"]
    output_dir: ./generated_output/gt_infer
    semantic_ckpt: "/mnt/bn/audio-diffusion/ckpts/musiclm/semantic_flash_llama/karaoke_and_playlist/checkpoints/last.ckpt"
    coarse_ckpt: "/mnt/bn/audio-diffusion/ckpts/musiclm/coarse_flash_llama/karaoke_and_playlist/checkpoints/last.ckpt"
    fine_ckpt: "/mnt/bn/audio-diffusion/ckpts/musiclm/fine_flash_llama/karaoke_and_playlist/checkpoints/last.ckpt"
    sample_rate: 24000
    duration: 10
    num_rounds: 3
    semantic_duration: 10
    coarse_duration: 10
    fine_duration: 4
    semantic_stride: 5
    coarse_stride: 5
    fine_stride: 3
    wav2vec_codebook_size: 1024
    mulan_codebook_size: 1024
    mulan_num_rvq: 12
    soundstream_codebook_size: 1024
    wav2vec_frame_rate: 25
    soundstream_frame_rate: 50
    num_coarse: 4
    num_fine: 8
    semantic_temperatue: 1.0
    coarse_temperature: 0.9
    fine_temperature: 0.8
    sample_mode: "gumbel"

run_opts:
    fast_dev_run: False
    precision: 32
    accelerator: auto
    strategy: ddp_find_unused_parameters_false
    cache_dir: .module_cache/musiclm
    batch_size: 20
    num_workers: 8

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

predict_dataset: !new:recipes.musiclm.datasets.karaoke.KaraokeDataset
    urls: "pipe:hdfs dfs -cat hdfs://harunava/home/byte_speech_sv/data/karaoke_for_singsong/shards-0131.tar"
    nodesplitter: !name:recipes.musiclm.datamodules.webdataset.return_self
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    audio_key: "acc.npy"
    sample_range_key: "acc_sample_range.npy"
    min_volume_threshold: 0.05

pl_datamodule: !new:recipes.musiclm.datamodules.webdataset.DataModule
    predict_dataset: !ref <predict_dataset>
    batch_size: !ref <run_opts[batch_size]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True

pl_module: !new:recipes.musiclm.lightning.inference.GTInferenceModule
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            - hdfs://harunava/home/byte_speech_sv/weitsung.lu/mulan_exp/MuLan_large/g4/checkpoints/mulan-step=044800-median_rank_1=170-kaggle.ckpt
            - !name:recipes.musiclm.requires.model_initializer.init_mulan
              cache_dir: !ref <run_opts[cache_dir]>
              version: "g4"
        mulan_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/mulan/kmeans_minibatch_codebook-mulan1b_g4_170-1024x12.npy
            - !name:recipes.musiclm.requires.model_initializer.init_mulan_centers
              cache_dir: !ref <run_opts[cache_dir]>
        wav2vec:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/semantic.jit.pt
            - !name:recipes.musiclm.requires.model_initializer.init_wav2vec
              cache_dir: !ref <run_opts[cache_dir]>
        semantic_centers:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/w2v/2.1/centroids_epoch_10.npy
            - !name:recipes.musiclm.requires.model_initializer.init_semantic_centers
              cache_dir: !ref <run_opts[cache_dir]>
        soundstream:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream
              cache_dir: !ref <run_opts[cache_dir]>
        soundstream_dec:
            - hdfs://harunava/home/byte_speech_sv/zongyu.yin/ckpts/soundstream/190k
            - !name:recipes.musiclm.requires.model_initializer.init_soundstream_decoder
              cache_dir: !ref <run_opts[cache_dir]>

trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    strategy: !ref <run_opts[strategy]>
    precision: !ref <run_opts[precision]>
