---

seed: 42
__set_seed: !apply:recipes.research.seed_everything [!ref <seed>, True]  # NOTE: This also seeds all workers individually (https://arc.net/l/quote/euoaupkf)
ckpt_path: null

num_channels: 2
duration: 30
n_segments_per_read: 1
batch_size: 2
num_workers: 16
sample_rate: 44100
log_name: "diff/default"
version: !applyref:samantha.utils.experiment.get_version_name
log_dir: "/mnt/bn/janne-research-xl/logs"
hdfs_log_dir: !ref "hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/data/js/logs/<log_name>/<version>"

playlist_v5: !new:recipes.research.dataset.collection.PlaylistV5ParquetDataset
  sample_rate: !ref <sample_rate>
  channels: !ref <num_channels>
  segment_duration: !ref <duration>
  resampled: True
  shardshuffle: True
  crop_from_start: False

billboard_v2: !new:samantha.data.audio.webdataset.AudioWebDataset
  url2index: /mnt/bd/billboard-44k/data/*/url2index.txt
  data_type: music_vocal
  sample_rate: !ref <sample_rate>
  channels: !ref <num_channels>
  pad: True
  segment_duration: !ref <duration>
  n_segments_per_read: !ref <n_segments_per_read>
  resampled: True
  shardshuffle: True
  shuffle_buffer_size: 0
  min_segment_ratio: 1.0 # no silence on end


musdb_test: !new:samantha.data.audio.dataset.AudioFolderDataset
  root: /mnt/bd/janne-download/data/music/musdb18hq/test
  data_type: music_instrumental
  duration: !ref <duration>
  sample_rate: !ref <sample_rate>
  shuffle: False
  num_channels: !ref <num_channels>
  pad: True
  num_workers: !ref <num_workers>
  min_segment_ratio: 1.0 # no silence on end


pl_datamodule: !new:samantha.data.audio.dataset.AudioFolderDataModule
  train_datasets:
    - !ref <playlist_v5>
    - !ref <billboard_v2>
  validation_datasets:
    - !ref <musdb_test>
  test_datasets:
    - !ref <musdb_test>
  weights: [0.85, 0.15]
  batch_size: !ref <batch_size>
  shuffle: null
  num_workers: !ref <num_workers>
  prefetch_factor: 2
  batch_drop_duplicates: True


pl_module: !new:recipes.research.diff.DiffCodec
  config: !new:recipes.research.diff.DiffConfig
    sample_rate: !ref <sample_rate>
    max_duration: !ref <duration>
    n_embd: 1536
    n_layer: 16
    n_head: 24
    noise_scale_factor: 1.0
    betas: [0.9, 0.999]
    cfg_dropout: 0.1

logger:
  - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: !ref <log_dir>
    name: !ref <log_name>
    version: !ref <version>
    default_hp_metric: False
  - !new:pytorch_lightning.loggers.WandbLogger
    save_dir: !ref <log_dir>
    project: !apply:samantha.utils.experiment.wandb_sanitize [!ref <log_name>]
    name: !apply:samantha.utils.experiment.wandb_sanitize [!ref <version>]

checkpoint: !new:samantha.callbacks.HDFSModelCheckpoint
  hdfs_path: !ref <hdfs_log_dir>
  monitor: step
  save_top_k: 100
  save_last: True
  every_n_train_steps: !ref <trainer[val_check_interval]>
  mode: max
  filename: "{step:06d}"

audio_demo: !new:recipes.research.diff.callback.AudioSampleCallback
  cfg_weight: 2.0
  schedule_tau: 0.4

model_summary: !new:pytorch_lightning.callbacks.ModelSummary
  max_depth: 3

progress_bar: !new:pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 20

lr_monitor: !new:pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: 'step'

data_monitor: !new:recipes.research.dataset.data_monitor.DataMonitor
  hdfs_log_dir: !ref <hdfs_log_dir>

plugins:
  - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
  strategy: ddp_find_unused_parameters_false
  sync_batchnorm: True
  logger: !ref <logger>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  enable_model_summary: True
  max_epochs: -1
  max_steps: 1000000
  precision: bf16-mixed
  val_check_interval: 10000
  limit_val_batches: 50
  check_val_every_n_epoch: null
  gradient_clip_val: 0.2
  callbacks:
    - !ref <model_summary>
    - !ref <progress_bar>
    - !ref <checkpoint>
    - !ref <lr_monitor>
    - !ref <data_monitor>
    - !ref <audio_demo>
  plugins: !ref <plugins>
