# UMM audio_transform

pl_datamodule: !new:recipes.datasets.billboard.BillboardLyricsDataModule
    sample_rate: 24000
    batch_size: 8
    shuffle_buffer_size: 50
    min_words: 1
    max_words: 10000 # inf
    min_seconds: 1
    max_seconds: 120
    resampled: False
    shardshuffle: False
    num_workers: 0 # !ref <run_opts[num_workers]>
    pin_memory: True
    padding_strategy: pad
