---
################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

# running parameters
log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
run_opts:
  fast_dev_run: False
  tensorboard_dir: !ref <log_dir>
  log_name: 'chord_probing_mert'
  version: '330'
  precision: 32
  accelerator: 'auto'
  num_workers: 4
  pin_memory: True

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################
train_params:
  learning_rate: 0.0001
  max_epochs: -1
  batch_size: 20
  scheduler_patience: 20
  scheduler_decay_factor: 0.5
  devices: 'auto'
  shuffle_buffer: 500
  num_iter: 250 # total number is num_workers * num_iter

val_params:
  num_sanity_val_steps: 2
  batch_size: 1

################################################################################
##########                    TASK CONFIGURATION                  ##########
################################################################################

audio:
  sampling_rate: 24000        # sampling rate for audio
  sample_len: 12.0             # duration in sec for input  #{24 or 6}
  hop_length: 750             # hop length to calculate spectrogram
  label_hop: 0.0625             # hop len in sec for label/activation curve  #{0.01 or 0.02}
  n_timesteps: 192


labels:
  beat_window_length: 2       # tolerance window when calculating beat labels
  n_chord: 26


################################################################################
##########             DATASET/DATALOADING CONFIGURATION              ##########
################################################################################

preprocessor: !new:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor
  - !ref <audio[sample_len]>
  - !ref <audio[sampling_rate]>
  - !ref <audio[label_hop]>

urls: !apply:recipes.mir_benchmark.utils.concat_chord_data.concatenate_dataset ["train"]
train_dataset: !new:webdataset.WebDataset
  urls: !ref <urls>
  resampled: True

train_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <train_dataset>
  pipeline:
    - !name:webdataset.WebDataset.shuffle
      - !ref <train_params[shuffle_buffer]>
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.compose
      - !name:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor.train_batch_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio chord_root chord_triad chord_note chord_ignore"]
    - !name:webdataset.WebDataset.batched
      - !ref <train_params[batch_size]>
    - !name:webdataset.WebDataset.with_epoch
      - !ref <train_params[num_iter]>

val_urls: !apply:recipes.mir_benchmark.utils.concat_chord_data.concatenate_dataset ["validation"]
val_dataset: !new:webdataset.WebDataset 
  urls: !ref <val_urls>

val_transformed: !apply:samantha.utils.webdataset.apply_webdataset_pipeline
  wds_dataset: !ref <val_dataset>
  pipeline:
    - !name:webdataset.WebDataset.decode
    - !name:webdataset.WebDataset.map
      - !name:recipes.mir_benchmark.utils.chord_processor.ChordPreprocessor.val_preprocess
        - !ref <preprocessor>
    - !name:webdataset.WebDataset.to_tuple ["audio chord_root chord_triad chord_note chord_ignore dataset.txt"]
    - !name:webdataset.WebDataset.batched [1]

# dataloader configuration
train_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <train_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

val_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

test_dataloader: !new:torch.utils.data.DataLoader
  dataset: !ref <val_transformed>
  shuffle: False
  batch_size: null
  num_workers: !ref <run_opts[num_workers]>
  pin_memory: !ref <run_opts[pin_memory]>
  persistent_workers: False

# datamodule configuration
pl_datamodule: !new:recipes.beat.pl_modules.pl_datamodule.BeatDataModule
  train_dataloader: !ref <train_dataloader>
  val_dataloader: !ref <val_dataloader>
  test_dataloader: !ref <test_dataloader>

################################################################################
##########                      MODEL CONFIGURATION                   ##########
################################################################################

frontend: !new:recipes.mir_benchmark.models.frontend.Frontend
  model:
    !new:recipes.musicfm.models.mert.MERTWrapper
  layer_ix: 12
  is_update: False

backend: !new:recipes.mir_benchmark.models.chord_probing.ChordProbingStage
  n_channel: 1024
  resample: !ref <audio[n_timesteps]>

model: !new:samantha.core.BaseModel
  input_names: [audio]
  output_names: [chord_root, chord_triad]
  stages:
      - !ref <frontend>
      - !ref <backend>

pl_module: !new:recipes.mir_benchmark.pl_modules.chord_pl.LitChord
  model: !ref <model>
  lr: !ref <train_params[learning_rate]>
  scheduler_patience: !ref <train_params[scheduler_patience]>
  scheduler_decay_factor: !ref <train_params[scheduler_decay_factor]>
  hop_length: !ref <audio[hop_length]>
  sample_rate: !ref <audio[sampling_rate]>
  sample_len: !ref <audio[sample_len]>
  label_hop: !ref <audio[label_hop]>

################################################################################
##########                     TRAINER CONFIGURATION                  ##########
################################################################################

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
  save_dir: !ref <run_opts[tensorboard_dir]>
  name: !ref <run_opts[log_name]>
  version: !ref <run_opts[version]>

trainer: !new:pytorch_lightning.Trainer
  strategy: "deepspeed_stage_2"
  fast_dev_run: !ref <run_opts[fast_dev_run]>
  num_nodes: !apply:samantha.utils.envs.getenv_int ["ARNOLD_WORKER_NUM", 1]
  logger: !ref <logger>
  accelerator: !ref <run_opts[accelerator]>
  profiler: simple
  devices: !ref <train_params[devices]>
  precision: !ref <run_opts[precision]>
  num_sanity_val_steps: !ref <val_params[num_sanity_val_steps]>
  max_epochs: !ref <train_params[max_epochs]>
  callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      every_n_epochs: 1
      mode: "max"
      monitor: "major_minor"
