---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

ckpt_path: 'last'

seed: 1995
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]
__set_float32_matmul_precision: !apply:torch.set_float32_matmul_precision ['high']

extra_params:
    sample_rate: 24000
    duration: [30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180]
    lyrics_codebook_size: 400
    semantic_codebook_size: 32_768
    semantic_frame_rate: 25
    mulan_embed_dim: 512
    hidden_size: 2048
    semantic_type: bestrq
    pretrained_path: null # for loading state dicts
    input_embedders: ["mulan", "duration", "intensity"]
    prediction_heads:
        intensity: 1.0
    # How to extract UMM tokens
    semantic_chunk_size: null
    # How to extract MuLan embedding
    mulan_crop: True
    mulan_average: True
    # For intensity control
    intensity_decimals: 2
    intensity_calculation: "mean"
    intensity_hz: 1

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: !apply:os.getenv ["ARNOLD_OUTPUT", "logs"]
    log_name: semantic_model_instrumental_07B
    version: sstk_vad_intensity-control_3min_varlen
    cache_dir: .module_cache/musiclm
    precision: "16"
    num_workers: 8
    accelerator: auto
    max_steps: 400000
    batch_size: 1
    learning_rate: 2.0e-4
    warmup_steps: 2000
    cycle_steps: 500000
    weight_decay: 0.05
    shuffle_buffer: 32
    gradient_clip_val: 1.0
    val_check_interval: 4000
    min_length_ratio: 0.95
    normalize_audio: False
    aed_filtered: False
    sstk_filtered: null
    avoid_vocal: True
    max_vocal_threshold: 0.5
    overlap_vocal_threshold: 0.1
    text_type: "sstk_random"
    max_num_crops: [3, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1]
    crop_step_size: [10, 15, 20, 25, 30, 30, 30, 30, 30, 30, 30]
    mixed_ratio: 0.5
    use_pipe: False

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

additional_transforms:
    - !new:recipes.bigmusic.datasets.transforms.structure.IntensityTransform
      sample_rate: !ref <extra_params[sample_rate]>
      calculation_mode: !ref <extra_params[intensity_calculation]>
      intensity_hz: !ref <extra_params[intensity_hz]>

pl_datamodule: !new:recipes.bigmusic.datasets.instrumental.InstrumentalWebDataModule
    dataset_name: "SSTK_US"
    val_split: "SSTK_US"
    sample_rate: !ref <extra_params[sample_rate]>
    duration: !ref <extra_params[duration]>
    batch_size: !ref <run_opts[batch_size]>
    shuffle_buffer_size: !ref <run_opts[shuffle_buffer]>
    num_workers: !ref <run_opts[num_workers]>
    pin_memory: True
    min_volume_threshold: 0.0
    loudness_ratio_threshold: 0.0
    min_length_ratio: !ref <run_opts[min_length_ratio]>
    normalize_audio: !ref <run_opts[normalize_audio]>
    aed_filtered: !ref <run_opts[aed_filtered]>
    sstk_filtered: !ref <run_opts[sstk_filtered]>
    avoid_vocal: !ref <run_opts[avoid_vocal]>
    max_vocal_threshold: !ref <run_opts[max_vocal_threshold]>
    overlap_vocal_threshold: !ref <run_opts[overlap_vocal_threshold]>
    text_type: !ref <run_opts[text_type]>
    max_num_crops: !ref <run_opts[max_num_crops]>
    crop_step_size: !ref <run_opts[crop_step_size]>
    additional_transforms: !ref <additional_transforms>
    mixed_ratio: !ref <run_opts[mixed_ratio]>
    use_pipe: !ref <run_opts[use_pipe]>

model_config: !new:transformers.GPT2Config
    vocab_size: 1 # placeholder. Embedding table gets removed on load
    max_position_embeddings: 0
    use_cache: False
    n_positions: 0  # No absolute position embedding
    num_logits: !ref <extra_params[semantic_codebook_size]> + 2 # +2 for EOS
    n_embd: !ref <extra_params[hidden_size]>
    n_layer: 48
    n_head: 16
    n_inner: 4352
    use_rms_norm: True
    activation_function: "swiglu"
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.0
    layer_norm_epsilon: 1e-6
    initializer_range: 0.02
    rescale_prenorm_residual: False
    rms_norm: True
    rotary_emb_fraction: 1.0
    rotary_emb_interleaved: True
    rotary_emb_compat: "default" #"byteformer"
    tie_word_embeddings: False
    qkv_proj_bias: False
    out_proj_bias: False
    mlp_fc1_bias: False
    mlp_fc2_bias: False
    use_flash_attn: True
    fused_bias_fc: True
    fused_mlp: False
    fused_dropout_add_ln: True
    residual_in_fp32: True

model_cls: !name:samantha.models.ctiga.gpt.GPTLMHeadModel
    config: !ref <model_config>

optimizer_cls: !name:torch.optim.AdamW
    lr: !ref <run_opts[learning_rate]>
    weight_decay: !ref <run_opts[weight_decay]>
    betas: [0.9, 0.98]
    eps: 0.00000001

scheduler_cls: !name:recipes.musiclm.optim.lr_scheduler.warmup_cosine_lr.WarmupCosine
    init_lr: !ref <run_opts[learning_rate]>
    warmup_steps: !ref <run_opts[warmup_steps]>
    cycle_steps: !ref <run_opts[cycle_steps]>
    min_lr: !ref <run_opts[learning_rate]> * 0.1

pl_module: !new:recipes.bigmusic.lightning.semantic_modules.SemanticModule
    checkpointing: False
    model_cls: !ref <model_cls>
    optimizer_cls: !ref <optimizer_cls>
    scheduler_cls: !ref <scheduler_cls>
    criterion_cls: !name:recipes.musiclm.lightning.modules.MaskedCrossEntropy
    extra_params: !ref <extra_params>
    required_modules:
        mulan:
            hpath: /mnt/bn/audio-diffusion/weituo/sstk_mulan/mulan-step=005000-median_rank_1=83-kaggle.ckpt
            # hpath: /mnt/bn/audio-diffusion/peng/clap_sstk_mulan_files/MuLan_sstk/CLAP_all_text_space_connect_large_dropout/checkpoints/mulan-step=005000-median_rank_1=61-kaggle.ckpt
            initializer: !name:recipes.musiclm.requires.model_initializer.init_mulan
                cache_dir: !ref <run_opts[cache_dir]>
                version: "sstkmae"
                # version: "sstkmae_v2"
        bestrq:
            # US conv UMM-chroma stage 3
            hpath: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/hanoi.hantrakul/logs/umm_conv_sstk/umm_stage3_conv1D_sstk_no_ctc_794_EMAVQ32768x32/checkpoints_for_inference/step=0850000.ckpt
            # hpath: hdfs://harunava/home/byte_data_seed_us/hdd_va/speech/user/hanoi.hantrakul/logs/umm_conv_sstk/umm_stage3_conv1D_sstk_no_ctc_794_EMAVQ4096x32/checkpoints_for_inference/step=0865000.ckpt
            initializer: !name:recipes.umm.requires.model_initializer.init_stage3_conv1d
                cache_dir: !ref <run_opts[cache_dir]>
        #structure:
        #    hpath: "/mnt/bn/audio-diffusion/ducle/recipes/diffusion/assets/structure90M_epoch=203-step=102000.ckpt"
        #    initializer: !name:recipes.structure.requires.model_initializer.init_structure_90M
        #        cache_dir: !ref <run_opts[cache_dir]>
        #        n_top_bound: 14

logger:
    - !new:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      save_dir: !ref <run_opts[log_dir]>
      name: !ref <run_opts[log_name]>
      version: !ref <run_opts[version]>
      default_hp_metric: False
    #- !new:pytorch_lightning.loggers.wandb.WandbLogger
    #  save_dir: !ref <run_opts[log_dir]>
    #  project: !ref <run_opts[log_name]>
    #  name: !ref <run_opts[version]>

# log_gradient_scaler: !new:recipes.musiclm.callbacks.loggers.LogGradientScalerCallback

callbacks:
    - !new:pytorch_lightning.callbacks.ModelCheckpoint
      monitor: step
      save_top_k: 10
      save_last: True
      every_n_train_steps: !ref <run_opts[val_check_interval]>
      mode: max
      filename: "{step:06d}"
    - !new:pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: 'step'

plugins:
    - !new:samantha.plugins.torch_io.LargeTorchCheckpointIO

trainer: !new:pytorch_lightning.Trainer
    strategy: "ddp_find_unused_parameters_false"
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    logger: !ref <logger>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    enable_model_summary: True
    log_every_n_steps: 100
    max_steps: !ref <run_opts[max_steps]>
    precision: !ref <run_opts[precision]>
    accumulate_grad_batches: 1
    gradient_clip_val: !ref <run_opts[gradient_clip_val]>
    val_check_interval: !ref <run_opts[val_check_interval]>
    check_val_every_n_epoch: null
    num_sanity_val_steps: 2  # skip validation sanity checks so we don't run into hdfs file close errors
    limit_val_batches: 50
    callbacks: !ref <callbacks>
    plugins: !ref <plugins>
