---

################################################################################
##########                       BASIC CONFIGURATION                  ##########
################################################################################

# data configuration
data_dir: './data'

# running parameters
run_opts:
    fast_dev_run: False
    log_dir: logs
    log_name: 'GPT2'
    version: '0.1'
    precision: 16
    num_workers: 4
    accelerator: 'auto'
    strategy: 'deepspeed_stage_3_offload'
    enable_activation_ckpt: True

seed: 0
__set_seed: !apply:pytorch_lightning.seed_everything [!ref <seed>]

################################################################################
##########                    TRAINING CONFIGURATION                  ##########
################################################################################

# training parameters
training_params:
    model: 'gpt2_2B'
    num_epochs: 3
    steps_per_epoch: 2000
    batch_size: 1
    seq_len: 1024
    learning_rate: 0.001
    provider: "huggingface"
    model_type: "GPT2LMHead"

# dataloader configuration
train_dataloader: !new:recipes.GPT2.modules.pl_datamodule.RandomDataloader
    n_steps: !ref <training_params[steps_per_epoch]>
    batch_size: !ref <training_params[batch_size]>
    seq_len: !ref <training_params[seq_len]>

# datamodule configuration
pl_datamodule: !new:recipes.GPT2.modules.pl_datamodule.GPTDataModule
    train_dataloader: !ref <train_dataloader>

# training module configuration
pl_module: !new:recipes.GPT2.modules.pl_module.GPTLitModule
    model_name: !ref <training_params[model]>
    betas: (0.9, 0.95)
    learning_rate: !ref <training_params[learning_rate]>
    checkpoint: !ref <run_opts[enable_activation_ckpt]>
    provider: !ref <training_params[provider]>
    model_type: !ref <training_params[model_type]>

logger: !new:pytorch_lightning.loggers.TensorBoardLogger
    save_dir: !ref <run_opts[log_dir]>
    name: !ref <run_opts[log_name]>
    version: !ref <run_opts[version]>

profiler: !new:pytorch_lightning.profilers.PyTorchProfiler
    record_shapes: True
    profile_memory: True
    with_stack: True
    with_flops: True

hdfs_model_ckpt: !new:samantha.callbacks.HDFSModelCheckpoint
    #   dirpath: ./logs/checkpoints
    monitor: step
    mode: max
    save_top_k: 100
    every_n_train_steps: 100

hdfs_backup: !new:samantha.callbacks.HDFSBackup
    src_dir: !ref <logger.log_dir>

callbacks:
    - !ref <hdfs_model_ckpt>
    - !new:samantha.callbacks.Timer
    - !ref <hdfs_backup>


trainer: !new:pytorch_lightning.Trainer
    fast_dev_run: !ref <run_opts[fast_dev_run]>
    accelerator: !ref <run_opts[accelerator]>
    devices: 'auto'
    num_nodes: !apply:os.getenv ["ARNOLD_WORKER_NUM", 1]
    deterministic: False
    strategy: !ref <run_opts[strategy]>
    enable_model_summary: True
    enable_checkpointing: True
    logger: !ref <logger>
    log_every_n_steps: 100
    profiler: !ref <profiler>
    gradient_clip_val: 0.1
    max_epochs: !ref <training_params[num_epochs]>
    precision: !ref <run_opts[precision]>
    callbacks: !ref <callbacks>
